// Auto-generated by scripts/build_scheduler.py - DO NOT EDIT.
// Deterministic scheduler FSM for nn2rtl shared-engine dispatch.
// Number of engine dispatches: 34
// Register map source-of-truth: docs/agent_tasks/10_engine_config_register_block.md

module nn2rtl_scheduler (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        start,
    output reg         done,
    // AXI4-Lite master to engine config_register_block
    output reg         s_axil_awvalid,
    input  wire        s_axil_awready,
    output reg  [7:0]  s_axil_awaddr,
    output reg         s_axil_wvalid,
    input  wire        s_axil_wready,
    output reg  [31:0] s_axil_wdata,
    output reg  [3:0]  s_axil_wstrb,
    input  wire        s_axil_bvalid,
    output reg         s_axil_bready,
    input  wire [1:0]  s_axil_bresp,
    // Engine handshake
    output reg         engine_start,
    input  wire        engine_busy,
    input  wire        engine_done,
    // Per-dispatch input-loader handshake (Fix 11): the wrapper
    // muxes the active dispatch's loaded signal here. The
    // scheduler waits on it in S_WAIT_LOAD before pulsing
    // CONTROL.start, so the engine never reads from a
    // half-filled activation BRAM.
    input  wire        current_loaded,
    // Per-dispatch output-FIFO drain handshake (Fix 14): the
    // engine writes its outputs into a shared FIFO; each
    // dispatch's bridge drains the expected number of beats.
    // The scheduler waits in S_WAIT_DRAIN until this asserts,
    // so dispatch N+1 cannot start while dispatch N's beats
    // still sit in the FIFO (which would interleave them).
    input  wire        current_drain_complete,
    // Dispatch index exposed so the wrapper's loaded-mux can
    // select the correct per-dispatch loaded signal.
    output wire [5:0] dispatch_idx_out,
    // Activation BRAM bank selection
    output reg  [2:0] input_bank_sel,
    output reg  [2:0] output_bank_sel,
    output reg  [5:0] skip_bank_reserved_mask,
    // Dataflow chain handshake
    output reg         spatial_stall,
    output reg         engine_output_ready
);

    // ------------------------------------------------------------
    // FSM state encoding
    // ------------------------------------------------------------
    localparam [3:0] S_IDLE        = 4'd0;
    localparam [3:0] S_WRITE       = 4'd1;
    localparam [3:0] S_WRITE_RESP  = 4'd3;
    localparam [3:0] S_NEXT_STEP   = 4'd4;
    localparam [3:0] S_WAIT_LOAD   = 4'd9;   // Fix 11: wait for input loader before starting engine
    localparam [3:0] S_PULSE_START = 4'd5;
    localparam [3:0] S_WAIT_DONE   = 4'd6;
    localparam [3:0] S_WAIT_DRAIN  = 4'd10;  // Fix 14: wait for engine_output_fifo to drain
    localparam [3:0] S_NEXT_DISP   = 4'd7;
    localparam [3:0] S_DONE        = 4'd8;

    reg aw_acked_r, w_acked_r;

    reg [3:0]           state, next_state;
    reg [5:0] dispatch_idx;
    assign dispatch_idx_out = dispatch_idx;
    reg [3:0] write_step;
    localparam [5:0] LAST_DISPATCH = 6'd33;
    localparam [3:0] LAST_STEP     = 4'd12;

    reg [15:0] channel_in_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: channel_in_rom = 16'd32;
            6'd1: channel_in_rom = 16'd16;
            6'd2: channel_in_rom = 16'd96;
            6'd3: channel_in_rom = 16'd24;
            6'd4: channel_in_rom = 16'd144;
            6'd5: channel_in_rom = 16'd24;
            6'd6: channel_in_rom = 16'd144;
            6'd7: channel_in_rom = 16'd32;
            6'd8: channel_in_rom = 16'd192;
            6'd9: channel_in_rom = 16'd32;
            6'd10: channel_in_rom = 16'd192;
            6'd11: channel_in_rom = 16'd32;
            6'd12: channel_in_rom = 16'd192;
            6'd13: channel_in_rom = 16'd64;
            6'd14: channel_in_rom = 16'd384;
            6'd15: channel_in_rom = 16'd64;
            6'd16: channel_in_rom = 16'd384;
            6'd17: channel_in_rom = 16'd64;
            6'd18: channel_in_rom = 16'd384;
            6'd19: channel_in_rom = 16'd64;
            6'd20: channel_in_rom = 16'd384;
            6'd21: channel_in_rom = 16'd96;
            6'd22: channel_in_rom = 16'd576;
            6'd23: channel_in_rom = 16'd96;
            6'd24: channel_in_rom = 16'd576;
            6'd25: channel_in_rom = 16'd96;
            6'd26: channel_in_rom = 16'd576;
            6'd27: channel_in_rom = 16'd160;
            6'd28: channel_in_rom = 16'd960;
            6'd29: channel_in_rom = 16'd160;
            6'd30: channel_in_rom = 16'd960;
            6'd31: channel_in_rom = 16'd160;
            6'd32: channel_in_rom = 16'd960;
            6'd33: channel_in_rom = 16'd320;
            default: channel_in_rom = 16'd0;
        endcase
    end

    reg [15:0] channel_out_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: channel_out_rom = 16'd16;
            6'd1: channel_out_rom = 16'd96;
            6'd2: channel_out_rom = 16'd24;
            6'd3: channel_out_rom = 16'd144;
            6'd4: channel_out_rom = 16'd24;
            6'd5: channel_out_rom = 16'd144;
            6'd6: channel_out_rom = 16'd32;
            6'd7: channel_out_rom = 16'd192;
            6'd8: channel_out_rom = 16'd32;
            6'd9: channel_out_rom = 16'd192;
            6'd10: channel_out_rom = 16'd32;
            6'd11: channel_out_rom = 16'd192;
            6'd12: channel_out_rom = 16'd64;
            6'd13: channel_out_rom = 16'd384;
            6'd14: channel_out_rom = 16'd64;
            6'd15: channel_out_rom = 16'd384;
            6'd16: channel_out_rom = 16'd64;
            6'd17: channel_out_rom = 16'd384;
            6'd18: channel_out_rom = 16'd64;
            6'd19: channel_out_rom = 16'd384;
            6'd20: channel_out_rom = 16'd96;
            6'd21: channel_out_rom = 16'd576;
            6'd22: channel_out_rom = 16'd96;
            6'd23: channel_out_rom = 16'd576;
            6'd24: channel_out_rom = 16'd96;
            6'd25: channel_out_rom = 16'd576;
            6'd26: channel_out_rom = 16'd160;
            6'd27: channel_out_rom = 16'd960;
            6'd28: channel_out_rom = 16'd160;
            6'd29: channel_out_rom = 16'd960;
            6'd30: channel_out_rom = 16'd160;
            6'd31: channel_out_rom = 16'd960;
            6'd32: channel_out_rom = 16'd320;
            6'd33: channel_out_rom = 16'd1280;
            default: channel_out_rom = 16'd0;
        endcase
    end

    reg [3:0] kernel_h_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: kernel_h_rom = 4'd1;
            6'd1: kernel_h_rom = 4'd1;
            6'd2: kernel_h_rom = 4'd1;
            6'd3: kernel_h_rom = 4'd1;
            6'd4: kernel_h_rom = 4'd1;
            6'd5: kernel_h_rom = 4'd1;
            6'd6: kernel_h_rom = 4'd1;
            6'd7: kernel_h_rom = 4'd1;
            6'd8: kernel_h_rom = 4'd1;
            6'd9: kernel_h_rom = 4'd1;
            6'd10: kernel_h_rom = 4'd1;
            6'd11: kernel_h_rom = 4'd1;
            6'd12: kernel_h_rom = 4'd1;
            6'd13: kernel_h_rom = 4'd1;
            6'd14: kernel_h_rom = 4'd1;
            6'd15: kernel_h_rom = 4'd1;
            6'd16: kernel_h_rom = 4'd1;
            6'd17: kernel_h_rom = 4'd1;
            6'd18: kernel_h_rom = 4'd1;
            6'd19: kernel_h_rom = 4'd1;
            6'd20: kernel_h_rom = 4'd1;
            6'd21: kernel_h_rom = 4'd1;
            6'd22: kernel_h_rom = 4'd1;
            6'd23: kernel_h_rom = 4'd1;
            6'd24: kernel_h_rom = 4'd1;
            6'd25: kernel_h_rom = 4'd1;
            6'd26: kernel_h_rom = 4'd1;
            6'd27: kernel_h_rom = 4'd1;
            6'd28: kernel_h_rom = 4'd1;
            6'd29: kernel_h_rom = 4'd1;
            6'd30: kernel_h_rom = 4'd1;
            6'd31: kernel_h_rom = 4'd1;
            6'd32: kernel_h_rom = 4'd1;
            6'd33: kernel_h_rom = 4'd1;
            default: kernel_h_rom = 4'd0;
        endcase
    end

    reg [3:0] kernel_w_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: kernel_w_rom = 4'd1;
            6'd1: kernel_w_rom = 4'd1;
            6'd2: kernel_w_rom = 4'd1;
            6'd3: kernel_w_rom = 4'd1;
            6'd4: kernel_w_rom = 4'd1;
            6'd5: kernel_w_rom = 4'd1;
            6'd6: kernel_w_rom = 4'd1;
            6'd7: kernel_w_rom = 4'd1;
            6'd8: kernel_w_rom = 4'd1;
            6'd9: kernel_w_rom = 4'd1;
            6'd10: kernel_w_rom = 4'd1;
            6'd11: kernel_w_rom = 4'd1;
            6'd12: kernel_w_rom = 4'd1;
            6'd13: kernel_w_rom = 4'd1;
            6'd14: kernel_w_rom = 4'd1;
            6'd15: kernel_w_rom = 4'd1;
            6'd16: kernel_w_rom = 4'd1;
            6'd17: kernel_w_rom = 4'd1;
            6'd18: kernel_w_rom = 4'd1;
            6'd19: kernel_w_rom = 4'd1;
            6'd20: kernel_w_rom = 4'd1;
            6'd21: kernel_w_rom = 4'd1;
            6'd22: kernel_w_rom = 4'd1;
            6'd23: kernel_w_rom = 4'd1;
            6'd24: kernel_w_rom = 4'd1;
            6'd25: kernel_w_rom = 4'd1;
            6'd26: kernel_w_rom = 4'd1;
            6'd27: kernel_w_rom = 4'd1;
            6'd28: kernel_w_rom = 4'd1;
            6'd29: kernel_w_rom = 4'd1;
            6'd30: kernel_w_rom = 4'd1;
            6'd31: kernel_w_rom = 4'd1;
            6'd32: kernel_w_rom = 4'd1;
            6'd33: kernel_w_rom = 4'd1;
            default: kernel_w_rom = 4'd0;
        endcase
    end

    reg [2:0] stride_h_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: stride_h_rom = 3'd1;
            6'd1: stride_h_rom = 3'd1;
            6'd2: stride_h_rom = 3'd1;
            6'd3: stride_h_rom = 3'd1;
            6'd4: stride_h_rom = 3'd1;
            6'd5: stride_h_rom = 3'd1;
            6'd6: stride_h_rom = 3'd1;
            6'd7: stride_h_rom = 3'd1;
            6'd8: stride_h_rom = 3'd1;
            6'd9: stride_h_rom = 3'd1;
            6'd10: stride_h_rom = 3'd1;
            6'd11: stride_h_rom = 3'd1;
            6'd12: stride_h_rom = 3'd1;
            6'd13: stride_h_rom = 3'd1;
            6'd14: stride_h_rom = 3'd1;
            6'd15: stride_h_rom = 3'd1;
            6'd16: stride_h_rom = 3'd1;
            6'd17: stride_h_rom = 3'd1;
            6'd18: stride_h_rom = 3'd1;
            6'd19: stride_h_rom = 3'd1;
            6'd20: stride_h_rom = 3'd1;
            6'd21: stride_h_rom = 3'd1;
            6'd22: stride_h_rom = 3'd1;
            6'd23: stride_h_rom = 3'd1;
            6'd24: stride_h_rom = 3'd1;
            6'd25: stride_h_rom = 3'd1;
            6'd26: stride_h_rom = 3'd1;
            6'd27: stride_h_rom = 3'd1;
            6'd28: stride_h_rom = 3'd1;
            6'd29: stride_h_rom = 3'd1;
            6'd30: stride_h_rom = 3'd1;
            6'd31: stride_h_rom = 3'd1;
            6'd32: stride_h_rom = 3'd1;
            6'd33: stride_h_rom = 3'd1;
            default: stride_h_rom = 3'd0;
        endcase
    end

    reg [2:0] stride_w_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: stride_w_rom = 3'd1;
            6'd1: stride_w_rom = 3'd1;
            6'd2: stride_w_rom = 3'd1;
            6'd3: stride_w_rom = 3'd1;
            6'd4: stride_w_rom = 3'd1;
            6'd5: stride_w_rom = 3'd1;
            6'd6: stride_w_rom = 3'd1;
            6'd7: stride_w_rom = 3'd1;
            6'd8: stride_w_rom = 3'd1;
            6'd9: stride_w_rom = 3'd1;
            6'd10: stride_w_rom = 3'd1;
            6'd11: stride_w_rom = 3'd1;
            6'd12: stride_w_rom = 3'd1;
            6'd13: stride_w_rom = 3'd1;
            6'd14: stride_w_rom = 3'd1;
            6'd15: stride_w_rom = 3'd1;
            6'd16: stride_w_rom = 3'd1;
            6'd17: stride_w_rom = 3'd1;
            6'd18: stride_w_rom = 3'd1;
            6'd19: stride_w_rom = 3'd1;
            6'd20: stride_w_rom = 3'd1;
            6'd21: stride_w_rom = 3'd1;
            6'd22: stride_w_rom = 3'd1;
            6'd23: stride_w_rom = 3'd1;
            6'd24: stride_w_rom = 3'd1;
            6'd25: stride_w_rom = 3'd1;
            6'd26: stride_w_rom = 3'd1;
            6'd27: stride_w_rom = 3'd1;
            6'd28: stride_w_rom = 3'd1;
            6'd29: stride_w_rom = 3'd1;
            6'd30: stride_w_rom = 3'd1;
            6'd31: stride_w_rom = 3'd1;
            6'd32: stride_w_rom = 3'd1;
            6'd33: stride_w_rom = 3'd1;
            default: stride_w_rom = 3'd0;
        endcase
    end

    reg [2:0] padding_h_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: padding_h_rom = 3'd0;
            6'd1: padding_h_rom = 3'd0;
            6'd2: padding_h_rom = 3'd0;
            6'd3: padding_h_rom = 3'd0;
            6'd4: padding_h_rom = 3'd0;
            6'd5: padding_h_rom = 3'd0;
            6'd6: padding_h_rom = 3'd0;
            6'd7: padding_h_rom = 3'd0;
            6'd8: padding_h_rom = 3'd0;
            6'd9: padding_h_rom = 3'd0;
            6'd10: padding_h_rom = 3'd0;
            6'd11: padding_h_rom = 3'd0;
            6'd12: padding_h_rom = 3'd0;
            6'd13: padding_h_rom = 3'd0;
            6'd14: padding_h_rom = 3'd0;
            6'd15: padding_h_rom = 3'd0;
            6'd16: padding_h_rom = 3'd0;
            6'd17: padding_h_rom = 3'd0;
            6'd18: padding_h_rom = 3'd0;
            6'd19: padding_h_rom = 3'd0;
            6'd20: padding_h_rom = 3'd0;
            6'd21: padding_h_rom = 3'd0;
            6'd22: padding_h_rom = 3'd0;
            6'd23: padding_h_rom = 3'd0;
            6'd24: padding_h_rom = 3'd0;
            6'd25: padding_h_rom = 3'd0;
            6'd26: padding_h_rom = 3'd0;
            6'd27: padding_h_rom = 3'd0;
            6'd28: padding_h_rom = 3'd0;
            6'd29: padding_h_rom = 3'd0;
            6'd30: padding_h_rom = 3'd0;
            6'd31: padding_h_rom = 3'd0;
            6'd32: padding_h_rom = 3'd0;
            6'd33: padding_h_rom = 3'd0;
            default: padding_h_rom = 3'd0;
        endcase
    end

    reg [2:0] padding_w_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: padding_w_rom = 3'd0;
            6'd1: padding_w_rom = 3'd0;
            6'd2: padding_w_rom = 3'd0;
            6'd3: padding_w_rom = 3'd0;
            6'd4: padding_w_rom = 3'd0;
            6'd5: padding_w_rom = 3'd0;
            6'd6: padding_w_rom = 3'd0;
            6'd7: padding_w_rom = 3'd0;
            6'd8: padding_w_rom = 3'd0;
            6'd9: padding_w_rom = 3'd0;
            6'd10: padding_w_rom = 3'd0;
            6'd11: padding_w_rom = 3'd0;
            6'd12: padding_w_rom = 3'd0;
            6'd13: padding_w_rom = 3'd0;
            6'd14: padding_w_rom = 3'd0;
            6'd15: padding_w_rom = 3'd0;
            6'd16: padding_w_rom = 3'd0;
            6'd17: padding_w_rom = 3'd0;
            6'd18: padding_w_rom = 3'd0;
            6'd19: padding_w_rom = 3'd0;
            6'd20: padding_w_rom = 3'd0;
            6'd21: padding_w_rom = 3'd0;
            6'd22: padding_w_rom = 3'd0;
            6'd23: padding_w_rom = 3'd0;
            6'd24: padding_w_rom = 3'd0;
            6'd25: padding_w_rom = 3'd0;
            6'd26: padding_w_rom = 3'd0;
            6'd27: padding_w_rom = 3'd0;
            6'd28: padding_w_rom = 3'd0;
            6'd29: padding_w_rom = 3'd0;
            6'd30: padding_w_rom = 3'd0;
            6'd31: padding_w_rom = 3'd0;
            6'd32: padding_w_rom = 3'd0;
            6'd33: padding_w_rom = 3'd0;
            default: padding_w_rom = 3'd0;
        endcase
    end

    reg [8:0] input_h_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: input_h_rom = 9'd112;
            6'd1: input_h_rom = 9'd112;
            6'd2: input_h_rom = 9'd56;
            6'd3: input_h_rom = 9'd56;
            6'd4: input_h_rom = 9'd56;
            6'd5: input_h_rom = 9'd56;
            6'd6: input_h_rom = 9'd28;
            6'd7: input_h_rom = 9'd28;
            6'd8: input_h_rom = 9'd28;
            6'd9: input_h_rom = 9'd28;
            6'd10: input_h_rom = 9'd28;
            6'd11: input_h_rom = 9'd28;
            6'd12: input_h_rom = 9'd14;
            6'd13: input_h_rom = 9'd14;
            6'd14: input_h_rom = 9'd14;
            6'd15: input_h_rom = 9'd14;
            6'd16: input_h_rom = 9'd14;
            6'd17: input_h_rom = 9'd14;
            6'd18: input_h_rom = 9'd14;
            6'd19: input_h_rom = 9'd14;
            6'd20: input_h_rom = 9'd14;
            6'd21: input_h_rom = 9'd14;
            6'd22: input_h_rom = 9'd14;
            6'd23: input_h_rom = 9'd14;
            6'd24: input_h_rom = 9'd14;
            6'd25: input_h_rom = 9'd14;
            6'd26: input_h_rom = 9'd7;
            6'd27: input_h_rom = 9'd7;
            6'd28: input_h_rom = 9'd7;
            6'd29: input_h_rom = 9'd7;
            6'd30: input_h_rom = 9'd7;
            6'd31: input_h_rom = 9'd7;
            6'd32: input_h_rom = 9'd7;
            6'd33: input_h_rom = 9'd7;
            default: input_h_rom = 9'd0;
        endcase
    end

    reg [8:0] input_w_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: input_w_rom = 9'd112;
            6'd1: input_w_rom = 9'd112;
            6'd2: input_w_rom = 9'd56;
            6'd3: input_w_rom = 9'd56;
            6'd4: input_w_rom = 9'd56;
            6'd5: input_w_rom = 9'd56;
            6'd6: input_w_rom = 9'd28;
            6'd7: input_w_rom = 9'd28;
            6'd8: input_w_rom = 9'd28;
            6'd9: input_w_rom = 9'd28;
            6'd10: input_w_rom = 9'd28;
            6'd11: input_w_rom = 9'd28;
            6'd12: input_w_rom = 9'd14;
            6'd13: input_w_rom = 9'd14;
            6'd14: input_w_rom = 9'd14;
            6'd15: input_w_rom = 9'd14;
            6'd16: input_w_rom = 9'd14;
            6'd17: input_w_rom = 9'd14;
            6'd18: input_w_rom = 9'd14;
            6'd19: input_w_rom = 9'd14;
            6'd20: input_w_rom = 9'd14;
            6'd21: input_w_rom = 9'd14;
            6'd22: input_w_rom = 9'd14;
            6'd23: input_w_rom = 9'd14;
            6'd24: input_w_rom = 9'd14;
            6'd25: input_w_rom = 9'd14;
            6'd26: input_w_rom = 9'd7;
            6'd27: input_w_rom = 9'd7;
            6'd28: input_w_rom = 9'd7;
            6'd29: input_w_rom = 9'd7;
            6'd30: input_w_rom = 9'd7;
            6'd31: input_w_rom = 9'd7;
            6'd32: input_w_rom = 9'd7;
            6'd33: input_w_rom = 9'd7;
            default: input_w_rom = 9'd0;
        endcase
    end

    reg [8:0] output_h_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: output_h_rom = 9'd112;
            6'd1: output_h_rom = 9'd112;
            6'd2: output_h_rom = 9'd56;
            6'd3: output_h_rom = 9'd56;
            6'd4: output_h_rom = 9'd56;
            6'd5: output_h_rom = 9'd56;
            6'd6: output_h_rom = 9'd28;
            6'd7: output_h_rom = 9'd28;
            6'd8: output_h_rom = 9'd28;
            6'd9: output_h_rom = 9'd28;
            6'd10: output_h_rom = 9'd28;
            6'd11: output_h_rom = 9'd28;
            6'd12: output_h_rom = 9'd14;
            6'd13: output_h_rom = 9'd14;
            6'd14: output_h_rom = 9'd14;
            6'd15: output_h_rom = 9'd14;
            6'd16: output_h_rom = 9'd14;
            6'd17: output_h_rom = 9'd14;
            6'd18: output_h_rom = 9'd14;
            6'd19: output_h_rom = 9'd14;
            6'd20: output_h_rom = 9'd14;
            6'd21: output_h_rom = 9'd14;
            6'd22: output_h_rom = 9'd14;
            6'd23: output_h_rom = 9'd14;
            6'd24: output_h_rom = 9'd14;
            6'd25: output_h_rom = 9'd14;
            6'd26: output_h_rom = 9'd7;
            6'd27: output_h_rom = 9'd7;
            6'd28: output_h_rom = 9'd7;
            6'd29: output_h_rom = 9'd7;
            6'd30: output_h_rom = 9'd7;
            6'd31: output_h_rom = 9'd7;
            6'd32: output_h_rom = 9'd7;
            6'd33: output_h_rom = 9'd7;
            default: output_h_rom = 9'd0;
        endcase
    end

    reg [8:0] output_w_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: output_w_rom = 9'd112;
            6'd1: output_w_rom = 9'd112;
            6'd2: output_w_rom = 9'd56;
            6'd3: output_w_rom = 9'd56;
            6'd4: output_w_rom = 9'd56;
            6'd5: output_w_rom = 9'd56;
            6'd6: output_w_rom = 9'd28;
            6'd7: output_w_rom = 9'd28;
            6'd8: output_w_rom = 9'd28;
            6'd9: output_w_rom = 9'd28;
            6'd10: output_w_rom = 9'd28;
            6'd11: output_w_rom = 9'd28;
            6'd12: output_w_rom = 9'd14;
            6'd13: output_w_rom = 9'd14;
            6'd14: output_w_rom = 9'd14;
            6'd15: output_w_rom = 9'd14;
            6'd16: output_w_rom = 9'd14;
            6'd17: output_w_rom = 9'd14;
            6'd18: output_w_rom = 9'd14;
            6'd19: output_w_rom = 9'd14;
            6'd20: output_w_rom = 9'd14;
            6'd21: output_w_rom = 9'd14;
            6'd22: output_w_rom = 9'd14;
            6'd23: output_w_rom = 9'd14;
            6'd24: output_w_rom = 9'd14;
            6'd25: output_w_rom = 9'd14;
            6'd26: output_w_rom = 9'd7;
            6'd27: output_w_rom = 9'd7;
            6'd28: output_w_rom = 9'd7;
            6'd29: output_w_rom = 9'd7;
            6'd30: output_w_rom = 9'd7;
            6'd31: output_w_rom = 9'd7;
            6'd32: output_w_rom = 9'd7;
            6'd33: output_w_rom = 9'd7;
            default: output_w_rom = 9'd0;
        endcase
    end

    reg [19:0] weight_base_word_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: weight_base_word_rom = 20'd0;
            6'd1: weight_base_word_rom = 20'd32;
            6'd2: weight_base_word_rom = 20'd48;
            6'd3: weight_base_word_rom = 20'd144;
            6'd4: weight_base_word_rom = 20'd168;
            6'd5: weight_base_word_rom = 20'd312;
            6'd6: weight_base_word_rom = 20'd336;
            6'd7: weight_base_word_rom = 20'd480;
            6'd8: weight_base_word_rom = 20'd512;
            6'd9: weight_base_word_rom = 20'd704;
            6'd10: weight_base_word_rom = 20'd736;
            6'd11: weight_base_word_rom = 20'd928;
            6'd12: weight_base_word_rom = 20'd960;
            6'd13: weight_base_word_rom = 20'd1152;
            6'd14: weight_base_word_rom = 20'd1280;
            6'd15: weight_base_word_rom = 20'd1664;
            6'd16: weight_base_word_rom = 20'd1792;
            6'd17: weight_base_word_rom = 20'd2176;
            6'd18: weight_base_word_rom = 20'd2304;
            6'd19: weight_base_word_rom = 20'd2688;
            6'd20: weight_base_word_rom = 20'd2816;
            6'd21: weight_base_word_rom = 20'd3200;
            6'd22: weight_base_word_rom = 20'd3488;
            6'd23: weight_base_word_rom = 20'd4064;
            6'd24: weight_base_word_rom = 20'd4352;
            6'd25: weight_base_word_rom = 20'd4928;
            6'd26: weight_base_word_rom = 20'd5216;
            6'd27: weight_base_word_rom = 20'd5792;
            6'd28: weight_base_word_rom = 20'd6432;
            6'd29: weight_base_word_rom = 20'd7392;
            6'd30: weight_base_word_rom = 20'd8032;
            6'd31: weight_base_word_rom = 20'd8992;
            6'd32: weight_base_word_rom = 20'd9632;
            6'd33: weight_base_word_rom = 20'd11552;
            default: weight_base_word_rom = 20'd0;
        endcase
    end

    reg [15:0] bias_base_word_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: bias_base_word_rom = 16'd0;
            6'd1: bias_base_word_rom = 16'd1;
            6'd2: bias_base_word_rom = 16'd2;
            6'd3: bias_base_word_rom = 16'd3;
            6'd4: bias_base_word_rom = 16'd4;
            6'd5: bias_base_word_rom = 16'd5;
            6'd6: bias_base_word_rom = 16'd6;
            6'd7: bias_base_word_rom = 16'd7;
            6'd8: bias_base_word_rom = 16'd8;
            6'd9: bias_base_word_rom = 16'd9;
            6'd10: bias_base_word_rom = 16'd10;
            6'd11: bias_base_word_rom = 16'd11;
            6'd12: bias_base_word_rom = 16'd12;
            6'd13: bias_base_word_rom = 16'd13;
            6'd14: bias_base_word_rom = 16'd15;
            6'd15: bias_base_word_rom = 16'd16;
            6'd16: bias_base_word_rom = 16'd18;
            6'd17: bias_base_word_rom = 16'd19;
            6'd18: bias_base_word_rom = 16'd21;
            6'd19: bias_base_word_rom = 16'd22;
            6'd20: bias_base_word_rom = 16'd24;
            6'd21: bias_base_word_rom = 16'd25;
            6'd22: bias_base_word_rom = 16'd28;
            6'd23: bias_base_word_rom = 16'd29;
            6'd24: bias_base_word_rom = 16'd32;
            6'd25: bias_base_word_rom = 16'd33;
            6'd26: bias_base_word_rom = 16'd36;
            6'd27: bias_base_word_rom = 16'd37;
            6'd28: bias_base_word_rom = 16'd41;
            6'd29: bias_base_word_rom = 16'd42;
            6'd30: bias_base_word_rom = 16'd46;
            6'd31: bias_base_word_rom = 16'd47;
            6'd32: bias_base_word_rom = 16'd51;
            6'd33: bias_base_word_rom = 16'd53;
            default: bias_base_word_rom = 16'd0;
        endcase
    end

    reg [31:0] scale_mult_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: scale_mult_rom = 32'd1022491539;
            6'd1: scale_mult_rom = 32'd821832354;
            6'd2: scale_mult_rom = 32'd829020812;
            6'd3: scale_mult_rom = 32'd1147864284;
            6'd4: scale_mult_rom = 32'd1044024640;
            6'd5: scale_mult_rom = 32'd799520324;
            6'd6: scale_mult_rom = 32'd1035644108;
            6'd7: scale_mult_rom = 32'd924505917;
            6'd8: scale_mult_rom = 32'd1313907656;
            6'd9: scale_mult_rom = 32'd1084263867;
            6'd10: scale_mult_rom = 32'd1232000712;
            6'd11: scale_mult_rom = 32'd1358779517;
            6'd12: scale_mult_rom = 32'd1413735258;
            6'd13: scale_mult_rom = 32'd983572715;
            6'd14: scale_mult_rom = 32'd1449198149;
            6'd15: scale_mult_rom = 32'd874323491;
            6'd16: scale_mult_rom = 32'd1488329205;
            6'd17: scale_mult_rom = 32'd1476324803;
            6'd18: scale_mult_rom = 32'd784656607;
            6'd19: scale_mult_rom = 32'd1440684280;
            6'd20: scale_mult_rom = 32'd1432824057;
            6'd21: scale_mult_rom = 32'd1087170017;
            6'd22: scale_mult_rom = 32'd992640914;
            6'd23: scale_mult_rom = 32'd1101575230;
            6'd24: scale_mult_rom = 32'd1157567709;
            6'd25: scale_mult_rom = 32'd1170230193;
            6'd26: scale_mult_rom = 32'd1230198091;
            6'd27: scale_mult_rom = 32'd1230840735;
            6'd28: scale_mult_rom = 32'd1123836570;
            6'd29: scale_mult_rom = 32'd1077844367;
            6'd30: scale_mult_rom = 32'd1295479220;
            6'd31: scale_mult_rom = 32'd836697630;
            6'd32: scale_mult_rom = 32'd1428852721;
            6'd33: scale_mult_rom = 32'd1468036427;
            default: scale_mult_rom = 32'd0;
        endcase
    end

    reg [5:0] scale_shift_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: scale_shift_rom = 6'd38;
            6'd1: scale_shift_rom = 6'd35;
            6'd2: scale_shift_rom = 6'd38;
            6'd3: scale_shift_rom = 6'd37;
            6'd4: scale_shift_rom = 6'd38;
            6'd5: scale_shift_rom = 6'd37;
            6'd6: scale_shift_rom = 6'd38;
            6'd7: scale_shift_rom = 6'd37;
            6'd8: scale_shift_rom = 6'd37;
            6'd9: scale_shift_rom = 6'd38;
            6'd10: scale_shift_rom = 6'd38;
            6'd11: scale_shift_rom = 6'd37;
            6'd12: scale_shift_rom = 6'd38;
            6'd13: scale_shift_rom = 6'd38;
            6'd14: scale_shift_rom = 6'd37;
            6'd15: scale_shift_rom = 6'd38;
            6'd16: scale_shift_rom = 6'd37;
            6'd17: scale_shift_rom = 6'd38;
            6'd18: scale_shift_rom = 6'd36;
            6'd19: scale_shift_rom = 6'd38;
            6'd20: scale_shift_rom = 6'd38;
            6'd21: scale_shift_rom = 6'd38;
            6'd22: scale_shift_rom = 6'd37;
            6'd23: scale_shift_rom = 6'd38;
            6'd24: scale_shift_rom = 6'd37;
            6'd25: scale_shift_rom = 6'd38;
            6'd26: scale_shift_rom = 6'd38;
            6'd27: scale_shift_rom = 6'd38;
            6'd28: scale_shift_rom = 6'd37;
            6'd29: scale_shift_rom = 6'd38;
            6'd30: scale_shift_rom = 6'd37;
            6'd31: scale_shift_rom = 6'd37;
            6'd32: scale_shift_rom = 6'd38;
            6'd33: scale_shift_rom = 6'd39;
            default: scale_shift_rom = 6'd0;
        endcase
    end

    reg [7:0] zero_point_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: zero_point_rom = 8'd0;
            6'd1: zero_point_rom = 8'd0;
            6'd2: zero_point_rom = 8'd0;
            6'd3: zero_point_rom = 8'd0;
            6'd4: zero_point_rom = 8'd0;
            6'd5: zero_point_rom = 8'd0;
            6'd6: zero_point_rom = 8'd0;
            6'd7: zero_point_rom = 8'd0;
            6'd8: zero_point_rom = 8'd0;
            6'd9: zero_point_rom = 8'd0;
            6'd10: zero_point_rom = 8'd0;
            6'd11: zero_point_rom = 8'd0;
            6'd12: zero_point_rom = 8'd0;
            6'd13: zero_point_rom = 8'd0;
            6'd14: zero_point_rom = 8'd0;
            6'd15: zero_point_rom = 8'd0;
            6'd16: zero_point_rom = 8'd0;
            6'd17: zero_point_rom = 8'd0;
            6'd18: zero_point_rom = 8'd0;
            6'd19: zero_point_rom = 8'd0;
            6'd20: zero_point_rom = 8'd0;
            6'd21: zero_point_rom = 8'd0;
            6'd22: zero_point_rom = 8'd0;
            6'd23: zero_point_rom = 8'd0;
            6'd24: zero_point_rom = 8'd0;
            6'd25: zero_point_rom = 8'd0;
            6'd26: zero_point_rom = 8'd0;
            6'd27: zero_point_rom = 8'd0;
            6'd28: zero_point_rom = 8'd0;
            6'd29: zero_point_rom = 8'd0;
            6'd30: zero_point_rom = 8'd0;
            6'd31: zero_point_rom = 8'd0;
            6'd32: zero_point_rom = 8'd0;
            6'd33: zero_point_rom = 8'd0;
            default: zero_point_rom = 8'd0;
        endcase
    end

    reg [2:0] input_bank_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: input_bank_rom = 3'd0;
            6'd1: input_bank_rom = 3'd1;
            6'd2: input_bank_rom = 3'd1;
            6'd3: input_bank_rom = 3'd0;
            6'd4: input_bank_rom = 3'd0;
            6'd5: input_bank_rom = 3'd0;
            6'd6: input_bank_rom = 3'd0;
            6'd7: input_bank_rom = 3'd1;
            6'd8: input_bank_rom = 3'd1;
            6'd9: input_bank_rom = 3'd1;
            6'd10: input_bank_rom = 3'd1;
            6'd11: input_bank_rom = 3'd1;
            6'd12: input_bank_rom = 3'd1;
            6'd13: input_bank_rom = 3'd0;
            6'd14: input_bank_rom = 3'd0;
            6'd15: input_bank_rom = 3'd0;
            6'd16: input_bank_rom = 3'd0;
            6'd17: input_bank_rom = 3'd0;
            6'd18: input_bank_rom = 3'd0;
            6'd19: input_bank_rom = 3'd0;
            6'd20: input_bank_rom = 3'd0;
            6'd21: input_bank_rom = 3'd1;
            6'd22: input_bank_rom = 3'd1;
            6'd23: input_bank_rom = 3'd1;
            6'd24: input_bank_rom = 3'd1;
            6'd25: input_bank_rom = 3'd1;
            6'd26: input_bank_rom = 3'd1;
            6'd27: input_bank_rom = 3'd0;
            6'd28: input_bank_rom = 3'd0;
            6'd29: input_bank_rom = 3'd0;
            6'd30: input_bank_rom = 3'd0;
            6'd31: input_bank_rom = 3'd0;
            6'd32: input_bank_rom = 3'd0;
            6'd33: input_bank_rom = 3'd1;
            default: input_bank_rom = 3'd0;
        endcase
    end

    reg [2:0] output_bank_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: output_bank_rom = 3'd1;
            6'd1: output_bank_rom = 3'd0;
            6'd2: output_bank_rom = 3'd0;
            6'd3: output_bank_rom = 3'd1;
            6'd4: output_bank_rom = 3'd1;
            6'd5: output_bank_rom = 3'd1;
            6'd6: output_bank_rom = 3'd1;
            6'd7: output_bank_rom = 3'd0;
            6'd8: output_bank_rom = 3'd0;
            6'd9: output_bank_rom = 3'd0;
            6'd10: output_bank_rom = 3'd0;
            6'd11: output_bank_rom = 3'd0;
            6'd12: output_bank_rom = 3'd0;
            6'd13: output_bank_rom = 3'd1;
            6'd14: output_bank_rom = 3'd1;
            6'd15: output_bank_rom = 3'd1;
            6'd16: output_bank_rom = 3'd1;
            6'd17: output_bank_rom = 3'd1;
            6'd18: output_bank_rom = 3'd1;
            6'd19: output_bank_rom = 3'd1;
            6'd20: output_bank_rom = 3'd1;
            6'd21: output_bank_rom = 3'd0;
            6'd22: output_bank_rom = 3'd0;
            6'd23: output_bank_rom = 3'd0;
            6'd24: output_bank_rom = 3'd0;
            6'd25: output_bank_rom = 3'd0;
            6'd26: output_bank_rom = 3'd0;
            6'd27: output_bank_rom = 3'd1;
            6'd28: output_bank_rom = 3'd1;
            6'd29: output_bank_rom = 3'd1;
            6'd30: output_bank_rom = 3'd1;
            6'd31: output_bank_rom = 3'd1;
            6'd32: output_bank_rom = 3'd1;
            6'd33: output_bank_rom = 3'd0;
            default: output_bank_rom = 3'd0;
        endcase
    end

    reg [5:0] skip_mask_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: skip_mask_rom = 6'd0;
            6'd1: skip_mask_rom = 6'd0;
            6'd2: skip_mask_rom = 6'd0;
            6'd3: skip_mask_rom = 6'd0;
            6'd4: skip_mask_rom = 6'd0;
            6'd5: skip_mask_rom = 6'd0;
            6'd6: skip_mask_rom = 6'd0;
            6'd7: skip_mask_rom = 6'd0;
            6'd8: skip_mask_rom = 6'd0;
            6'd9: skip_mask_rom = 6'd0;
            6'd10: skip_mask_rom = 6'd0;
            6'd11: skip_mask_rom = 6'd0;
            6'd12: skip_mask_rom = 6'd0;
            6'd13: skip_mask_rom = 6'd0;
            6'd14: skip_mask_rom = 6'd0;
            6'd15: skip_mask_rom = 6'd0;
            6'd16: skip_mask_rom = 6'd0;
            6'd17: skip_mask_rom = 6'd0;
            6'd18: skip_mask_rom = 6'd0;
            6'd19: skip_mask_rom = 6'd0;
            6'd20: skip_mask_rom = 6'd0;
            6'd21: skip_mask_rom = 6'd0;
            6'd22: skip_mask_rom = 6'd0;
            6'd23: skip_mask_rom = 6'd0;
            6'd24: skip_mask_rom = 6'd0;
            6'd25: skip_mask_rom = 6'd0;
            6'd26: skip_mask_rom = 6'd0;
            6'd27: skip_mask_rom = 6'd0;
            6'd28: skip_mask_rom = 6'd0;
            6'd29: skip_mask_rom = 6'd0;
            6'd30: skip_mask_rom = 6'd0;
            6'd31: skip_mask_rom = 6'd0;
            6'd32: skip_mask_rom = 6'd0;
            6'd33: skip_mask_rom = 6'd0;
            default: skip_mask_rom = 6'd0;
        endcase
    end

    reg [15:0] act_in_base_word_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: act_in_base_word_rom = 16'd0;
            6'd1: act_in_base_word_rom = 16'd12544;
            6'd2: act_in_base_word_rom = 16'd4096;
            6'd3: act_in_base_word_rom = 16'd0;
            6'd4: act_in_base_word_rom = 16'd0;
            6'd5: act_in_base_word_rom = 16'd0;
            6'd6: act_in_base_word_rom = 16'd0;
            6'd7: act_in_base_word_rom = 16'd4096;
            6'd8: act_in_base_word_rom = 16'd4096;
            6'd9: act_in_base_word_rom = 16'd4096;
            6'd10: act_in_base_word_rom = 16'd4096;
            6'd11: act_in_base_word_rom = 16'd4096;
            6'd12: act_in_base_word_rom = 16'd4096;
            6'd13: act_in_base_word_rom = 16'd0;
            6'd14: act_in_base_word_rom = 16'd0;
            6'd15: act_in_base_word_rom = 16'd0;
            6'd16: act_in_base_word_rom = 16'd0;
            6'd17: act_in_base_word_rom = 16'd0;
            6'd18: act_in_base_word_rom = 16'd0;
            6'd19: act_in_base_word_rom = 16'd0;
            6'd20: act_in_base_word_rom = 16'd0;
            6'd21: act_in_base_word_rom = 16'd4096;
            6'd22: act_in_base_word_rom = 16'd4096;
            6'd23: act_in_base_word_rom = 16'd4096;
            6'd24: act_in_base_word_rom = 16'd4096;
            6'd25: act_in_base_word_rom = 16'd4096;
            6'd26: act_in_base_word_rom = 16'd4096;
            6'd27: act_in_base_word_rom = 16'd0;
            6'd28: act_in_base_word_rom = 16'd0;
            6'd29: act_in_base_word_rom = 16'd0;
            6'd30: act_in_base_word_rom = 16'd0;
            6'd31: act_in_base_word_rom = 16'd0;
            6'd32: act_in_base_word_rom = 16'd0;
            6'd33: act_in_base_word_rom = 16'd4096;
            default: act_in_base_word_rom = 16'd0;
        endcase
    end

    reg [15:0] act_out_base_word_rom;
    always @(*) begin
        case (dispatch_idx)
            6'd0: act_out_base_word_rom = 16'd12544;
            6'd1: act_out_base_word_rom = 16'd12544;
            6'd2: act_out_base_word_rom = 16'd0;
            6'd3: act_out_base_word_rom = 16'd4096;
            6'd4: act_out_base_word_rom = 16'd4096;
            6'd5: act_out_base_word_rom = 16'd4096;
            6'd6: act_out_base_word_rom = 16'd4096;
            6'd7: act_out_base_word_rom = 16'd0;
            6'd8: act_out_base_word_rom = 16'd0;
            6'd9: act_out_base_word_rom = 16'd0;
            6'd10: act_out_base_word_rom = 16'd0;
            6'd11: act_out_base_word_rom = 16'd0;
            6'd12: act_out_base_word_rom = 16'd0;
            6'd13: act_out_base_word_rom = 16'd4096;
            6'd14: act_out_base_word_rom = 16'd4096;
            6'd15: act_out_base_word_rom = 16'd4096;
            6'd16: act_out_base_word_rom = 16'd4096;
            6'd17: act_out_base_word_rom = 16'd4096;
            6'd18: act_out_base_word_rom = 16'd4096;
            6'd19: act_out_base_word_rom = 16'd4096;
            6'd20: act_out_base_word_rom = 16'd4096;
            6'd21: act_out_base_word_rom = 16'd0;
            6'd22: act_out_base_word_rom = 16'd0;
            6'd23: act_out_base_word_rom = 16'd0;
            6'd24: act_out_base_word_rom = 16'd0;
            6'd25: act_out_base_word_rom = 16'd0;
            6'd26: act_out_base_word_rom = 16'd0;
            6'd27: act_out_base_word_rom = 16'd4096;
            6'd28: act_out_base_word_rom = 16'd4096;
            6'd29: act_out_base_word_rom = 16'd4096;
            6'd30: act_out_base_word_rom = 16'd4096;
            6'd31: act_out_base_word_rom = 16'd4096;
            6'd32: act_out_base_word_rom = 16'd4096;
            6'd33: act_out_base_word_rom = 16'd0;
            default: act_out_base_word_rom = 16'd0;
        endcase
    end

    // ------------------------------------------------------------
    // Per-step AXI write address + data
    // ------------------------------------------------------------
    reg [7:0]  step_addr;
    reg [31:0] step_data;
    always @(*) begin
        step_addr = 8'h00;
        step_data = 32'd0;
        case (write_step)
            4'd0: begin step_addr = 8'h00; step_data = {16'd0, channel_in_rom}; end
            4'd1: begin step_addr = 8'h04; step_data = {16'd0, channel_out_rom}; end
            4'd2: begin step_addr = 8'h08; step_data = {24'd0, kernel_h_rom, kernel_w_rom}; end
            4'd3: begin step_addr = 8'h0C; step_data = {26'd0, stride_h_rom, stride_w_rom}; end
            4'd4: begin step_addr = 8'h10; step_data = {26'd0, padding_h_rom, padding_w_rom}; end
            4'd5: begin step_addr = 8'h14; step_data = {7'd0, input_h_rom, 7'd0, input_w_rom}; end
            4'd6: begin step_addr = 8'h18; step_data = {7'd0, output_h_rom, 7'd0, output_w_rom}; end
            4'd7: begin step_addr = 8'h1C; step_data = {12'd0, weight_base_word_rom}; end
            4'd8: begin step_addr = 8'h20; step_data = {16'd0, bias_base_word_rom}; end
            4'd9: begin step_addr = 8'h24; step_data = scale_mult_rom; end
            4'd10: begin step_addr = 8'h28; step_data = {18'd0, zero_point_rom, scale_shift_rom}; end
            4'd11: begin step_addr = 8'h34; step_data = {16'd0, act_in_base_word_rom}; end
            4'd12: begin step_addr = 8'h38; step_data = {16'd0, act_out_base_word_rom}; end
            default: begin step_addr = 8'h00; step_data = 32'd0; end
        endcase
    end

    // ------------------------------------------------------------
    // FSM next-state logic
    // ------------------------------------------------------------
    always @(*) begin
        next_state = state;
        case (state)
            S_IDLE:        if (start) next_state = S_WRITE;
            // S_WRITE asserts AW and W in the same cycle. A correct AXI4-Lite
            // slave fires the handshake when (awvalid & awready & wvalid & wready)
            // are all true in one cycle. aw_acked_r / w_acked_r let the slave
            // return the two ready signals in different cycles too.
            S_WRITE:
                if ((aw_acked_r || (s_axil_awvalid && s_axil_awready)) &&
                    (w_acked_r  || (s_axil_wvalid  && s_axil_wready)))
                    next_state = S_WRITE_RESP;
            S_WRITE_RESP:  if (s_axil_bvalid)  next_state = S_NEXT_STEP;
            // Fix 11: after the final config write, wait until the input
            // loader bridge for the current dispatch has finished filling
            // the activation BRAM. current_loaded comes from a wrapper-
            // side mux over per-dispatch `loaded` signals.
            S_NEXT_STEP:   next_state = (write_step == LAST_STEP) ? S_WAIT_LOAD : S_WRITE;
            S_WAIT_LOAD:   if (current_loaded) next_state = S_PULSE_START;
            S_PULSE_START: next_state = S_WAIT_DONE;
            // Fix 14: between dispatches, wait in S_WAIT_DRAIN until the
            // engine_output_fifo has been fully drained by this dispatch's
            // bridge. Otherwise dispatch N+1's writes would interleave with
            // N's outputs still in the FIFO. spatial_stall=0 in this state
            // so the spatial chain runs and drains the bridge → FIFO →
            // downstream relu/add → next input_loader path.
            S_WAIT_DONE:   if (engine_done) next_state = S_WAIT_DRAIN;
            S_WAIT_DRAIN:  if (current_drain_complete) next_state = S_NEXT_DISP;
            S_NEXT_DISP:   next_state = (dispatch_idx == LAST_DISPATCH) ? S_DONE : S_WRITE;
            S_DONE:        next_state = S_DONE;
            default:       next_state = S_IDLE;
        endcase
    end

    // ------------------------------------------------------------
    // Sequential state + counters
    // ------------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state        <= S_IDLE;
            dispatch_idx <= {6{1'b0}};
            write_step   <= {4{1'b0}};
            aw_acked_r   <= 1'b0;
            w_acked_r    <= 1'b0;
        end else begin
            state <= next_state;
            if (state == S_IDLE && start) begin
                dispatch_idx <= {6{1'b0}};
                write_step   <= {4{1'b0}};
            end
            if (state == S_NEXT_STEP) begin
                if (write_step == LAST_STEP) begin
                    write_step <= {4{1'b0}};
                end else begin
                    write_step <= write_step + 1'b1;
                end
            end
            if (state == S_NEXT_DISP && dispatch_idx != LAST_DISPATCH) begin
                dispatch_idx <= dispatch_idx + 1'b1;
            end
            // Latch per-channel handshake acks while in S_WRITE; clear
            // when leaving S_WRITE so the next register write starts fresh.
            if (state == S_WRITE) begin
                if (s_axil_awvalid && s_axil_awready) aw_acked_r <= 1'b1;
                if (s_axil_wvalid  && s_axil_wready)  w_acked_r  <= 1'b1;
            end else begin
                aw_acked_r <= 1'b0;
                w_acked_r  <= 1'b0;
            end
        end
    end

    // ------------------------------------------------------------
    // Output assignments
    // ------------------------------------------------------------
    always @(*) begin
        s_axil_awvalid          = 1'b0;
        s_axil_awaddr           = 8'd0;
        s_axil_wvalid           = 1'b0;
        s_axil_wdata            = 32'd0;
        s_axil_wstrb            = 4'b1111;
        s_axil_bready           = 1'b0;
        engine_start            = 1'b0;
        done                    = 1'b0;
        spatial_stall           = 1'b0;
        engine_output_ready     = 1'b0;
        input_bank_sel          = input_bank_rom;
        output_bank_sel         = output_bank_rom;
        skip_bank_reserved_mask = skip_mask_rom;

        case (state)
            S_IDLE: begin
                spatial_stall = 1'b0;
            end
            // Single S_WRITE: drive AW and W simultaneously. Hold each
            // valid line high until its respective handshake fires, then
            // (per the FSM next-state logic) wait for the other before
            // transitioning to S_WRITE_RESP.
            S_WRITE: begin
                s_axil_awvalid = ~aw_acked_r;
                s_axil_awaddr  = step_addr;
                s_axil_wvalid  = ~w_acked_r;
                s_axil_wdata   = step_data;
                s_axil_wstrb   = 4'b1111;
                spatial_stall  = 1'b1;
            end
            S_WRITE_RESP: begin
                s_axil_bready = 1'b1;
                spatial_stall = 1'b1;
            end
            S_NEXT_STEP: begin
                spatial_stall = 1'b1;
            end
            S_WAIT_LOAD: begin
                spatial_stall = 1'b0; // let the spatial chain keep filling the loader BRAM
            end
            S_PULSE_START: begin
                // Fix 11: CONTROL.start AXI write is removed; this pin is now
                // the SOLE engine-start trigger. We reach here only after
                // S_WAIT_LOAD has observed current_loaded, so the activation
                // BRAM is guaranteed populated for this dispatch.
                engine_start  = 1'b1;
                spatial_stall = 1'b1;
            end
            S_WAIT_DONE: begin
                spatial_stall = 1'b0;  // [OVERLAP-FIX] run the spatial chain DURING engine compute so engine->spatial dispatch outputs (SLOT-1..33) drain into the running chain (same reasoning as S_WAIT_DRAIN below). Engine writes act-BRAM directly at arbiter priority -> hazard-safe; verify byte-exact e2e.
            end
            S_WAIT_DRAIN: begin
                // Fix 14: chain MUST run so the bridge can drain the
                // engine_output_fifo and feed downstream relu/add layers.
                spatial_stall = 1'b0;
            end
            S_NEXT_DISP: begin
                spatial_stall       = 1'b1;
                engine_output_ready = 1'b1;
            end
            S_DONE: begin
                done                = 1'b1;
            end
            default: begin
                spatial_stall = 1'b0;
            end
        endcase
    end

    wire _unused_s_axil_bresp = |s_axil_bresp;

endmodule
