import { execFile } from "node:child_process";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

import type { PipelineIR, VerificationSidecar, VerifResult, VerilogModule } from "./types.js";

const execFileAsync = promisify(execFile);

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

async function withTempDir<T>(prefix: string, fn: (tempDir: string) => Promise<T>): Promise<T> {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), prefix));
  try {
    return await fn(tempDir);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

function stderrFromUnknown(error: unknown): string {
  if (typeof error === "object" && error !== null && "stderr" in error) {
    const stderr = (error as { stderr?: string | Buffer }).stderr;
    if (typeof stderr === "string") {
      return stderr;
    }
    if (stderr instanceof Buffer) {
      return stderr.toString("utf8");
    }
  }

  if (error instanceof Error) {
    return error.message;
  }

  return String(error);
}

function resolveOutputRoot(outputDir: string): string {
  return path.resolve(process.cwd(), outputDir);
}

export async function run_iverilog(
  verilog_source: string,
  module_name: string,
): Promise<{ success: boolean; stderr: string }> {
  // TODO: Write verilog_source to a temp file, run `iverilog -o /dev/null -g2012 <tempfile>`, capture stderr, and return success based on the exit code.
  return withTempDir("nn2rtl-iverilog-", async (tempDir) => {
    const verilogPath = path.join(tempDir, `${module_name}.v`);
    await writeFile(verilogPath, verilog_source, "utf8");

    try {
      await execFileAsync("iverilog", ["-o", os.devNull, "-g2012", verilogPath], {
        cwd: tempDir,
      });
      return { success: true, stderr: "" };
    } catch (error: unknown) {
      return { success: false, stderr: stderrFromUnknown(error) };
    }
  });
}

export async function run_verilator(
  verilog_source: string,
  module_name: string,
  sidecar_path: string,
): Promise<VerifResult> {
  // TODO: Write verilog_source to a temp file, load the JSON sidecar generated by Assayer, copy the static C++ testbench template, run `verilator --cc --exe --build`, execute the binary, parse the structured results JSON, and return a complete VerifResult including timing checks.
  return withTempDir("nn2rtl-verilator-", async (tempDir) => {
    const verilogPath = path.join(tempDir, `${module_name}.v`);
    await writeFile(verilogPath, verilog_source, "utf8");
    const sidecar = await readJsonFileIfPresent<VerificationSidecar>(sidecar_path);

    try {
      await execFileAsync("verilator", ["--lint-only", verilogPath], { cwd: tempDir });
    } catch (error: unknown) {
      return {
        module_id: module_name,
        status: "syntax_error",
        timing_pass: false,
        timing_actual_cycles: 0,
        timing_expected_cycles: sidecar?.pipeline_latency_cycles ?? 0,
        verilator_stderr: stderrFromUnknown(error),
        fix_hint: "Verilator lint failed before stimulus generation could run.",
      };
    }

    return {
      module_id: module_name,
      status: "fail",
      timing_pass: false,
      timing_actual_cycles: 0,
      timing_expected_cycles: sidecar?.pipeline_latency_cycles ?? 0,
      expected: [],
      got: [],
      max_error: Number.POSITIVE_INFINITY,
      mean_error: Number.POSITIVE_INFINITY,
      failure_class: null,
      fix_hint:
        "run_verilator is scaffolded but still needs the static testbench copy, sidecar-driven build, binary execution, and results parser.",
    };
  });
}

export async function run_yosys(
  verilog_source: string,
  module_name: string,
): Promise<{ success: boolean; lut_count: number; fmax_mhz: number; report: string }> {
  // TODO: Write verilog_source to a temp file, run `yosys -p "synth_ice40 -abc9; stat" <tempfile>`, parse the report for LUT count and critical-path-derived Fmax, and return the raw report text alongside the parsed metrics.
  return withTempDir("nn2rtl-yosys-", async (tempDir) => {
    const verilogPath = path.join(tempDir, `${module_name}.v`);
    await writeFile(verilogPath, verilog_source, "utf8");

    try {
      const { stdout, stderr } = await execFileAsync(
        "yosys",
        ["-p", "synth_ice40 -abc9; stat", verilogPath],
        { cwd: tempDir },
      );

      const report = [stdout, stderr].filter(Boolean).join("\n");
      const lutMatch = report.match(/LUT4\s+(\d+)/);
      const fmaxMatch = report.match(/([0-9]+(?:\.[0-9]+)?)\s*MHz/i);
      return {
        success: true,
        lut_count: lutMatch ? Number(lutMatch[1]) : 0,
        fmax_mhz: fmaxMatch ? Number(fmaxMatch[1]) : 0,
        report,
      };
    } catch (error: unknown) {
      return {
        success: false,
        lut_count: 0,
        fmax_mhz: 0,
        report: stderrFromUnknown(error),
      };
    }
  });
}

export async function read_weights(
  checkpoint_path: string,
  quantization_config: object,
): Promise<PipelineIR> {
  // TODO: Spawn `python3 scripts/generate_golden.py <checkpoint_path>` as a child process, wait for completion, ensure the script also emitted weight and bias hex files under output/weights, and parse output/golden_vectors.json as PipelineIR.
  const scriptPath = path.join(repoRoot, "scripts", "generate_golden.py");
  const outputPath = path.join(repoRoot, "output", "golden_vectors.json");

  await execFileAsync("python3", [scriptPath, checkpoint_path], {
    cwd: repoRoot,
    env: {
      ...process.env,
      NN2RTL_QUANTIZATION_CONFIG: JSON.stringify(quantization_config),
    },
  });

  const raw = await readFile(outputPath, "utf8");
  return JSON.parse(raw) as PipelineIR;
}

export async function write_verilog(
  module: VerilogModule,
  output_dir: string,
): Promise<string> {
  // TODO: Compute the file path as `<output_dir>/rtl/<module.module_id>.v`, write the Verilog source there, emit the metadata JSON alongside it, and return the absolute RTL file path.
  const outputRoot = resolveOutputRoot(output_dir);
  const rtlDir = path.join(outputRoot, "rtl");
  const verilogPath = path.join(rtlDir, `${module.module_id}.v`);
  const metadataPath = path.join(rtlDir, `${module.module_id}.meta.json`);

  await mkdir(rtlDir, { recursive: true });
  await writeFile(verilogPath, module.verilog_source, "utf8");
  await writeFile(metadataPath, `${JSON.stringify(module, null, 2)}\n`, "utf8");

  return verilogPath;
}

async function readJsonFileIfPresent<T>(filePath: string): Promise<T | null> {
  try {
    const raw = await readFile(filePath, "utf8");
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}
