// nn2rtl_top — auto-generated top-level wrapper for resnet8
// Generated by scripts/build_top_wrapper.ts.
// Source LayerIR:    output/resnet8/layer_ir.json
// Heavy module list: D:\RTL_LLM_CLAUDE\nn2rtl-repo\output\resnet8\engine_modules_empty.txt
// Skip-FIFO sizes:   output/wrapper/skip_fifo_sizes.json
// Weight memory map: output/resnet8/weights/weight_memory_map.json
// Layers total: 21, spatial: 21, engine-dispatched: 0, residual adds: 3, projection convs: 2.
//
// This file is deterministically regenerated; do not edit by hand.

`timescale 1ns/1ps

`define NN2RTL_ENGINE_SUBBLOCKS_PROVIDED

module nn2rtl_top (
    input  wire                clk,
    input  wire                rst_n,

    // AXI4-Stream image input (network input)
    input  wire                s_axis_tvalid,
    output wire                s_axis_tready,
    input  wire [23:0]         s_axis_tdata,
    input  wire                s_axis_tlast,

    // AXI4-Stream feature output (final layer's data_out)
    output wire                m_axis_tvalid,
    input  wire                m_axis_tready,
    output wire [79:0]         m_axis_tdata,
    output wire                m_axis_tlast,

    // AXI4-Lite control slave (forwarded to shared_engine)
    input  wire                s_axil_awvalid,
    output wire                s_axil_awready,
    input  wire [31:0]         s_axil_awaddr,
    input  wire                s_axil_wvalid,
    output wire                s_axil_wready,
    input  wire [31:0]         s_axil_wdata,
    input  wire [3:0]          s_axil_wstrb,
    output wire                s_axil_bvalid,
    input  wire                s_axil_bready,
    output wire [1:0]          s_axil_bresp,
    input  wire                s_axil_arvalid,
    output wire                s_axil_arready,
    input  wire [31:0]         s_axil_araddr,
    output wire                s_axil_rvalid,
    input  wire                s_axil_rready,
    output wire [31:0]         s_axil_rdata,
    output wire [1:0]          s_axil_rresp
);

    // ----- network input (PIXEL_IN) -----
    wire [23:0] PIXEL_IN_data  = s_axis_tdata;
    wire                       PIXEL_IN_valid = s_axis_tvalid;

    // ----- per-layer stream wires -----
    wire node_conv2d_valid_out;
    wire [127:0] node_conv2d_data_out;
    wire node_conv2d_ready_in;
    wire node_relu_valid_out;
    wire [127:0] node_relu_data_out;
    wire node_relu_ready_in;
    wire node_conv2d_1_valid_out;
    wire [127:0] node_conv2d_1_data_out;
    wire node_conv2d_1_ready_in;
    wire node_relu_1_valid_out;
    wire [127:0] node_relu_1_data_out;
    wire node_relu_1_ready_in;
    wire node_conv2d_2_valid_out;
    wire [127:0] node_conv2d_2_data_out;
    wire node_conv2d_2_ready_in;
    wire node_add_25_valid_out;
    wire [127:0] node_add_25_data_out;
    wire node_add_25_ready_in;
    wire node_relu_2_valid_out;
    wire [127:0] node_relu_2_data_out;
    wire node_relu_2_ready_in;
    wire node_conv2d_3_valid_out;
    wire [255:0] node_conv2d_3_data_out;
    wire node_conv2d_3_ready_in;
    wire node_conv2d_4_valid_out;
    wire [255:0] node_conv2d_4_data_out;
    wire node_conv2d_4_ready_in;
    wire node_relu_3_valid_out;
    wire [255:0] node_relu_3_data_out;
    wire node_relu_3_ready_in;
    wire node_conv2d_5_valid_out;
    wire [255:0] node_conv2d_5_data_out;
    wire node_conv2d_5_ready_in;
    wire node_add_56_valid_out;
    wire [255:0] node_add_56_data_out;
    wire node_add_56_ready_in;
    wire node_relu_4_valid_out;
    wire [255:0] node_relu_4_data_out;
    wire node_relu_4_ready_in;
    wire node_conv2d_6_valid_out;
    wire [511:0] node_conv2d_6_data_out;
    wire node_conv2d_6_ready_in;
    wire node_conv2d_7_valid_out;
    wire [511:0] node_conv2d_7_data_out;
    wire node_conv2d_7_ready_in;
    wire node_relu_5_valid_out;
    wire [511:0] node_relu_5_data_out;
    wire node_relu_5_ready_in;
    wire node_conv2d_8_valid_out;
    wire [511:0] node_conv2d_8_data_out;
    wire node_conv2d_8_ready_in;
    wire node_add_87_valid_out;
    wire [511:0] node_add_87_data_out;
    wire node_add_87_ready_in;
    wire node_relu_6_valid_out;
    wire [511:0] node_relu_6_data_out;
    wire node_relu_6_ready_in;
    wire node_mean_valid_out;
    wire [511:0] node_mean_data_out;
    wire node_mean_ready_in;
    wire node_linear_valid_out;
    wire [79:0] node_linear_data_out;
    wire node_linear_ready_in;

    // ----- skip-FIFO outputs (one per residual add) -----
    wire node_add_25_skip_valid;
    wire [127:0] node_add_25_skip_data;
    wire node_add_56_skip_valid;
    wire [255:0] node_add_56_skip_data;
    wire node_add_87_skip_valid;
    wire [511:0] node_add_87_skip_data;

    // ----- shared_engine internal port wires (driven by engine/scheduler) -----
    wire [15:0]                engine_act_in_rd_addr;
    wire [2047:0]              engine_act_in_rd_data;
    wire                       engine_act_in_rd_en;
    wire [15:0]                engine_act_out_wr_addr;
    wire [2047:0]              engine_act_out_wr_data;
    wire                       engine_act_out_wr_en;
    wire [21:0]                engine_weight_rd_addr;
    wire                       engine_weight_rd_en;
    wire [2047:0]              engine_weight_rd_data;
    wire [21:0]                engine_bias_rd_addr;
    wire                       engine_bias_rd_en;
    wire [8191:0]              engine_bias_rd_data;
    wire [21:0]                engine_scale_rd_addr;
    wire                       engine_scale_rd_en;
    wire [8191:0]              engine_scale_rd_data;
    wire                       engine_start;
    wire                       engine_busy;
    wire                       engine_done;

    // ----- scheduler ↔ engine AXI4-Lite master/slave bundle (Fix 6) -----
    wire        sched_axil_awvalid;
    wire        sched_axil_awready;
    wire [7:0]  sched_axil_awaddr;
    wire        sched_axil_wvalid;
    wire        sched_axil_wready;
    wire [31:0] sched_axil_wdata;
    wire [3:0]  sched_axil_wstrb;
    wire        sched_axil_bvalid;
    wire        sched_axil_bready;
    wire [1:0]  sched_axil_bresp;
    wire [2:0]  sched_input_bank_sel;
    wire [2:0]  sched_output_bank_sel;
    wire [5:0]  sched_skip_bank_reserved_mask;
    wire        sched_spatial_stall;
    wire        sched_engine_output_ready;
    wire        sched_done;
    wire [0:0] sched_dispatch_idx;
    wire current_loaded;
    wire current_drain_complete;

    // ----- scheduler 'start' one-shot from first accepted input beat (Fix 6) -----
    // Per task 13a Fix 6: easiest source for the scheduler's start is the
    // first cycle the host's image stream is accepted (s_axis_tvalid &&
    // s_axis_tready). Latched so we don't re-pulse on every subsequent beat.
    reg sched_started_r;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) sched_started_r <= 1'b0;
        else if (s_axis_tvalid && s_axis_tready) sched_started_r <= 1'b1;
    end
    wire sched_start = s_axis_tvalid & s_axis_tready & ~sched_started_r;

    // ----- host AXI4-Lite to engine: TIED OFF in Phase 2 first-light -----
    // The scheduler is the engine's sole AXI master right now; muxing the
    // host in is task 13's concern. Hold every host *_ready / *_valid low
    // so any external host that tries to write never sees a handshake.
    assign s_axil_awready = 1'b0;
    assign s_axil_wready  = 1'b0;
    assign s_axil_bvalid  = 1'b0;
    assign s_axil_bresp   = 2'b00;
    assign s_axil_arready = 1'b0;
    assign s_axil_rvalid  = 1'b0;
    assign s_axil_rdata   = 32'd0;
    assign s_axil_rresp   = 2'b00;

    // ----- scheduler instantiation (Fix 6) -----
    nn2rtl_scheduler u_scheduler (
        .clk(clk), .rst_n(rst_n),
        .start(sched_start),
        .done(sched_done),
        .s_axil_awvalid(sched_axil_awvalid),
        .s_axil_awready(sched_axil_awready),
        .s_axil_awaddr(sched_axil_awaddr),
        .s_axil_wvalid(sched_axil_wvalid),
        .s_axil_wready(sched_axil_wready),
        .s_axil_wdata(sched_axil_wdata),
        .s_axil_wstrb(sched_axil_wstrb),
        .s_axil_bvalid(sched_axil_bvalid),
        .s_axil_bready(sched_axil_bready),
        .s_axil_bresp(sched_axil_bresp),
        .engine_start(engine_start),
        .engine_busy(engine_busy),
        .engine_done(engine_done),
        .current_loaded(current_loaded),
        .current_drain_complete(current_drain_complete),
        .dispatch_idx_out(sched_dispatch_idx),
        .input_bank_sel(sched_input_bank_sel),
        .output_bank_sel(sched_output_bank_sel),
        .skip_bank_reserved_mask(sched_skip_bank_reserved_mask),
        .spatial_stall(sched_spatial_stall),
        .engine_output_ready(sched_engine_output_ready)
    );

    // ----- task 04c: spatial_throttle = engine_busy -----
    // While the engine is processing a heavy layer, every spatial
    // module's incoming valid handshake is gated low. This freezes
    // the entire spatial chain so the skip FIFOs do not accumulate
    // during engine windows, which lets the bounded FIFO depths
    // chosen in output/wrapper/skip_fifo_sizes.json fit U250's
    // on-chip memory budget. The gate is harmless for blocks with
    // no engine dispatches: engine_busy stays low for those phases.
    wire spatial_throttle = engine_busy | sched_spatial_stall;
    wire spatial_run      = ~spatial_throttle;

    assign s_axis_tready = node_conv2d_ready_in & spatial_run;

    // ----- spatial module instantiations -----
    node_conv2d u_node_conv2d (
        .clk(clk), .rst_n(rst_n),
        .valid_in(PIXEL_IN_valid & spatial_run),
        .ready_in(node_conv2d_ready_in),
        .data_in(PIXEL_IN_data),
        .valid_out(node_conv2d_valid_out),
        .data_out(node_conv2d_data_out)
    );

    node_relu u_node_relu (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_valid_out & spatial_run),
        .ready_in(node_relu_ready_in),
        .data_in(node_conv2d_data_out),
        .valid_out(node_relu_valid_out),
        .data_out(node_relu_data_out)
    );

    // [CONV INPUT FIFO] inserted by apply_resnet8_conv_input_fifos.py (skip)
    wire node_conv2d_1_infifo_out_valid;
    wire [127:0] node_conv2d_1_infifo_out_data;
    wire node_conv2d_1_infifo_in_ready;
    bram_fifo #(.WIDTH(128), .DEPTH(1024)) u_infifo_node_conv2d_1 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_relu_valid_out & spatial_run & node_conv2d_1_infifo_in_ready),
        .in_data(node_relu_data_out[127:0]),
        .in_ready(node_conv2d_1_infifo_in_ready),
        .out_valid(node_conv2d_1_infifo_out_valid),
        .out_data(node_conv2d_1_infifo_out_data),
        .out_ready(node_conv2d_1_ready_in)
    );

    node_conv2d_1 u_node_conv2d_1 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_1_infifo_out_valid),
        .ready_in(node_conv2d_1_ready_in),
        .data_in(node_conv2d_1_infifo_out_data),
        .valid_out(node_conv2d_1_valid_out),
        .data_out(node_conv2d_1_data_out)
    );

    node_relu_1 u_node_relu_1 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_1_valid_out & spatial_run),
        .ready_in(node_relu_1_ready_in),
        .data_in(node_conv2d_1_data_out),
        .valid_out(node_relu_1_valid_out),
        .data_out(node_relu_1_data_out)
    );

    // [CONV INPUT FIFO] inserted by apply_resnet8_conv_input_fifos.py (frame)
    wire node_conv2d_2_infifo_out_valid;
    wire [127:0] node_conv2d_2_infifo_out_data;
    wire node_conv2d_2_infifo_in_ready;
    bram_fifo #(.WIDTH(128), .DEPTH(2048)) u_infifo_node_conv2d_2 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_relu_1_valid_out & spatial_run & node_conv2d_2_infifo_in_ready),
        .in_data(node_relu_1_data_out[127:0]),
        .in_ready(node_conv2d_2_infifo_in_ready),
        .out_valid(node_conv2d_2_infifo_out_valid),
        .out_data(node_conv2d_2_infifo_out_data),
        .out_ready(node_conv2d_2_ready_in)
    );

    node_conv2d_2 u_node_conv2d_2 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_2_infifo_out_valid),
        .ready_in(node_conv2d_2_ready_in),
        .data_in(node_conv2d_2_infifo_out_data),
        .valid_out(node_conv2d_2_valid_out),
        .data_out(node_conv2d_2_data_out)
    );

    // residual add: lhs (LOW half) from skip FIFO, rhs (HIGH half) from main path
    node_add_25 u_node_add_25 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_2_valid_out & node_add_25_skip_valid & spatial_run),
        .ready_in(node_add_25_ready_in),
        .data_in({node_conv2d_2_data_out[127:0], node_add_25_skip_data}),
        .valid_out(node_add_25_valid_out),
        .data_out(node_add_25_data_out)
    );

    node_relu_2 u_node_relu_2 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_add_25_valid_out & spatial_run),
        .ready_in(node_relu_2_ready_in),
        .data_in(node_add_25_data_out),
        .valid_out(node_relu_2_valid_out),
        .data_out(node_relu_2_data_out)
    );

    // [CONV INPUT FIFO] inserted by apply_resnet8_conv_input_fifos.py (frame)
    wire node_conv2d_3_infifo_out_valid;
    wire [127:0] node_conv2d_3_infifo_out_data;
    wire node_conv2d_3_infifo_in_ready;
    bram_fifo #(.WIDTH(128), .DEPTH(2048)) u_infifo_node_conv2d_3 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_relu_2_valid_out & spatial_run & node_conv2d_3_infifo_in_ready),
        .in_data(node_relu_2_data_out[127:0]),
        .in_ready(node_conv2d_3_infifo_in_ready),
        .out_valid(node_conv2d_3_infifo_out_valid),
        .out_data(node_conv2d_3_infifo_out_data),
        .out_ready(node_conv2d_3_ready_in)
    );

    node_conv2d_3 u_node_conv2d_3 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_3_infifo_out_valid),
        .ready_in(node_conv2d_3_ready_in),
        .data_in(node_conv2d_3_infifo_out_data),
        .valid_out(node_conv2d_3_valid_out),
        .data_out(node_conv2d_3_data_out)
    );

    // [CONV INPUT FIFO] inserted by apply_resnet8_conv_input_fifos.py (skip)
    wire node_conv2d_4_infifo_out_valid;
    wire [127:0] node_conv2d_4_infifo_out_data;
    wire node_conv2d_4_infifo_in_ready;
    bram_fifo #(.WIDTH(128), .DEPTH(1024)) u_infifo_node_conv2d_4 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_relu_2_valid_out & spatial_run & node_conv2d_4_infifo_in_ready),
        .in_data(node_relu_2_data_out[127:0]),
        .in_ready(node_conv2d_4_infifo_in_ready),
        .out_valid(node_conv2d_4_infifo_out_valid),
        .out_data(node_conv2d_4_infifo_out_data),
        .out_ready(node_conv2d_4_ready_in)
    );

    node_conv2d_4 u_node_conv2d_4 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_4_infifo_out_valid),
        .ready_in(node_conv2d_4_ready_in),
        .data_in(node_conv2d_4_infifo_out_data),
        .valid_out(node_conv2d_4_valid_out),
        .data_out(node_conv2d_4_data_out)
    );

    node_relu_3 u_node_relu_3 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_4_valid_out & spatial_run),
        .ready_in(node_relu_3_ready_in),
        .data_in(node_conv2d_4_data_out),
        .valid_out(node_relu_3_valid_out),
        .data_out(node_relu_3_data_out)
    );

    // [CONV INPUT FIFO] inserted by apply_resnet8_conv_input_fifos.py (skip)
    wire node_conv2d_5_infifo_out_valid;
    wire [255:0] node_conv2d_5_infifo_out_data;
    wire node_conv2d_5_infifo_in_ready;
    bram_fifo #(.WIDTH(256), .DEPTH(256)) u_infifo_node_conv2d_5 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_relu_3_valid_out & spatial_run & node_conv2d_5_infifo_in_ready),
        .in_data(node_relu_3_data_out[255:0]),
        .in_ready(node_conv2d_5_infifo_in_ready),
        .out_valid(node_conv2d_5_infifo_out_valid),
        .out_data(node_conv2d_5_infifo_out_data),
        .out_ready(node_conv2d_5_ready_in)
    );

    node_conv2d_5 u_node_conv2d_5 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_5_infifo_out_valid),
        .ready_in(node_conv2d_5_ready_in),
        .data_in(node_conv2d_5_infifo_out_data),
        .valid_out(node_conv2d_5_valid_out),
        .data_out(node_conv2d_5_data_out)
    );

    // [ADD56 MAIN-OPERAND FIFO] inserted by apply_resnet8_add56_main_fifo.py
    // Buffers the serialized conv_5 (main) operand so node_add_56 can pair it with
    // the skip operand (projection conv_3) at its own pace. Without this, conv_5's
    // 1-cycle valid_out pulses (no output backpressure) miss the skip-valid window
    // and are dropped -> add_56 starves. Two-FIFO join, immune to operand skew.
    // DEPTH=512 >= the 256-pixel stage-2 frame so the FIFO never fills during
    // conv_5's 256 outputs (its in_ready stays high -> no dropped outputs).
    wire node_add_56_main_valid;
    wire [255:0] node_add_56_main_data;
    wire node_add_56_main_in_ready;
    bram_fifo #(.WIDTH(256), .DEPTH(512)) u_main_node_add_56 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_conv2d_5_valid_out & spatial_run & node_add_56_main_in_ready),
        .in_data(node_conv2d_5_data_out[255:0]),
        .in_ready(node_add_56_main_in_ready),
        .out_valid(node_add_56_main_valid),
        .out_data(node_add_56_main_data),
        .out_ready(node_add_56_skip_valid & node_add_56_ready_in)
    );

    // residual add: lhs (LOW half) from skip FIFO, rhs (HIGH half) from main FIFO
    node_add_56 u_node_add_56 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_add_56_main_valid & node_add_56_skip_valid),
        .ready_in(node_add_56_ready_in),
        .data_in({node_add_56_main_data, node_add_56_skip_data}),
        .valid_out(node_add_56_valid_out),
        .data_out(node_add_56_data_out)
    );

    node_relu_4 u_node_relu_4 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_add_56_valid_out & spatial_run),
        .ready_in(node_relu_4_ready_in),
        .data_in(node_add_56_data_out),
        .valid_out(node_relu_4_valid_out),
        .data_out(node_relu_4_data_out)
    );

    // [CONV INPUT FIFO] inserted by apply_resnet8_conv_input_fifos.py (frame)
    wire node_conv2d_6_infifo_out_valid;
    wire [255:0] node_conv2d_6_infifo_out_data;
    wire node_conv2d_6_infifo_in_ready;
    bram_fifo #(.WIDTH(256), .DEPTH(512)) u_infifo_node_conv2d_6 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_relu_4_valid_out & spatial_run & node_conv2d_6_infifo_in_ready),
        .in_data(node_relu_4_data_out[255:0]),
        .in_ready(node_conv2d_6_infifo_in_ready),
        .out_valid(node_conv2d_6_infifo_out_valid),
        .out_data(node_conv2d_6_infifo_out_data),
        .out_ready(node_conv2d_6_ready_in)
    );

    node_conv2d_6 u_node_conv2d_6 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_6_infifo_out_valid),
        .ready_in(node_conv2d_6_ready_in),
        .data_in(node_conv2d_6_infifo_out_data),
        .valid_out(node_conv2d_6_valid_out),
        .data_out(node_conv2d_6_data_out)
    );

    // [CONV INPUT FIFO] inserted by apply_resnet8_conv_input_fifos.py (skip)
    wire node_conv2d_7_infifo_out_valid;
    wire [255:0] node_conv2d_7_infifo_out_data;
    wire node_conv2d_7_infifo_in_ready;
    bram_fifo #(.WIDTH(256), .DEPTH(256)) u_infifo_node_conv2d_7 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_relu_4_valid_out & spatial_run & node_conv2d_7_infifo_in_ready),
        .in_data(node_relu_4_data_out[255:0]),
        .in_ready(node_conv2d_7_infifo_in_ready),
        .out_valid(node_conv2d_7_infifo_out_valid),
        .out_data(node_conv2d_7_infifo_out_data),
        .out_ready(node_conv2d_7_ready_in)
    );

    node_conv2d_7 u_node_conv2d_7 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_7_infifo_out_valid),
        .ready_in(node_conv2d_7_ready_in),
        .data_in(node_conv2d_7_infifo_out_data),
        .valid_out(node_conv2d_7_valid_out),
        .data_out(node_conv2d_7_data_out)
    );

    node_relu_5 u_node_relu_5 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_7_valid_out & spatial_run),
        .ready_in(node_relu_5_ready_in),
        .data_in(node_conv2d_7_data_out),
        .valid_out(node_relu_5_valid_out),
        .data_out(node_relu_5_data_out)
    );

    // [CONV INPUT FIFO] inserted by apply_resnet8_conv_input_fifos.py (skip)
    wire node_conv2d_8_infifo_out_valid;
    wire [511:0] node_conv2d_8_infifo_out_data;
    wire node_conv2d_8_infifo_in_ready;
    bram_fifo #(.WIDTH(512), .DEPTH(64)) u_infifo_node_conv2d_8 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_relu_5_valid_out & spatial_run & node_conv2d_8_infifo_in_ready),
        .in_data(node_relu_5_data_out[511:0]),
        .in_ready(node_conv2d_8_infifo_in_ready),
        .out_valid(node_conv2d_8_infifo_out_valid),
        .out_data(node_conv2d_8_infifo_out_data),
        .out_ready(node_conv2d_8_ready_in)
    );

    node_conv2d_8 u_node_conv2d_8 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_conv2d_8_infifo_out_valid),
        .ready_in(node_conv2d_8_ready_in),
        .data_in(node_conv2d_8_infifo_out_data),
        .valid_out(node_conv2d_8_valid_out),
        .data_out(node_conv2d_8_data_out)
    );

    // [ADD87 MAIN-OPERAND FIFO] inserted by apply_resnet8_add87_main_fifo.py
    // Buffers the free-running conv_8 (main) operand so node_add_87 can pair it
    // with the LATE-arriving skip operand (projection conv_6). Two-FIFO join:
    // both FIFOs pop only when BOTH present, immune to operand arrival skew.
    wire node_add_87_main_valid;
    wire [511:0] node_add_87_main_data;
    wire node_add_87_main_in_ready;
    bram_fifo #(.WIDTH(512), .DEPTH(128)) u_main_node_add_87 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_conv2d_8_valid_out & spatial_run & node_add_87_main_in_ready),
        .in_data(node_conv2d_8_data_out[511:0]),
        .in_ready(node_add_87_main_in_ready),
        .out_valid(node_add_87_main_valid),
        .out_data(node_add_87_main_data),
        .out_ready(node_add_87_skip_valid & node_add_87_ready_in)
    );

    // residual add: lhs (LOW half) from skip FIFO, rhs (HIGH half) from main FIFO
    node_add_87 u_node_add_87 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_add_87_main_valid & node_add_87_skip_valid),
        .ready_in(node_add_87_ready_in),
        .data_in({node_add_87_main_data, node_add_87_skip_data}),
        .valid_out(node_add_87_valid_out),
        .data_out(node_add_87_data_out)
    );

    node_relu_6 u_node_relu_6 (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_add_87_valid_out & spatial_run),
        .ready_in(node_relu_6_ready_in),
        .data_in(node_add_87_data_out),
        .valid_out(node_relu_6_valid_out),
        .data_out(node_relu_6_data_out)
    );

    node_mean u_node_mean (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_relu_6_valid_out & spatial_run),
        .ready_in(node_mean_ready_in),
        .data_in(node_relu_6_data_out),
        .valid_out(node_mean_valid_out),
        .data_out(node_mean_data_out)
    );

    node_linear u_node_linear (
        .clk(clk), .rst_n(rst_n),
        .valid_in(node_mean_valid_out & spatial_run),
        .ready_in(node_linear_ready_in),
        .data_in(node_mean_data_out),
        .valid_out(node_linear_valid_out),
        .data_out(node_linear_data_out)
    );

    // ----- skip FIFOs (one per residual add) -----
    wire node_add_25_skip_in_ready;
    bram_fifo #(.WIDTH(128), .DEPTH(2048)) u_skip_node_add_25 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_relu_valid_out & spatial_run & node_add_25_skip_in_ready),
        .in_data(node_relu_data_out[127:0]),
        .in_ready(node_add_25_skip_in_ready),
        .out_valid(node_add_25_skip_valid),
        .out_data(node_add_25_skip_data),
        .out_ready(node_conv2d_2_valid_out & node_add_25_ready_in)
    );

    wire node_add_56_skip_in_ready;
    bram_fifo #(.WIDTH(256), .DEPTH(512)) u_skip_node_add_56 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_conv2d_3_valid_out & spatial_run & node_add_56_skip_in_ready),
        .in_data(node_conv2d_3_data_out[255:0]),
        .in_ready(node_add_56_skip_in_ready),
        .out_valid(node_add_56_skip_valid),
        .out_data(node_add_56_skip_data),
        .out_ready(node_add_56_main_valid & node_add_56_ready_in)
    );

    wire node_add_87_skip_in_ready;
    bram_fifo #(.WIDTH(512), .DEPTH(2048)) u_skip_node_add_87 (
        .clk(clk), .rst_n(rst_n),
        .in_valid(node_conv2d_6_valid_out & spatial_run & node_add_87_skip_in_ready),
        .in_data(node_conv2d_6_data_out[511:0]),
        .in_ready(node_add_87_skip_in_ready),
        .out_valid(node_add_87_skip_valid),
        .out_data(node_add_87_skip_data),
        .out_ready(node_add_87_main_valid & node_add_87_ready_in)
    );

    // ----- URAM-resident weight memory subsystem (Path D: 8 parallel banks) -----
    // Total MAC cycles = 0; per-bank depth = 0.
    // Address path: engine_weight_rd_addr[0:0] -> each bank's rd_addr.
    wire [0:0] weight_bank_rd_addr = engine_weight_rd_addr[0:0];
    wire [287:0] uram_bank0_rd_data;
    wire [287:0] uram_bank1_rd_data;
    wire [287:0] uram_bank2_rd_data;
    wire [287:0] uram_bank3_rd_data;
    wire [287:0] uram_bank4_rd_data;
    wire [287:0] uram_bank5_rd_data;
    wire [287:0] uram_bank6_rd_data;
    wire [287:0] uram_bank7_rd_data;

    // MAC bus = concat of the low 256 bits of each bank (bank 0 lowest).
    assign engine_weight_rd_data = {uram_bank7_rd_data[255:0],
        uram_bank6_rd_data[255:0],
        uram_bank5_rd_data[255:0],
        uram_bank4_rd_data[255:0],
        uram_bank3_rd_data[255:0],
        uram_bank2_rd_data[255:0],
        uram_bank1_rd_data[255:0],
        uram_bank0_rd_data[255:0]};

    uram_weight_bank #(
        .DEPTH(0),
        .ADDR_W(1),
        .MEM_INIT_FILE("output/resnet8/weights/uram_weights_bank0.mem")
    ) u_uram_weight_bank0 (
        .clk(clk),
        .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank0_rd_data),
        .rd_en(engine_weight_rd_en)
    );
    uram_weight_bank #(
        .DEPTH(0),
        .ADDR_W(1),
        .MEM_INIT_FILE("output/resnet8/weights/uram_weights_bank1.mem")
    ) u_uram_weight_bank1 (
        .clk(clk),
        .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank1_rd_data),
        .rd_en(engine_weight_rd_en)
    );
    uram_weight_bank #(
        .DEPTH(0),
        .ADDR_W(1),
        .MEM_INIT_FILE("output/resnet8/weights/uram_weights_bank2.mem")
    ) u_uram_weight_bank2 (
        .clk(clk),
        .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank2_rd_data),
        .rd_en(engine_weight_rd_en)
    );
    uram_weight_bank #(
        .DEPTH(0),
        .ADDR_W(1),
        .MEM_INIT_FILE("output/resnet8/weights/uram_weights_bank3.mem")
    ) u_uram_weight_bank3 (
        .clk(clk),
        .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank3_rd_data),
        .rd_en(engine_weight_rd_en)
    );
    uram_weight_bank #(
        .DEPTH(0),
        .ADDR_W(1),
        .MEM_INIT_FILE("output/resnet8/weights/uram_weights_bank4.mem")
    ) u_uram_weight_bank4 (
        .clk(clk),
        .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank4_rd_data),
        .rd_en(engine_weight_rd_en)
    );
    uram_weight_bank #(
        .DEPTH(0),
        .ADDR_W(1),
        .MEM_INIT_FILE("output/resnet8/weights/uram_weights_bank5.mem")
    ) u_uram_weight_bank5 (
        .clk(clk),
        .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank5_rd_data),
        .rd_en(engine_weight_rd_en)
    );
    uram_weight_bank #(
        .DEPTH(0),
        .ADDR_W(1),
        .MEM_INIT_FILE("output/resnet8/weights/uram_weights_bank6.mem")
    ) u_uram_weight_bank6 (
        .clk(clk),
        .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank6_rd_data),
        .rd_en(engine_weight_rd_en)
    );
    uram_weight_bank #(
        .DEPTH(0),
        .ADDR_W(1),
        .MEM_INIT_FILE("output/resnet8/weights/uram_weights_bank7.mem")
    ) u_uram_weight_bank7 (
        .clk(clk),
        .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank7_rd_data),
        .rd_en(engine_weight_rd_en)
    );

    // ----- bias memory (Fix 5: per-oc_pass wide bias word, 256 × INT32) -----
    bias_mem #(
        .SIZE_WORDS(256),
        .WORD_WIDTH(8192),
        .ADDR_W(8),
        .MEM_INIT_FILE("output/resnet8/weights/bias.mem")
    ) u_bias_mem (
        .clk(clk),
        .rd_addr(engine_bias_rd_addr[7:0]),
        .rd_data(engine_bias_rd_data),
        .rd_en(engine_bias_rd_en)
    );

    // ----- per-OC requant scale ROM (256 × {shift,mult} per oc_pass) -----
    bias_mem #(
        .SIZE_WORDS(256),
        .WORD_WIDTH(8192),
        .ADDR_W(8),
        .MEM_INIT_FILE("output/resnet8/weights/scale.mem")
    ) u_scale_mem (
        .clk(clk),
        .rd_addr(engine_scale_rd_addr[7:0]),
        .rd_data(engine_scale_rd_data),
        .rd_en(engine_scale_rd_en)
    );

    // ----- input-loader bridges (Fix 11: spatial-stream -> activation BRAM) -----
    // Each bridge captures one heavy dispatch's predecessor stream and
    // writes 2048-bit BRAM words into its dispatch's bank window.
    // ----- act BRAM write arbiter: engine priority, then bridges -----
    wire        act_wr_en_final;
    wire [14:0] act_wr_addr_final;
    wire [2047:0] act_wr_data_final;
    assign act_wr_en_final   = engine_act_out_wr_en;
    assign act_wr_addr_final = engine_act_out_wr_addr[14:0];
    assign act_wr_data_final = engine_act_out_wr_data;

    // ----- activation BRAM (Fix 8 + Fix 11: unified 6-bank URAM, 24576 × 2048b) -----
    act_unified_mem #(
        .DEPTH(24576),
        .ADDR_W(15)
    ) u_act_mem (
        .clk(clk),
        .rd_addr(engine_act_in_rd_addr[14:0]),
        .rd_en  (engine_act_in_rd_en),
        .rd_data(engine_act_in_rd_data),
        .wr_addr(act_wr_addr_final),
        .wr_en  (act_wr_en_final),
        .wr_data(act_wr_data_final)
    );
    wire _unused_act_in_addr_hi  = |engine_act_in_rd_addr[15:15];
    wire _unused_act_out_addr_hi = |engine_act_out_wr_addr[15:15];
    wire _unused_sched_bank_sels = |sched_input_bank_sel
                                  | |sched_output_bank_sel
                                  | |sched_skip_bank_reserved_mask;
    wire _unused_sched_done      = sched_done;

    // ----- per-dispatch loaded mux (Fix 11: scheduler waits before engine start) -----
    // The scheduler samples current_loaded in S_WAIT_LOAD to ensure the
    // input_loader bridge for the current dispatch has finished filling
    // the BRAM before pulsing engine_start.
    assign current_loaded = 1'b1;

    // ----- shared compute engine (handles 0 heavy modules) -----
    // Fix 6: AXI4-Lite slave is driven by u_scheduler, not by the host
    // top-level s_axil_*. The host bundle is tied off above. The read
    // channel is unused by the scheduler (write-only); ground it.
    shared_engine u_shared_engine (
        .clk(clk), .rst_n(rst_n),
        .s_axil_awvalid(sched_axil_awvalid), .s_axil_awready(sched_axil_awready), .s_axil_awaddr(sched_axil_awaddr),
        .s_axil_wvalid(sched_axil_wvalid),   .s_axil_wready(sched_axil_wready),   .s_axil_wdata(sched_axil_wdata),  .s_axil_wstrb(sched_axil_wstrb),
        .s_axil_bvalid(sched_axil_bvalid),   .s_axil_bready(sched_axil_bready),   .s_axil_bresp(sched_axil_bresp),
        .s_axil_arvalid(1'b0),               .s_axil_arready(),                   .s_axil_araddr(8'd0),
        .s_axil_rvalid(),                    .s_axil_rready(1'b0),                .s_axil_rdata(),              .s_axil_rresp(),
        .engine_start(engine_start),
        .engine_busy(engine_busy),
        .engine_done(engine_done),
        .act_in_rd_addr(engine_act_in_rd_addr),
        .act_in_rd_en(engine_act_in_rd_en),
        .act_in_rd_data(engine_act_in_rd_data),
        .act_out_wr_addr(engine_act_out_wr_addr),
        .act_out_wr_en(engine_act_out_wr_en),
        .act_out_wr_data(engine_act_out_wr_data),
        .weight_rd_addr(engine_weight_rd_addr),
        .weight_rd_en(engine_weight_rd_en),
        .weight_rd_data(engine_weight_rd_data),
        .bias_rd_addr(engine_bias_rd_addr),
        .bias_rd_en(engine_bias_rd_en),
        .bias_rd_data(engine_bias_rd_data),
        .scale_rd_addr(engine_scale_rd_addr),
        .scale_rd_en(engine_scale_rd_en),
        .scale_rd_data(engine_scale_rd_data)
    );

    // ----- shared engine output FIFO (Fix 14) -----
    wire        eofifo_in_ready;
    wire        eofifo_out_valid;
    wire [2047:0] eofifo_out_data;
    wire        eofifo_out_ready;
    engine_output_fifo #(
        .DEPTH(4096),
        .ADDR_W(12),
        .DATA_W(2048)
    ) u_engine_out_fifo (
        .clk(clk), .rst_n(rst_n),
        .in_valid(engine_act_out_wr_en),
        .in_data(engine_act_out_wr_data),
        .in_ready(eofifo_in_ready),
        .out_valid(eofifo_out_valid),
        .out_data(eofifo_out_data),
        .out_ready(eofifo_out_ready)
    );
    wire _unused_eofifo_in_ready = eofifo_in_ready;

    // ----- engine-output bridges (Fix 7 + Fix 14: FIFO-drain shims) -----
    assign eofifo_out_ready = 1'b0;

    // ----- per-dispatch drain_complete mux (Fix 14) -----
    wire [1:0] all_drain;
    assign all_drain[0] = 1'b1;
    assign all_drain[1] = 1'b1;
    assign current_drain_complete = all_drain[sched_dispatch_idx[0:0]];

    // ----- network output (Fix #4: tlast on final output beat) -----
    assign m_axis_tvalid = node_linear_valid_out;
    assign m_axis_tdata  = node_linear_data_out;
    // Output frame size: C=10 H=1 W=1, busOut=80b -> 1 beats
    reg [0:0] m_axis_beat_count;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            m_axis_beat_count <= 1'd0;
        end else if (m_axis_tvalid & m_axis_tready) begin
            if (m_axis_beat_count == 1'd0)
                m_axis_beat_count <= 1'd0;
            else
                m_axis_beat_count <= m_axis_beat_count + 1'd1;
        end
    end
    assign m_axis_tlast = (m_axis_beat_count == 1'd0);

endmodule

`ifndef NN2RTL_TOP_NO_STUBS
// ===== Wrapper-local module bodies (suppress with `define NN2RTL_TOP_NO_STUBS) =====

module skip_fifo #(
    parameter integer WIDTH = 8,
    parameter integer DEPTH = 16
) (
    input  wire              clk,
    input  wire              rst_n,
    input  wire              in_valid,
    input  wire [WIDTH-1:0]  in_data,
    output wire              in_ready,
    output wire              out_valid,
    output wire [WIDTH-1:0]  out_data,
    input  wire              out_ready
);
    // DEPTH must be a power of 2; ADDR_W = log2(DEPTH).
    function integer clog2;
        input integer value;
        integer v;
        begin
            v = value - 1;
            for (clog2 = 0; v > 0; clog2 = clog2 + 1) v = v >> 1;
        end
    endfunction
    localparam integer ADDR_W = clog2(DEPTH);

    (* ram_style = "distributed" *) reg [WIDTH-1:0] mem [0:DEPTH-1];
    reg [ADDR_W:0]  wr_ptr;
    reg [ADDR_W:0]  rd_ptr;

    wire [ADDR_W-1:0] wr_idx = wr_ptr[ADDR_W-1:0];
    wire [ADDR_W-1:0] rd_idx = rd_ptr[ADDR_W-1:0];
    wire empty = (wr_ptr == rd_ptr);
    // full when low bits match but top bit differs (one-extra-bit pointer trick).
    wire full  = (wr_ptr[ADDR_W] != rd_ptr[ADDR_W]) &&
                 (wr_ptr[ADDR_W-1:0] == rd_ptr[ADDR_W-1:0]);

    assign in_ready  = ~full;
    assign out_valid = ~empty;
    assign out_data  = mem[rd_idx];

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_ptr <= {(ADDR_W+1){1'b0}};
            rd_ptr <= {(ADDR_W+1){1'b0}};
        end else begin
            if (in_valid && ~full)        wr_ptr <= wr_ptr + 1'b1;
            if (out_ready && ~empty)      rd_ptr <= rd_ptr + 1'b1;
        end
    end

    // Array-memory write split out per knowledge/patterns/protected/08_common_bugs.md.
    always @(posedge clk) begin
        if (in_valid && ~full) mem[wr_idx] <= in_data;
    end
endmodule

// ---------------------------------------------------------------------------
// bram_fifo: FWFT FIFO with SYNCHRONOUS-read BRAM storage. Drop-in replacement
// for skip_fifo (identical ports + external contract). Storage moved off LUTRAM
// to BRAM to free LUTs. See scripts/apply_resnet8_fifo_bram.py.
// ---------------------------------------------------------------------------
module bram_fifo #(
    parameter integer WIDTH = 8,
    parameter integer DEPTH = 16
) (
    input  wire              clk,
    input  wire              rst_n,
    input  wire              in_valid,
    input  wire [WIDTH-1:0]  in_data,
    output wire              in_ready,
    output wire              out_valid,
    output wire [WIDTH-1:0]  out_data,
    input  wire              out_ready
);
    function integer clog2;
        input integer value;
        integer v;
        begin
            v = value - 1;
            for (clog2 = 0; v > 0; clog2 = clog2 + 1) v = v >> 1;
        end
    endfunction
    localparam integer ADDR_W = clog2(DEPTH);

    (* ram_style = "block" *) reg [WIDTH-1:0] mem [0:DEPTH-1];

    // Ring pointers (one extra bit for full/empty disambiguation).
    reg  [ADDR_W:0] wr_ptr;     // next write slot
    reg  [ADDR_W:0] rd_ptr;     // next slot to READ from BRAM (issued address)
    // Count of beats committed to BRAM but not yet pulled into the output skid.
    reg  [ADDR_W:0] mem_count;
    wire [ADDR_W-1:0] wr_idx = wr_ptr[ADDR_W-1:0];
    wire [ADDR_W-1:0] rd_idx = rd_ptr[ADDR_W-1:0];

    // ---- 2-entry output skid (FWFT) ----
    reg [WIDTH-1:0] out_reg;     // head-of-queue (presented on out_data)
    reg             out_reg_v;
    reg [WIDTH-1:0] skid_reg;    // second prefetched beat
    reg             skid_v;

    // BRAM sync read pipeline: when we issue a read, data arrives next cycle.
    reg             rd_issue_q;  // a read was issued last cycle -> mem_q valid now
    reg [WIDTH-1:0] mem_q;       // BRAM registered-read output

    wire push = in_valid && in_ready;
    wire pop  = out_valid && out_ready;

    // Occupancy for full: beats in BRAM + skid + outreg + the in-flight read.
    wire [ADDR_W+1:0] occupancy = mem_count
                                + (out_reg_v ? 1 : 0)
                                + (skid_v    ? 1 : 0)
                                + (rd_issue_q ? 1 : 0);
    wire full = (occupancy >= DEPTH);

    assign in_ready  = ~full;
    assign out_valid = out_reg_v;
    assign out_data  = out_reg;

    // Issue a BRAM read whenever a beat sits in BRAM and the 2-entry skid will
    // have room for it next cycle (a slot free now, or a pop frees the head now).
    wire skid_has_room = !(out_reg_v && skid_v) || pop;
    wire do_issue = (mem_count != 0) && skid_has_room && !rd_issue_q;

    // ---- BRAM access: write + registered read in ONE clocked block (no reset).
    // This is the canonical Vivado simple-dual-port BRAM template -> infers a
    // RAMB36 cleanly (the split-into-two-blocks form was dissolved to FFs).
    always @(posedge clk) begin
        if (push) mem[wr_idx] <= in_data;
        mem_q <= mem[rd_idx];
    end

    // ---- control / pointers / skid (FFs, async reset; NO memory access here) ----
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_ptr     <= {(ADDR_W+1){1'b0}};
            rd_ptr     <= {(ADDR_W+1){1'b0}};
            mem_count  <= {(ADDR_W+1){1'b0}};
            out_reg_v  <= 1'b0;
            skid_v     <= 1'b0;
            rd_issue_q <= 1'b0;
            out_reg    <= {WIDTH{1'b0}};
            skid_reg   <= {WIDTH{1'b0}};
        end else begin
            if (push)     wr_ptr <= wr_ptr + 1'b1;
            rd_issue_q <= do_issue;
            if (do_issue) rd_ptr <= rd_ptr + 1'b1;

            // skid / output update: pop -> shift skid -> accept freshly-read mem_q.
            begin : skid_update
                reg or_v;  reg [WIDTH-1:0] or_d;
                reg sk_v;  reg [WIDTH-1:0] sk_d;
                or_v = out_reg_v;  or_d = out_reg;
                sk_v = skid_v;     sk_d = skid_reg;
                if (pop) or_v = 1'b0;                      // head consumed
                if (!or_v && sk_v) begin                   // shift skid -> head
                    or_v = 1'b1; or_d = sk_d; sk_v = 1'b0;
                end
                if (rd_issue_q) begin                      // accept mem_q (valid now)
                    if (!or_v) begin or_v = 1'b1; or_d = mem_q; end
                    else if (!sk_v) begin sk_v = 1'b1; sk_d = mem_q; end
                end
                out_reg_v <= or_v;  out_reg  <= or_d;
                skid_v    <= sk_v;  skid_reg <= sk_d;
            end

            // mem_count: +1 on push, -1 when a beat is pulled from BRAM (do_issue).
            case ({push, do_issue})
                2'b10: mem_count <= mem_count + 1'b1;
                2'b01: mem_count <= mem_count - 1'b1;
                default: mem_count <= mem_count;
            endcase
        end
    end
endmodule


module uram_weight_bank #(
    parameter integer DEPTH         = 1024,
    parameter integer ADDR_W        = 17,
    parameter         MEM_INIT_FILE = ""
) (
    input  wire                    clk,
    input  wire [ADDR_W-1:0]       rd_addr,
    output wire [287:0]            rd_data,
    input  wire                    rd_en
);
generate
if (DEPTH <= 0) begin : g_empty_bank
    // Engine-less build (0 engine dispatches): this weight bank is inert — the
    // shared engine never reads it. Tie off to 0 instead of instantiating a
    // zero-size XPM URAM (MEMORY_SIZE must be > 0). Byte-exact: the spatial
    // datapath does not touch this bank, and opt_design prunes it.
    assign rd_data = 288'b0;
end else begin : g_real_bank
`ifdef NN2RTL_SYNTHESIS
    // Vivado-only: forces URAM via XPM. MEM_INIT_FILE is a .mem file.
    xpm_memory_sprom #(
        .ADDR_WIDTH_A(ADDR_W),
        .AUTO_SLEEP_TIME(0),
        .CASCADE_HEIGHT(0),
        .ECC_MODE("no_ecc"),
        .MEMORY_INIT_FILE(MEM_INIT_FILE),
        .MEMORY_INIT_PARAM(""),
        .MEMORY_OPTIMIZATION("true"),
        .MEMORY_PRIMITIVE("ultra"),
        .MEMORY_SIZE(DEPTH * 288),
        .MESSAGE_CONTROL(0),
        .READ_DATA_WIDTH_A(288),
        .READ_LATENCY_A(2),
        .READ_RESET_VALUE_A("0"),
        .RST_MODE_A("SYNC"),
        .SIM_ASSERT_CHK(0),
        .USE_MEM_INIT(1),
        .USE_MEM_INIT_MMI(0),
        .WAKEUP_TIME("disable_sleep")
    ) u_xpm (
        .douta(rd_data),
        .addra(rd_addr),
        .clka(clk),
        .ena(rd_en),
        .rsta(1'b0),
        .regcea(1'b1),
        .sleep(1'b0),
        .injectdbiterra(1'b0),
        .injectsbiterra(1'b0),
        .dbiterra(),
        .sbiterra()
    );
`else
    // Behavioral path for Verilator/iverilog. MEM_INIT_FILE is a .hex file.
    // 2-cycle read latency to match XPM URAM READ_LATENCY_A=2.
    reg [287:0] mem [0:DEPTH-1];
    initial begin
        if (MEM_INIT_FILE != "") $readmemh(MEM_INIT_FILE, mem);
    end
    reg [287:0] rd_data_r1, rd_data_r2;
    always @(posedge clk) begin
        if (rd_en) rd_data_r1 <= mem[rd_addr];
        rd_data_r2 <= rd_data_r1;
    end
    assign rd_data = rd_data_r2;
`endif
end
endgenerate
endmodule

module stream_to_act_bram_bridge #(
    parameter integer BUS_W            = 2048,
    parameter integer BRAM_BASE_ADDR   = 0,
    parameter integer TOTAL_BRAM_WORDS = 1
) (
    input  wire             clk,
    input  wire             rst_n,
    input  wire             in_valid,
    input  wire [BUS_W-1:0] in_data,
    output reg              wr_req,
    input  wire             wr_grant,
    output reg  [14:0]      wr_addr,
    output reg  [2047:0]    wr_data,
    output reg              loaded
);
    // Word counter (BRAM words written so far).
    reg [15:0] word_count;
    wire [15:0] next_word_count = word_count + 16'd1;
    // bridge_free pulses when wr_req is empty OR being granted this cycle.
    wire bridge_free = !wr_req || (wr_req && wr_grant);
    // wr_addr to use when bridge_free fires this cycle (use next_word_count
    // if a grant just retired the previous wr_req).
    wire [14:0] next_wr_addr = BRAM_BASE_ADDR[14:0]
                             + ((wr_req && wr_grant) ? next_word_count[14:0]
                                                     : word_count[14:0]);

    generate
    if (BUS_W == 2048) begin : g_w_eq
        // 13a audit fix (Fix 12): 1-deep producer-side skid buffer.
        // Previously the old "else if (in_valid && !wr_req)" guard dropped
        // every beat that arrived while wr_req was pending — including the
        // every-other-cycle case where grant+beat coincide. The skid lets
        // us accept a beat in cycle N while wr_data from cycle N-1 is
        // still on the bus, then submit it cycle N+1. Steady-state grant
        // yields one BRAM write per beat, lossless.
        //
        // Known limitation: multi-cycle grant denial (when several bridges
        // and the engine all contend) still drops beats after the skid
        // fills. For the ResNet-50 schedule's mild contention pattern this
        // is rare; a deeper FIFO can be added later if it becomes a hot
        // path in Verilator simulation.
        reg [2047:0] skid_data;
        reg          skid_valid;
        wire         drain_skid = skid_valid && bridge_free;
        always @(posedge clk or negedge rst_n) begin
            if (!rst_n) begin
                wr_req     <= 1'b0;
                wr_addr    <= 15'd0;
                wr_data    <= 2048'd0;
                word_count <= 16'd0;
                loaded     <= 1'b0;
                skid_valid <= 1'b0;
                skid_data  <= 2048'd0;
            end else begin
                // (1) Grant retires wr_req and advances count.
                if (wr_req && wr_grant) begin
                    wr_req <= 1'b0;
                    word_count <= next_word_count;
                    if (next_word_count == TOTAL_BRAM_WORDS) loaded <= 1'b1;
                end
                // (2) Drain skid into wr_req when bridge is free.
                if (drain_skid) begin
                    wr_req  <= 1'b1;
                    wr_addr <= next_wr_addr;
                    wr_data <= skid_data;
                end
                // (3) Capture new beat into skid; clear skid if drained and no new.
                if (in_valid && !loaded && (!skid_valid || drain_skid)) begin
                    skid_valid <= 1'b1;
                    skid_data  <= in_data;
                end else if (drain_skid) begin
                    skid_valid <= 1'b0;
                end
            end
        end
    end else if (BUS_W < 2048) begin : g_w_lt
        // Accumulate BEATS_PER_WORD beats into one BRAM word, with a
        // 1-deep producer-side skid so beats are not lost when the
        // BRAM write port is denied for a cycle.
        localparam integer BEATS_PER_WORD = 2048 / BUS_W;
        localparam integer BEAT_W = $clog2(BEATS_PER_WORD);
        reg [2047:0] accumulator;
        reg [BEAT_W:0] beat_idx;
        reg [BUS_W-1:0] skid_data;
        reg             skid_valid;
        // The accumulator absorbs a skid beat each cycle UNLESS the
        // beat would complete a new word AND wr_req is still pending
        // (then we have to hold the new word — currently we just stall
        // the accumulator until wr_req retires).
        wire would_complete = (beat_idx == BEATS_PER_WORD - 1);
        wire drain_skid = skid_valid && (!would_complete || bridge_free);
        always @(posedge clk or negedge rst_n) begin
            if (!rst_n) begin
                wr_req      <= 1'b0;
                wr_addr     <= 15'd0;
                wr_data     <= 2048'd0;
                word_count  <= 16'd0;
                accumulator <= 2048'd0;
                beat_idx    <= {(BEAT_W+1){1'b0}};
                loaded      <= 1'b0;
                skid_valid  <= 1'b0;
                skid_data   <= {BUS_W{1'b0}};
            end else begin
                // (1) Grant retires wr_req and advances count.
                if (wr_req && wr_grant) begin
                    wr_req <= 1'b0;
                    word_count <= next_word_count;
                    if (next_word_count == TOTAL_BRAM_WORDS) loaded <= 1'b1;
                end
                // (2) Drain skid into accumulator (and possibly emit word).
                if (drain_skid) begin
                    accumulator[beat_idx*BUS_W +: BUS_W] <= skid_data;
                    if (would_complete) begin
                        beat_idx <= {(BEAT_W+1){1'b0}};
                        wr_req   <= 1'b1;
                        wr_addr  <= next_wr_addr;
                        wr_data  <= { skid_data,
                                      accumulator[2048-BUS_W-1:0] };
                    end else begin
                        beat_idx <= beat_idx + 1'b1;
                    end
                end
                // (3) Capture new beat into skid.
                if (in_valid && !loaded && (!skid_valid || drain_skid)) begin
                    skid_valid <= 1'b1;
                    skid_data  <= in_data;
                end else if (drain_skid) begin
                    skid_valid <= 1'b0;
                end
            end
        end
    end else begin : g_w_gt
        // BUS_W > 2048: each beat carries WORDS_PER_BEAT BRAM words.
        // 1-deep skid lets a new beat be queued while the current
        // is still being sliced.
        localparam integer WORDS_PER_BEAT = BUS_W / 2048;
        localparam integer SLICE_W = $clog2(WORDS_PER_BEAT);
        reg [BUS_W-1:0] beat_buf;
        reg [SLICE_W:0] slice_idx;
        reg             buf_active;
        reg [BUS_W-1:0] skid_data;
        reg             skid_valid;
        wire beat_complete = buf_active && wr_req && wr_grant
                           && (slice_idx == WORDS_PER_BEAT - 1);
        wire can_load_new  = !buf_active || beat_complete;
        wire drain_skid    = skid_valid && can_load_new;
        always @(posedge clk or negedge rst_n) begin
            if (!rst_n) begin
                wr_req     <= 1'b0;
                wr_addr    <= 15'd0;
                wr_data    <= 2048'd0;
                word_count <= 16'd0;
                beat_buf   <= {BUS_W{1'b0}};
                slice_idx  <= {(SLICE_W+1){1'b0}};
                buf_active <= 1'b0;
                loaded     <= 1'b0;
                skid_valid <= 1'b0;
                skid_data  <= {BUS_W{1'b0}};
            end else begin
                // (1) Grant retires wr_req and advances count.
                if (wr_req && wr_grant) begin
                    wr_req <= 1'b0;
                    word_count <= next_word_count;
                    if (next_word_count == TOTAL_BRAM_WORDS) loaded <= 1'b1;
                    if (slice_idx == WORDS_PER_BEAT - 1) begin
                        slice_idx  <= {(SLICE_W+1){1'b0}};
                        buf_active <= 1'b0;
                    end else if (next_word_count != TOTAL_BRAM_WORDS) begin
                        // Continue slicing the current beat (defensive guard
                        // on next_word_count so we don't overrun TOTAL_BRAM_WORDS
                        // when a frame ends mid-beat with a non-divisible total).
                        slice_idx <= slice_idx + 1'b1;
                        wr_req    <= 1'b1;
                        wr_addr   <= BRAM_BASE_ADDR[14:0] + next_word_count[14:0];
                        wr_data   <= beat_buf[(slice_idx+1)*2048 +: 2048];
                    end
                end
                // (2) Load new beat from skid when buf is free.
                if (drain_skid) begin
                    beat_buf   <= skid_data;
                    buf_active <= 1'b1;
                    slice_idx  <= {(SLICE_W+1){1'b0}};
                    wr_req     <= 1'b1;
                    wr_addr    <= next_wr_addr;
                    wr_data    <= skid_data[2047:0];
                end
                // (3) Capture new beat into skid.
                if (in_valid && !loaded && (!skid_valid || drain_skid)) begin
                    skid_valid <= 1'b1;
                    skid_data  <= in_data;
                end else if (drain_skid) begin
                    skid_valid <= 1'b0;
                end
            end
        end
    end
    endgenerate
endmodule

module act_unified_mem #(
    parameter integer DEPTH  = 24576,
    parameter integer ADDR_W = 15
) (
    input  wire                    clk,
    input  wire [ADDR_W-1:0]       rd_addr,
    input  wire                    rd_en,
    output reg  [2047:0]           rd_data,
    input  wire [ADDR_W-1:0]       wr_addr,
    input  wire                    wr_en,
    input  wire [2047:0]           wr_data
);
    (* ram_style = "ultra" *) reg [2047:0] mem [0:DEPTH-1];
    always @(posedge clk) begin
        if (rd_en) rd_data <= mem[rd_addr];
    end
    // Array-memory write split into its own always block per
    // knowledge/patterns/protected/08_common_bugs.md §"Array memory
    // write in async-reset block" — no reset clause here.
    always @(posedge clk) begin
        if (wr_en) mem[wr_addr] <= wr_data;
    end
endmodule

module engine_output_fifo #(
    parameter integer DEPTH  = 4096,
    parameter integer ADDR_W = 12,             // log2(DEPTH)
    parameter integer DATA_W = 2048
) (
    input  wire             clk,
    input  wire             rst_n,
    input  wire             in_valid,
    input  wire [DATA_W-1:0] in_data,
    output wire             in_ready,
    output reg              out_valid,
    output reg  [DATA_W-1:0] out_data,
    input  wire             out_ready
);
    (* ram_style = "ultra" *) reg [DATA_W-1:0] mem [0:DEPTH-1];
    reg [ADDR_W:0] wr_ptr;
    reg [ADDR_W:0] rd_ptr;

    wire fifo_empty = (wr_ptr == rd_ptr);
    wire fifo_full  = (wr_ptr[ADDR_W-1:0] == rd_ptr[ADDR_W-1:0])
                    && (wr_ptr[ADDR_W] != rd_ptr[ADDR_W]);
    wire wr_fire = in_valid && !fifo_full;
    wire load_skid = !fifo_empty && (!out_valid || (out_valid && out_ready));
    assign in_ready = !fifo_full;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_ptr    <= {(ADDR_W+1){1'b0}};
            rd_ptr    <= {(ADDR_W+1){1'b0}};
            out_valid <= 1'b0;
            out_data  <= {DATA_W{1'b0}};
        end else begin
            if (wr_fire) wr_ptr <= wr_ptr + 1'b1;
            // Output handshake: drop valid when consumer accepts.
            if (out_valid && out_ready) begin
                out_valid <= 1'b0;
            end
            // Refill output skid when it is empty (or being consumed
            // this cycle) and the FIFO has data. rd_ptr advances on the
            // same edge so the next refill reads the next entry.
            if (load_skid) begin
                out_data  <= mem[rd_ptr[ADDR_W-1:0]];
                out_valid <= 1'b1;
                rd_ptr    <= rd_ptr + 1'b1;
            end
        end
    end
    // Memory write split into its own clock-only always block per
    // knowledge/patterns/protected/08_common_bugs.md.
    always @(posedge clk) begin
        if (wr_fire) mem[wr_ptr[ADDR_W-1:0]] <= in_data;
    end
endmodule

module bias_mem #(
    parameter integer SIZE_WORDS    = 256,
    parameter integer WORD_WIDTH    = 8192,
    parameter integer ADDR_W        = 16,
    parameter         MEM_INIT_FILE = "output/weights/bias.mem"
) (
    input  wire                    clk,
    input  wire [ADDR_W-1:0]       rd_addr,
    output reg  [WORD_WIDTH-1:0]   rd_data,
    input  wire                    rd_en
);
    (* ram_style = "block" *) reg [WORD_WIDTH-1:0] mem [0:SIZE_WORDS-1];
    initial begin
        if (MEM_INIT_FILE != "") $readmemh(MEM_INIT_FILE, mem);
    end
    always @(posedge clk) begin
        if (rd_en) rd_data <= mem[rd_addr];
    end
endmodule

module engine_output_bridge #(
    parameter integer SLOT           = 0,
    parameter integer ACT_W          = 2048,
    parameter integer DATA_W         = 2048,
    parameter integer EXPECTED_BEATS = 1,
    parameter integer NUM_DISPATCHES = 14
) (
    input  wire              clk,
    input  wire              rst_n,
    input  wire              start,                 // sched_engine_output_ready
    input  wire              fifo_out_valid,
    input  wire [ACT_W-1:0]  fifo_out_data,
    output wire              fifo_out_ready,
    input  wire              ready_out,             // downstream consumer's ready_in
    output reg               valid_out,
    output reg  [DATA_W-1:0] data_out,
    output reg               drain_complete         // 1 = this dispatch's beats fully drained
);
    // Serialization geometry. For DATA_W >= ACT_W (no serialization needed)
    // TILES_PER_BEAT collapses to 1; the engine beat is zero-padded into a
    // single consumer tile in the slice expression.
    localparam integer TILES_PER_BEAT = (DATA_W >= ACT_W) ? 1 : (ACT_W / DATA_W);
    localparam integer TILE_IDX_W    = (TILES_PER_BEAT <= 1) ? 1 : $clog2(TILES_PER_BEAT);
    localparam integer EXPECTED_TILES = EXPECTED_BEATS * TILES_PER_BEAT;

    // dispatch_count gates active_slot; ticks once per scheduler 'start' pulse.
    // Width = clog2(NUM_DISPATCHES)+1 headroom bit so it scales past 16 dispatches
    // (MobileNet-v2 has 34 -> needs 6 bits; the old fixed [3:0] truncated SLOT 16..33
    // and wrapped dispatch_count at 16 = guaranteed deadlock on dispatches 16+).
    // Fix 14's "+1" cushion also catches the final S_NEXT_DISP increment past LAST_DISPATCH.
    localparam integer DC_W = ((NUM_DISPATCHES <= 1) ? 1 : $clog2(NUM_DISPATCHES)) + 1;
    reg [DC_W-1:0] dispatch_count;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) dispatch_count <= {DC_W{1'b0}};
        else if (start) dispatch_count <= dispatch_count + {{(DC_W-1){1'b0}}, 1'b1};
    end
    wire active_slot = (dispatch_count == SLOT[DC_W-1:0]);

    // Beat buffer + tile index. beat_buf holds the current engine beat;
    // tile_idx walks 0..TILES_PER_BEAT-1, emitting one slice per ready cycle.
    reg [ACT_W-1:0]      beat_buf;
    reg                  buf_valid;
    reg [TILE_IDX_W:0]   tile_idx;
    reg [31:0]           tiles_emitted;

    // Tile-slice multiplexer. The +: indexed-part-select picks DATA_W bits
    // starting at tile_idx*DATA_W; for DATA_W>=ACT_W the slice degenerates
    // to "low ACT_W bits with zero-pad above".
    wire [DATA_W-1:0] current_tile;
    generate
        if (DATA_W >= ACT_W) begin : g_pad
            assign current_tile = { {(DATA_W-ACT_W){1'b0}}, beat_buf };
        end else begin : g_slice
            assign current_tile = beat_buf[tile_idx * DATA_W +: DATA_W];
        end
    endgenerate

    // Combinational gates:
    //   emit_ready    : we can send a tile this cycle (buffer has data,
    //                   downstream slot is free, slot is active, not done)
    //   last_tile     : this would be the final tile of the current beat
    //   need_new_beat : next cycle the buffer will be empty
    //   fifo_out_ready: only this slot's active bridge pulls; OR-cascade at
    //                   the wrapper trivially picks the right gate.
    wire emit_ready = active_slot && (!valid_out || ready_out)
                    && !drain_complete && buf_valid;
    wire last_tile  = (tile_idx == (TILES_PER_BEAT[TILE_IDX_W:0] - 1'b1));
    wire need_new_beat = !buf_valid || (emit_ready && last_tile);
    assign fifo_out_ready = active_slot && fifo_out_valid
                          && need_new_beat && !drain_complete;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            valid_out      <= 1'b0;
            data_out       <= {DATA_W{1'b0}};
            beat_buf       <= {ACT_W{1'b0}};
            buf_valid      <= 1'b0;
            tile_idx       <= {(TILE_IDX_W+1){1'b0}};
            tiles_emitted  <= 32'd0;
            drain_complete <= 1'b0;
        end else begin
            // (1) Consumer accepted current tile — drop valid_out.
            if (valid_out && ready_out) valid_out <= 1'b0;
            // (2) Emit a tile this cycle.
            if (emit_ready) begin
                valid_out     <= 1'b1;
                data_out      <= current_tile;
                tiles_emitted <= tiles_emitted + 32'd1;
                if (tiles_emitted + 32'd1 == EXPECTED_TILES[31:0]) begin
                    drain_complete <= 1'b1;
                end
                // Advance tile index OR finish this beat.
                if (last_tile) begin
                    buf_valid <= 1'b0;
                    tile_idx  <= {(TILE_IDX_W+1){1'b0}};
                end else begin
                    tile_idx  <= tile_idx + 1'b1;
                end
            end
            // (3) Pull next beat from FIFO. Placed AFTER the emit block so
            // a simultaneous "emit last tile + load new beat" lands with
            // buf_valid=1 (FIFO load wins the NBA race) and tile_idx=0.
            if (fifo_out_ready && fifo_out_valid) begin
                beat_buf  <= fifo_out_data;
                buf_valid <= 1'b1;
                tile_idx  <= {(TILE_IDX_W+1){1'b0}};
            end
            // Single-image: drain_complete latches once and stays. For
            // multi-image inference, a 'clear' input would reset this
            // and tiles_emitted per-frame. Out of scope.
        end
    end
endmodule


// [FRAME-GATE FIFO] appended by apply_resnet8_conv_input_fifos.py.
// Buffers FRAME beats, then releases them as a contiguous gap-free burst.
// Fronts the cycle_count(whole-frame) convs whose time-based output trigger
// mis-fires on gappy input.
module frame_gate_fifo #(
    parameter integer WIDTH = 128,
    parameter integer DEPTH = 2048,
    parameter integer FRAME = 1024
) (
    input  wire             clk,
    input  wire             rst_n,
    input  wire             in_valid,
    input  wire [WIDTH-1:0] in_data,
    output wire             in_ready,
    output wire             out_valid,
    output wire [WIDTH-1:0] out_data,
    input  wire             out_ready
);
    function integer clog2; input integer value; integer v; begin
        v = value - 1; for (clog2 = 0; v > 0; clog2 = clog2 + 1) v = v >> 1; end
    endfunction
    localparam integer AW = clog2(DEPTH);
    localparam integer FW = clog2(FRAME + 1);

    (* ram_style = "distributed" *) reg [WIDTH-1:0] mem [0:DEPTH-1];
    reg [AW:0] wr_ptr, rd_ptr;
    wire [AW-1:0] wr_idx = wr_ptr[AW-1:0];
    wire [AW-1:0] rd_idx = rd_ptr[AW-1:0];
    wire empty = (wr_ptr == rd_ptr);
    wire full  = (wr_ptr[AW] != rd_ptr[AW]) && (wr_ptr[AW-1:0] == rd_ptr[AW-1:0]);

    reg [FW-1:0] fill_q;
    reg          releasing_q;
    reg [FW-1:0] drain_q;

    wire push = in_valid && ~full;
    wire pop  = out_valid && out_ready;

    assign in_ready  = ~full;
    assign out_valid = releasing_q && ~empty;
    assign out_data  = mem[rd_idx];

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_ptr <= 0; rd_ptr <= 0;
            fill_q <= 0; releasing_q <= 1'b0; drain_q <= 0;
        end else begin
            if (push) begin wr_ptr <= wr_ptr + 1'b1; end
            if (pop) rd_ptr <= rd_ptr + 1'b1;
            if (!releasing_q) begin
                if (push) begin
                    if (fill_q == FRAME - 1) begin
                        releasing_q <= 1'b1; drain_q <= 0; fill_q <= 0;
                    end else fill_q <= fill_q + 1'b1;
                end
            end else begin
                if (pop) begin
                    if (drain_q == FRAME - 1) begin releasing_q <= 1'b0; drain_q <= 0; end
                    else drain_q <= drain_q + 1'b1;
                end
                if (push) fill_q <= fill_q + 1'b1;
            end
        end
    end

    // Array-memory write split out (reset-free) for BRAM/DRAM inference.
    always @(posedge clk) begin
        if (push) mem[wr_idx] <= in_data;
    end
endmodule

`endif // NN2RTL_TOP_NO_STUBS
