// Driver for engine_iso_wrap_mbv2 (REAL MobileNetV2 engine, REAL memories).
// AXI config + act preload + start + compare vs the per-module golden vector.
// All geometry comes from tb/engine_iso_cfg.h (generated by
// scripts/gen_engine_iso_cfg.py <module_id> [vec]).
//
// Golden file layout (NN2V): magic[4]="NN2V", u32 version, u32 num_vectors,
// u32 samples_per_vec, u32 bytes_per_sample. Header = 20 bytes, then payload.
// We compare vector CFG_VEC: input = samples_per_vec * IN_BYTES, output likewise.
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
#include <string>
#include "Vengine_iso_wrap_mbv2.h"
#include "verilated.h"
#include "engine_iso_cfg.h"

double sc_time_stamp() { return 0; }

namespace {
constexpr uint64_t kMaxCycles = 50'000'000ull;
struct NN2VHdr { uint32_t ver, nvec, samples, bps; };

// Read NN2V header (after 4-byte magic). Returns payload byte offset.
size_t read_hdr(std::ifstream& f, NN2VHdr& h) {
  char magic[4];
  f.read(magic, 4);
  f.read(reinterpret_cast<char*>(&h), 16);
  return 20;
}
}  // namespace

int main(int argc, char** argv) {
  Verilated::commandArgs(argc, argv);
  auto* dut = new Vengine_iso_wrap_mbv2;
  uint64_t cyc = 0;
  auto tick = [&]() { dut->clk = 0; dut->eval(); dut->clk = 1; dut->eval(); cyc++; };

  // helper to set a 2048-bit (64 x uint32) WData word from a byte buffer
  auto set_word_from_bytes = [&](VlWide<64>& w, const unsigned char* buf, int nbytes) {
    for (int i = 0; i < 64; i++) w[i] = 0;
    for (int by = 0; by < nbytes; by++)
      w[by / 4] |= (static_cast<uint32_t>(buf[by]) << ((by % 4) * 8));
  };

  // ---- reset ----
  dut->rst_n = 0; dut->engine_start = 0;
  dut->s_axil_awvalid = 0; dut->s_axil_wvalid = 0; dut->s_axil_bready = 0;
  dut->s_axil_arvalid = 0; dut->s_axil_rready = 0;
  dut->tb_act_wr_en = 0; dut->tb_act_wr_addr = 0;
  for (int i = 0; i < 64; i++) dut->tb_act_wr_data[i] = 0;
  dut->tb_act_rd_addr = 0;
  dut->clk = 0; dut->eval();
  for (int i = 0; i < 20; i++) tick();
  dut->rst_n = 1; for (int i = 0; i < 5; i++) tick();

  // ---- preload activations from goldin vector CFG_VEC ----
  const uint32_t IN_BPS  = CFG_IN_BYTES_PER_SAMPLE;   // channels (bytes) per input pixel
  const uint32_t IC_CHUNKS = CFG_IC_CHUNKS;
  {
    std::ifstream f(CFG_GOLDIN, std::ios::binary);
    if (!f) { std::fprintf(stderr, "missing goldin %s\n", CFG_GOLDIN); return 2; }
    NN2VHdr h; read_hdr(f, h);
    if (h.bps != IN_BPS || h.samples != CFG_N_IN_PIXELS) {
      std::printf("[wrap] WARN goldin hdr bps=%u samples=%u (cfg IN_BPS=%u N_IN=%u)\n",
                  h.bps, h.samples, IN_BPS, CFG_N_IN_PIXELS);
    }
    // seek to vector CFG_VEC
    f.seekg(20 + static_cast<std::streamoff>(CFG_VEC) * h.samples * h.bps, std::ios::beg);
    std::vector<unsigned char> sample(IN_BPS);
    for (uint32_t p = 0; p < CFG_N_IN_PIXELS; p++) {
      f.read(reinterpret_cast<char*>(sample.data()), IN_BPS);
      // split across ic_chunks: chunk c holds channels [c*256 .. c*256+255]
      for (uint32_t c = 0; c < IC_CHUNKS; c++) {
        unsigned char buf[256]; std::memset(buf, 0, 256);
        uint32_t chstart = c * 256;
        uint32_t nb = (chstart + 256 <= IN_BPS) ? 256 : (IN_BPS - chstart);
        if (chstart < IN_BPS) std::memcpy(buf, sample.data() + chstart, nb);
        dut->clk = 0;
        dut->tb_act_wr_en = 1;
        dut->tb_act_wr_addr = CFG_ACT_IN_BASE + p * IC_CHUNKS + c;
        set_word_from_bytes(dut->tb_act_wr_data, buf, 256);
        dut->eval(); dut->clk = 1; dut->eval(); cyc++;
      }
    }
    dut->clk = 0; dut->tb_act_wr_en = 0; dut->eval(); dut->clk = 1; dut->eval(); cyc++;
    std::printf("[wrap] preloaded %u act pixels (ic_chunks=%u)\n", CFG_N_IN_PIXELS, IC_CHUNKS);
  }

  // ---- AXI config ----
  auto axi_write = [&](uint32_t addr, uint32_t data) {
    dut->s_axil_awvalid = 1; dut->s_axil_awaddr = addr;
    dut->s_axil_wvalid = 1; dut->s_axil_wdata = data; dut->s_axil_wstrb = 0xF; dut->s_axil_bready = 1;
    for (int g = 0; g < 1000; g++) { tick(); if (dut->s_axil_awready && dut->s_axil_wready) break; }
    dut->s_axil_awvalid = 0; dut->s_axil_wvalid = 0;
    for (int g = 0; g < 1000; g++) { tick(); if (dut->s_axil_bvalid) break; }
    dut->s_axil_bready = 0; tick();
  };
  axi_write(0x00, CFG_IC);                                // INPUT_CHANNELS
  axi_write(0x04, CFG_OC);                                // OUTPUT_CHANNELS
  axi_write(0x08, (CFG_KH << 4) | CFG_KW);                // KERNEL_H_W (nibble each? matches ResNet wrap (3<<4)|3)
  axi_write(0x0C, (CFG_SH << 3) | CFG_SW);                // STRIDE_H_W
  axi_write(0x10, (CFG_PH << 3) | CFG_PW);                // PADDING_H_W
  axi_write(0x14, (CFG_IH << 16) | CFG_IW);               // INPUT_H_W
  axi_write(0x18, (CFG_OH << 16) | CFG_OW);               // OUTPUT_H_W
  axi_write(0x1C, CFG_WEIGHT_BASE);                       // WEIGHT_BASE_WORD
  axi_write(0x20, CFG_BIAS_BASE);                         // BIAS_BASE_WORD (scale shares this base)
  axi_write(0x24, CFG_SCALE_MULT);                        // SCALE_MULT (vestigial: requant is per-OC from scale.mem)
  axi_write(0x28, (CFG_ZP << 6) | CFG_SCALE_SHIFT);       // SCALE_SHIFT_AND_ZP
  axi_write(0x34, CFG_ACT_IN_BASE);                       // ACT_IN_BASE
  axi_write(0x38, CFG_ACT_OUT_BASE);                      // ACT_OUT_BASE
#ifdef CFG_DEPTHWISE
  axi_write(0x3C, CFG_DEPTHWISE);                         // [DW-ENGINE P1] depthwise mode flag
#endif
  std::printf("[wrap] config done at cyc=%llu  (%s IC=%u OC=%u %ux%u->%ux%u wbase=%u bbase=%u)\n",
              (unsigned long long)cyc, CFG_MODULE_ID, CFG_IC, CFG_OC, CFG_IH, CFG_IW,
              CFG_OH, CFG_OW, CFG_WEIGHT_BASE, CFG_BIAS_BASE);

  // ---- run ----
  for (int i = 0; i < 4; i++) tick();
  dut->engine_start = 1; tick(); dut->engine_start = 0;
  uint64_t start = cyc; bool done = false;
  while (cyc < kMaxCycles) { tick(); if (dut->engine_done) { done = true; break; } }
  std::printf("[wrap] done=%d took=%llu cycles\n", (int)done, (unsigned long long)(cyc - start));
  for (int i = 0; i < 8; i++) tick();
  if (!done) { std::printf("[wrap] FAIL: never completed\n"); delete dut; return 1; }

  // ---- compare act_out vs goldout vector CFG_VEC ----
  const uint32_t OUT_BPS = CFG_OUT_BYTES_PER_SAMPLE;  // OC channels per output pixel
  const uint32_t OC_PASSES = CFG_OC_PASSES;
  std::ifstream gf(CFG_GOLDOUT, std::ios::binary);
  if (!gf) { std::fprintf(stderr, "missing goldout %s\n", CFG_GOLDOUT); delete dut; return 2; }
  NN2VHdr gh; read_hdr(gf, gh);
  gf.seekg(20 + static_cast<std::streamoff>(CFG_VEC) * gh.samples * gh.bps, std::ios::beg);

  long total = 0, mism = 0, maxe = 0, firstbad = -1;
  std::vector<unsigned char> g(OUT_BPS);
  for (uint32_t p = 0; p < CFG_N_OUT_PIXELS; p++) {
    gf.read(reinterpret_cast<char*>(g.data()), OUT_BPS);
    // gather the engine's OUT_BPS bytes across oc_passes
    std::vector<uint8_t> got(OUT_BPS, 0);
    for (uint32_t q = 0; q < OC_PASSES; q++) {
      dut->tb_act_rd_addr = CFG_ACT_OUT_BASE + p * OC_PASSES + q;
      dut->eval();
      uint32_t ocstart = q * 256;
      uint32_t nb = (ocstart + 256 <= OUT_BPS) ? 256 : (OUT_BPS - ocstart);
      for (uint32_t by = 0; by < nb; by++) {
        uint32_t word = dut->tb_act_rd_data[by / 4];
        got[ocstart + by] = (word >> ((by % 4) * 8)) & 0xFF;
      }
    }
    if (p == 0) {
      std::printf("[dbg] pixel0 got vs gold (first 24 OC):\n  got:");
      for (int by = 0; by < 24 && by < (int)OUT_BPS; by++) std::printf("%4d", (int8_t)got[by]);
      std::printf("\n  gld:");
      for (int by = 0; by < 24 && by < (int)OUT_BPS; by++) std::printf("%4d", (int8_t)g[by]);
      std::printf("\n");
    }
    for (uint32_t by = 0; by < OUT_BPS; by++) {
      uint8_t gv = g[by], ov = got[by];
      total++;
      if (gv != ov) {
        mism++;
        int gs = (gv >= 128) ? gv - 256 : gv, os = (ov >= 128) ? ov - 256 : ov;
        if (std::abs(gs - os) > maxe) maxe = std::abs(gs - os);
        if (firstbad < 0) firstbad = (int)p;
      }
    }
  }
  std::printf("\n=== WRAP engine-ISOLATION (%s, REAL mbv2 mems) vs goldout vec%d ===\n",
              CFG_MODULE_ID, CFG_VEC);
  std::printf("bytes=%ld mismatch=%ld max|err|=%ld firstbad_pixel=%ld\n",
              total, mism, maxe, (long)firstbad);
  std::printf("%s\n", mism == 0 ? "PASS: byte-exact" : "MISMATCH");
  delete dut;
  return mism == 0 ? 0 : 1;
}
