`timescale 1ns/1ps

// engine_one_layer_tb.v
// ---------------------------------------------------------------------------
// Self-contained iverilog testbench that verifies the nn2rtl shared compute
// engine end-to-end on ONE heavy ResNet-50 layer.
//
// PARAMETERIZED via include file `build_engine_one_layer_tb/dispatch_cfg.vh`
// which is generated by scripts/run_engine_sweep_all.sh from
// output/rtl/nn2rtl_scheduler_schedule.json for the chosen dispatch index.
//
// The include file MUST define ALL of:
//   CFG_IC, CFG_OC,
//   CFG_KH, CFG_KW, CFG_SH, CFG_SW, CFG_PH, CFG_PW,
//   CFG_IH, CFG_IW, CFG_OH, CFG_OW,
//   CFG_WEIGHT_BASE, CFG_BIAS_BASE,
//   CFG_SCALE_MULT, CFG_SCALE_SHIFT, CFG_ZP,
//   CFG_ACT_IN_BASE, CFG_ACT_OUT_BASE,
//   N_IN_PIXELS   (IH*IW),
//   IC_CHUNKS     (ceil(IC/256)),
//   N_IN_WORDS    (N_IN_PIXELS * IC_CHUNKS),
//   N_OUT_PIXELS  (OH*OW),
//   OC_PASSES     (ceil(OC/256)),
//   N_OUT_WORDS   (N_OUT_PIXELS * OC_PASSES),
//   IC_BYTES      (CFG_IC; bytes-per-sample in the goldin),
//   OC_BYTES      (CFG_OC; bytes-per-sample in the goldout),
//   GOLDIN_PATH   (string literal),
//   OBSERVED_HEX_PATH (string literal).
//
// Compile with:
//   iverilog -g2012 -DNN2RTL_ENGINE_SUBBLOCKS_PROVIDED -o engine_tb.vvp \
//       tb/engine_one_layer_tb.v \
//       output/rtl/shared_engine_skeleton.v \
//       output/rtl/engine/*.v
//   (note: pass `-I<build_dir>` to iverilog; the include below resolves
//    against that include search path. For serial runs that's
//    `-I build_engine_one_layer_tb`; for parallel runs each worker passes
//    its own per-worker build dir.)
// ---------------------------------------------------------------------------

`include "dispatch_cfg.vh"

module engine_one_layer_tb;

    // ----- clock / reset -----
    reg clk = 1'b0;
    reg rst_n = 1'b0;
    always #5 clk = ~clk;   // 100 MHz

    // ----- AXI4-Lite slave wires (driven by TB master FSM) -----
    reg         s_axil_awvalid;
    wire        s_axil_awready;
    reg  [7:0]  s_axil_awaddr;
    reg         s_axil_wvalid;
    wire        s_axil_wready;
    reg  [31:0] s_axil_wdata;
    reg  [3:0]  s_axil_wstrb;
    wire        s_axil_bvalid;
    reg         s_axil_bready;
    wire [1:0]  s_axil_bresp;
    reg         s_axil_arvalid;
    wire        s_axil_arready;
    reg  [7:0]  s_axil_araddr;
    wire        s_axil_rvalid;
    reg         s_axil_rready;
    wire [31:0] s_axil_rdata;
    wire [1:0]  s_axil_rresp;

    // ----- engine handshake -----
    reg         engine_start;
    wire        engine_busy;
    wire        engine_done;

    // ----- engine <-> activation BRAM -----
    wire [15:0]   engine_act_in_rd_addr;
    wire          engine_act_in_rd_en;
    wire [2047:0] engine_act_in_rd_data;
    wire [15:0]   engine_act_out_wr_addr;
    wire          engine_act_out_wr_en;
    wire [2047:0] engine_act_out_wr_data;

    // ----- engine <-> URAM weight banks -----
    wire [21:0]   engine_weight_rd_addr;
    wire          engine_weight_rd_en;
    wire [2047:0] engine_weight_rd_data;

    // ----- engine <-> bias mem -----
    wire [21:0]   engine_bias_rd_addr;
    wire          engine_bias_rd_en;
    wire [8191:0] engine_bias_rd_data;

    // ----- engine <-> per-OC scale ROM (Phase 2 INT4-GPTQ) -----
    wire [21:0]   engine_scale_rd_addr;
    wire          engine_scale_rd_en;
    wire [8191:0] engine_scale_rd_data;

    // ====================================================================
    // 8 URAM weight banks (each 288-bit wide; only low 256 bits used).
    // ====================================================================
    wire [16:0]  weight_bank_rd_addr = engine_weight_rd_addr[16:0];
    wire [287:0] uram_bank0_rd_data;
    wire [287:0] uram_bank1_rd_data;
    wire [287:0] uram_bank2_rd_data;
    wire [287:0] uram_bank3_rd_data;
    wire [287:0] uram_bank4_rd_data;
    wire [287:0] uram_bank5_rd_data;
    wire [287:0] uram_bank6_rd_data;
    wire [287:0] uram_bank7_rd_data;
    assign engine_weight_rd_data = {uram_bank7_rd_data[255:0],
                                    uram_bank6_rd_data[255:0],
                                    uram_bank5_rd_data[255:0],
                                    uram_bank4_rd_data[255:0],
                                    uram_bank3_rd_data[255:0],
                                    uram_bank2_rd_data[255:0],
                                    uram_bank1_rd_data[255:0],
                                    uram_bank0_rd_data[255:0]};

    uram_weight_bank #(.DEPTH(96659), .ADDR_W(17),
        .MEM_INIT_FILE("output/weights/uram_weights_bank0.mem"))
      u_uram_weight_bank0 (.clk(clk), .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank0_rd_data), .rd_en(engine_weight_rd_en));
    uram_weight_bank #(.DEPTH(96659), .ADDR_W(17),
        .MEM_INIT_FILE("output/weights/uram_weights_bank1.mem"))
      u_uram_weight_bank1 (.clk(clk), .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank1_rd_data), .rd_en(engine_weight_rd_en));
    uram_weight_bank #(.DEPTH(96659), .ADDR_W(17),
        .MEM_INIT_FILE("output/weights/uram_weights_bank2.mem"))
      u_uram_weight_bank2 (.clk(clk), .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank2_rd_data), .rd_en(engine_weight_rd_en));
    uram_weight_bank #(.DEPTH(96659), .ADDR_W(17),
        .MEM_INIT_FILE("output/weights/uram_weights_bank3.mem"))
      u_uram_weight_bank3 (.clk(clk), .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank3_rd_data), .rd_en(engine_weight_rd_en));
    uram_weight_bank #(.DEPTH(96659), .ADDR_W(17),
        .MEM_INIT_FILE("output/weights/uram_weights_bank4.mem"))
      u_uram_weight_bank4 (.clk(clk), .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank4_rd_data), .rd_en(engine_weight_rd_en));
    uram_weight_bank #(.DEPTH(96659), .ADDR_W(17),
        .MEM_INIT_FILE("output/weights/uram_weights_bank5.mem"))
      u_uram_weight_bank5 (.clk(clk), .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank5_rd_data), .rd_en(engine_weight_rd_en));
    uram_weight_bank #(.DEPTH(96659), .ADDR_W(17),
        .MEM_INIT_FILE("output/weights/uram_weights_bank6.mem"))
      u_uram_weight_bank6 (.clk(clk), .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank6_rd_data), .rd_en(engine_weight_rd_en));
    uram_weight_bank #(.DEPTH(96659), .ADDR_W(17),
        .MEM_INIT_FILE("output/weights/uram_weights_bank7.mem"))
      u_uram_weight_bank7 (.clk(clk), .rd_addr(weight_bank_rd_addr),
        .rd_data(uram_bank7_rd_data), .rd_en(engine_weight_rd_en));

    // ====================================================================
    // Bias memory (256 entries × 8192 bits).
    // ====================================================================
    bias_mem #(.SIZE_WORDS(256), .WORD_WIDTH(8192), .ADDR_W(8),
        .MEM_INIT_FILE("output/weights/bias.mem"))
      u_bias_mem (.clk(clk),
        .rd_addr(engine_bias_rd_addr[7:0]),
        .rd_data(engine_bias_rd_data),
        .rd_en(engine_bias_rd_en));

    // Per-OC scale ROM: same 8192-bit word geometry as bias, read at the same
    // address (scale base_words == bias base_words). Reuses the bias_mem module.
    bias_mem #(.SIZE_WORDS(256), .WORD_WIDTH(8192), .ADDR_W(8),
        .MEM_INIT_FILE("output/weights/scale.mem"))
      u_scale_mem (.clk(clk),
        .rd_addr(engine_scale_rd_addr[7:0]),
        .rd_data(engine_scale_rd_data),
        .rd_en(engine_scale_rd_en));

    // ====================================================================
    // Activation BRAM (unified 24576×2048).
    // ====================================================================
    reg          tb_act_wr_en;
    reg  [14:0]  tb_act_wr_addr;
    reg  [2047:0] tb_act_wr_data;
    wire         act_wr_en_final   = engine_act_out_wr_en | tb_act_wr_en;
    wire [14:0]  act_wr_addr_final = engine_act_out_wr_en
                                   ? engine_act_out_wr_addr[14:0]
                                   : tb_act_wr_addr;
    wire [2047:0] act_wr_data_final = engine_act_out_wr_en
                                    ? engine_act_out_wr_data
                                    : tb_act_wr_data;

    act_unified_mem #(.DEPTH(24576), .ADDR_W(15)) u_act_mem (
        .clk(clk),
        .rd_addr(engine_act_in_rd_addr[14:0]),
        .rd_en  (engine_act_in_rd_en),
        .rd_data(engine_act_in_rd_data),
        .wr_addr(act_wr_addr_final),
        .wr_en  (act_wr_en_final),
        .wr_data(act_wr_data_final)
    );

    // ====================================================================
    // DUT: shared compute engine.
    // ====================================================================
    shared_engine u_shared_engine (
        .clk(clk), .rst_n(rst_n),
        .s_axil_awvalid(s_axil_awvalid), .s_axil_awready(s_axil_awready),
        .s_axil_awaddr (s_axil_awaddr),
        .s_axil_wvalid (s_axil_wvalid),  .s_axil_wready (s_axil_wready),
        .s_axil_wdata  (s_axil_wdata),   .s_axil_wstrb  (s_axil_wstrb),
        .s_axil_bvalid (s_axil_bvalid),  .s_axil_bready (s_axil_bready),
        .s_axil_bresp  (s_axil_bresp),
        .s_axil_arvalid(s_axil_arvalid), .s_axil_arready(s_axil_arready),
        .s_axil_araddr (s_axil_araddr),
        .s_axil_rvalid (s_axil_rvalid),  .s_axil_rready (s_axil_rready),
        .s_axil_rdata  (s_axil_rdata),   .s_axil_rresp  (s_axil_rresp),
        .engine_start  (engine_start),
        .engine_busy   (engine_busy),
        .engine_done   (engine_done),
        .act_in_rd_addr (engine_act_in_rd_addr),
        .act_in_rd_en   (engine_act_in_rd_en),
        .act_in_rd_data (engine_act_in_rd_data),
        .act_out_wr_addr(engine_act_out_wr_addr),
        .act_out_wr_en  (engine_act_out_wr_en),
        .act_out_wr_data(engine_act_out_wr_data),
        .weight_rd_addr (engine_weight_rd_addr),
        .weight_rd_en   (engine_weight_rd_en),
        .weight_rd_data (engine_weight_rd_data),
        .bias_rd_addr   (engine_bias_rd_addr),
        .bias_rd_en     (engine_bias_rd_en),
        .bias_rd_data   (engine_bias_rd_data),
        .scale_rd_addr  (engine_scale_rd_addr),
        .scale_rd_en    (engine_scale_rd_en),
        .scale_rd_data  (engine_scale_rd_data)
    );

    // ====================================================================
    // AXI4-Lite master tasks.
    // ====================================================================
    task automatic axil_write(input [7:0] addr, input [31:0] data);
        begin
            @(posedge clk);
            s_axil_awvalid <= 1'b1;
            s_axil_awaddr  <= addr;
            s_axil_wvalid  <= 1'b1;
            s_axil_wdata   <= data;
            s_axil_wstrb   <= 4'b1111;
            s_axil_bready  <= 1'b1;
            do begin
                @(posedge clk);
            end while (!(s_axil_awready && s_axil_wready));
            s_axil_awvalid <= 1'b0;
            s_axil_wvalid  <= 1'b0;
            do begin
                @(posedge clk);
            end while (!s_axil_bvalid);
            @(posedge clk);
            s_axil_bready <= 1'b0;
        end
    endtask

    // ====================================================================
    // Pre-load activation BRAM from .goldin vector 0.
    // ====================================================================
    integer i, j, k;
    integer fh;
    integer rc;
    integer chunk_byte;

    // Buffer for one BRAM word (2048 bits = 256 bytes = 256 channels).
    reg [2047:0] sample_bus;
    // Buffer for ONE full input pixel: up to IC_BYTES bytes (max 2048).
    reg [7:0] pixel_buf [0:2047];

    // ====================================================================
    // Output capture.
    // ====================================================================
    integer out_fh;
    reg [2047:0] obs_word;

    // ====================================================================
    // Timeout supplied by +TIMEOUT_CYCLES=NNN plusarg.
    // ====================================================================
    integer timeout_cycles;
    integer cycle_counter;
    integer start_cycle;
    integer end_cycle;

    // ====================================================================
    // Main stimulus.
    // ====================================================================
    initial begin
        // Defaults.
        s_axil_awvalid = 1'b0; s_axil_awaddr = 8'h00;
        s_axil_wvalid  = 1'b0; s_axil_wdata  = 32'd0; s_axil_wstrb = 4'b0000;
        s_axil_bready  = 1'b0;
        s_axil_arvalid = 1'b0; s_axil_araddr = 8'h00; s_axil_rready = 1'b0;
        engine_start   = 1'b0;
        tb_act_wr_en   = 1'b0; tb_act_wr_addr = 15'd0; tb_act_wr_data = 2048'd0;

        if (!$value$plusargs("TIMEOUT_CYCLES=%d", timeout_cycles))
            timeout_cycles = 50_000_000;
        $display("[TB] Timeout set to %0d cycles", timeout_cycles);
        $display("[TB] Dispatch config: IC=%0d OC=%0d K=%0dx%0d S=%0dx%0d P=%0dx%0d IH=%0d IW=%0d OH=%0d OW=%0d",
                 `CFG_IC, `CFG_OC, `CFG_KH, `CFG_KW, `CFG_SH, `CFG_SW,
                 `CFG_PH, `CFG_PW, `CFG_IH, `CFG_IW, `CFG_OH, `CFG_OW);
        $display("[TB]   wbase=%0d bbase=%0d sm=%0d ss=%0d zp=%0d act_in=%0d act_out=%0d",
                 `CFG_WEIGHT_BASE, `CFG_BIAS_BASE, `CFG_SCALE_MULT,
                 `CFG_SCALE_SHIFT, `CFG_ZP, `CFG_ACT_IN_BASE, `CFG_ACT_OUT_BASE);
        $display("[TB]   n_in_pixels=%0d ic_chunks=%0d n_in_words=%0d",
                 `N_IN_PIXELS, `IC_CHUNKS, `N_IN_WORDS);
        $display("[TB]   n_out_pixels=%0d oc_passes=%0d n_out_words=%0d",
                 `N_OUT_PIXELS, `OC_PASSES, `N_OUT_WORDS);
        $display("[TB]   ic_bytes=%0d oc_bytes=%0d",
                 `IC_BYTES, `OC_BYTES);
        $display("[TB]   goldin=%s", `GOLDIN_PATH);
        $display("[TB]   observed_hex=%s", `OBSERVED_HEX_PATH);
        $fflush;

        // Reset.
        rst_n = 1'b0;
        repeat (20) @(posedge clk);
        rst_n = 1'b1;
        repeat (5) @(posedge clk);

        // ----- Load .goldin vector 0 into activation BRAM -----
        fh = $fopen(`GOLDIN_PATH, "rb");
        if (fh == 0) begin
            $display("[TB] FATAL: cannot open .goldin file");
            $finish;
        end
        // Skip 20-byte header.
        for (i = 0; i < 20; i = i + 1) begin
            rc = $fgetc(fh);
        end
        $display("[TB] Skipped 20-byte .goldin header.");

        // Per pixel: read IC_BYTES bytes from goldin into pixel_buf, then
        // split into IC_CHUNKS BRAM words of up to 256 bytes each. Channel 0
        // is the LSByte of chunk 0; channel 256 is the LSByte of chunk 1; etc.
        // BRAM layout = pixel_index * IC_CHUNKS + ic_chunk_idx (matches the
        // engine's act_in addressing formula).
        for (i = 0; i < `N_IN_PIXELS; i = i + 1) begin
            for (j = 0; j < `IC_BYTES; j = j + 1) begin
                pixel_buf[j] = $fgetc(fh);
            end
            for (k = 0; k < `IC_CHUNKS; k = k + 1) begin
                sample_bus = 2048'd0;
                for (chunk_byte = 0; chunk_byte < 256; chunk_byte = chunk_byte + 1) begin
                    if ((k * 256 + chunk_byte) < `IC_BYTES) begin
                        sample_bus[chunk_byte*8 +: 8] =
                            pixel_buf[k * 256 + chunk_byte];
                    end
                end
                @(posedge clk);
                tb_act_wr_en   <= 1'b1;
                tb_act_wr_addr <= `CFG_ACT_IN_BASE + (i * `IC_CHUNKS + k);
                tb_act_wr_data <= sample_bus;
            end
        end
        @(posedge clk);
        tb_act_wr_en   <= 1'b0;
        tb_act_wr_addr <= 15'd0;
        tb_act_wr_data <= 2048'd0;
        $fclose(fh);
        $display("[TB] Loaded %0d activation BRAM words (%0d pixels x %0d ic_chunks).",
                 `N_IN_WORDS, `N_IN_PIXELS, `IC_CHUNKS);
        $fflush;

        repeat (4) @(posedge clk);

        // ----- Program the engine via AXI4-Lite (13 writes) -----
        // Note: include file defines each CFG_* as a sized literal (e.g.
        // 12'd256 for CFG_IC) so concatenation widths line up.
        axil_write(8'h00, {20'd0, `CFG_IC});
        axil_write(8'h04, {20'd0, `CFG_OC});
        axil_write(8'h08, {24'd0, 1'b0, `CFG_KH, 1'b0, `CFG_KW});
        axil_write(8'h0C, {26'd0, `CFG_SH, `CFG_SW});
        axil_write(8'h10, {26'd0, `CFG_PH, `CFG_PW});
        axil_write(8'h14, {8'd0, `CFG_IH, 8'd0, `CFG_IW});
        axil_write(8'h18, {8'd0, `CFG_OH, 8'd0, `CFG_OW});
        axil_write(8'h1C, {12'd0, `CFG_WEIGHT_BASE});
        axil_write(8'h20, {16'd0, `CFG_BIAS_BASE});
        axil_write(8'h24, `CFG_SCALE_MULT);
        axil_write(8'h28, {18'd0, `CFG_ZP, `CFG_SCALE_SHIFT});
        axil_write(8'h34, {16'd0, `CFG_ACT_IN_BASE});
        axil_write(8'h38, {16'd0, `CFG_ACT_OUT_BASE});

        $display("[TB] AXI config writes complete at cycle %0d.", cycle_counter);
        $fflush;

        repeat (4) @(posedge clk);

        // ----- Pulse engine_start for ONE cycle -----
        @(posedge clk);
        engine_start <= 1'b1;
        start_cycle = cycle_counter;
        @(posedge clk);
        engine_start <= 1'b0;
        $display("[TB] engine_start pulse asserted at cycle %0d.", start_cycle);
        $fflush;

        // ----- Wait for engine_done -----
        while (!engine_done) begin
            if ((cycle_counter - start_cycle) > timeout_cycles) begin
                $display("[TB] FATAL: engine_done not asserted within %0d cycles.",
                         timeout_cycles);
                $finish;
            end
            if (((cycle_counter - start_cycle) % 50000) == 0
                 && (cycle_counter - start_cycle) > 0) begin
                $display("[TB] heartbeat: %0d cycles elapsed since engine_start",
                         cycle_counter - start_cycle);
                $fflush;
            end
            @(posedge clk);
        end
        end_cycle = cycle_counter;
        $display("[TB] engine_done at cycle %0d (took %0d cycles).",
                 end_cycle, end_cycle - start_cycle);
        $display("[TB] CYCLES_FROM_START=%0d", end_cycle - start_cycle);

        repeat (8) @(posedge clk);

        // ----- Dump engine output: N_OUT_WORDS wide BRAM words to hex file -----
        out_fh = $fopen(`OBSERVED_HEX_PATH, "w");
        if (out_fh == 0) begin
            $display("[TB] FATAL: cannot open observed output file.");
            $finish;
        end
        for (i = 0; i < `N_OUT_WORDS; i = i + 1) begin
            obs_word = u_act_mem.mem[(`CFG_ACT_OUT_BASE + i) & 16'h7FFF];
            $fdisplay(out_fh, "%0512h", obs_word);
        end
        $fclose(out_fh);
        $display("[TB] Wrote %0d output words to %s.",
                 `N_OUT_WORDS, `OBSERVED_HEX_PATH);

        $display("[TB] Done.");
        $finish;
    end

    // Free-running cycle counter.
    initial cycle_counter = 0;
    always @(posedge clk) cycle_counter <= cycle_counter + 1;

`ifdef DEBUG_PIXEL
    integer dbg_r, dbg_c, dbg_p;
    initial begin
        if (!$value$plusargs("DEBUG_R=%d", dbg_r)) dbg_r = 0;
        if (!$value$plusargs("DEBUG_C=%d", dbg_c)) dbg_c = 6;
        if (!$value$plusargs("DEBUG_P=%d", dbg_p)) dbg_p = 0;
        $display("[DBG] tracking pixel [%0d,%0d] oc_pass=%0d", dbg_r, dbg_c, dbg_p);
    end
    wire dbg_match = (u_shared_engine.pixel_h_r == dbg_r[7:0])
                  && (u_shared_engine.pixel_w_r == dbg_c[7:0])
                  && (u_shared_engine.oc_pass_idx_r == dbg_p[2:0]);
    reg dbg_match_d;
    always @(posedge clk) dbg_match_d <= dbg_match;
    // Print every cycle the tracked region is active
    always @(posedge clk) if (dbg_match || (dbg_match_d && !dbg_match)) begin
            $display("[DBG] cyc=%0d state=%0d ph=%0d pw=%0d op=%0d k=%0d ic=%0d wraddr=%0d wren=%b ag_wren_d=%b aren=%b ag_aren_d=%b byteidx=%0d byteidx_d=%0d mac_done=%b mvi=%b mvq1=%b mclr=%b acc42=%0d wrd_b0=0x%h aird=0x%h",
                cycle_counter,
                u_shared_engine.state,
                u_shared_engine.pixel_h_r,
                u_shared_engine.pixel_w_r,
                u_shared_engine.oc_pass_idx_r,
                u_shared_engine.u_address_generator.k_cnt,
                u_shared_engine.u_address_generator.ic_cnt,
                u_shared_engine.u_address_generator.weight_rd_addr,
                u_shared_engine.u_address_generator.weight_rd_en,
                u_shared_engine.ag_weight_rd_en_d,
                u_shared_engine.u_address_generator.act_in_rd_en,
                u_shared_engine.ag_act_in_rd_en_d,
                u_shared_engine.u_address_generator.act_in_ic_byte_idx,
                u_shared_engine.ag_act_in_ic_byte_idx_d,
                u_shared_engine.u_address_generator.mac_done,
                u_shared_engine.mac_valid_in,
                u_shared_engine.u_mac_array.mac_valid_q1,
                u_shared_engine.mac_clear,
                $signed(u_shared_engine.u_mac_array.g_mac[42].acc),
                u_shared_engine.mac_weight_bus[42*8 +: 8],
                u_shared_engine.act_in_rd_data[7:0]);
    end
`endif

    // Hard wall-clock timeout watchdog.
    initial begin
        #(20 * 50_000_000);  // 50M cycles @ 10ns
        $display("[TB] FATAL: hard simulation timeout.");
        $finish;
    end

`ifdef DBG_DUMP_ACC
    // ============================================================
    // Diagnostic instrumentation: capture engine acc + bias at the
    // moment of requant_valid_in for a SPECIFIC (pixel, oc_pass).
    // ============================================================
    integer dbg_pass;
    integer dbg_pixel_h;
    integer dbg_pixel_w;
    integer dbg_ch;
    integer dbg_acc;
    integer dbg_bias;
    always @(posedge clk) begin
        if (rst_n && u_shared_engine.requant_valid_in) begin
            dbg_pixel_h = u_shared_engine.pixel_h_r;
            dbg_pixel_w = u_shared_engine.pixel_w_r;
            dbg_pass    = u_shared_engine.oc_pass_idx_r;
            // Dump only for the failing pixels we care about.
            if (
                 (dbg_pixel_h == 0 && dbg_pixel_w == 0) ||
                 (dbg_pixel_h == 0 && dbg_pixel_w == 1)
                ) begin
                $display("[DBG] cycle=%0d requant_valid_in @ pixel=(%0d,%0d) oc_pass=%0d",
                         cycle_counter, dbg_pixel_h, dbg_pixel_w, dbg_pass);
                for (dbg_ch = 0; dbg_ch < 256; dbg_ch = dbg_ch + 1) begin
                    dbg_acc  = $signed(u_shared_engine.mac_acc_out[dbg_ch*32 +: 32]);
                    dbg_bias = $signed(u_shared_engine.requant_bias_in[dbg_ch*32 +: 32]);
                    $display("[DBG]   lane=%0d acc=%0d bias=%0d",
                             dbg_ch, dbg_acc, dbg_bias);
                end
                $fflush;
            end
        end
    end
`endif

`ifdef DBG_DUMP_MAC
    // ============================================================
    // Diagnostic instrumentation: dump cycle-by-cycle engine state
    // around the pass 0 → pass 1 boundary of the first output pixel.
    // ============================================================
    integer dbg_mac_count;
    initial dbg_mac_count = 0;
    always @(posedge clk) begin
        if (rst_n && cycle_counter >= 2510 && cycle_counter <= 2550) begin
            $write("[B cyc=%0d state=%0d run_act=%0b mac_clr=%0b mac_v_in=%0b mac_v_q1=%0b op=%0d ic_cnt=%0d byte_d=%0d act_d=%0d byte_idx=%0d act=%0d w_l21=%0d w_l0=%0d acc[0]=%0d acc[21]=%0d]\n",
                   cycle_counter,
                   u_shared_engine.state,
                   u_shared_engine.run_active,
                   u_shared_engine.mac_clear,
                   u_shared_engine.mac_valid_in,
                   u_shared_engine.u_mac_array.mac_valid_q1,
                   u_shared_engine.oc_pass_idx_r,
                   u_shared_engine.u_address_generator.ic_cnt,
                   u_shared_engine.ag_act_in_ic_byte_idx_d,
                   u_shared_engine.ag_act_in_rd_en_d,
                   u_shared_engine.u_address_generator.act_in_ic_byte_idx,
                   $signed(u_shared_engine.mac_act_byte),
                   $signed(u_shared_engine.mac_weight_bus[21*8 +: 8]),
                   $signed(u_shared_engine.mac_weight_bus[0 +: 8]),
                   $signed(u_shared_engine.mac_acc_out[0 +: 32]),
                   $signed(u_shared_engine.mac_acc_out[21*32 +: 32]));
        end
    end
`endif

`ifdef DBG_TRACE_PIXEL
    // ============================================================
    // Trace every MAC cycle and end-of-pass state for ONE specific
    // output pixel (DBG_PIX_R, DBG_PIX_C). Useful when comparing
    // engine MAC sequence against the Python golden to localize a
    // missing/extra MAC product.
    // ============================================================
    integer dbg_pix_r, dbg_pix_c;
    integer dbg_lane_a, dbg_lane_b;
    initial begin
        if (!$value$plusargs("DBG_PIX_R=%d", dbg_pix_r)) dbg_pix_r = 3;
        if (!$value$plusargs("DBG_PIX_C=%d", dbg_pix_c)) dbg_pix_c = 5;
        if (!$value$plusargs("DBG_LANE_A=%d", dbg_lane_a)) dbg_lane_a = 9;
        if (!$value$plusargs("DBG_LANE_B=%d", dbg_lane_b)) dbg_lane_b = 58;
        $display("[TRACE] watching pixel [%0d,%0d] lanes %0d %0d",
                 dbg_pix_r, dbg_pix_c, dbg_lane_a, dbg_lane_b);
    end
    wire dbg_trace_match = (u_shared_engine.pixel_h_r == dbg_pix_r[7:0])
                        && (u_shared_engine.pixel_w_r == dbg_pix_c[7:0]);
    reg [15:0] dbg_mac_seq;
    initial dbg_mac_seq = 0;
    // Reset MAC sequence counter on mac_clear (start of new oc_pass)
    always @(posedge clk) begin
        if (dbg_trace_match && u_shared_engine.mac_clear) begin
            dbg_mac_seq <= 0;
            $display("[TRACE] cyc=%0d MAC_CLEAR @ pixel=(%0d,%0d) oc_pass=%0d",
                     cycle_counter,
                     u_shared_engine.pixel_h_r, u_shared_engine.pixel_w_r,
                     u_shared_engine.oc_pass_idx_r);
        end
    end
    // For the first 8 cycles after MAC_CLEAR (or just before), dump addr_gen
    // internals to see exactly when/where ic_cnt advances.
    reg [3:0] dbg_postclear_cnt;
    always @(posedge clk) begin
        if (!rst_n) dbg_postclear_cnt <= 4'd0;
        else if (dbg_trace_match && u_shared_engine.mac_clear) dbg_postclear_cnt <= 4'd1;
        else if (dbg_trace_match && dbg_postclear_cnt != 4'd0 && dbg_postclear_cnt < 4'd10)
            dbg_postclear_cnt <= dbg_postclear_cnt + 4'd1;
    end
    always @(posedge clk) begin
        if (dbg_trace_match && dbg_postclear_cnt != 4'd0 && dbg_postclear_cnt < 4'd10) begin
            $display("[AG] cyc=%0d post=%0d state=%0d run=%b run_d=%b ic=%0d kw=%0d kh=%0d k=%0d wraddr=%0d wren=%b araddr=%0d aren=%b byteidx=%0d byteidx_d=%0d mac_done=%b mac_valid_in=%b ag_wren_d=%b ag_aren_d=%b",
                cycle_counter,
                dbg_postclear_cnt,
                u_shared_engine.state,
                u_shared_engine.run_active,
                u_shared_engine.u_address_generator.run_active_d,
                u_shared_engine.u_address_generator.ic_cnt,
                u_shared_engine.u_address_generator.kw_cnt,
                u_shared_engine.u_address_generator.kh_cnt,
                u_shared_engine.u_address_generator.k_cnt,
                u_shared_engine.u_address_generator.weight_rd_addr,
                u_shared_engine.u_address_generator.weight_rd_en,
                u_shared_engine.u_address_generator.act_in_rd_addr,
                u_shared_engine.u_address_generator.act_in_rd_en,
                u_shared_engine.u_address_generator.act_in_ic_byte_idx,
                u_shared_engine.ag_act_in_ic_byte_idx_d,
                u_shared_engine.u_address_generator.mac_done,
                u_shared_engine.mac_valid_in,
                u_shared_engine.ag_weight_rd_en_d,
                u_shared_engine.ag_act_in_rd_en_d);
        end
    end
    // Every cycle that mac_valid_in is high (acc updates next cycle),
    // dump the act byte and the two lanes' weights and products.
    always @(posedge clk) begin
        if (dbg_trace_match && u_shared_engine.mac_valid_in) begin
            $display("[TRACE] cyc=%0d seq=%0d ic_byte_idx_d=%0d act=%0d w[%0d]=%0d p[%0d]=%0d w[%0d]=%0d p[%0d]=%0d",
                cycle_counter,
                dbg_mac_seq,
                u_shared_engine.ag_act_in_ic_byte_idx_d,
                $signed(u_shared_engine.mac_act_byte),
                dbg_lane_a,
                $signed(u_shared_engine.mac_weight_bus[dbg_lane_a*8 +: 8]),
                dbg_lane_a,
                $signed(u_shared_engine.mac_act_byte) *
                  $signed(u_shared_engine.mac_weight_bus[dbg_lane_a*8 +: 8]),
                dbg_lane_b,
                $signed(u_shared_engine.mac_weight_bus[dbg_lane_b*8 +: 8]),
                dbg_lane_b,
                $signed(u_shared_engine.mac_act_byte) *
                  $signed(u_shared_engine.mac_weight_bus[dbg_lane_b*8 +: 8]));
            dbg_mac_seq <= dbg_mac_seq + 1;
        end
    end
    // Dump final acc for the two tracked lanes when requant_valid_in fires.
    always @(posedge clk) begin
        if (dbg_trace_match && u_shared_engine.requant_valid_in) begin
            $display("[TRACE] cyc=%0d REQUANT_VALID_IN seq=%0d acc[%0d]=%0d acc[%0d]=%0d bias[%0d]=%0d bias[%0d]=%0d",
                cycle_counter, dbg_mac_seq,
                dbg_lane_a,
                $signed(u_shared_engine.mac_acc_out[dbg_lane_a*32 +: 32]),
                dbg_lane_b,
                $signed(u_shared_engine.mac_acc_out[dbg_lane_b*32 +: 32]),
                dbg_lane_a,
                $signed(u_shared_engine.requant_bias_in[dbg_lane_a*32 +: 32]),
                dbg_lane_b,
                $signed(u_shared_engine.requant_bias_in[dbg_lane_b*32 +: 32]));
        end
        if (dbg_trace_match && u_shared_engine.requant_valid_out) begin
            $display("[TRACE] cyc=%0d REQUANT_VALID_OUT out[%0d]=%0d out[%0d]=%0d",
                cycle_counter,
                dbg_lane_a,
                $signed(u_shared_engine.requant_data_out[dbg_lane_a*8 +: 8]),
                dbg_lane_b,
                $signed(u_shared_engine.requant_data_out[dbg_lane_b*8 +: 8]));
        end
    end
`endif

endmodule

// ===========================================================================
// Copies of the BRAM/URAM/bias module bodies from output/rtl/nn2rtl_top.v
// so the TB is self-contained.
// ===========================================================================

module uram_weight_bank #(
    parameter integer DEPTH         = 1024,
    parameter integer ADDR_W        = 17,
    parameter         MEM_INIT_FILE = ""
) (
    input  wire                    clk,
    input  wire [ADDR_W-1:0]       rd_addr,
    output reg  [287:0]            rd_data,
    input  wire                    rd_en
);
    (* ram_style = "ultra" *) reg [287:0] mem [0:DEPTH-1];
    initial begin
        if (MEM_INIT_FILE != "") $readmemh(MEM_INIT_FILE, mem);
    end
    // 2-cycle read latency to match the DEPLOYMENT URAM (nn2rtl_top.v
    // uram_weight_bank, xpm READ_LATENCY_A=2). [FIX 2026-05-28: was 1-cycle,
    // which masked the engine's weight-latency misalignment — the sweep was
    // byte-exact in isolation but the engine was wrong in-chain. The engine
    // now aligns to 2 cycles; this TB must match so the sweep tests deployment.]
    reg [287:0] rd_data_r1;
    always @(posedge clk) begin
        if (rd_en) rd_data_r1 <= mem[rd_addr];
        rd_data <= rd_data_r1;
    end
endmodule

module act_unified_mem #(
    parameter integer DEPTH  = 24576,
    parameter integer ADDR_W = 15
) (
    input  wire                    clk,
    input  wire [ADDR_W-1:0]       rd_addr,
    input  wire                    rd_en,
    output reg  [2047:0]           rd_data,
    input  wire [ADDR_W-1:0]       wr_addr,
    input  wire                    wr_en,
    input  wire [2047:0]           wr_data
);
    (* ram_style = "ultra" *) reg [2047:0] mem [0:DEPTH-1];
    always @(posedge clk) begin
        if (rd_en) rd_data <= mem[rd_addr];
    end
    always @(posedge clk) begin
        if (wr_en) mem[wr_addr] <= wr_data;
    end
endmodule

module bias_mem #(
    parameter integer SIZE_WORDS    = 256,
    parameter integer WORD_WIDTH    = 8192,
    parameter integer ADDR_W        = 16,
    parameter         MEM_INIT_FILE = "output/weights/bias.mem"
) (
    input  wire                    clk,
    input  wire [ADDR_W-1:0]       rd_addr,
    output reg  [WORD_WIDTH-1:0]   rd_data,
    input  wire                    rd_en
);
    (* ram_style = "block" *) reg [WORD_WIDTH-1:0] mem [0:SIZE_WORDS-1];
    initial begin
        if (MEM_INIT_FILE != "") $readmemh(MEM_INIT_FILE, mem);
    end
    always @(posedge clk) begin
        if (rd_en) rd_data <= mem[rd_addr];
    end
endmodule
