// Static Verilator testbench for nn2rtl.
//
// Handwritten infrastructure. Never regenerated by an agent.
//
// Build-time contract:
//   -DVMODEL_HEADER="\"Vconv1x1.h\""   // generated Verilator header for the DUT
//   -DVMODEL_CLASS=Vconv1x1            // generated Verilator class name for the DUT
//
// Run-time contract:
//   argv[1]  path to sidecar JSON produced by Assayer
//
// Canonical DUT port names (enforced at run time against the sidecar):
//   clk, rst_n, valid_in, ready_in, valid_out, data_in, data_out
//
// Handshake semantics implemented by this bench:
//   * valid_in / data_in are driven by the bench.
//   * ready_in is an OUTPUT of the DUT (backpressure upstream). The bench waits
//     for ready_in == 1 before asserting valid_in. A DUT that does not need
//     backpressure must tie ready_in high after reset.
//   * valid_out is an OUTPUT of the DUT. The bench samples data_out only on
//     cycles where valid_out == 1, tolerating bubbles between outputs.
//
// The testbench writes its structured results to the `results_path` field in
// the sidecar. `run_verilator` reads that file and returns a full VerifResult.

#include <algorithm>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <exception>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

#include "third_party/json.hpp"
#include "verilated.h"
#if __has_include("verilated_heavy.h")
#  include "verilated_heavy.h"
#endif

// Verilator's linker looks for this stub; it is the simulation timestamp used
// by waveform dumps. The bench does not emit waves, so a constant is fine.
double sc_time_stamp() {
  return 0;
}

#ifndef VMODEL_HEADER
#  error "VMODEL_HEADER must be defined at build time (e.g. -DVMODEL_HEADER=\"\\\"Vfoo.h\\\"\")."
#endif
#ifndef VMODEL_CLASS
#  error "VMODEL_CLASS must be defined at build time (e.g. -DVMODEL_CLASS=Vfoo)."
#endif

#include VMODEL_HEADER

using json = nlohmann::json;

namespace {

constexpr int64_t kNumericalTolerance = 3;  // README: pass threshold max_error <= 3.

struct Sidecar {
  std::string module_name;
  std::string module_id;
  std::string clock_signal;
  std::string reset_signal;
  std::string valid_in_signal;
  std::string valid_out_signal;
  std::string ready_in_signal;
  std::string data_in_signal;
  std::string data_out_signal;
  int bus_bytes_per_sample = 0;
  int input_width_bits = 0;
  int output_width_bits = 0;
  int pipeline_latency_cycles = 0;
  double clock_period_ns = 0.0;
  std::string golden_inputs_path;
  std::string golden_outputs_path;
  std::string results_path;
  std::string testbench_template_path;
  std::string contract_id;
  std::string weights_path;
  std::vector<std::string> weight_bank_paths;
  int axi_weight_data_width_bits = 64;
};

struct VectorFile {
  uint32_t samples_per_vector = 0;
  uint32_t bytes_per_sample = 0;
  uint32_t words_per_sample = 0;
  std::vector<std::vector<std::vector<uint32_t>>> vectors;
};

Sidecar loadSidecar(const std::string& path) {
  std::ifstream in(path);
  if (!in.is_open()) {
    throw std::runtime_error("Could not open sidecar '" + path + "'.");
  }

  json j;
  in >> j;

  Sidecar s;
  s.module_name = j.at("module_name").get<std::string>();
  s.module_id = j.at("module_id").get<std::string>();
  s.clock_signal = j.at("clock_signal").get<std::string>();
  s.reset_signal = j.at("reset_signal").get<std::string>();
  s.valid_in_signal = j.at("valid_in_signal").get<std::string>();
  s.valid_out_signal = j.at("valid_out_signal").get<std::string>();
  s.ready_in_signal = j.at("ready_in_signal").get<std::string>();
  s.data_in_signal = j.at("data_in_signal").get<std::string>();
  s.data_out_signal = j.at("data_out_signal").get<std::string>();
  s.bus_bytes_per_sample = j.at("bus_bytes_per_sample").get<int>();
  s.input_width_bits = j.at("input_width_bits").get<int>();
  s.output_width_bits = j.at("output_width_bits").get<int>();
  s.pipeline_latency_cycles = j.at("pipeline_latency_cycles").get<int>();
  s.clock_period_ns = j.at("clock_period_ns").get<double>();
  s.golden_inputs_path = j.at("golden_inputs_path").get<std::string>();
  s.golden_outputs_path = j.at("golden_outputs_path").get<std::string>();
  s.results_path = j.at("results_path").get<std::string>();
  s.testbench_template_path = j.at("testbench_template_path").get<std::string>();
  s.contract_id = j.value("contract_id", std::string(""));
  s.weights_path = j.value("weights_path", std::string(""));
  s.axi_weight_data_width_bits = j.value("axi_weight_data_width_bits", 64);
  if (j.contains("weight_bank_paths") && j.at("weight_bank_paths").is_array()) {
    s.weight_bank_paths = j.at("weight_bank_paths").get<std::vector<std::string>>();
  }
  return s;
}

// Binary vector file format (.goldin / .goldout):
//   [ 0..4)  magic            : ASCII "NN2V"
//   [ 4..8)  version          : uint32 LE (= 2)
//   [ 8..12) num_vectors      : uint32 LE
//   [12..16) samples_per_vector : uint32 LE
//   [16..20) bytes_per_sample : uint32 LE
//   [20..)   data             : num_vectors * samples_per_vector *
//                               ceil(bytes_per_sample / 4) int32 LE words
VectorFile loadVectorFile(const std::string& path) {
  std::ifstream in(path, std::ios::binary);
  if (!in.is_open()) {
    throw std::runtime_error("Could not open vector file '" + path + "'.");
  }

  char magic[4];
  uint32_t version = 0;
  uint32_t num_vectors = 0;
  uint32_t samples_per_vector = 0;
  uint32_t bytes_per_sample = 0;
  in.read(magic, sizeof(magic));
  in.read(reinterpret_cast<char*>(&version), sizeof(version));
  in.read(reinterpret_cast<char*>(&num_vectors), sizeof(num_vectors));
  in.read(reinterpret_cast<char*>(&samples_per_vector), sizeof(samples_per_vector));
  in.read(reinterpret_cast<char*>(&bytes_per_sample), sizeof(bytes_per_sample));
  if (!in) {
    throw std::runtime_error("Vector file '" + path + "' header is truncated.");
  }
  if (magic[0] != 'N' || magic[1] != 'N' || magic[2] != '2' || magic[3] != 'V') {
    throw std::runtime_error("Vector file '" + path + "' has wrong magic; expected 'NN2V'.");
  }
  if (version != 2) {
    throw std::runtime_error("Vector file '" + path + "' has unsupported version.");
  }
  if (bytes_per_sample == 0) {
    throw std::runtime_error("Vector file '" + path + "' bytes_per_sample must be positive.");
  }

  VectorFile file;
  file.samples_per_vector = samples_per_vector;
  file.bytes_per_sample = bytes_per_sample;
  file.words_per_sample = (bytes_per_sample + 3U) / 4U;
  file.vectors.reserve(num_vectors);

  std::vector<int32_t> row_buffer(samples_per_vector * file.words_per_sample);
  for (uint32_t v = 0; v < num_vectors; ++v) {
    in.read(
        reinterpret_cast<char*>(row_buffer.data()),
        static_cast<std::streamsize>(row_buffer.size() * sizeof(int32_t)));
    if (!in) {
      throw std::runtime_error("Vector file '" + path + "' data is truncated.");
    }

    std::vector<std::vector<uint32_t>> vector_samples;
    vector_samples.reserve(samples_per_vector);
    for (uint32_t sample = 0; sample < samples_per_vector; ++sample) {
      std::vector<uint32_t> words(file.words_per_sample, 0U);
      for (uint32_t word = 0; word < file.words_per_sample; ++word) {
        const size_t index = static_cast<size_t>(sample) * file.words_per_sample + word;
        words[word] = static_cast<uint32_t>(row_buffer[index]);
      }
      vector_samples.push_back(std::move(words));
    }
    file.vectors.push_back(std::move(vector_samples));
  }

  return file;
}

std::vector<uint8_t> loadReadmemhByteFile(const std::string& path) {
  std::ifstream in(path);
  if (!in.is_open()) {
    throw std::runtime_error("Could not open weight hex file '" + path + "'.");
  }

  std::vector<uint8_t> bytes;
  std::string line;
  size_t cursor = 0;
  while (std::getline(in, line)) {
    const size_t comment = line.find("//");
    if (comment != std::string::npos) {
      line = line.substr(0, comment);
    }
    std::istringstream iss(line);
    std::string token;
    while (iss >> token) {
      if (token.empty()) continue;
      if (token[0] == '@') {
        cursor = static_cast<size_t>(std::stoull(token.substr(1), nullptr, 16));
        if (bytes.size() < cursor) {
          bytes.resize(cursor, 0);
        }
        continue;
      }
      const uint64_t value = std::stoull(token, nullptr, 16);
      if (bytes.size() <= cursor) {
        bytes.resize(cursor + 1, 0);
      }
      bytes[cursor] = static_cast<uint8_t>(value & 0xFFU);
      ++cursor;
    }
  }
  return bytes;
}

void requireCanonicalSignals(const Sidecar& s) {
  const auto check = [](const std::string& field,
                        const std::string& value,
                        const std::string& expected) {
    if (value != expected) {
      throw std::runtime_error(
          "Sidecar field '" + field + "' must be '" + expected +
          "' (canonical signal name); got '" + value + "'.");
    }
  };
  check("clock_signal", s.clock_signal, "clk");
  check("reset_signal", s.reset_signal, "rst_n");
  check("valid_in_signal", s.valid_in_signal, "valid_in");
  check("valid_out_signal", s.valid_out_signal, "valid_out");
  check("ready_in_signal", s.ready_in_signal, "ready_in");
  check("data_in_signal", s.data_in_signal, "data_in");
  check("data_out_signal", s.data_out_signal, "data_out");
}

void requireConsistentBusWidths(const Sidecar& sidecar) {
  if (sidecar.input_width_bits <= 0 || sidecar.input_width_bits % 8 != 0) {
    throw std::runtime_error(
        "Sidecar input_width_bits must be a positive multiple of 8; got " +
        std::to_string(sidecar.input_width_bits) + ".");
  }
  if (sidecar.output_width_bits <= 0 || sidecar.output_width_bits % 8 != 0) {
    throw std::runtime_error(
        "Sidecar output_width_bits must be a positive multiple of 8; got " +
        std::to_string(sidecar.output_width_bits) + ".");
  }
  if (sidecar.bus_bytes_per_sample != sidecar.input_width_bits / 8) {
    throw std::runtime_error(
        "Sidecar bus_bytes_per_sample=" + std::to_string(sidecar.bus_bytes_per_sample) +
        " does not match input_width_bits/8=" + std::to_string(sidecar.input_width_bits / 8) +
        ".");
  }
}

template <typename SignalT>
void clearSignal(SignalT& signal) {
  if constexpr (std::is_integral_v<SignalT>) {
    signal = 0;
  }
}

template <std::size_t N_Words>
void clearSignal(VlWide<N_Words>& signal) {
  for (size_t i = 0; i < N_Words; ++i) {
    signal.at(i) = 0U;
  }
}

template <std::size_t N_Words>
void clearSignal(WData (&signal)[N_Words]) {
  for (size_t i = 0; i < N_Words; ++i) {
    signal[i] = 0U;
  }
}

template <typename SignalT>
void assignPackedWords(SignalT& signal, const std::vector<uint32_t>& words) {
  if constexpr (std::is_integral_v<SignalT>) {
    const size_t max_words = (sizeof(SignalT) + 3U) / 4U;
    if (words.size() > max_words) {
      throw std::runtime_error(
          "Packed sample needs " + std::to_string(words.size()) +
          " words but the DUT input port can hold only " + std::to_string(max_words) +
          " words.");
    }
    uint64_t packed = 0;
    for (size_t i = 0; i < words.size(); ++i) {
      packed |= static_cast<uint64_t>(words[i]) << (32U * i);
    }
    signal = static_cast<SignalT>(packed);
  }
}

template <std::size_t N_Words>
void assignPackedWords(VlWide<N_Words>& signal, const std::vector<uint32_t>& words) {
  if (words.size() > N_Words) {
    throw std::runtime_error(
        "Packed sample needs " + std::to_string(words.size()) +
        " words but the DUT input port can hold only " + std::to_string(N_Words) +
        " words.");
  }
  clearSignal(signal);
  for (size_t i = 0; i < words.size(); ++i) {
    signal.at(i) = words[i];
  }
}

template <std::size_t N_Words>
void assignPackedWords(WData (&signal)[N_Words], const std::vector<uint32_t>& words) {
  if (words.size() > N_Words) {
    throw std::runtime_error(
        "Packed sample needs " + std::to_string(words.size()) +
        " words but the DUT input port can hold only " + std::to_string(N_Words) +
        " words.");
  }
  clearSignal(signal);
  for (size_t i = 0; i < words.size(); ++i) {
    signal[i] = words[i];
  }
}

template <typename SignalT>
std::vector<uint32_t> readPackedWords(const SignalT& signal, size_t words_per_sample) {
  std::vector<uint32_t> words(words_per_sample, 0U);
  if constexpr (std::is_integral_v<SignalT>) {
    const size_t max_words = (sizeof(SignalT) + 3U) / 4U;
    if (words_per_sample > max_words) {
      throw std::runtime_error(
          "Expected " + std::to_string(words_per_sample) +
          " output words but the DUT output port can hold only " +
          std::to_string(max_words) + " words.");
    }
    using UnsignedSignalT = std::make_unsigned_t<SignalT>;
    const uint64_t packed = static_cast<uint64_t>(static_cast<UnsignedSignalT>(signal));
    for (size_t i = 0; i < words_per_sample; ++i) {
      words[i] = static_cast<uint32_t>(packed >> (32U * i));
    }
  }
  return words;
}

template <std::size_t N_Words>
std::vector<uint32_t> readPackedWords(const VlWide<N_Words>& signal, size_t words_per_sample) {
  if (words_per_sample > N_Words) {
    throw std::runtime_error(
        "Expected " + std::to_string(words_per_sample) +
        " output words but the DUT output port can hold only " +
        std::to_string(N_Words) + " words.");
  }
  std::vector<uint32_t> words(words_per_sample, 0U);
  for (size_t i = 0; i < words_per_sample; ++i) {
    words[i] = signal.at(i);
  }
  return words;
}

template <std::size_t N_Words>
std::vector<uint32_t> readPackedWords(const WData (&signal)[N_Words], size_t words_per_sample) {
  if (words_per_sample > N_Words) {
    throw std::runtime_error(
        "Expected " + std::to_string(words_per_sample) +
        " output words but the DUT output port can hold only " +
        std::to_string(N_Words) + " words.");
  }
  std::vector<uint32_t> words(words_per_sample, 0U);
  for (size_t i = 0; i < words_per_sample; ++i) {
    words[i] = signal[i];
  }
  return words;
}

std::vector<int64_t> unpackInt8Channels(
    const std::vector<uint32_t>& words,
    uint32_t bytes_per_sample) {
  std::vector<int64_t> channels;
  channels.reserve(bytes_per_sample);
  for (uint32_t byte_index = 0; byte_index < bytes_per_sample; ++byte_index) {
    const uint32_t word = words[byte_index / 4U];
    const uint8_t raw = static_cast<uint8_t>((word >> (8U * (byte_index % 4U))) & 0xFFU);
    channels.push_back(static_cast<int64_t>(static_cast<int8_t>(raw)));
  }
  return channels;
}

template <typename Dut>
void tickClock(Dut* dut, int64_t& cycle_counter) {
  dut->clk = 0;
  dut->eval();
  dut->clk = 1;
  dut->eval();
  ++cycle_counter;
}

template <typename Dut, typename = void>
struct HasAxiWeightReadPorts : std::false_type {};

template <typename Dut>
struct HasAxiWeightReadPorts<Dut, std::void_t<
    decltype(std::declval<Dut&>().weights_arvalid),
    decltype(std::declval<Dut&>().weights_arready),
    decltype(std::declval<Dut&>().weights_araddr),
    decltype(std::declval<Dut&>().weights_arlen),
    decltype(std::declval<Dut&>().weights_rvalid),
    decltype(std::declval<Dut&>().weights_rready),
    decltype(std::declval<Dut&>().weights_rdata),
    decltype(std::declval<Dut&>().weights_rlast)>> : std::true_type {};

template <typename Dut>
void clearAxiWeightInputs(Dut* dut) {
  if constexpr (HasAxiWeightReadPorts<Dut>::value) {
    dut->weights_arready = 0;
    dut->weights_rvalid = 0;
    dut->weights_rdata = 0;
    dut->weights_rlast = 0;
  }
}

template <typename Dut>
void applyReset(Dut* dut, int64_t& cycle_counter, int cycles = 5) {
  dut->rst_n = 0;
  dut->valid_in = 0;
  clearSignal(dut->data_in);
  clearAxiWeightInputs(dut);
  for (int i = 0; i < cycles; ++i) {
    tickClock(dut, cycle_counter);
  }
  dut->rst_n = 1;
}

class AxiWeightMemory {
 public:
  explicit AxiWeightMemory(const Sidecar& sidecar)
      : contract_id_(sidecar.contract_id),
        bytes_per_beat_(std::max(1, sidecar.axi_weight_data_width_bits / 8)) {
    if (contract_id_ != "dram-backed-weights") {
      return;
    }
    if (sidecar.weights_path.empty()) {
      status_ = "missing_weights_path";
      return;
    }
    memory_ = loadReadmemhByteFile(sidecar.weights_path);
    enabled_ = true;
    status_ = "ready";
  }

  bool enabled() const { return enabled_; }
  const std::string& status() const { return status_; }
  int64_t arvalid_cycles() const { return arvalid_cycles_; }
  int64_t arready_cycles() const { return arready_cycles_; }
  int64_t ar_handshakes() const { return ar_handshakes_; }
  int64_t rvalid_cycles() const { return rvalid_cycles_; }
  int64_t rready_cycles() const { return rready_cycles_; }
  int64_t r_beats() const { return r_beats_; }
  int64_t completed_bursts() const { return completed_bursts_; }
  int64_t first_arvalid_cycle() const { return first_arvalid_cycle_; }
  int64_t first_ar_handshake_cycle() const { return first_ar_handshake_cycle_; }
  int64_t first_r_beat_cycle() const { return first_r_beat_cycle_; }
  int64_t out_of_range_reads() const { return out_of_range_reads_; }
  bool applicable() const { return contract_id_ == "dram-backed-weights"; }

  template <typename Dut>
  void requireCompatibleDut() const {
    if (applicable() && !HasAxiWeightReadPorts<Dut>::value) {
      throw std::runtime_error(
          "dram-backed-weights sidecar requires DUT AXI weight ports "
          "(weights_arvalid/arready/araddr/arlen/rvalid/rready/rdata/rlast), "
          "but the generated Verilated model does not expose them.");
    }
  }

  template <typename Dut>
  void drive(Dut* dut, int64_t cycle) {
    if constexpr (!HasAxiWeightReadPorts<Dut>::value) {
      (void)dut;
      (void)cycle;
      return;
    } else {
      if (!applicable()) {
        dut->weights_arready = 0;
        dut->weights_rvalid = 0;
        dut->weights_rdata = 0;
        dut->weights_rlast = 0;
        return;
      }

      if (dut->weights_arvalid) {
        ++arvalid_cycles_;
        if (first_arvalid_cycle_ < 0) first_arvalid_cycle_ = cycle;
      }
      if (dut->weights_rready) {
        ++rready_cycles_;
      }

      const bool can_accept_ar = enabled_ && !burst_active_ && !holding_r_;
      dut->weights_arready = can_accept_ar ? 1 : 0;
      if (can_accept_ar) {
        ++arready_cycles_;
      }

      if (can_accept_ar && dut->weights_arvalid) {
        burst_active_ = true;
        burst_addr_ = static_cast<uint64_t>(dut->weights_araddr);
        burst_len_ = static_cast<uint32_t>(dut->weights_arlen);
        beat_index_ = 0;
        ++ar_handshakes_;
        if (first_ar_handshake_cycle_ < 0) first_ar_handshake_cycle_ = cycle;
      }

      if (!holding_r_ && burst_active_) {
        hold_data_ = readBeat(burst_addr_ + static_cast<uint64_t>(beat_index_) * bytes_per_beat_);
        hold_last_ = beat_index_ >= burst_len_;
        holding_r_ = true;
      }

      if (holding_r_) {
        dut->weights_rvalid = 1;
        dut->weights_rdata = static_cast<decltype(dut->weights_rdata)>(hold_data_);
        dut->weights_rlast = hold_last_ ? 1 : 0;
        ++rvalid_cycles_;
        if (dut->weights_rready) {
          ++r_beats_;
          if (first_r_beat_cycle_ < 0) first_r_beat_cycle_ = cycle;
          if (hold_last_) {
            ++completed_bursts_;
            burst_active_ = false;
          } else {
            ++beat_index_;
          }
          holding_r_ = false;
        }
      } else {
        dut->weights_rvalid = 0;
        dut->weights_rdata = 0;
        dut->weights_rlast = 0;
      }
    }
  }

  json traceJson() const {
    return {
        {"axi_weight_memory_model_enabled", enabled_},
        {"axi_weight_memory_model_status", status_},
        {"axi_weight_bytes_loaded", static_cast<int64_t>(memory_.size())},
        {"axi_weight_bytes_per_beat", bytes_per_beat_},
        {"axi_weight_arvalid_cycles", arvalid_cycles_},
        {"axi_weight_arready_cycles", arready_cycles_},
        {"axi_weight_ar_handshakes", ar_handshakes_},
        {"axi_weight_rvalid_cycles", rvalid_cycles_},
        {"axi_weight_rready_cycles", rready_cycles_},
        {"axi_weight_r_beats", r_beats_},
        {"axi_weight_completed_bursts", completed_bursts_},
        {"axi_weight_first_arvalid_cycle", first_arvalid_cycle_},
        {"axi_weight_first_ar_handshake_cycle", first_ar_handshake_cycle_},
        {"axi_weight_first_r_beat_cycle", first_r_beat_cycle_},
        {"axi_weight_out_of_range_reads", out_of_range_reads_},
    };
  }

 private:
  uint64_t readBeat(uint64_t byte_addr) {
    uint64_t word = 0;
    for (int byte = 0; byte < bytes_per_beat_ && byte < 8; ++byte) {
      const uint64_t index = byte_addr + static_cast<uint64_t>(byte);
      uint8_t value = 0;
      if (index < memory_.size()) {
        value = memory_[static_cast<size_t>(index)];
      } else {
        ++out_of_range_reads_;
      }
      word |= static_cast<uint64_t>(value) << (8U * byte);
    }
    return word;
  }

  std::string contract_id_;
  std::vector<uint8_t> memory_;
  bool enabled_ = false;
  std::string status_ = "not_applicable";
  int bytes_per_beat_ = 8;
  bool burst_active_ = false;
  bool holding_r_ = false;
  uint64_t burst_addr_ = 0;
  uint32_t burst_len_ = 0;
  uint32_t beat_index_ = 0;
  uint64_t hold_data_ = 0;
  bool hold_last_ = false;
  int64_t arvalid_cycles_ = 0;
  int64_t arready_cycles_ = 0;
  int64_t ar_handshakes_ = 0;
  int64_t rvalid_cycles_ = 0;
  int64_t rready_cycles_ = 0;
  int64_t r_beats_ = 0;
  int64_t completed_bursts_ = 0;
  int64_t first_arvalid_cycle_ = -1;
  int64_t first_ar_handshake_cycle_ = -1;
  int64_t first_r_beat_cycle_ = -1;
  int64_t out_of_range_reads_ = 0;
};

void writeResults(const std::string& results_path, const json& results) {
  std::filesystem::path p = results_path;
  if (!p.parent_path().empty()) {
    std::filesystem::create_directories(p.parent_path());
  }
  std::ofstream out(p);
  if (!out.is_open()) {
    throw std::runtime_error("Could not open results file '" + results_path + "' for writing.");
  }
  out << results.dump(2) << std::endl;
}

void writeFallbackError(const std::string& sidecar_path, const std::exception& e) {
  try {
    std::ifstream in(sidecar_path);
    if (!in.is_open()) {
      return;
    }
    json j;
    in >> j;
    if (!j.contains("results_path")) {
      return;
    }
    const std::string results_path = j.at("results_path").get<std::string>();
    const std::string module_id = j.value("module_id", std::string(""));

    json error_result = {
        {"module_id", module_id},
        {"status", "fail"},
        // status_class = "tb_setup_error" is distinct from "sim_stalled" /
        // "sim_completed_mismatch" — it means the testbench could not start
        // simulation at all (bad sidecar, could not open goldens, etc.).
        // Surgeon should treat this as "the RTL never ran; preflight or
        // compile probably caught the real issue" rather than reasoning
        // about output values.
        {"status_class", "tb_setup_error"},
        {"timing_pass", false},
        {"timing_actual_cycles", -1},
        {"timing_expected_cycles", -1},
        {"expected", json::array()},
        {"got", json::array()},
        {"max_error", -1},
        {"mean_error", -1.0},
        {"failure_class", nullptr},
        {"fix_hint", std::string("Testbench setup error before simulation: ") + e.what()},
        {"verilator_stderr", std::string(e.what())},
        {"outputs_expected", 0},
        {"outputs_received", 0},
        {"missing_index_start", -1},
        {"missing_index_end", -1},
        {"last_valid_out_cycle", -1},
        {"simulation_end_cycle", -1},
        {"output_gap_histogram", std::vector<int64_t>{0, 0, 0, 0}},
        {"first_mismatch_index", -1},
        {"first_mismatch_expected", 0},
        {"first_mismatch_got", 0},
    };
    writeResults(results_path, error_result);
  } catch (...) {
    // Best-effort only — we already have a stderr trace.
  }
}

}  // namespace

int main(int argc, char** argv) {
  Verilated::commandArgs(argc, argv);

  if (argc < 2) {
    std::cerr << "Usage: " << argv[0] << " <sidecar.json>\n";
    return 2;
  }

  const std::string sidecar_path = argv[1];

  try {
    const Sidecar sidecar = loadSidecar(sidecar_path);
    requireCanonicalSignals(sidecar);
    requireConsistentBusWidths(sidecar);

    const VectorFile golden_inputs = loadVectorFile(sidecar.golden_inputs_path);
    const VectorFile golden_outputs = loadVectorFile(sidecar.golden_outputs_path);

    if (golden_inputs.vectors.size() != golden_outputs.vectors.size()) {
      throw std::runtime_error(
          "Golden inputs and outputs differ in vector count (" +
          std::to_string(golden_inputs.vectors.size()) + " vs " +
          std::to_string(golden_outputs.vectors.size()) + ").");
    }
    if (golden_inputs.bytes_per_sample != static_cast<uint32_t>(sidecar.bus_bytes_per_sample)) {
      throw std::runtime_error(
          "Golden inputs bytes_per_sample=" + std::to_string(golden_inputs.bytes_per_sample) +
          " does not match sidecar bus_bytes_per_sample=" +
          std::to_string(sidecar.bus_bytes_per_sample) + ".");
    }
    if (golden_outputs.bytes_per_sample != static_cast<uint32_t>(sidecar.output_width_bits / 8)) {
      throw std::runtime_error(
          "Golden outputs bytes_per_sample=" + std::to_string(golden_outputs.bytes_per_sample) +
          " does not match sidecar output_width_bits/8=" +
          std::to_string(sidecar.output_width_bits / 8) + ".");
    }

    AxiWeightMemory axi_weight_memory(sidecar);
    auto dut = std::make_unique<VMODEL_CLASS>();
    axi_weight_memory.requireCompatibleDut<VMODEL_CLASS>();
    int64_t cycle_counter = 0;
    applyReset(dut.get(), cycle_counter);

    std::vector<int64_t> expected_flat;
    std::vector<int64_t> actual_flat;
    int64_t max_abs_error = 0;
    double sum_abs_error = 0.0;
    size_t sample_count = 0;

    int64_t first_valid_in_cycle = -1;
    int64_t first_valid_out_cycle = -1;
    bool timing_observed = false;

    // Per-vector timing check: every vector must honour the sidecar's declared
    // latency, not just the first one. A single boolean collapses the per-vector
    // results.
    bool all_vectors_timing_ok = true;
    int64_t worst_vector_actual_cycles = -1;

    const int64_t hang_budget = sidecar.pipeline_latency_cycles * 4 + 16;

    // The testbench emits **facts** about simulation behaviour — never
    // interpretation or guesses at root cause. The Surgeon agent reasons
    // from these facts with a reasoning-capable model; it does not need
    // (and should not be misled by) pre-written hypotheses like "DUT
    // likely missing a drain phase". That style of hint is architecture-
    // specific, grows without bound, and is frequently wrong.
    //
    // Facts we capture below:
    //   status_class          "sim_stalled" | "sim_completed_mismatch"
    //   outputs_expected      total expected outputs across all vectors
    //   outputs_received      how many the DUT actually emitted
    //   missing_index_start   first index the DUT never emitted (or -1)
    //   missing_index_end     exclusive end of the contiguous missing range
    //   last_valid_out_cycle  absolute cycle of the most recent valid_out
    //   simulation_end_cycle  absolute cycle when simulation stopped
    //   output_gap_histogram  4-quarter bucket counts of missing outputs
    //                         (start-heavy ≈ reset/init bug; middle-heavy
    //                         ≈ counter overflow; end-heavy ≈ drain exits
    //                         early; uniform ≈ per-cycle arithmetic —
    //                         but THIS IS FOR SURGEON TO INFER, not for
    //                         the testbench to assert.)
    //   first_mismatch_*      first index where expected != got, plus the
    //                         (expected, got) values at that index
    bool stalled = false;
    int64_t total_outputs_expected = 0;
    int64_t total_outputs_received = 0;
    int64_t last_valid_out_cycle_tracked = -1;
    int64_t simulation_end_cycle_tracked = 0;
    int64_t stall_vector_index = -1;
    int64_t first_mismatch_flat_index = -1;
    int64_t first_mismatch_expected_v = 0;
    int64_t first_mismatch_got_v = 0;
    int64_t first_mismatch_vector_index = -1;
    int64_t first_mismatch_output_index = -1;
    int64_t first_mismatch_channel_index = -1;
    int64_t exact_match_count = 0;
    int64_t mismatch_count = 0;
    int64_t signed_error_sum = 0;
    int64_t positive_error_count = 0;
    int64_t negative_error_count = 0;

    // Per-vector accumulators. Each entry mirrors the aggregate stats but
    // restricted to a single golden vector. Surgeon uses these to localize
    // failures (e.g. "v0 passes 100%, v2 fails 8%") without the simulation
    // having to be re-run.
    struct PerVectorAccum {
      int64_t vector_idx = 0;
      int64_t outputs_received = 0;
      int64_t exact_match_count = 0;
      int64_t mismatch_count = 0;
      int64_t max_error = 0;
      double sum_abs_error = 0.0;
      int64_t sample_count = 0;
      int64_t actual_cycles = -1;
      int64_t first_mismatch_output_index = -1;
    };
    std::vector<PerVectorAccum> per_vector_accums;
    per_vector_accums.reserve(golden_inputs.vectors.size());

    // Unified interleaved drive/sample loop. For each test vector we drive
    // packed input samples whenever the DUT is ready and we sample packed
    // outputs whenever valid_out is high, both in the same tick.
    for (size_t v = 0; v < golden_inputs.vectors.size() && !stalled; ++v) {
      const auto& inputs = golden_inputs.vectors[v];
      const auto& outputs = golden_outputs.vectors[v];
      total_outputs_expected += static_cast<int64_t>(outputs.size());

      PerVectorAccum vacc;
      vacc.vector_idx = static_cast<int64_t>(v);

      size_t input_idx = 0;
      size_t output_idx = 0;
      int64_t idle_cycles = 0;
      int64_t vector_first_valid_in = -1;
      int64_t vector_first_valid_out = -1;

      while (output_idx < outputs.size()) {
        if (idle_cycles > hang_budget) {
          stalled = true;
          stall_vector_index = static_cast<int64_t>(v);
          break;
        }

        if (dut->valid_out) {
          if (!timing_observed) {
            first_valid_out_cycle = cycle_counter;
            timing_observed = true;
          }
          if (vector_first_valid_out < 0) {
            vector_first_valid_out = cycle_counter;
          }
          last_valid_out_cycle_tracked = cycle_counter;

          const auto got_words = readPackedWords(dut->data_out, golden_outputs.words_per_sample);
          const auto got_channels = unpackInt8Channels(got_words, golden_outputs.bytes_per_sample);
          const auto expected_channels =
              unpackInt8Channels(outputs[output_idx], golden_outputs.bytes_per_sample);

          if (got_channels.size() != expected_channels.size()) {
            throw std::runtime_error(
                "Packed output width mismatch on vector " + std::to_string(v) +
                " sample " + std::to_string(output_idx) + ".");
          }

          for (size_t channel = 0; channel < expected_channels.size(); ++channel) {
            const int64_t got = got_channels[channel];
            const int64_t expected = expected_channels[channel];
            expected_flat.push_back(expected);
            actual_flat.push_back(got);

            if (first_mismatch_flat_index < 0 && got != expected) {
              first_mismatch_flat_index =
                  static_cast<int64_t>(expected_flat.size()) - 1;
              first_mismatch_expected_v = expected;
              first_mismatch_got_v = got;
              first_mismatch_vector_index = static_cast<int64_t>(v);
              first_mismatch_output_index = static_cast<int64_t>(output_idx);
              first_mismatch_channel_index = static_cast<int64_t>(channel);
            }

            const int64_t signed_diff = got - expected;
            signed_error_sum += signed_diff;
            if (signed_diff == 0) {
              ++exact_match_count;
              ++vacc.exact_match_count;
            } else {
              ++mismatch_count;
              ++vacc.mismatch_count;
              if (vacc.first_mismatch_output_index < 0) {
                vacc.first_mismatch_output_index = static_cast<int64_t>(output_idx);
              }
              if (signed_diff > 0) {
                ++positive_error_count;
              } else {
                ++negative_error_count;
              }
            }

            const int64_t diff = got >= expected ? got - expected : expected - got;
            if (diff > max_abs_error) {
              max_abs_error = diff;
            }
            if (diff > vacc.max_error) {
              vacc.max_error = diff;
            }
            sum_abs_error += static_cast<double>(diff);
            vacc.sum_abs_error += static_cast<double>(diff);
            ++sample_count;
            ++vacc.sample_count;
          }

          ++output_idx;
          ++total_outputs_received;
          ++vacc.outputs_received;
          idle_cycles = 0;
        } else {
          ++idle_cycles;
        }

        if (input_idx < inputs.size() && dut->ready_in) {
          if (first_valid_in_cycle < 0) {
            first_valid_in_cycle = cycle_counter;
          }
          if (vector_first_valid_in < 0) {
            vector_first_valid_in = cycle_counter;
          }
          assignPackedWords(dut->data_in, inputs[input_idx]);
          dut->valid_in = 1;
          ++input_idx;
        } else {
          dut->valid_in = 0;
          clearSignal(dut->data_in);
        }

        axi_weight_memory.drive(dut.get(), cycle_counter);

        // Always tick — including the cycle that sampled the vector's final
        // output. Skipping this tick leaves valid_out/data_out live into the
        // next vector, which would then mis-sample the previous final output
        // as its own first output.
        tickClock(dut.get(), cycle_counter);
      }

      dut->valid_in = 0;
      clearSignal(dut->data_in);

      if (vector_first_valid_in >= 0 && vector_first_valid_out >= 0) {
        const int64_t vector_actual = vector_first_valid_out - vector_first_valid_in;
        std::cerr << "[NN2RTL_DEBUG] vec=" << v
                  << " first_in=" << vector_first_valid_in
                  << " first_out=" << vector_first_valid_out
                  << " actual=" << vector_actual
                  << " expected=" << sidecar.pipeline_latency_cycles
                  << "\n";
        if (vector_actual != sidecar.pipeline_latency_cycles) {
          all_vectors_timing_ok = false;
        }
        if (vector_actual > worst_vector_actual_cycles) {
          worst_vector_actual_cycles = vector_actual;
        }
        vacc.actual_cycles = vector_actual;
      } else {
        std::cerr << "[NN2RTL_DEBUG] vec=" << v
                  << " first_in=" << vector_first_valid_in
                  << " first_out=" << vector_first_valid_out
                  << " (incomplete)\n";
        all_vectors_timing_ok = false;
      }
      per_vector_accums.push_back(vacc);
    }

    dut->final();
    simulation_end_cycle_tracked = cycle_counter;

    const double mean_error =
        sample_count ? sum_abs_error / static_cast<double>(sample_count) : 0.0;
    const int64_t timing_expected_cycles = sidecar.pipeline_latency_cycles;
    const int64_t timing_actual_cycles =
        (first_valid_in_cycle >= 0 && first_valid_out_cycle >= 0)
            ? first_valid_out_cycle - first_valid_in_cycle
            : -1;
    const bool timing_pass =
        timing_observed &&
        timing_actual_cycles == timing_expected_cycles &&
        all_vectors_timing_ok;
    const int64_t timing_actual_cycles_reported =
        (worst_vector_actual_cycles >= 0 && !all_vectors_timing_ok)
            ? worst_vector_actual_cycles
            : timing_actual_cycles;
    const bool numerical_pass = max_abs_error <= kNumericalTolerance;
    const std::string status = (numerical_pass && timing_pass) ? "pass" : "fail";

    // Cap the expected/got arrays to a diagnostic head+tail sample. The full
    // arrays for a 64-channel conv are ~1.6M entries; embedding them all in
    // results.json bloats pipeline_state.json (which stores the VerifResult)
    // and the Surgeon delegation prompt (which must fit in a model context
    // window). Surgeon only needs a sample of the mismatch to diagnose; the
    // aggregate stats (max_error, mean_error, sample_count) cover the rest.
    constexpr size_t kMaxDiagnosticSamples = 1000;
    json expected_json;
    json got_json;
    if (expected_flat.size() <= kMaxDiagnosticSamples) {
      expected_json = expected_flat;
      got_json = actual_flat;
    } else {
      const size_t head = kMaxDiagnosticSamples / 2;
      const size_t tail = kMaxDiagnosticSamples - head;
      expected_json = json::array();
      got_json = json::array();
      for (size_t i = 0; i < head; ++i) {
        expected_json.push_back(expected_flat[i]);
        got_json.push_back(actual_flat[i]);
      }
      for (size_t i = expected_flat.size() - tail; i < expected_flat.size(); ++i) {
        expected_json.push_back(expected_flat[i]);
        got_json.push_back(actual_flat[i]);
      }
    }

    // A stall always forces a fail, even if the partial outputs that DID
    // arrive matched exactly (that still leaves the missing ones).
    const std::string final_status = stalled ? std::string("fail") : status;

    // status_class is a FACT about simulation shape, not a root-cause guess:
    //   sim_stalled              simulation began, partial outputs, stopped emitting
    //   sim_completed_mismatch   simulation finished normally but values disagreed
    //   sim_passed               functional + timing pass (returned as status "pass")
    std::string status_class;
    if (stalled) {
      status_class = "sim_stalled";
    } else if (final_status == "pass") {
      status_class = "sim_passed";
    } else {
      status_class = "sim_completed_mismatch";
    }

    // Missing output range — contiguous from first not-emitted index to the
    // total expected count. For multi-vector runs with a stall on vector v,
    // this covers everything from the stall point onward across all later
    // vectors. When no outputs are missing, both fields are -1.
    int64_t missing_index_start = -1;
    int64_t missing_index_end = -1;
    if (total_outputs_received < total_outputs_expected) {
      missing_index_start = total_outputs_received;
      missing_index_end = total_outputs_expected;
    }

    // 4-quarter histogram of MISSING output indices (not of received ones).
    // Interpreting this is Surgeon's job — the testbench just buckets:
    //   start-heavy = missing near index 0
    //   middle-heavy = missing around the middle of the expected stream
    //   end-heavy = missing at the tail
    //   uniform = scattered across all quarters
    std::vector<int64_t> output_gap_histogram = {0, 0, 0, 0};
    if (missing_index_start >= 0 && total_outputs_expected > 0) {
      for (int64_t i = missing_index_start; i < missing_index_end; ++i) {
        const int64_t q_raw = (i * 4) / total_outputs_expected;
        const int64_t q = (q_raw < 0) ? 0 : (q_raw > 3 ? 3 : q_raw);
        output_gap_histogram[static_cast<size_t>(q)] += 1;
      }
    }

    // Factual fix_hint. Restates the numbers so downstream tooling that
    // only looks at fix_hint still sees the headline. No interpretation.
    std::string fix_hint_text;
    if (stalled) {
      fix_hint_text =
          "Simulation stalled at cycle " +
          std::to_string(simulation_end_cycle_tracked) + " on vector " +
          std::to_string(stall_vector_index) + " after emitting " +
          std::to_string(total_outputs_received) + " of " +
          std::to_string(total_outputs_expected) +
          " expected outputs. Last valid_out fired at cycle " +
          std::to_string(last_valid_out_cycle_tracked) +
          ". Missing output indices: [" +
          std::to_string(missing_index_start) + ", " +
          std::to_string(missing_index_end) +
          "). See output_gap_histogram and the head/tail samples of "
          "expected/got for raw evidence.";
    } else if (final_status != "pass") {
      fix_hint_text =
          "Simulation completed but values disagreed. max_error=" +
          std::to_string(max_abs_error) + " across " +
          std::to_string(sample_count) +
          " samples. See first_mismatch_* and expected/got for raw evidence.";
    }
    if (axi_weight_memory.applicable() && final_status != "pass") {
      const std::string axi_trace =
          " AXI weight trace: model_status=" + axi_weight_memory.status() +
          ", model_enabled=" + std::string(axi_weight_memory.enabled() ? "true" : "false") +
          ", arvalid_cycles=" + std::to_string(axi_weight_memory.arvalid_cycles()) +
          ", arready_cycles=" + std::to_string(axi_weight_memory.arready_cycles()) +
          ", ar_handshakes=" + std::to_string(axi_weight_memory.ar_handshakes()) +
          ", rvalid_cycles=" + std::to_string(axi_weight_memory.rvalid_cycles()) +
          ", rready_cycles=" + std::to_string(axi_weight_memory.rready_cycles()) +
          ", r_beats=" + std::to_string(axi_weight_memory.r_beats()) +
          ", completed_bursts=" + std::to_string(axi_weight_memory.completed_bursts()) +
          ", out_of_range_reads=" + std::to_string(axi_weight_memory.out_of_range_reads()) + ".";
      if (fix_hint_text.empty()) {
        fix_hint_text = axi_trace.substr(1);
      } else {
        fix_hint_text += axi_trace;
      }
    }

    json results = {
        {"module_id", sidecar.module_id},
        {"status", final_status},
        {"status_class", status_class},
        {"expected", expected_json},
        {"got", got_json},
        {"sample_count", sample_count},
        {"max_error", max_abs_error},
        {"mean_error", mean_error},
        {"timing_pass", stalled ? false : timing_pass},
        {"timing_actual_cycles", timing_actual_cycles_reported},
        {"timing_expected_cycles", timing_expected_cycles},
        {"failure_class", nullptr},
        {"verilator_stderr", fix_hint_text},
        // Factual simulation evidence — Surgeon reasons from these directly.
        {"outputs_expected", total_outputs_expected},
        {"outputs_received", total_outputs_received},
        {"missing_index_start", missing_index_start},
        {"missing_index_end", missing_index_end},
        {"last_valid_out_cycle", last_valid_out_cycle_tracked},
        {"simulation_end_cycle", simulation_end_cycle_tracked},
        {"output_gap_histogram", output_gap_histogram},
        {"first_mismatch_index", first_mismatch_flat_index},
        {"first_mismatch_expected", first_mismatch_expected_v},
        {"first_mismatch_got", first_mismatch_got_v},
        {"first_mismatch_vector_index", first_mismatch_vector_index},
        {"first_mismatch_output_index", first_mismatch_output_index},
        {"first_mismatch_channel_index", first_mismatch_channel_index},
        {"exact_match_count", exact_match_count},
        {"mismatch_count", mismatch_count},
        {"signed_error_sum", signed_error_sum},
        {"positive_error_count", positive_error_count},
        {"negative_error_count", negative_error_count},
        {"first_valid_in_cycle", first_valid_in_cycle},
        {"first_valid_out_cycle", first_valid_out_cycle},
    };

    // Per-vector breakdown: one entry per vector that the loop reached
    // before any stall. Stalled vectors are simply absent from the array
    // (the aggregate `stall_vector_index` and `outputs_received` already
    // pinpoint the stall site).
    json per_vector_json = json::array();
    for (const auto& vacc : per_vector_accums) {
      const double v_mean =
          vacc.sample_count
              ? vacc.sum_abs_error / static_cast<double>(vacc.sample_count)
              : 0.0;
      per_vector_json.push_back({
          {"vector_idx", vacc.vector_idx},
          {"outputs_received", vacc.outputs_received},
          {"exact_match_count", vacc.exact_match_count},
          {"mismatch_count", vacc.mismatch_count},
          {"max_error", vacc.max_error},
          {"mean_error", v_mean},
          {"actual_cycles", vacc.actual_cycles},
          {"first_mismatch_output_index",
           vacc.first_mismatch_output_index < 0
               ? json(nullptr)
               : json(vacc.first_mismatch_output_index)},
      });
    }
    results["per_vector"] = per_vector_json;
    if (axi_weight_memory.applicable()) {
      const json trace = axi_weight_memory.traceJson();
      for (const auto& item : trace.items()) {
        results[item.key()] = item.value();
      }
    }
    if (!fix_hint_text.empty()) {
      results["fix_hint"] = fix_hint_text;
    }

    writeResults(sidecar.results_path, results);
    return 0;
  } catch (const std::exception& e) {
    std::cerr << "static_verilator_tb error: " << e.what() << "\n";
    writeFallbackError(sidecar_path, e);
    return 1;
  }
}
