// Static Verilator testbench for nn2rtl.
//
// Handwritten infrastructure. Never regenerated by an agent.
//
// Build-time contract:
//   -DVMODEL_HEADER="\"Vconv1x1.h\""   // generated Verilator header for the DUT
//   -DVMODEL_CLASS=Vconv1x1            // generated Verilator class name for the DUT
//
// Run-time contract:
//   argv[1]  path to sidecar JSON produced by Assayer
//
// Canonical DUT port names (enforced at run time against the sidecar):
//   clk, rst_n, valid_in, ready_in, valid_out, data_in, data_out
//
// Handshake semantics implemented by this bench:
//   * valid_in / data_in are driven by the bench.
//   * ready_in is an OUTPUT of the DUT (backpressure upstream). The bench waits
//     for ready_in == 1 before asserting valid_in. A DUT that does not need
//     backpressure must tie ready_in high after reset.
//   * valid_out is an OUTPUT of the DUT. The bench samples data_out only on
//     cycles where valid_out == 1, tolerating bubbles between outputs.
//
// The testbench writes its structured results to the `results_path` field in
// the sidecar. `run_verilator` reads that file and returns a full VerifResult.

#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <exception>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <vector>

#include "third_party/json.hpp"
#include "verilated.h"

// Verilator's linker looks for this stub; it is the simulation timestamp used
// by waveform dumps. The bench does not emit waves, so a constant is fine.
double sc_time_stamp() {
  return 0;
}

#ifndef VMODEL_HEADER
#  error "VMODEL_HEADER must be defined at build time (e.g. -DVMODEL_HEADER=\"\\\"Vfoo.h\\\"\")."
#endif
#ifndef VMODEL_CLASS
#  error "VMODEL_CLASS must be defined at build time (e.g. -DVMODEL_CLASS=Vfoo)."
#endif

#include VMODEL_HEADER

using json = nlohmann::json;

namespace {

constexpr int64_t kNumericalTolerance = 3;  // README: pass threshold max_error <= 3.

struct Sidecar {
  std::string module_name;
  std::string module_id;
  std::string clock_signal;
  std::string reset_signal;
  std::string valid_in_signal;
  std::string valid_out_signal;
  std::string ready_in_signal;
  std::string data_in_signal;
  std::string data_out_signal;
  int input_width_bits = 0;
  int output_width_bits = 0;
  int pipeline_latency_cycles = 0;
  double clock_period_ns = 0.0;
  std::string golden_inputs_path;
  std::string golden_outputs_path;
  std::string results_path;
  std::string testbench_template_path;
};

Sidecar loadSidecar(const std::string& path) {
  std::ifstream in(path);
  if (!in.is_open()) {
    throw std::runtime_error("Could not open sidecar '" + path + "'.");
  }

  json j;
  in >> j;

  Sidecar s;
  s.module_name             = j.at("module_name").get<std::string>();
  s.module_id               = j.at("module_id").get<std::string>();
  s.clock_signal            = j.at("clock_signal").get<std::string>();
  s.reset_signal            = j.at("reset_signal").get<std::string>();
  s.valid_in_signal         = j.at("valid_in_signal").get<std::string>();
  s.valid_out_signal        = j.at("valid_out_signal").get<std::string>();
  s.ready_in_signal         = j.at("ready_in_signal").get<std::string>();
  s.data_in_signal          = j.at("data_in_signal").get<std::string>();
  s.data_out_signal         = j.at("data_out_signal").get<std::string>();
  s.input_width_bits        = j.at("input_width_bits").get<int>();
  s.output_width_bits       = j.at("output_width_bits").get<int>();
  s.pipeline_latency_cycles = j.at("pipeline_latency_cycles").get<int>();
  s.clock_period_ns         = j.at("clock_period_ns").get<double>();
  s.golden_inputs_path      = j.at("golden_inputs_path").get<std::string>();
  s.golden_outputs_path     = j.at("golden_outputs_path").get<std::string>();
  s.results_path            = j.at("results_path").get<std::string>();
  s.testbench_template_path = j.at("testbench_template_path").get<std::string>();
  return s;
}

// Binary vector file format (.goldin / .goldout):
//   [ 0..4)  magic        : ASCII "NN2V"
//   [ 4..8)  version      : uint32 LE (= 1)
//   [ 8..12) num_vectors  : uint32 LE
//   [12..16) samples_per_vector : uint32 LE
//   [16..)   data         : num_vectors * samples_per_vector * int32 LE
// Documented in scripts/golden_impl.py (write_golden_vector_file).
std::vector<std::vector<int64_t>> loadVectorFile(const std::string& path) {
  std::ifstream in(path, std::ios::binary);
  if (!in.is_open()) {
    throw std::runtime_error("Could not open vector file '" + path + "'.");
  }

  char magic[4];
  uint32_t version = 0;
  uint32_t num_vectors = 0;
  uint32_t samples_per_vector = 0;
  in.read(magic, sizeof(magic));
  in.read(reinterpret_cast<char*>(&version), sizeof(version));
  in.read(reinterpret_cast<char*>(&num_vectors), sizeof(num_vectors));
  in.read(reinterpret_cast<char*>(&samples_per_vector), sizeof(samples_per_vector));
  if (!in) {
    throw std::runtime_error("Vector file '" + path + "' header is truncated.");
  }
  if (magic[0] != 'N' || magic[1] != 'N' || magic[2] != '2' || magic[3] != 'V') {
    throw std::runtime_error("Vector file '" + path + "' has wrong magic; expected 'NN2V'.");
  }
  if (version != 1) {
    throw std::runtime_error("Vector file '" + path + "' has unsupported version.");
  }

  std::vector<std::vector<int64_t>> vectors;
  vectors.reserve(num_vectors);
  std::vector<int32_t> row_buffer(samples_per_vector);
  for (uint32_t v = 0; v < num_vectors; ++v) {
    in.read(reinterpret_cast<char*>(row_buffer.data()),
            static_cast<std::streamsize>(samples_per_vector * sizeof(int32_t)));
    if (!in) {
      throw std::runtime_error("Vector file '" + path + "' data is truncated.");
    }
    std::vector<int64_t> parsed(samples_per_vector);
    for (uint32_t i = 0; i < samples_per_vector; ++i) {
      parsed[i] = static_cast<int64_t>(row_buffer[i]);
    }
    vectors.push_back(std::move(parsed));
  }
  return vectors;
}

void requireCanonicalSignals(const Sidecar& s) {
  const auto check = [](const std::string& field,
                        const std::string& value,
                        const std::string& expected) {
    if (value != expected) {
      throw std::runtime_error(
          "Sidecar field '" + field + "' must be '" + expected +
          "' (canonical signal name); got '" + value + "'.");
    }
  };
  check("clock_signal",     s.clock_signal,     "clk");
  check("reset_signal",     s.reset_signal,     "rst_n");
  check("valid_in_signal",  s.valid_in_signal,  "valid_in");
  check("valid_out_signal", s.valid_out_signal, "valid_out");
  check("ready_in_signal",  s.ready_in_signal,  "ready_in");
  check("data_in_signal",   s.data_in_signal,   "data_in");
  check("data_out_signal",  s.data_out_signal,  "data_out");
}

template <typename Dut>
void tickClock(Dut* dut, int64_t& cycle_counter) {
  dut->clk = 0;
  dut->eval();
  dut->clk = 1;
  dut->eval();
  ++cycle_counter;
}

template <typename Dut>
void applyReset(Dut* dut, int64_t& cycle_counter, int cycles = 5) {
  dut->rst_n    = 0;
  dut->valid_in = 0;
  dut->data_in  = 0;
  for (int i = 0; i < cycles; ++i) {
    tickClock(dut, cycle_counter);
  }
  dut->rst_n = 1;
}

void writeResults(const std::string& results_path, const json& results) {
  std::filesystem::path p = results_path;
  if (!p.parent_path().empty()) {
    std::filesystem::create_directories(p.parent_path());
  }
  std::ofstream out(p);
  if (!out.is_open()) {
    throw std::runtime_error("Could not open results file '" + results_path + "' for writing.");
  }
  out << results.dump(2) << std::endl;
}

void writeFallbackError(const std::string& sidecar_path, const std::exception& e) {
  try {
    std::ifstream in(sidecar_path);
    if (!in.is_open()) {
      return;
    }
    json j;
    in >> j;
    if (!j.contains("results_path")) {
      return;
    }
    const std::string results_path = j.at("results_path").get<std::string>();
    const std::string module_id    = j.value("module_id", std::string(""));

    json error_result = {
        {"module_id", module_id},
        {"status", "fail"},
        {"timing_pass", false},
        {"timing_actual_cycles", -1},
        {"timing_expected_cycles", -1},
        {"expected", json::array()},
        {"got", json::array()},
        {"max_error", -1},
        {"mean_error", -1.0},
        {"failure_class", nullptr},
        {"fix_hint", std::string("static testbench failed before simulation: ") + e.what()},
        {"verilator_stderr", std::string(e.what())},
    };
    writeResults(results_path, error_result);
  } catch (...) {
    // Best-effort only — we already have a stderr trace.
  }
}

}  // namespace

int main(int argc, char** argv) {
  Verilated::commandArgs(argc, argv);

  if (argc < 2) {
    std::cerr << "Usage: " << argv[0] << " <sidecar.json>\n";
    return 2;
  }

  const std::string sidecar_path = argv[1];

  try {
    const Sidecar sidecar = loadSidecar(sidecar_path);
    requireCanonicalSignals(sidecar);

    const auto golden_inputs  = loadVectorFile(sidecar.golden_inputs_path);
    const auto golden_outputs = loadVectorFile(sidecar.golden_outputs_path);

    if (golden_inputs.size() != golden_outputs.size()) {
      throw std::runtime_error(
          "Golden inputs and outputs differ in vector count (" +
          std::to_string(golden_inputs.size()) + " vs " +
          std::to_string(golden_outputs.size()) + ").");
    }

    auto dut = std::make_unique<VMODEL_CLASS>();
    int64_t cycle_counter = 0;
    applyReset(dut.get(), cycle_counter);

    std::vector<int64_t> expected_flat;
    std::vector<int64_t> actual_flat;
    int64_t max_abs_error = 0;
    double  sum_abs_error = 0.0;
    size_t  sample_count  = 0;

    int64_t first_valid_in_cycle  = -1;
    int64_t first_valid_out_cycle = -1;
    bool    timing_observed       = false;

    // Per-vector timing check: every vector must honour the sidecar's declared
    // latency, not just the first one. A single boolean collapses the per-vector
    // results.
    bool    all_vectors_timing_ok = true;
    int64_t worst_vector_actual_cycles = -1;

    // Sign-extend DUT outputs according to output_width_bits so negative int8s
    // are not reported as their unsigned 8-bit encoding.
    const int output_width_bits = sidecar.output_width_bits;
    const uint64_t output_mask  = (output_width_bits >= 64)
                                      ? ~static_cast<uint64_t>(0)
                                      : ((static_cast<uint64_t>(1) << output_width_bits) - 1);
    const uint64_t sign_bit     = (output_width_bits > 0 && output_width_bits < 64)
                                      ? (static_cast<uint64_t>(1) << (output_width_bits - 1))
                                      : 0;
    const auto signExtendOutput = [&](uint64_t raw) -> int64_t {
      const uint64_t masked = raw & output_mask;
      if (sign_bit && (masked & sign_bit)) {
        return static_cast<int64_t>(masked | ~output_mask);
      }
      return static_cast<int64_t>(masked);
    };

    const int64_t hang_budget = sidecar.pipeline_latency_cycles * 4 + 16;

    // Unified interleaved drive/sample loop. For each test vector we drive inputs
    // whenever the DUT is ready and we sample outputs whenever valid_out is high,
    // both in the same tick. This handles short-latency DUTs (output arrives
    // before all inputs are sent) and bubbly DUTs (gaps between outputs) without
    // smuggling state across vectors.
    for (size_t v = 0; v < golden_inputs.size(); ++v) {
      const auto& inputs  = golden_inputs[v];
      const auto& outputs = golden_outputs[v];

      size_t  input_idx    = 0;
      size_t  output_idx   = 0;
      int64_t idle_cycles  = 0;
      int64_t vector_first_valid_in  = -1;
      int64_t vector_first_valid_out = -1;

      while (output_idx < outputs.size()) {
        if (idle_cycles > hang_budget) {
          throw std::runtime_error(
              "Stalled on vector " + std::to_string(v) +
              " (output " + std::to_string(output_idx) + " of " +
              std::to_string(outputs.size()) +
              ") for " + std::to_string(idle_cycles) + " cycles without valid_out.");
        }

        // Sample whatever the DUT is asserting this cycle before driving new inputs.
        if (dut->valid_out) {
          if (!timing_observed) {
            first_valid_out_cycle = cycle_counter;
            timing_observed = true;
          }
          if (vector_first_valid_out < 0) {
            vector_first_valid_out = cycle_counter;
          }

          const int64_t got      = signExtendOutput(static_cast<uint64_t>(dut->data_out));
          const int64_t expected = outputs[output_idx];
          expected_flat.push_back(expected);
          actual_flat.push_back(got);

          const int64_t diff = got >= expected ? got - expected : expected - got;
          if (diff > max_abs_error) {
            max_abs_error = diff;
          }
          sum_abs_error += static_cast<double>(diff);
          ++sample_count;

          ++output_idx;
          idle_cycles = 0;
        } else {
          ++idle_cycles;
        }

        // Drive the next input on this cycle if we still have inputs to send and
        // the DUT is ready to accept them. Otherwise deassert valid_in.
        if (input_idx < inputs.size() && dut->ready_in) {
          if (first_valid_in_cycle < 0) {
            first_valid_in_cycle = cycle_counter;
          }
          if (vector_first_valid_in < 0) {
            vector_first_valid_in = cycle_counter;
          }
          dut->data_in  = static_cast<uint64_t>(inputs[input_idx]);
          dut->valid_in = 1;
          ++input_idx;
        } else {
          dut->valid_in = 0;
        }

        // Always tick — including the cycle that sampled the vector's final
        // output. Skipping this tick leaves valid_out/data_out live into the
        // next vector, which would then mis-sample the previous final output
        // as its own first output.
        tickClock(dut.get(), cycle_counter);
      }

      dut->valid_in = 0;

      if (vector_first_valid_in >= 0 && vector_first_valid_out >= 0) {
        const int64_t vector_actual = vector_first_valid_out - vector_first_valid_in;
        if (vector_actual != sidecar.pipeline_latency_cycles) {
          all_vectors_timing_ok = false;
        }
        if (vector_actual > worst_vector_actual_cycles) {
          worst_vector_actual_cycles = vector_actual;
        }
      } else {
        all_vectors_timing_ok = false;
      }
    }

    dut->final();

    const double  mean_error             = sample_count ? sum_abs_error / static_cast<double>(sample_count) : 0.0;
    const int64_t timing_expected_cycles = sidecar.pipeline_latency_cycles;
    const int64_t timing_actual_cycles   =
        (first_valid_in_cycle >= 0 && first_valid_out_cycle >= 0)
            ? first_valid_out_cycle - first_valid_in_cycle
            : -1;
    const bool timing_pass =
        timing_observed &&
        timing_actual_cycles == timing_expected_cycles &&
        all_vectors_timing_ok;
    const int64_t timing_actual_cycles_reported =
        (worst_vector_actual_cycles >= 0 && !all_vectors_timing_ok)
            ? worst_vector_actual_cycles
            : timing_actual_cycles;
    const bool numerical_pass = max_abs_error <= kNumericalTolerance;
    const std::string status  = (numerical_pass && timing_pass) ? "pass" : "fail";

    json results = {
        {"module_id", sidecar.module_id},
        {"status", status},
        {"expected", expected_flat},
        {"got", actual_flat},
        {"max_error", max_abs_error},
        {"mean_error", mean_error},
        {"timing_pass", timing_pass},
        {"timing_actual_cycles", timing_actual_cycles_reported},
        {"timing_expected_cycles", timing_expected_cycles},
        {"failure_class", nullptr},
        {"verilator_stderr", std::string("")},
    };

    writeResults(sidecar.results_path, results);
    return 0;
  } catch (const std::exception& e) {
    std::cerr << "static_verilator_tb error: " << e.what() << "\n";
    writeFallbackError(sidecar_path, e);
    return 1;
  }
}
