#!/usr/bin/env python3
"""Convert ResNet-8 per-TENSOR conv requant RTL to PER-OUTPUT-CHANNEL, matching
the golden's exact per-OC requant contract (compute_scale_approx per OC).

WHY
---
output/resnet8/layer_ir.json carries per-OC quantization (scale_factor_per_oc +
weight_scale_per_oc) for every groups==1 non-1x1 conv (NN2RTL_STEM_PER_CHANNEL=1).
The on-disk weight .hex are ALREADY per-OC quantized (each OC row reaches +-127).
The goldens are generated by golden_impl.requantize_tensor_with_scale_per_oc,
which applies, per output channel:

    mult, shift = compute_scale_approx(scale_factor_per_oc[oc])   # variable shift
    out[oc] = clamp( (acc_oc * mult + (1<<(shift-1))) >>> shift , -128, 127)

The generator emitted that per-OC requant for the stem (node_conv2d), conv_4 and
conv_8, but left node_conv2d_{1,2,5,7} on a single per-TENSOR SCALE_MULT/SHIFT
(stale scale_factor), so those layers saturate and the e2e logits are wrong.
Additionally node_conv2d_{1,5} pair the ic-INNERMOST window byte directly with
the ic-OUTERMOST weight byte (naive win_s1[k_i*8] MAC) -- a second bug; the
stem/conv_8 decompose k_i (ic-outer) and index window_flat (ic-inner).

This script (idempotent; writes .pre<tag> backups) rewrites the four convs to:
  * per-OC scale_mult_arr[OC] + scale_shift_arr[OC] (compute_scale_approx, the
    EXACT golden constants -> bit-exact by construction, variable shift),
  * per-OC requant (single positive round bias + arithmetic >>> = floor, the
    golden's rounding), and
  * decomposed (ic-outer) MAC indexing for conv_1 / conv_5.

The 1x1 stride-2 projection convs node_conv2d_{3,6} are per-TENSOR BY DESIGN
(NN2RTL_PW_PER_CHANNEL=0) and are NOT touched.

Verification of the contract (does not modify anything):
  python scripts/_verify_perOC_contract.py node_conv2d_1   # -> 0 mismatches
"""
from __future__ import annotations
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
from scripts.golden_impl import compute_scale_approx  # noqa: E402

RTL_DIR = REPO / "output" / "resnet8" / "rtl"
IR_PATH = REPO / "output" / "resnet8" / "layer_ir.json"
BACKUP_TAG = ".pretensor_perOC"

TARGETS = ["node_conv2d_1", "node_conv2d_2", "node_conv2d_4", "node_conv2d_5", "node_conv2d_7"]
# convs whose MAC pairs ic-inner window with ic-outer weight at the same k_i:
# node_conv2d_4 is NOT here -- it already decomposes k via the tap_at() function
# (ic_idx = k/(KH*KW), window_flat ic-inner), so its MAC is already correct. Its
# ONLY bug is the requant: it used scale_mult_rom = round(s*2^23) with a UNIFORM
# SCALE_SHIFT=23, not the variable-shift compute_scale_approx golden contract.
MAC_NAIVE = {"node_conv2d_1", "node_conv2d_5"}


def per_oc_pairs(mid: str):
    ir = json.loads(IR_PATH.read_text())
    layer = next(l for l in ir["layers"]
                 if l.get("module_id") == mid and l.get("op_type") == "conv2d")
    sf = layer["scale_factor_per_oc"]
    pairs = [compute_scale_approx(float(s)) for s in sf]
    oc = layer["output_shape"][1]
    if len(pairs) != oc:
        raise SystemExit(f"{mid}: {len(pairs)} scales vs OC={oc}")
    return pairs, oc


def emit_arrays(pairs, indent="        "):
    """Verilog initial-block lines for scale_mult_arr + scale_shift_arr."""
    lines = []
    for i, (m, sh) in enumerate(pairs):
        lines.append(f"{indent}scale_mult_arr[{i}]  = 16'sd{m};")
    for i, (m, sh) in enumerate(pairs):
        lines.append(f"{indent}scale_shift_arr[{i}] = 6'd{sh};")
    return "\n".join(lines)


def backup(path: Path):
    bak = path.with_suffix(path.suffix + BACKUP_TAG)
    if not bak.exists():
        bak.write_bytes(path.read_bytes())
        print(f"  backup -> {bak.name}")


# ---------------------------------------------------------------------------
# conv_1 / conv_5 : fully-parallel datapath (identical shape, both bugs).
# ---------------------------------------------------------------------------
def patch_parallel(mid: str):
    path = RTL_DIR / f"{mid}.v"
    txt = path.read_text()
    pairs, oc = per_oc_pairs(mid)

    if "scale_mult_arr" in txt and "scale_shift_arr" in txt:
        print(f"{mid}: already per-OC (scale_*_arr present); skip")
        return False
    backup(path)

    # 1) Replace the single-scale localparams with per-OC ROM declarations.
    #    Original block (conv_1 uses SCALE_MULT=...; SCALE_SHIFT=...; SCALE_MULT_CONST;
    #    conv_5 same). We drop SCALE_MULT/SCALE_MULT_CONST and the uniform
    #    SCALE_SHIFT, and key the round-half off the per-OC shift at use-site.
    # Keep SCALE_CONST_W and SCALED_W; introduce SCALE_SHIFT_MAX for widths.
    txt = re.sub(r"^\s*localparam integer SCALE_MULT\s*=\s*\d+;\s*\n", "", txt, flags=re.M)
    txt = re.sub(r"^\s*localparam integer SCALE_SHIFT\s*=\s*\d+;\s*\n",
                 "    localparam integer SCALE_SHIFT_MAX = 23;\n", txt, flags=re.M)
    txt = re.sub(r"^\s*localparam signed \[SCALE_CONST_W-1:0\] SCALE_MULT_CONST\s*=\s*SCALE_MULT;\s*\n",
                 "", txt, flags=re.M)
    # Drop the uniform round-half localparams (we compute per-OC at use-site).
    txt = re.sub(r"\s*localparam signed \[SCALED_W-1:0\] SCALE_ROUND_HALF\s*=\s*"
                 r"\{\{\(SCALED_W-1\)\{1'b0\}\}, 1'b1\} <<< \(SCALE_SHIFT - 1\);", "", txt)
    txt = re.sub(r"\s*localparam signed \[SCALED_W-1:0\] SCALE_ROUND_HALF_M1\s*=\s*"
                 r"SCALE_ROUND_HALF - \{\{\(SCALED_W-1\)\{1'b0\}\}, 1'b1\};", "", txt)

    # 2) Insert per-OC ROM declaration + init right before the weights ROM.
    arrays = emit_arrays(pairs)
    rom_decl = (
        "    // Per-OC requant: compute_scale_approx(scale_factor_per_oc[oc]).\n"
        "    // Variable per-OC shift = the exact golden contract.\n"
        "    reg signed [SCALE_CONST_W-1:0] scale_mult_arr  [0:OC-1];\n"
        "    reg        [5:0]               scale_shift_arr [0:OC-1];\n"
        "    initial begin\n" + arrays + "\n    end\n\n"
    )
    anchor = '    (* rom_style = "block", ram_style = "block" *) reg signed [7:0]  weights'
    if anchor not in txt:
        raise SystemExit(f"{mid}: weights ROM anchor not found")
    txt = txt.replace(anchor, rom_decl + anchor, 1)

    # 3) Fix MAC indexing (naive -> decomposed) for conv_1 / conv_5.
    if mid in MAC_NAIVE:
        # Add scratch index integers next to the existing loop-index decls.
        txt = txt.replace(
            "    integer oc_i, k_i, oc_b, oc_s, oc_r, pi;",
            "    integer oc_i, k_i, oc_b, oc_s, oc_r, pi;\n"
            "    integer w_ic, w_kh, w_kw, win_byte_idx;",
            1,
        )
        naive = ("            for (k_i = 0; k_i < K_TOTAL; k_i = k_i + 1)\n"
                 "                tmp_acc = tmp_acc + $signed(win_s1[k_i*8 +: 8])\n"
                 "                                  * $signed(weights[oc_i*K_TOTAL + k_i]);")
        decomp = ("            for (k_i = 0; k_i < K_TOTAL; k_i = k_i + 1) begin\n"
                  "                // window_flat is ic-INNERMOST; weights are ic-OUTERMOST.\n"
                  "                w_ic = k_i / (KH*KW);\n"
                  "                w_kh = (k_i % (KH*KW)) / KW;\n"
                  "                w_kw = k_i % KW;\n"
                  "                win_byte_idx = w_kh*KW*IC + w_kw*IC + w_ic;\n"
                  "                tmp_acc = tmp_acc + $signed(win_s1[win_byte_idx*8 +: 8])\n"
                  "                                  * $signed(weights[oc_i*K_TOTAL + k_i]);\n"
                  "            end")
        if naive in txt:
            txt = txt.replace(naive, decomp, 1)
        else:
            # conv_1 has the loop on one line.
            naive1 = ("            for (k_i=0; k_i<K_TOTAL; k_i=k_i+1) "
                      "tmp_acc = tmp_acc + $signed(win_s1[k_i*8 +: 8]) * "
                      "$signed(weights[oc_i*K_TOTAL + k_i]);")
            decomp1 = ("            for (k_i=0; k_i<K_TOTAL; k_i=k_i+1) begin\n"
                       "                w_ic = k_i / (KH*KW); w_kh = (k_i % (KH*KW)) / KW; w_kw = k_i % KW;\n"
                       "                win_byte_idx = w_kh*KW*IC + w_kw*IC + w_ic;\n"
                       "                tmp_acc = tmp_acc + $signed(win_s1[win_byte_idx*8 +: 8]) * "
                       "$signed(weights[oc_i*K_TOTAL + k_i]);\n"
                       "            end")
            if naive1 not in txt:
                raise SystemExit(f"{mid}: naive MAC loop not found")
            txt = txt.replace(naive1, decomp1, 1)

    # 4) SCALE stage: multiply by per-OC mult (was SCALE_MULT_CONST).
    txt = txt.replace("$signed(SCALE_MULT_CONST)", "$signed(scale_mult_arr[oc_s])")

    # 5) ROUND/SAT stage: per-OC shift + single positive bias (golden floor).
    #    conv_1 (one-liner) and conv_5 (multi-line) both have the same expr
    #    using SCALE_ROUND_HALF / SCALE_ROUND_HALF_M1 + SCALE_SHIFT.
    round_multi = (
        "            v_tmp = (scaled_s4[oc_r] +\n"
        "                     (scaled_s4[oc_r][SCALED_W-1] ? SCALE_ROUND_HALF_M1\n"
        "                                                  : SCALE_ROUND_HALF)\n"
        "                    ) >>> SCALE_SHIFT;")
    round_repl = (
        "            v_tmp = (scaled_s4[oc_r] +\n"
        "                     ($signed({{(SCALED_W-1){1'b0}}, 1'b1}) <<< (scale_shift_arr[oc_r] - 1))\n"
        "                    ) >>> scale_shift_arr[oc_r];")
    if round_multi in txt:
        txt = txt.replace(round_multi, round_repl, 1)
    else:
        round_one = ("            v_tmp = (scaled_s4[oc_r] + "
                     "(scaled_s4[oc_r][SCALED_W-1] ? SCALE_ROUND_HALF_M1 : SCALE_ROUND_HALF)) "
                     ">>> SCALE_SHIFT;")
        round_one_repl = ("            v_tmp = (scaled_s4[oc_r] + "
                          "($signed({{(SCALED_W-1){1'b0}}, 1'b1}) <<< (scale_shift_arr[oc_r] - 1))) "
                          ">>> scale_shift_arr[oc_r];")
        if round_one not in txt:
            raise SystemExit(f"{mid}: round/sat expr not found")
        txt = txt.replace(round_one, round_one_repl, 1)

    path.write_text(txt)
    print(f"{mid}: patched parallel datapath to per-OC "
          f"(MAC {'fixed' if mid in MAC_NAIVE else 'ok'})")
    return True


# ---------------------------------------------------------------------------
# conv_2 : elaborate 7-stage pipeline (correct MAC, single SCALE_MULT_S).
# ---------------------------------------------------------------------------
def patch_conv2(mid="node_conv2d_2"):
    path = RTL_DIR / f"{mid}.v"
    txt = path.read_text()
    pairs, oc = per_oc_pairs(mid)
    if "scale_mult_arr" in txt:
        print(f"{mid}: already per-OC; skip")
        return False
    backup(path)

    # Replace the 4 scale localparams with per-OC ROMs.
    old_scale = (
        "    localparam signed [15:0] SCALE_MULT_S    = 16'sd17910;\n"
        "    localparam integer       SCALE_SHIFT     = 14;\n"
        "    localparam signed [48:0] SCALE_HALF_S    = 49'sd8192;   // 1 << (SCALE_SHIFT-1)\n"
        "    localparam signed [48:0] SCALE_HALF_M1_S = 49'sd8191;")
    if old_scale not in txt:
        raise SystemExit(f"{mid}: scale localparam block not found")
    arrays = emit_arrays(pairs)
    new_scale = (
        "    // Per-OC requant: compute_scale_approx(scale_factor_per_oc[oc]).\n"
        "    reg signed [15:0] scale_mult_arr  [0:OC-1];\n"
        "    reg        [5:0]  scale_shift_arr [0:OC-1];\n"
        "    initial begin\n" + arrays + "\n    end")
    txt = txt.replace(old_scale, new_scale, 1)

    # Stage 6: x per-OC mult.
    txt = txt.replace(
        "            scaled_reg[oc_i] <= biased_reg[oc_i] * SCALE_MULT_S;",
        "            scaled_reg[oc_i] <= biased_reg[oc_i] * scale_mult_arr[oc_i];",
        1,
    )

    # Stage 7: per-OC shift + single positive bias (golden floor).
    old_round = (
        "        for (oc_i = 0; oc_i < OC; oc_i = oc_i + 1) begin\n"
        "            if (scaled_reg[oc_i][48])\n"
        "                rounded_reg[oc_i] <= (scaled_reg[oc_i] + SCALE_HALF_M1_S) >>> SCALE_SHIFT;\n"
        "            else\n"
        "                rounded_reg[oc_i] <= (scaled_reg[oc_i] + SCALE_HALF_S) >>> SCALE_SHIFT;\n"
        "        end")
    if old_round not in txt:
        raise SystemExit(f"{mid}: round stage not found")
    new_round = (
        "        for (oc_i = 0; oc_i < OC; oc_i = oc_i + 1) begin\n"
        "            rounded_reg[oc_i] <= (scaled_reg[oc_i] +\n"
        "                (49'sd1 <<< (scale_shift_arr[oc_i] - 1))) >>> scale_shift_arr[oc_i];\n"
        "        end")
    txt = txt.replace(old_round, new_round, 1)

    path.write_text(txt)
    print(f"{mid}: patched 7-stage pipeline to per-OC")
    return True


# ---------------------------------------------------------------------------
# conv_7 : instantiates the SHARED conv_datapath (single scale param). We must
# NOT modify the shared library, so inline a per-OC FSM datapath modeled on
# conv_4 (the proven 4x4-stride-2 per-OC inline), adapted to conv_7 geometry.
# ---------------------------------------------------------------------------
def patch_conv7(mid="node_conv2d_7"):
    path = RTL_DIR / f"{mid}.v"
    txt = path.read_text()
    if "scale_mult_rom" in txt or "conv_datapath" not in txt:
        print(f"{mid}: already inlined per-OC (or no conv_datapath); skip")
        return False
    pairs, oc = per_oc_pairs(mid)
    backup(path)

    rom_lines = "\n".join(f"        scale_mult_rom[{i}]  = 16'sd{m};" for i, (m, sh) in enumerate(pairs))
    shf_lines = "\n".join(f"        scale_shift_rom[{i}] = 6'd{sh};" for i, (m, sh) in enumerate(pairs))

    new = f"""// node_conv2d_7 -- 4x4 stride-2 pad-1 conv (IC=32, OC=64, IH=IW=16, OH=OW=8).
// PER-OC requant (resnet8 is per-OC quantized). The shared conv_datapath
// library only supports a single scalar SCALE_MULT/SCALE_SHIFT, so this top
// inlines the MAC/BIAS/SCALE/OUTPUT FSM (mirroring node_conv2d_4) with per-OC
// scale_mult_rom[oc] / scale_shift_rom[oc] = compute_scale_approx(
//   scale_factor_per_oc[oc]) -- the exact golden requant constants.
// FSM cadence is identical to the prior conv_datapath instance: MP*K_TOTAL+6
// cycles per OC-group pass, OC_PASSES passes per output pixel, so the
// pipeline_latency_cycles contract (32902) is preserved.

module node_conv2d_7 (
    input  wire                       clk,
    input  wire                       rst_n,
    input  wire                       valid_in,
    output wire                       ready_in,
    input  wire [255:0]               data_in,
    output wire                       valid_out,
    output wire [511:0]               data_out
);
    localparam integer IC          = 32;
    localparam integer OC          = 64;
    localparam integer IH          = 16;
    localparam integer IW          = 16;
    localparam integer OH          = 8;
    localparam integer OW          = 8;
    localparam integer KH          = 4;
    localparam integer KW          = 4;
    localparam integer SH          = 2;
    localparam integer SW          = 2;
    localparam integer PH          = 1;
    localparam integer PW          = 1;
    localparam integer K_TOTAL     = IC * KH * KW; // 512
    localparam integer MP          = 4;
    localparam integer OC_PASSES   = OC / MP;       // 16
    localparam integer NUM_WEIGHTS = OC * K_TOTAL;  // 32768

    localparam integer SCALE_SHIFT_MAX = 23;
    localparam integer PROD_W       = 16;
    localparam integer ACC_W        = PROD_W + $clog2(K_TOTAL);                // 25
    localparam integer BIAS_W       = 32;
    localparam integer BIASED_W     = ((ACC_W > BIAS_W) ? ACC_W : BIAS_W) + 1; // 33
    localparam integer SCALE_MULT_W = 16;
    localparam integer SCALED_W     = BIASED_W + SCALE_MULT_W;                 // 49

    localparam integer WEIGHT_ADDR_W   = $clog2(NUM_WEIGHTS);
    localparam integer K_COUNTER_W     = $clog2(K_TOTAL);
    localparam integer LANE_COUNTER_W  = $clog2(MP);
    localparam integer OC_GROUP_W      = $clog2(OC_PASSES);
    localparam integer OC_INDEX_W      = $clog2(OC + MP);

    // ---- Per-OC requant ROMs: compute_scale_approx(scale_factor_per_oc[oc]) ----
    reg signed [SCALE_MULT_W-1:0] scale_mult_rom  [0:OC-1];
    reg        [5:0]              scale_shift_rom [0:OC-1];
    initial begin
{rom_lines}
{shf_lines}
    end

    reg started, start_pulse, pending_rearm;
    wire sched_out_frame_done;
    wire                              sched_needs_real_input;
    wire                              sched_ready_in;
    wire                              sched_output_fires;
    wire                              sched_advance;
    wire [$clog2(IH + PH + 1)-1:0]    sched_in_row;
    wire [$clog2(IW + PW + 1)-1:0]    sched_in_col;
    wire [$clog2(OH * OW + 1)-1:0]    sched_outputs_emitted;
    wire [KH*KW*IC*8-1:0]             window_flat;
    wire                              mac_busy_w;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            started       <= 1'b0;
            start_pulse   <= 1'b0;
            pending_rearm <= 1'b0;
        end else begin
            start_pulse <= 1'b0;
            if (sched_out_frame_done) begin
                pending_rearm <= 1'b1;
            end
            if (!started) begin
                started     <= 1'b1;
                start_pulse <= 1'b1;
            end else if (pending_rearm && !mac_busy_w) begin
                started       <= 1'b0;
                pending_rearm <= 1'b0;
            end
        end
    end

    wire stall_in = mac_busy_w;

    coord_scheduler #(
        .IH(IH), .IW(IW), .OH(OH), .OW(OW),
        .KH(KH), .KW(KW), .SH(SH), .SW(SW),
        .PH(PH), .PW(PW)
    ) scheduler (
        .clk(clk), .rst_n(rst_n),
        .start(start_pulse),
        .stall_in(stall_in),
        .valid_in(valid_in),
        .ready_in(sched_ready_in),
        .needs_real_input(sched_needs_real_input),
        .in_row(sched_in_row),
        .in_col(sched_in_col),
        .output_fires(sched_output_fires),
        .advance(sched_advance),
        .in_frame_done(),
        .out_frame_done(sched_out_frame_done),
        .outputs_emitted(sched_outputs_emitted)
    );

    line_buf_window #(
        .IC(IC), .IW(IW), .IH(IH),
        .KH(KH), .KW(KW), .PW(PW), .PH(PH)
    ) lbw (
        .clk(clk), .rst_n(rst_n),
        .frame_start(start_pulse),
        .sched_in_row(sched_in_row),
        .sched_in_col(sched_in_col),
        .sched_needs_real_input(sched_needs_real_input),
        .sched_advance(sched_advance),
        .sched_output_fires(sched_output_fires),
        .valid_in(valid_in),
        .data_in(data_in),
        .window_flat(window_flat)
    );

    localparam ST_IDLE   = 3'd0;
    localparam ST_MAC    = 3'd1;
    localparam ST_BIAS   = 3'd2;
    localparam ST_SCALE  = 3'd3;
    localparam ST_OUTPUT = 3'd4;

    reg [2:0]   state;
    reg         valid_out_r;
    reg [511:0] data_out_r;

    (* rom_style = "block", ram_style = "block" *) reg signed [7:0]  weights_mem [0:NUM_WEIGHTS-1];
    (* rom_style = "block", ram_style = "block" *) reg signed [31:0] biases_mem  [0:OC-1];
    initial begin
        $readmemh("D:/RTL_LLM_CLAUDE/nn2rtl-repo/output/resnet8/weights/node_conv2d_7_weights.hex", weights_mem);
        $readmemh("D:/RTL_LLM_CLAUDE/nn2rtl-repo/output/resnet8/weights/node_conv2d_7_bias.hex",    biases_mem);
    end

    reg signed [ACC_W-1:0]    acc    [0:MP-1];
    reg signed [BIASED_W-1:0] biased [0:MP-1];
    reg signed [SCALED_W-1:0] scaled [0:MP-1];
    reg [5:0]                 shift_lane [0:MP-1];
    reg signed [SCALED_W-1:0] v_tmp;

    reg [K_COUNTER_W-1:0]    k_counter;
    reg [LANE_COUNTER_W-1:0] lane_counter;
    reg [OC_GROUP_W-1:0]     oc_group;

    integer i, lane_i;
    integer bias_oc;
    integer out_oc;

    assign mac_busy_w = (state != ST_IDLE);
    assign valid_out  = valid_out_r;     // [INVARIANT:VALID_OUT_LATENCY]
    assign data_out   = data_out_r;
    assign ready_in   = sched_ready_in;  // [INVARIANT:READY_IN_GATING]

    wire [OC_INDEX_W-1:0]    current_global_oc = oc_group * MP + lane_counter;
    wire [WEIGHT_ADDR_W-1:0] weight_read_addr  = current_global_oc * K_TOTAL + k_counter;

    function [7:0] tap_at;
        input [K_COUNTER_W-1:0] k;
        integer kh_idx, kw_idx, ic_idx, flat_idx;
        begin
            kh_idx   = (k % (KH * KW)) / KW;
            kw_idx   = k % KW;
            ic_idx   = k / (KH * KW);
            flat_idx = kh_idx * KW * IC + kw_idx * IC + ic_idx;
            tap_at   = window_flat[flat_idx*8 +: 8];
        end
    endfunction

    reg signed [7:0] weight_q;
    reg signed [7:0] tap_q;
    always @(posedge clk) begin
        weight_q <= weights_mem[weight_read_addr];
        tap_q    <= $signed(tap_at(k_counter));
    end

    (* use_dsp = "yes" *) reg signed [PROD_W-1:0] mul_q;

    reg                       mac_valid_q1;
    reg [LANE_COUNTER_W-1:0]  mac_lane_q1;
    reg [OC_INDEX_W-1:0]      mac_global_oc_q1;
    reg                       mac_done_issuing;

    reg                       mac_valid_q2;
    reg [LANE_COUNTER_W-1:0]  mac_lane_q2;
    reg [OC_INDEX_W-1:0]      mac_global_oc_q2;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state            <= ST_IDLE;
            valid_out_r      <= 1'b0;
            data_out_r       <= 512'd0;
            k_counter        <= 0;
            lane_counter     <= 0;
            oc_group         <= 0;
            mac_valid_q1     <= 1'b0;
            mac_lane_q1      <= 0;
            mac_global_oc_q1 <= 0;
            mac_valid_q2     <= 1'b0;
            mac_lane_q2      <= 0;
            mac_global_oc_q2 <= 0;
            mac_done_issuing <= 1'b0;
            mul_q            <= 0;
            for (i = 0; i < MP; i = i + 1) begin
                acc[i]        <= 0;
                biased[i]     <= 0;
                scaled[i]     <= 0;
                shift_lane[i] <= 0;
            end
        end else begin
            valid_out_r <= 1'b0;

            mul_q            <= $signed(weight_q) * $signed(tap_q);
            mac_valid_q2     <= mac_valid_q1;
            mac_lane_q2      <= mac_lane_q1;
            mac_global_oc_q2 <= mac_global_oc_q1;

            if (mac_valid_q2 && mac_global_oc_q2 < OC) begin
                acc[mac_lane_q2] <= acc[mac_lane_q2] + $signed(mul_q);
            end

            case (state)
                ST_IDLE: begin
                    if (sched_output_fires) begin
                        state            <= ST_MAC;
                        k_counter        <= 0;
                        lane_counter     <= 0;
                        oc_group         <= 0;
                        mac_valid_q1     <= 1'b0;
                        mac_valid_q2     <= 1'b0;
                        mac_done_issuing <= 1'b0;
                        for (lane_i = 0; lane_i < MP; lane_i = lane_i + 1)
                            acc[lane_i] <= 0;
                    end
                end

                ST_MAC: begin
                    if (mac_done_issuing) begin
                        mac_valid_q1 <= 1'b0;
                        if (!mac_valid_q1 && !mac_valid_q2) begin
                            mac_done_issuing <= 1'b0;
                            state            <= ST_BIAS;
                        end
                    end else begin
                        mac_lane_q1      <= lane_counter;
                        mac_global_oc_q1 <= current_global_oc;
                        mac_valid_q1     <= 1'b1;

                        if (lane_counter == MP - 1) begin
                            lane_counter <= 0;
                            if (k_counter == K_TOTAL - 1) begin
                                mac_done_issuing <= 1'b1;
                            end else begin
                                k_counter <= k_counter + 1'b1;
                            end
                        end else begin
                            lane_counter <= lane_counter + 1'b1;
                        end
                    end
                end

                ST_BIAS: begin
                    for (lane_i = 0; lane_i < MP; lane_i = lane_i + 1) begin
                        bias_oc = oc_group * MP + lane_i;
                        biased[lane_i] <= $signed(acc[lane_i]) + $signed(biases_mem[bias_oc]);
                    end
                    state <= ST_SCALE;
                end

                ST_SCALE: begin
                    for (lane_i = 0; lane_i < MP; lane_i = lane_i + 1) begin
                        scaled[lane_i]     <= $signed(biased[lane_i]) *
                                              $signed(scale_mult_rom[oc_group * MP + lane_i]);
                        shift_lane[lane_i] <= scale_shift_rom[oc_group * MP + lane_i];
                    end
                    state <= ST_OUTPUT;
                end

                ST_OUTPUT: begin
                    for (lane_i = 0; lane_i < MP; lane_i = lane_i + 1) begin
                        out_oc = oc_group * MP + lane_i;
                        // [INVARIANT:ROUNDING] single positive bias + arith >>> = golden floor.
                        v_tmp = (scaled[lane_i] +
                                 ($signed({{{{(SCALED_W-1){{1'b0}}}}, 1'b1}}) <<< (shift_lane[lane_i] - 1))
                                ) >>> shift_lane[lane_i];
                        data_out_r[out_oc*8 +: 8] <=
                            (v_tmp >  127) ?  8'sd127 :
                            (v_tmp < -128) ? -8'sd128 : v_tmp[7:0];
                    end

                    if (oc_group == OC_PASSES - 1) begin
                        valid_out_r <= 1'b1;
                        state       <= ST_IDLE;
                    end else begin
                        oc_group     <= oc_group + 1'b1;
                        k_counter    <= 0;
                        lane_counter <= 0;
                        for (lane_i = 0; lane_i < MP; lane_i = lane_i + 1)
                            acc[lane_i] <= 0;
                        state <= ST_MAC;
                    end
                end

                default: state <= ST_IDLE;
            endcase
        end
    end

endmodule
"""
    path.write_text(new)
    print(f"{mid}: inlined per-OC FSM datapath (replaces shared conv_datapath)")
    return True


# ---------------------------------------------------------------------------
# conv_4 : already an inlined MAC/BIAS/SCALE/OUTPUT FSM with CORRECT decomposed
# MAC (tap_at: ic_idx = k/(KH*KW), window_flat ic-inner). Its ONLY bug is the
# requant approximation: it bakes scale_mult_rom[oc] = round(s*2^23) with a
# UNIFORM SCALE_SHIFT=23 + a sign-dependent round bias, which is NOT the golden
# compute_scale_approx contract (variable per-OC shift). 12/32 OCs disagree at
# the +-1 clip boundary -> e2e logit mismatch. This surgically rewrites conv_4
# to per-OC compute_scale_approx mult + per-OC scale_shift_rom[oc] + a per-OC
# shift_lane + the single positive round bias (golden floor), exactly mirroring
# node_conv2d_7. The MAC, scheduler, line buffer and FSM cadence are untouched,
# so pipeline_latency_cycles / the e2e cycle count are preserved.
# ---------------------------------------------------------------------------
def patch_conv4(mid="node_conv2d_4"):
    path = RTL_DIR / f"{mid}.v"
    txt = path.read_text()
    if "scale_shift_rom" in txt:
        print(f"{mid}: already per-OC (scale_shift_rom present); skip")
        return False
    pairs, oc = per_oc_pairs(mid)
    backup(path)

    # 1) Replace the uniform-shift localparam + the two SCALE_ROUND_HALF consts.
    txt = re.sub(
        r"\s*// Uniform shift; per-OC MULT chosen via round\(s \* 2\^SCALE_SHIFT\)\.\n"
        r"\s*localparam integer SCALE_SHIFT\s*=\s*23;\n",
        "\n    localparam integer SCALE_SHIFT_MAX = 23;\n",
        txt, count=1,
    )
    txt = re.sub(
        r"\s*localparam signed \[SCALED_W-1:0\] SCALE_ROUND_HALF\s*=\n"
        r"\s*\{\{\(SCALED_W-1\)\{1'b0\}\}, 1'b1\} <<< \(SCALE_SHIFT - 1\);\n"
        r"\s*localparam signed \[SCALED_W-1:0\] SCALE_ROUND_HALF_M1\s*=\n"
        r"\s*SCALE_ROUND_HALF - \{\{\(SCALED_W-1\)\{1'b0\}\}, 1'b1\};\n",
        "\n",
        txt, count=1,
    )
    # NB: SCALE_ROUND_HALF still appears in the OUTPUT stage here -- step 6 below
    # rewrites that usage. Only assert the *localparam declarations* are gone.
    if ("localparam signed [SCALED_W-1:0] SCALE_ROUND_HALF" in txt
            or re.search(r"localparam integer SCALE_SHIFT\s*=\s*23;", txt)):
        raise SystemExit(f"{mid}: failed to strip uniform-shift requant localparams")

    # 2) Replace the per-OC ROM declaration + init (round s*2^23, no shift ROM)
    #    with compute_scale_approx mult + per-OC scale_shift_rom.
    rom_block_re = re.compile(
        r"    // ---------------- Per-OC scale ROM .*?\n"
        r"    reg signed \[SCALE_MULT_W-1:0\] scale_mult_rom \[0:OC-1\];\n"
        r"    initial begin\n.*?\n    end\n",
        re.S,
    )
    if not rom_block_re.search(txt):
        raise SystemExit(f"{mid}: scale_mult_rom init block not found")
    mult_lines = "\n".join(f"        scale_mult_rom[{i}]  = 16'sd{m};" for i, (m, sh) in enumerate(pairs))
    shf_lines = "\n".join(f"        scale_shift_rom[{i}] = 6'd{sh};" for i, (m, sh) in enumerate(pairs))
    new_rom = (
        "    // ---- Per-OC requant ROMs: compute_scale_approx(scale_factor_per_oc[oc]) ----\n"
        "    // Variable per-OC shift = the EXACT golden contract (replaces the prior\n"
        "    // round(s*2^23) + uniform SCALE_SHIFT=23 approximation, which disagreed\n"
        "    // with the golden at the +-1 clip boundary on 12/32 output channels).\n"
        "    reg signed [SCALE_MULT_W-1:0] scale_mult_rom  [0:OC-1];\n"
        "    reg        [5:0]              scale_shift_rom [0:OC-1];\n"
        "    initial begin\n" + mult_lines + "\n" + shf_lines + "\n    end\n"
    )
    txt = rom_block_re.sub(new_rom, txt, count=1)

    # 3) Add a per-OC shift_lane register alongside the scaled[] regs.
    txt = txt.replace(
        "    reg signed [SCALED_W-1:0] scaled [0:MP-1];\n"
        "    reg signed [SCALED_W-1:0] v_tmp;",
        "    reg signed [SCALED_W-1:0] scaled [0:MP-1];\n"
        "    reg [5:0]                 shift_lane [0:MP-1];\n"
        "    reg signed [SCALED_W-1:0] v_tmp;",
        1,
    )

    # 4) Reset: clear shift_lane[] with the other lane regs.
    txt = txt.replace(
        "                acc[i]    <= 0;\n"
        "                biased[i] <= 0;\n"
        "                scaled[i] <= 0;\n"
        "            end",
        "                acc[i]        <= 0;\n"
        "                biased[i]     <= 0;\n"
        "                scaled[i]     <= 0;\n"
        "                shift_lane[i] <= 0;\n"
        "            end",
        1,
    )

    # 5) SCALE stage: latch the per-OC shift alongside the per-OC mult.
    txt = txt.replace(
        "                ST_SCALE: begin\n"
        "                    for (lane_i = 0; lane_i < MP; lane_i = lane_i + 1) begin\n"
        "                        scaled[lane_i] <= $signed(biased[lane_i]) *\n"
        "                                          $signed(scale_mult_rom[oc_group * MP + lane_i]);\n"
        "                    end\n"
        "                    state <= ST_OUTPUT;\n"
        "                end",
        "                ST_SCALE: begin\n"
        "                    for (lane_i = 0; lane_i < MP; lane_i = lane_i + 1) begin\n"
        "                        scaled[lane_i]     <= $signed(biased[lane_i]) *\n"
        "                                              $signed(scale_mult_rom[oc_group * MP + lane_i]);\n"
        "                        shift_lane[lane_i] <= scale_shift_rom[oc_group * MP + lane_i];\n"
        "                    end\n"
        "                    state <= ST_OUTPUT;\n"
        "                end",
        1,
    )

    # 6) OUTPUT stage: per-OC variable shift + single positive round bias (floor).
    txt = txt.replace(
        "                        // [INVARIANT:ROUNDING]\n"
        "                        v_tmp = (scaled[lane_i] +\n"
        "                                 (scaled[lane_i][SCALED_W-1] ? SCALE_ROUND_HALF_M1\n"
        "                                                             : SCALE_ROUND_HALF)\n"
        "                                ) >>> SCALE_SHIFT;",
        "                        // [INVARIANT:ROUNDING] single positive bias + arith >>> = golden floor.\n"
        "                        v_tmp = (scaled[lane_i] +\n"
        "                                 ($signed({{(SCALED_W-1){1'b0}}, 1'b1}) <<< (shift_lane[lane_i] - 1))\n"
        "                                ) >>> shift_lane[lane_i];",
        1,
    )

    # 7) Refresh the header comment to reflect the per-OC contract.
    txt = txt.replace(
        "// The conv_datapath library only supports a single scalar SCALE_MULT/SCALE_SHIFT,\n"
        "// so this top inlines the MAC/BIAS/SCALE/OUTPUT pipeline with a per-OC scale ROM\n"
        "// (scale_mult_rom[oc] = round(scale_factor_per_oc[oc] * 2^23)) and uniform\n"
        "// SCALE_SHIFT=23. FSM cadence is identical to conv_datapath: MP*K_TOTAL + 6",
        "// The conv_datapath library only supports a single scalar SCALE_MULT/SCALE_SHIFT,\n"
        "// so this top inlines the MAC/BIAS/SCALE/OUTPUT pipeline with per-OC requant ROMs\n"
        "// scale_mult_rom[oc] / scale_shift_rom[oc] = compute_scale_approx(\n"
        "//   scale_factor_per_oc[oc]) -- the EXACT golden requant constants (variable\n"
        "// per-OC shift). FSM cadence is identical to conv_datapath: MP*K_TOTAL + 6",
        1,
    )

    path.write_text(txt)
    print(f"{mid}: patched inline FSM requant to per-OC compute_scale_approx "
          f"(mult + variable shift); MAC untouched (already decomposed)")
    return True


# ---------------------------------------------------------------------------
# node_conv2d (STEM) : 3x3 stride-1 pad-1, IC=3 OC=16. 5-stage parallel pipe
# (win -> MAC -> bias -> scale -> round/sat -> LATENCY_PAD shift register). The
# MAC indexing is ALREADY decomposed (ic-outer k -> ic-inner window), proven by
# the per-module tap (its MAC matches the golden). Its ONLY bug is the requant:
# it bakes scale_mult_arr[oc] = round(scale_factor_per_oc[oc] * 2^22) with a
# UNIFORM SCALE_SHIFT=22, NOT the variable-shift compute_scale_approx golden
# contract. 13/16 OCs need a shift != 22 (17..23) -> the uniform-22 mult is the
# wrong fixed-point approximation -> off-by-1 at the +-1 clip boundary on those
# OCs (the e2e first-divergence, e.g. oc3 exp=30 got=29). This rewrites the stem
# to per-OC compute_scale_approx mult + per-OC scale_shift_arr[oc] + a pipelined
# per-OC shift (shift_s4) + the single positive round bias (golden floor). The
# MAC, scheduler, line buffer and pipeline cadence are untouched, so
# pipeline_latency_cycles / the e2e cycle count are preserved.
# ---------------------------------------------------------------------------
# node_conv2d_8 (3x3 stride-1 pad-1, IC=OC=64) has the IDENTICAL parallel-pipe
# structure and the SAME bug: per-OC scale_mult_arr baked as round(s*2^22) with a
# UNIFORM SCALE_SHIFT=22, while 53/64 OCs need a shift != 22 (compute_scale_approx
# gives 17..23). Off-by-1 at the clip boundary on a handful of OCs (e.g. oc25)
# -> e2e logit error. patch_stem() is structure-generic (matches the win->MAC->
# bias->scale->round->LATENCY_PAD pipe), so it fixes conv_8 too.
def patch_stem(mid="node_conv2d"):
    path = RTL_DIR / f"{mid}.v"
    txt = path.read_text()
    if "scale_shift_arr" in txt:
        print(f"{mid}: already per-OC (scale_shift_arr present); skip")
        return False
    pairs, oc = per_oc_pairs(mid)
    backup(path)

    # 1) Drop the uniform SCALE_SHIFT localparam + the two SCALE_ROUND_HALF
    #    consts (round bias now computed per-OC at the use-site).
    txt = re.sub(r"^\s*localparam integer SCALE_SHIFT\s*=\s*22;\s*\n",
                 "    localparam integer SCALE_SHIFT_MAX = 23;\n", txt, flags=re.M)
    txt = re.sub(
        r"\s*localparam signed \[SCALED_W-1:0\] SCALE_ROUND_HALF\s*=\n"
        r"\s*\{\{\(SCALED_W-1\)\{1'b0\}\}, 1'b1\} <<< \(SCALE_SHIFT - 1\);\n"
        r"\s*localparam signed \[SCALED_W-1:0\] SCALE_ROUND_HALF_M1\s*=\n"
        r"\s*SCALE_ROUND_HALF - \{\{\(SCALED_W-1\)\{1'b0\}\}, 1'b1\};\n",
        "\n", txt, count=1)
    # NB: SCALE_ROUND_HALF still appears in the ROUND stage body here -- step 5
    # rewrites that usage. Only assert the *localparam declarations* are gone.
    if ("localparam signed [SCALED_W-1:0] SCALE_ROUND_HALF" in txt
            or re.search(r"localparam integer SCALE_SHIFT\s*=\s*22;", txt)):
        raise SystemExit(f"{mid}: failed to strip uniform-shift requant localparams")

    # 2) Replace the scale_mult_arr init block (wrong round(s*2^22) mults) with
    #    compute_scale_approx mults + a scale_shift_arr.
    mult_block_re = re.compile(
        r"    reg signed \[SCALE_CONST_W-1:0\] scale_mult_arr \[0:OC-1\];\n"
        r"    initial begin\n.*?\n    end\n",
        re.S,
    )
    if not mult_block_re.search(txt):
        raise SystemExit(f"{mid}: scale_mult_arr init block not found")
    mult_lines = "\n".join(f"        scale_mult_arr[{i}]  = 16'sd{m};" for i, (m, sh) in enumerate(pairs))
    shf_lines = "\n".join(f"        scale_shift_arr[{i}] = 6'd{sh};" for i, (m, sh) in enumerate(pairs))
    new_rom = (
        "    // ---- Per-OC requant ROMs: compute_scale_approx(scale_factor_per_oc[oc]) ----\n"
        "    // Variable per-OC shift = the EXACT golden contract (replaces the prior\n"
        "    // round(s*2^22) + uniform SCALE_SHIFT=22 approximation, which disagreed\n"
        "    // with the golden at the +-1 clip boundary on 13/16 output channels).\n"
        "    reg signed [SCALE_CONST_W-1:0] scale_mult_arr  [0:OC-1];\n"
        "    reg        [5:0]               scale_shift_arr [0:OC-1];\n"
        "    initial begin\n" + mult_lines + "\n" + shf_lines + "\n    end\n"
    )
    txt = mult_block_re.sub(new_rom, txt, count=1)

    # 3) Add a per-OC shift pipeline reg alongside scaled_s4 (latched in SCALE
    #    stage, consumed in ROUND stage one cycle later).
    txt = txt.replace(
        "    reg signed [SCALED_W-1:0] scaled_s4 [0:OC-1];\n",
        "    reg signed [SCALED_W-1:0] scaled_s4 [0:OC-1];\n"
        "    reg        [5:0]          shift_s4  [0:OC-1];\n",
        1,
    )

    # 4) SCALE stage: latch the per-OC shift next to the per-OC mult.
    txt = txt.replace(
        "        for (oc_s = 0; oc_s < OC; oc_s = oc_s + 1)\n"
        "            scaled_s4[oc_s] <= $signed(biased_s3[oc_s]) *\n"
        "                               $signed(scale_mult_arr[oc_s]);",
        "        for (oc_s = 0; oc_s < OC; oc_s = oc_s + 1) begin\n"
        "            scaled_s4[oc_s] <= $signed(biased_s3[oc_s]) *\n"
        "                               $signed(scale_mult_arr[oc_s]);\n"
        "            shift_s4[oc_s]  <= scale_shift_arr[oc_s];\n"
        "        end",
        1,
    )

    # 5) ROUND/SAT stage: per-OC variable shift + single positive round bias.
    txt = txt.replace(
        "            // [INVARIANT:ROUNDING]\n"
        "            v_tmp = (scaled_s4[oc_r] +\n"
        "                     (scaled_s4[oc_r][SCALED_W-1] ? SCALE_ROUND_HALF_M1\n"
        "                                                  : SCALE_ROUND_HALF)\n"
        "                    ) >>> SCALE_SHIFT;",
        "            // [INVARIANT:ROUNDING] single positive bias + arith >>> = golden floor.\n"
        "            v_tmp = (scaled_s4[oc_r] +\n"
        "                     ($signed({{(SCALED_W-1){1'b0}}, 1'b1}) <<< (shift_s4[oc_r] - 1))\n"
        "                    ) >>> shift_s4[oc_r];",
        1,
    )

    path.write_text(txt)
    print(f"{mid}: patched stem requant to per-OC compute_scale_approx "
          f"(mult + variable shift); MAC untouched (already decomposed)")
    return True


# ---------------------------------------------------------------------------
# node_conv2d_3 / node_conv2d_6 : per-TENSOR 1x1 stride-2 projection convs
# (per-tensor BY DESIGN, NN2RTL_PW_PER_CHANNEL=0). They use a single scalar
# SCALE_MULT / SCALE_SHIFT localparam. node_conv2d_3 shipped a STALE SCALE_MULT
# (19189) that disagrees with the golden's compute_scale_approx(scale_factor)
# (=19187) by 2 LSB -> wrong requant on the whole projection feature map (the
# next first-divergence after the stem). This corrects the per-tensor scalar to
# the EXACT compute_scale_approx constants. Idempotent: only writes if the
# baked values differ from the golden's.
# ---------------------------------------------------------------------------
def patch_pw_scale(mid):
    path = RTL_DIR / f"{mid}.v"
    txt = path.read_text()
    ir = json.loads(IR_PATH.read_text())
    layer = next(l for l in ir["layers"]
                 if l.get("module_id") == mid and l.get("op_type") == "conv2d")
    sf = float(layer["scale_factor"])
    want_mult, want_shift = compute_scale_approx(sf)

    m_mult = re.search(r"localparam\s+SCALE_MULT\s*=\s*(\d+);", txt)
    m_shift = re.search(r"localparam\s+SCALE_SHIFT\s*=\s*(\d+);", txt)
    if not m_mult or not m_shift:
        raise SystemExit(f"{mid}: SCALE_MULT/SCALE_SHIFT localparam not found")
    cur_mult, cur_shift = int(m_mult.group(1)), int(m_shift.group(1))
    if cur_mult == want_mult and cur_shift == want_shift:
        print(f"{mid}: per-tensor scale already correct "
              f"(mult={cur_mult} shift={cur_shift}); skip")
        return False
    backup(path)
    txt = txt[:m_mult.start(1)] + str(want_mult) + txt[m_mult.end(1):]
    # re-find shift (offset shifted by mult-length change)
    m_shift = re.search(r"localparam\s+SCALE_SHIFT\s*=\s*(\d+);", txt)
    txt = txt[:m_shift.start(1)] + str(want_shift) + txt[m_shift.end(1):]
    path.write_text(txt)
    print(f"{mid}: per-tensor scale {cur_mult}/{cur_shift} -> "
          f"{want_mult}/{want_shift} (compute_scale_approx, golden-exact)")
    return True


def main():
    print("Applying per-OC requant fix to ResNet-8 convs:",
          ", ".join(["node_conv2d"] + TARGETS + ["node_conv2d_8", "node_conv2d_3", "node_conv2d_6"]))
    patch_stem("node_conv2d")
    patch_stem("node_conv2d_8")   # same uniform-shift-22 bug as the stem
    patch_pw_scale("node_conv2d_3")
    patch_pw_scale("node_conv2d_6")
    patch_parallel("node_conv2d_1")
    patch_conv2("node_conv2d_2")
    patch_conv4("node_conv2d_4")
    patch_parallel("node_conv2d_5")
    patch_conv7("node_conv2d_7")
    print("Done.")


if __name__ == "__main__":
    main()
