#!/usr/bin/env python3
"""Regenerate the 7 spatial 3x3 convs with a BACKPRESSURED output streamer.

These modules (conv_200,208,214,220,228,234,240) use the split-arch wrapper
(coord_scheduler + line_buf_window + conv_datapath_mp_k) but ship a *free-running*
output streamer (valid_out asserted N cycles/pixel with no ready_out). Under a
fast/slow imbalance their consumer's skid fills and beats are silently dropped
-> chain-wide starvation freeze (see docs/E2E_SIM_DEBUG_HANDOFF.md §3/§5).

Fix: re-emit each module from ONE uniform template carrying the proven
backpressured streamer used by the parallel 1x1 convs (latch the full OC pixel,
stream OUT_BEATS tiles gated by ready_out, stall_in |= out_busy). The computed
VALUES are identical (same coord_scheduler/line_buf_window/conv_datapath_mp_k
params + same weights); only output timing is paced. Byte-exact is verified by
tying ready_out high (--equiv emits a self-contained tie-high variant).

Params (IC/OC/IH/IW/OH/OW/KH/KW/SH/SW/PH/PW/MP/MP_K/SCALE_*/weight paths) are
read from the CURRENT module on disk so nothing is hard-coded or assumed.

USAGE:
  python scripts/apply_3x3_backpressure.py            # regenerate all 7
  python scripts/apply_3x3_backpressure.py --only 200
  python scripts/apply_3x3_backpressure.py --equiv 200 # write tie-high temp for equiv
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

RTL = Path("output/rtl")
TARGETS = [200, 208, 214, 220, 228, 234, 240]


def grab_int(txt: str, name: str) -> int | None:
    # localparam integer NAME = 123;  (also tolerates sized literals 32'd123)
    m = re.search(rf"\b{name}\b\s*=\s*\d+'([dh])([0-9a-fA-F]+)", txt)
    if m:
        return int(m.group(2), 16 if m.group(1) == "h" else 10)
    m = re.search(rf"\b{name}\b\s*=\s*(\d+)", txt)
    return int(m.group(1)) if m else None


def grab_str(txt: str, name: str) -> str | None:
    m = re.search(rf"\.{name}\(\"([^\"]+)\"\)", txt)
    return m.group(1) if m else None


def grab_mp_k(txt: str) -> int | None:
    # Original modules: datapath inst `.MP_K(9)`. Regenerated modules:
    # localparam `MP_K=9` with inst `.MP_K(MP_K)`.
    m = re.search(r"\.MP_K\((\d+)\)", txt)
    if m:
        return int(m.group(1))
    return grab_int(txt, "MP_K")


def gen_wrapper(n: int, p: dict, tie_ready_high: bool = False) -> str:
    # ready_out is a real input port; for equiv (no driver in static TB) emit a
    # tie-high internal wire instead so the streamer drains every cycle.
    if tie_ready_high:
        ready_port = ""
        ready_decl = "    wire ready_out = 1'b1;  // equiv: consumer always ready\n"
    else:
        ready_port = "    input  wire                       ready_out,\n"
        ready_decl = ""
    return f"""`timescale 1ns / 1ps
// node_conv_{n} - {p['kh']}x{p['kw']} conv2d, split-arch datapath
// (coord_scheduler + line_buf_window + conv_datapath_mp_k) with a BACKPRESSURED
// output streamer (holds valid_out until ready_out). Byte-exact vs the prior
// free-running streamer; only output timing is paced. Auto-generated by
// scripts/apply_3x3_backpressure.py.
//   IC={p['ic']}, OC={p['oc']}, {p['ih']}x{p['iw']}->{p['oh']}x{p['ow']}, stride {p['sh']}, pad {p['ph']}. MP={p['mp']}, MP_K={p['mp_k']}.
module node_conv_{n} (
    input  wire                       clk,
    input  wire                       rst_n,
    input  wire                       valid_in,
    output wire                       ready_in,
    input  wire [255:0]               data_in,
    output wire                       valid_out,
{ready_port}    output wire [255:0]               data_out
);
    localparam integer IC={p['ic']}, OC={p['oc']}, IH={p['ih']}, IW={p['iw']}, OH={p['oh']}, OW={p['ow']};
    localparam integer KH={p['kh']}, KW={p['kw']}, SH={p['sh']}, SW={p['sw']}, PH={p['ph']}, PW={p['pw']};
    localparam integer K_TOTAL=IC*KH*KW;
    localparam integer MP={p['mp']}, MP_K={p['mp_k']};
    localparam integer SCALE_MULT={p['smult']}, SCALE_SHIFT={p['sshift']};
    localparam integer CHANNEL_TILE=32;
    localparam integer TILE_BITS=CHANNEL_TILE*8;
    localparam integer IN_BEATS=IC/CHANNEL_TILE;
    localparam integer OUT_BEATS=OC/CHANNEL_TILE;
    localparam integer IN_PIXEL_BITS=IC*8;
    localparam integer OUT_PIXEL_BITS=OC*8;
    localparam integer INB_W=$clog2(IN_BEATS);
    localparam integer OUTB_W=$clog2(OUT_BEATS);
{ready_decl}
    wire sched_needs_real_input, sched_ready_in, sched_output_fires, sched_advance;
    wire [$clog2(IH+PH+1)-1:0] sched_in_row;
    wire [$clog2(IW+PW+1)-1:0] sched_in_col;
    wire [$clog2(OH*OW+1)-1:0] sched_outputs_emitted;
    wire sched_out_frame_done;
    wire [KH*KW*IC*8-1:0] window_flat;
    wire mac_busy, lib_valid_out_w;
    wire [OUT_PIXEL_BITS-1:0] lib_data_out_w;

    reg start_pulse;
    reg [1:0] frame_state;
    localparam ST_ARM=2'd0, ST_RUN=2'd1, ST_WAIT=2'd2;

    reg [INB_W-1:0] in_beat_idx;
    reg [IN_PIXEL_BITS-TILE_BITS-1:0] in_lo;
    wire is_last_in_beat = (in_beat_idx == IN_BEATS-1);
    assign ready_in = is_last_in_beat ? sched_ready_in : 1'b1;
    wire beat_fire = valid_in && ready_in;
    wire last_beat_fire = beat_fire && is_last_in_beat;
    wire lib_valid_in_w = last_beat_fire;
    wire [IN_PIXEL_BITS-1:0] lib_data_in_w = {{data_in, in_lo}};

    // Backpressured output streamer: latch the full OC pixel on lib_valid_out_w,
    // then stream OUT_BEATS tiles gated by ready_out. stall_in |= out_busy keeps
    // the datapath from producing a new pixel over an undrained one -> lossless.
    reg [OUT_PIXEL_BITS-1:0] out_pix;
    reg [OUTB_W:0]           out_idx;
    reg                      out_busy;
    assign valid_out = out_busy;
    assign data_out  = out_pix[out_idx*TILE_BITS +: TILE_BITS];

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            frame_state<=ST_ARM; start_pulse<=1'b0; in_beat_idx<=0; in_lo<=0;
            out_pix<=0; out_idx<=0; out_busy<=1'b0;
        end else begin
            start_pulse <= 1'b0;
            case (frame_state)
                ST_ARM:  begin start_pulse<=1'b1; frame_state<=ST_RUN; end
                ST_RUN:  begin if (sched_out_frame_done) frame_state<=ST_WAIT; end
                ST_WAIT: begin if (!mac_busy) frame_state<=ST_ARM; end
                default: frame_state<=ST_ARM;
            endcase
            if (beat_fire) begin
                if (!is_last_in_beat)
                    in_lo[in_beat_idx*TILE_BITS +: TILE_BITS] <= data_in;
                in_beat_idx <= is_last_in_beat ? 0 : in_beat_idx + 1'b1;
            end
            if (lib_valid_out_w && !out_busy) begin
                out_pix  <= lib_data_out_w;
                out_idx  <= 0;
                out_busy <= 1'b1;
            end else if (out_busy && ready_out) begin
                if (out_idx == OUT_BEATS-1) out_busy <= 1'b0;
                else                        out_idx  <= out_idx + 1'b1;
            end
        end
    end

    wire stall_in = mac_busy || out_busy;
    coord_scheduler #(.IH(IH),.IW(IW),.OH(OH),.OW(OW),.KH(KH),.KW(KW),.SH(SH),.SW(SW),.PH(PH),.PW(PW)) scheduler (
        .clk(clk),.rst_n(rst_n),.start(start_pulse),.stall_in(stall_in),
        .valid_in(lib_valid_in_w),.ready_in(sched_ready_in),
        .needs_real_input(sched_needs_real_input),
        .in_row(sched_in_row),.in_col(sched_in_col),
        .output_fires(sched_output_fires),.advance(sched_advance),
        .in_frame_done(),.out_frame_done(sched_out_frame_done),
        .outputs_emitted(sched_outputs_emitted));
    line_buf_window #(.IC(IC),.IW(IW),.IH(IH),.KH(KH),.KW(KW),.PW(PW),.PH(PH)) lbw (
        .clk(clk),.rst_n(rst_n),.frame_start(start_pulse),
        .sched_in_row(sched_in_row),.sched_in_col(sched_in_col),
        .sched_needs_real_input(sched_needs_real_input),
        .sched_advance(sched_advance),.sched_output_fires(sched_output_fires),
        .valid_in(lib_valid_in_w),.data_in(lib_data_in_w),.window_flat(window_flat));
    conv_datapath_mp_k #(.IC(IC),.OC(OC),.KH(KH),.KW(KW),.K_TOTAL(K_TOTAL),.MP(MP),
        .MP_K(MP_K),.SCALE_MULT(SCALE_MULT),.SCALE_SHIFT(SCALE_SHIFT),
        .WEIGHTS_PATH("{p['wpath']}"),
        .BIAS_PATH("{p['bpath']}")) dp (
        .clk(clk),.rst_n(rst_n),.window_flat(window_flat),
        .start_mac(sched_output_fires),
        .valid_out(lib_valid_out_w),.data_out(lib_data_out_w),.mac_busy(mac_busy));
endmodule
"""


def extract(n: int) -> dict:
    src = (RTL / f"node_conv_{n}.v").read_text()
    p = dict(
        ic=grab_int(src, "IC"), oc=grab_int(src, "OC"),
        ih=grab_int(src, "IH"), iw=grab_int(src, "IW"),
        oh=grab_int(src, "OH"), ow=grab_int(src, "OW"),
        kh=grab_int(src, "KH"), kw=grab_int(src, "KW"),
        sh=grab_int(src, "SH"), sw=grab_int(src, "SW"),
        ph=grab_int(src, "PH"), pw=grab_int(src, "PW"),
        mp=grab_int(src, "MP"), mp_k=grab_mp_k(src),
        smult=grab_int(src, "SCALE_MULT"), sshift=grab_int(src, "SCALE_SHIFT"),
        wpath=grab_str(src, "WEIGHTS_PATH"), bpath=grab_str(src, "BIAS_PATH"),
    )
    missing = [k for k, v in p.items() if v is None]
    if missing:
        raise SystemExit(f"conv_{n}: failed to extract {missing}")
    return p


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="comma-separated conv ids")
    ap.add_argument("--equiv", help="emit tie-high temp <mod>.equiv.v for ONE id (no overwrite)")
    ap.add_argument("--mp", type=int, help="override output-channel parallelism MP (perf). "
                                           "Requires weights repacked at this MP first. Byte-exact (verify equiv).")
    args = ap.parse_args()

    if args.equiv:
        # Overwrite the real path with the tie-high (no-port) variant so
        # equiv_one.ts (fixed path + sidecar by module name) can drive it.
        # The pre-existing backup protects the original; re-run without
        # --equiv afterwards to emit the real ready_out-port version.
        n = int(args.equiv)
        p = extract(n)
        if args.mp:
            p['mp'] = args.mp
        (RTL / f"node_conv_{n}.v").write_text(gen_wrapper(n, p, tie_ready_high=True))
        print(f"[equiv] node_conv_{n}.v overwritten with ready_out tied high (MP={p['mp']})")
        return

    only = set(int(x) for x in args.only.split(",")) if args.only else set(TARGETS)
    for n in TARGETS:
        if n not in only:
            continue
        p = extract(n)
        if args.mp:
            p['mp'] = args.mp
        (RTL / f"node_conv_{n}.v").write_text(gen_wrapper(n, p))
        print(f"[ok] conv_{n}: IC={p['ic']} OC={p['oc']} {p['ih']}x{p['iw']}->{p['oh']}x{p['ow']} "
              f"s{p['sh']} MP={p['mp']} MP_K={p['mp_k']} (backpressured)")


if __name__ == "__main__":
    main()
