#!/usr/bin/env python3
"""Decisive per-conv gate: recompute a conv's output the EXACT way the RTL does
(un-permute the on-disk WIDE hex via the RTL slice formula at WGT_BITS, + bias hex
+ per-OC scale via compute_scale_approx of the IR scale_factor_per_oc), compare to
its FRESH LOGICAL golden (output/goldens/<mid>.goldout). Validates that the INT3
(or INT4) generated artifacts are CONSUMED correctly by the datapath.

Handles stride/padding (reads from layer_ir). Compares against the LOGICAL golden
(untiled OH*OW*OC), which is regenerated by generate_golden (the contract-dir
golden can be stale — see refresh_final_golden.py).

Usage: python scripts/gate_conv_int3.py <module_id> <wgt_bits>
"""
from __future__ import annotations
import sys, json
from pathlib import Path
import numpy as np
import struct
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from scripts.golden_impl import compute_scale_approx

MID = sys.argv[1] if len(sys.argv) > 1 else "node_conv_284"
WGT_BITS = int(sys.argv[2]) if len(sys.argv) > 2 else 3
IR = {l["module_id"]: l for l in json.load(open(ROOT / "output/layer_ir.json"))["layers"]}
L = IR[MID]
OC, IC, KH, KW = L["weight_shape"]
K_TOTAL = IC * KH * KW
ish, osh = L["input_shape"], L["output_shape"]
IH, IW = ish[-2], ish[-1]
OH, OW = osh[-2], osh[-1]
SH, SW = L.get("stride", [1, 1])
PH, PW = L.get("padding", [1, 1])


def rtl_mp(path):
    import re
    txt = path.read_text()
    return int(re.search(r"\bMP\s*=\s*(\d+)", txt).group(1)), int(re.search(r"\bMP_K\s*=\s*(\d+)", txt).group(1))


MP, MP_K = rtl_mp(ROOT / "output/rtl" / f"{MID}.v")
OC_PASSES = (OC + MP - 1) // MP
K_GROUPS = K_TOTAL // MP_K


def logical_vec0(suffix, expect_ch):
    """vec0 of the FRESH logical golden: NN2V 20B hdr, nvec, samples, bps."""
    p = ROOT / "output/goldens" / f"{MID}.{suffix}"
    raw = p.read_bytes()
    magic, ver, nvec, samp, bps = struct.unpack_from("<4sIIII", raw, 0)
    assert magic == b"NN2V" and bps == expect_ch, f"{p}: bps={bps} expect={expect_ch}"
    return np.frombuffer(raw[20:20 + samp * bps], dtype=np.int8).astype(np.int64), samp


def sbits(v, nb):
    return v - (1 << nb) if (v >> (nb - 1)) & 1 else v


def unpermute(path, wgt_bits):
    lines = [ln.strip() for ln in path.read_text().splitlines() if ln.strip()]
    assert len(lines) == OC_PASSES * K_GROUPS, f"{len(lines)} words != {OC_PASSES*K_GROUPS}"
    mask = (1 << wgt_bits) - 1
    flat = np.zeros(OC * K_TOTAL, dtype=np.int32)
    for i, hexstr in enumerate(lines):
        word = int(hexstr, 16)
        g, kg = i // K_GROUPS, i % K_GROUPS
        for lane in range(MP):
            for kpos in range(MP_K):
                field = (word >> ((lane * MP_K + kpos) * wgt_bits)) & mask
                oc, k = g * MP + lane, kg * MP_K + kpos
                if oc < OC and k < K_TOTAL:
                    flat[oc * K_TOTAL + k] = sbits(field, wgt_bits)
    return flat


def load_flat(path):
    out = []
    for ln in path.read_text().splitlines():
        s = ln.strip()
        if s and not s.startswith("//"):
            v = int(s, 16)
            out.append(v - 256 if v > 127 else v)
    return np.array(out, dtype=np.int32)


def main():
    wide_suffix = f"mp_k_{MP_K}"
    wide = ROOT / "output/weights" / f"{MID}_weights_{wide_suffix}.hex"
    w_un = unpermute(wide, WGT_BITS)
    w_flat = load_flat(ROOT / "output/weights" / f"{MID}_weights.hex")
    print(f"{MID}: OC={OC} IC={IC} K={KH}x{KW} stride={SH}x{SW} pad={PH}x{PW} "
          f"IH={IH} IW={IW} OH={OH} OW={OW} MP={MP} MP_K={MP_K} WGT_BITS={WGT_BITS}")
    print(f"[UNPERMUTE] WIDE un-permuted vs FLAT: elem_equal={np.array_equal(w_un, w_flat)} "
          f"mism={int((w_un!=w_flat).sum())}/{w_un.size}  range[{w_un.min()},{w_un.max()}]")

    inp_flat, in_samp = logical_vec0("goldin", IC)
    gold_flat, out_samp = logical_vec0("goldout", OC)
    assert in_samp == IH * IW and out_samp == OH * OW, (in_samp, out_samp, IH * IW, OH * OW)
    inp = inp_flat.reshape(IH, IW, IC)
    gold = gold_flat.reshape(OH * OW, OC)
    w = w_un.reshape(OC, IC, KH, KW)
    bias = np.array([int(x, 16) if int(x, 16) < 2**31 else int(x, 16) - 2**32
                     for x in (ROOT / "output/weights" / f"{MID}_bias.hex").read_text().split()], dtype=np.int64)

    pad = np.zeros((IH + 2 * PH, IW + 2 * PW, IC), np.int64)
    pad[PH:PH + IH, PW:PW + IW, :] = inp
    acc = np.zeros((OH * OW, OC), np.int64)
    for kh in range(KH):
        for kw in range(KW):
            # strided window: out (oh,ow) reads pad[oh*SH+kh, ow*SW+kw]
            sub = pad[kh:kh + OH * SH:SH, kw:kw + OW * SW:SW, :]   # [OH,OW,IC]
            acc += sub.reshape(OH * OW, IC) @ w[:, :, kh, kw].T.astype(np.int64)
    acc = acc + bias[None, :]
    spo = L["scale_factor_per_oc"]
    my = np.zeros((OH * OW, OC), np.int32)
    for oc in range(OC):
        mult, shift = compute_scale_approx(float(spo[oc]))
        rb = (1 << (shift - 1)) if shift > 0 else 0
        my[:, oc] = np.clip((acc[:, oc] * mult + rb) >> shift, -128, 127)

    d = np.abs(my - gold)
    mm = int((d != 0).sum())
    ys, xs = np.where(d != 0)
    print("  DEBUG mismatching samples (pix, oc, int_mac, bias, mult, shift, my, gold):")
    for k in range(min(6, len(ys))):
        p, oc = int(ys[k]), int(xs[k])
        mult, shift = compute_scale_approx(float(spo[oc]))
        print(f"    pix={p} oc={oc}: int_mac={acc[p,oc]-bias[oc]} bias={bias[oc]} mult={mult} shift={shift} "
              f"my={my[p,oc]} gold={gold[p,oc]}  sf={spo[oc]:.6g}")
    print(f"[GATE] recompute(WIDE+bias+scale, RTL-way) vs FRESH LOGICAL GOLDOUT: "
          f"mismatch={mm}/{my.size} ({100*mm/my.size:.2f}%)  max_err={int(d.max()) if my.size else 0}")
    print("  => " + ("ARTIFACTS+ALGORITHM CORRECT -> any e2e mismatch is RTL Verilog"
                     if mm == 0 else "MISMATCH -> on-disk artifacts/algorithm != golden"))


if __name__ == "__main__":
    main()
