#!/usr/bin/env python3
"""gen_resnet_engine_iso_cfg.py — emit tb/engine_iso_cfg.h for a ResNet
engine dispatch, with every geometry/base value parsed DIRECTLY from the
deployed scheduler ROMs (output/rtl/nn2rtl_scheduler.v) — so the iso config
can never drift from the dispatch table the e2e top actually runs.

Sibling of scripts/gen_mbv2_dense_engine_iso_cfg.py, built for the
[KPAR4-RN] gate: ResNet dispatches BOTH dense 1x1 AND dense 3x3 convs on
the engine; the 3x3s take the NEW pos-major fast walk (transposed _kp4
banks), so the iso set must cover at least one of each.

Golden vectors come from the contract goldens
(output/goldens/contracts/node_conv_<X>_tiled-streaming*/node_conv_<X>.gold{in,out}).

Usage: python scripts/gen_resnet_engine_iso_cfg.py <conv> [vec]
       e.g. <conv> = 246 (dispatch 0, 3x3 IC=256), 250 (dispatch 1, 1x1
       IC=512 OC=1024), 284 (dispatch 9, 3x3 IC=512 stride2)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCHED = REPO / "output" / "rtl" / "nn2rtl_scheduler.v"
CONTRACTS = REPO / "output" / "goldens" / "contracts"

# dispatch order (mirrors the deployed top's engine_output_bridge SLOTs).
MODULES = [
    "node_conv_246", "node_conv_250", "node_conv_254", "node_conv_260",
    "node_conv_264", "node_conv_266", "node_conv_272", "node_conv_278",
    "node_conv_282", "node_conv_284", "node_conv_286", "node_conv_290",
    "node_conv_292", "node_conv_294", "node_conv_296", "node_conv_298",
    "node_conv_300",
]


def parse_rom(text: str, name: str) -> dict[int, int]:
    vals = {int(i): int(v)
            for i, v in re.findall(rf"5'd(\d+): {name} = \d+'d(\d+);", text)}
    if len(vals) != 17:
        raise SystemExit(f"ROM {name}: {len(vals)} rows != 17")
    return vals


def find_golden(mid: str, ext: str) -> Path:
    pref = f"{mid}_tiled-streaming"
    cands = sorted(d for d in CONTRACTS.iterdir() if d.name.startswith(pref))
    if not cands:
        raise SystemExit(f"no contract dir '{pref}*' under {CONTRACTS}")
    p = cands[0] / f"{mid}.{ext}"
    if not p.exists():
        raise SystemExit(f"golden missing: {p}")
    return p


def main() -> int:
    conv = sys.argv[1] if len(sys.argv) > 1 else "246"
    vec = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    mid = f"node_conv_{conv}"
    if mid not in MODULES:
        raise SystemExit(f"{mid} not an engine dispatch")
    d = MODULES.index(mid)

    t = SCHED.read_text(encoding="utf-8")
    ic = parse_rom(t, "channel_in_rom")[d]
    oc = parse_rom(t, "channel_out_rom")[d]
    kh = parse_rom(t, "kernel_h_rom")[d]
    kw = parse_rom(t, "kernel_w_rom")[d]
    sh = parse_rom(t, "stride_h_rom")[d]
    sw = parse_rom(t, "stride_w_rom")[d]
    ph = parse_rom(t, "padding_h_rom")[d]
    pw = parse_rom(t, "padding_w_rom")[d]
    ih = parse_rom(t, "input_h_rom")[d]
    iw = parse_rom(t, "input_w_rom")[d]
    oh = parse_rom(t, "output_h_rom")[d]
    ow = parse_rom(t, "output_w_rom")[d]
    wbase = parse_rom(t, "weight_base_word_rom")[d]
    bbase = parse_rom(t, "bias_base_word_rom")[d]

    goldin = find_golden(mid, "goldin").as_posix()
    goldout = find_golden(mid, "goldout").as_posix()
    # repo-root-relative (the iso exe runs with cwd=repo root)
    goldin = Path(goldin).relative_to(REPO).as_posix()
    goldout = Path(goldout).relative_to(REPO).as_posix()

    chunks = (ic + 255) // 256
    passes = (oc + 255) // 256
    n_in = ih * iw
    n_out = oh * ow
    out_base = max(4096, n_in * chunks)
    if out_base + n_out * passes > 65536:
        raise SystemExit("act regions exceed the iso act mem (64K words)")

    hdr = f"""// AUTO-GENERATED by scripts/gen_resnet_engine_iso_cfg.py {conv} {vec} — do not edit.
// ResNet engine-isolation config for {mid} (dispatch {d}): every value below
// is parsed from the deployed scheduler ROMs (nn2rtl_scheduler.v row 5'd{d}).
#define CFG_MODULE_ID "{mid}"
#define CFG_VEC {vec}
#define CFG_GOLDIN  "{goldin}"
#define CFG_GOLDOUT "{goldout}"
#define CFG_IC {ic}
#define CFG_OC {oc}
#define CFG_KH {kh}
#define CFG_KW {kw}
#define CFG_SH {sh}
#define CFG_SW {sw}
#define CFG_PH {ph}
#define CFG_PW {pw}
#define CFG_IH {ih}
#define CFG_IW {iw}
#define CFG_OH {oh}
#define CFG_OW {ow}
#define CFG_WEIGHT_BASE {wbase}
#define CFG_BIAS_BASE {bbase}
#define CFG_SCALE_MULT 0
#define CFG_SCALE_SHIFT 0
#define CFG_ZP 0
#define CFG_ACT_IN_BASE 0
#define CFG_ACT_OUT_BASE {out_base}
#define CFG_IC_CHUNKS {chunks}
#define CFG_OC_PASSES {passes}
#define CFG_N_IN_PIXELS {n_in}
#define CFG_N_OUT_PIXELS {n_out}
#define CFG_IN_BYTES_PER_SAMPLE {ic}
#define CFG_OUT_BYTES_PER_SAMPLE {oc}
"""
    out = REPO / "tb" / "engine_iso_cfg.h"
    out.write_text(hdr, encoding="utf-8", newline="\n")
    print(f"[gen-rn-iso] wrote {out} for {mid} vec {vec} (dispatch {d}: "
          f"IC={ic} OC={oc} k={kh}x{kw} {ih}x{iw}->{oh}x{ow} wbase={wbase} "
          f"bbase={bbase} chunks={chunks} passes={passes} out_base={out_base})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
