#!/usr/bin/env python3
"""gen_dw_engine_iso_cfg.py — emit tb/engine_iso_cfg.h for a depthwise engine
dispatch so tb/engine_iso_wrap_mbv2.v + tb/engine_iso_wrap_mbv2_tb.cpp can run
the REAL engine in DEPTHWISE mode against the per-module golden (WLAT=2
deployment URAM latency).

DW-ENGINE P1 trio (896/902/908) + the STRIDE-1 EXTENSION nine
(824/836/842/854/860/866/872/878/884). Bases match
scripts/extend_mbv2_engine_maps_dw.py / extend_mbv2_engine_maps_dw_ext.py
and the patched scheduler ROMs.

Usage: python scripts/gen_dw_engine_iso_cfg.py <conv> [vec]
       python scripts/gen_dw_engine_iso_cfg.py linear [vec]   ([FC-ENGINE] dense FC)
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# conv -> (C, H, weight_base_word, bias/scale_base_word)
DW_TABLE = {
    # P1 (wide 7x7 trio)
    "896": (960, 7, 13152, 58),
    "902": (960, 7, 13188, 62),
    "908": (960, 7, 13224, 66),
    # STRIDE-1 EXTENSION
    "824": (144, 56, 13260, 70),
    "836": (192, 28, 13269, 71),
    "842": (192, 28, 13278, 72),
    "854": (384, 14, 13287, 73),
    "860": (384, 14, 13305, 75),
    "866": (384, 14, 13323, 77),
    "872": (384, 14, 13341, 79),
    "878": (576, 14, 13359, 81),
    "884": (576, 14, 13386, 84),
}

# [DW-QUARTET] STRIDE-2 quartet: conv -> (C, IH, OH, weight_base_word
# [RELOCATED kp8 domain], bias/scale_base_word). Bases from
# scripts/extend_mbv2_engine_maps_dw_quartet.py + the patched scheduler.
S2_TABLE = {
    "818": (96, 112, 56, 18536, 91),
    "830": (144, 56, 28, 18545, 92),
    "848": (192, 28, 14, 18554, 93),
    "890": (576, 14, 7, 18563, 94),
}


def _fc_base_from_scheduler() -> int:
    """[KPAR8 FC-PAD] row 46 weight base is patched 13413 -> 13416 by
    apply_mbv2_kpar8.py; parse the deployed scheduler so this cfg can never
    drift from the dispatch table the e2e top actually runs."""
    import re as _re
    t = (REPO / "output" / "mobilenet-v2" / "rtl" / "nn2rtl_scheduler.v").read_text(encoding="utf-8")
    m = _re.search(r"6'd46: weight_base_word_rom = 20'd(\d+);", t)
    if not m:
        raise SystemExit("scheduler row 46 weight base not found")
    return int(m.group(1))


def emit_linear(vec: int) -> int:
    """[FC-ENGINE] node_linear as ONE dense dispatch: 1x1 conv over a 1x1
    image, IC=1280 (5 act chunks), OC=1000 (4 oc_passes, lanes 1000..1023
    dead). Bases match scripts/extend_mbv2_engine_maps_fc.py + the patched
    scheduler row 6'd46. CFG_DEPTHWISE 0 -> dense walk (k_total = 1280)."""
    fc_base = _fc_base_from_scheduler()
    hdr = f"""// AUTO-GENERATED by scripts/gen_dw_engine_iso_cfg.py linear {vec} — do not edit.
// [FC-ENGINE] dense engine-isolation config for node_linear (FC 1000x1280,
// 1x1 px=1, 4 oc_passes, K_TOTAL=1280; bases from extend_mbv2_engine_maps_fc.py
// + the patched scheduler row 46). Golden = the INTEGER FC golden
// node_linear.goldout (the same file the 8/8 e2e gate compares against).
#define CFG_MODULE_ID "node_linear"
#define CFG_VEC {vec}
#define CFG_GOLDIN  "output/mobilenet-v2/goldens/node_linear.goldin"
#define CFG_GOLDOUT "output/mobilenet-v2/goldens/node_linear.goldout"
#define CFG_IC 1280
#define CFG_OC 1000
#define CFG_KH 1
#define CFG_KW 1
#define CFG_SH 1
#define CFG_SW 1
#define CFG_PH 0
#define CFG_PW 0
#define CFG_IH 1
#define CFG_IW 1
#define CFG_OH 1
#define CFG_OW 1
#define CFG_WEIGHT_BASE {fc_base}
#define CFG_BIAS_BASE 87
#define CFG_SCALE_MULT 0
#define CFG_SCALE_SHIFT 0
#define CFG_ZP 0
#define CFG_ACT_IN_BASE 0
#define CFG_ACT_OUT_BASE 4096
#define CFG_IC_CHUNKS 5
#define CFG_OC_PASSES 4
#define CFG_N_IN_PIXELS 1
#define CFG_N_OUT_PIXELS 1
#define CFG_IN_BYTES_PER_SAMPLE 1280
#define CFG_OUT_BYTES_PER_SAMPLE 1000
#define CFG_DEPTHWISE 0
"""
    out = REPO / "tb" / "engine_iso_cfg.h"
    out.write_text(hdr, encoding="utf-8", newline="\n")
    print(f"[gen-fc-iso] wrote {out} for node_linear vec {vec} "
          f"(IC=1280 OC=1000 wbase=13413 bbase=87 chunks=5 passes=4)")
    return 0


def emit_s2(conv: str, vec: int) -> int:
    """[DW-QUARTET] stride-2 depthwise: full IHxIW input image preloaded,
    OHxOW output read back (IN px = 4x OUT px). The address_generator's DW
    walk reads input rows 2*oh_r..2*oh_r+2 with pad-1 bounds — the EXACT
    arithmetic the spatial module implements (this ISO is the A/B proof)."""
    c, ih, oh, wbase, bbase = S2_TABLE[conv]
    chunks = (c + 255) // 256
    in_px = ih * ih
    out_px = oh * oh
    out_base = max(4096, in_px * chunks)
    mid = f"node_conv_{conv}"
    hdr = f"""// AUTO-GENERATED by scripts/gen_dw_engine_iso_cfg.py {conv} {vec} — do not edit.
// [DW-QUARTET] STRIDE-2 depthwise engine-isolation config for {mid}
// (C={c} 3x3 s2 p1, {ih}x{ih} -> {oh}x{oh}, {chunks} oc_passes, K_TOTAL=9; bases
//  from extend_mbv2_engine_maps_dw_quartet.py [kp8-relocated] + the patched scheduler).
#define CFG_MODULE_ID "{mid}"
#define CFG_VEC {vec}
#define CFG_GOLDIN  "output/mobilenet-v2/goldens/{mid}.goldin"
#define CFG_GOLDOUT "output/mobilenet-v2/goldens/{mid}.goldout"
#define CFG_IC {c}
#define CFG_OC {c}
#define CFG_KH 3
#define CFG_KW 3
#define CFG_SH 2
#define CFG_SW 2
#define CFG_PH 1
#define CFG_PW 1
#define CFG_IH {ih}
#define CFG_IW {ih}
#define CFG_OH {oh}
#define CFG_OW {oh}
#define CFG_WEIGHT_BASE {wbase}
#define CFG_BIAS_BASE {bbase}
#define CFG_SCALE_MULT 0
#define CFG_SCALE_SHIFT 0
#define CFG_ZP 0
#define CFG_ACT_IN_BASE 0
#define CFG_ACT_OUT_BASE {out_base}
#define CFG_IC_CHUNKS {chunks}
#define CFG_OC_PASSES {chunks}
#define CFG_N_IN_PIXELS {in_px}
#define CFG_N_OUT_PIXELS {out_px}
#define CFG_IN_BYTES_PER_SAMPLE {c}
#define CFG_OUT_BYTES_PER_SAMPLE {c}
#define CFG_DEPTHWISE 1
"""
    out = REPO / "tb" / "engine_iso_cfg.h"
    out.write_text(hdr, encoding="utf-8", newline="\n")
    print(f"[gen-dw-s2-iso] wrote {out} for {mid} vec {vec} "
          f"(C={c} {ih}x{ih}->{oh}x{oh} s2 wbase={wbase} bbase={bbase} "
          f"chunks={chunks} out_base={out_base})")
    return 0


def main() -> int:
    conv = sys.argv[1] if len(sys.argv) > 1 else "896"
    vec = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    if conv == "linear":
        return emit_linear(vec)
    if conv in S2_TABLE:
        return emit_s2(conv, vec)
    if conv not in DW_TABLE:
        raise SystemExit(f"unknown DW conv {conv}; want one of "
                         f"{sorted(DW_TABLE)} / {sorted(S2_TABLE)} or 'linear'")
    c, h, wbase, bbase = DW_TABLE[conv]
    chunks = (c + 255) // 256          # = oc_passes = act words per pixel
    px = h * h
    # ACT_OUT_BASE: clear of the input region [0, px*chunks) with margin.
    out_base = max(4096, px * chunks)
    mid = f"node_conv_{conv}"
    hdr = f"""// AUTO-GENERATED by scripts/gen_dw_engine_iso_cfg.py {conv} {vec} — do not edit.
// [DW-ENGINE] depthwise engine-isolation config for {mid}
// (C={c} 3x3 s1 p1, {h}x{h}, {chunks} oc_passes, K_TOTAL=9; bases from the
//  map-extension scripts + the patched scheduler).
#define CFG_MODULE_ID "{mid}"
#define CFG_VEC {vec}
#define CFG_GOLDIN  "output/mobilenet-v2/goldens/{mid}.goldin"
#define CFG_GOLDOUT "output/mobilenet-v2/goldens/{mid}.goldout"
#define CFG_IC {c}
#define CFG_OC {c}
#define CFG_KH 3
#define CFG_KW 3
#define CFG_SH 1
#define CFG_SW 1
#define CFG_PH 1
#define CFG_PW 1
#define CFG_IH {h}
#define CFG_IW {h}
#define CFG_OH {h}
#define CFG_OW {h}
#define CFG_WEIGHT_BASE {wbase}
#define CFG_BIAS_BASE {bbase}
#define CFG_SCALE_MULT 0
#define CFG_SCALE_SHIFT 0
#define CFG_ZP 0
#define CFG_ACT_IN_BASE 0
#define CFG_ACT_OUT_BASE {out_base}
#define CFG_IC_CHUNKS {chunks}
#define CFG_OC_PASSES {chunks}
#define CFG_N_IN_PIXELS {px}
#define CFG_N_OUT_PIXELS {px}
#define CFG_IN_BYTES_PER_SAMPLE {c}
#define CFG_OUT_BYTES_PER_SAMPLE {c}
#define CFG_DEPTHWISE 1
"""
    out = REPO / "tb" / "engine_iso_cfg.h"
    out.write_text(hdr, encoding="utf-8", newline="\n")
    print(f"[gen-dw-iso] wrote {out} for {mid} vec {vec} "
          f"(C={c} {h}x{h} wbase={wbase} bbase={bbase} chunks={chunks} out_base={out_base})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
