#!/usr/bin/env python3
"""gen_dw_engine_iso_cfg.py — emit tb/engine_iso_cfg.h for a depthwise engine
dispatch so tb/engine_iso_wrap_mbv2.v + tb/engine_iso_wrap_mbv2_tb.cpp can run
the REAL engine in DEPTHWISE mode against the per-module golden (WLAT=2
deployment URAM latency).

DW-ENGINE P1 trio (896/902/908) + the STRIDE-1 EXTENSION nine
(824/836/842/854/860/866/872/878/884). Bases match
scripts/extend_mbv2_engine_maps_dw.py / extend_mbv2_engine_maps_dw_ext.py
and the patched scheduler ROMs.

Usage: python scripts/gen_dw_engine_iso_cfg.py <conv> [vec]
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# conv -> (C, H, weight_base_word, bias/scale_base_word)
DW_TABLE = {
    # P1 (wide 7x7 trio)
    "896": (960, 7, 13152, 58),
    "902": (960, 7, 13188, 62),
    "908": (960, 7, 13224, 66),
    # STRIDE-1 EXTENSION
    "824": (144, 56, 13260, 70),
    "836": (192, 28, 13269, 71),
    "842": (192, 28, 13278, 72),
    "854": (384, 14, 13287, 73),
    "860": (384, 14, 13305, 75),
    "866": (384, 14, 13323, 77),
    "872": (384, 14, 13341, 79),
    "878": (576, 14, 13359, 81),
    "884": (576, 14, 13386, 84),
}


def main() -> int:
    conv = sys.argv[1] if len(sys.argv) > 1 else "896"
    vec = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    if conv not in DW_TABLE:
        raise SystemExit(f"unknown DW conv {conv}; want one of {sorted(DW_TABLE)}")
    c, h, wbase, bbase = DW_TABLE[conv]
    chunks = (c + 255) // 256          # = oc_passes = act words per pixel
    px = h * h
    # ACT_OUT_BASE: clear of the input region [0, px*chunks) with margin.
    out_base = max(4096, px * chunks)
    mid = f"node_conv_{conv}"
    hdr = f"""// AUTO-GENERATED by scripts/gen_dw_engine_iso_cfg.py {conv} {vec} — do not edit.
// [DW-ENGINE] depthwise engine-isolation config for {mid}
// (C={c} 3x3 s1 p1, {h}x{h}, {chunks} oc_passes, K_TOTAL=9; bases from the
//  map-extension scripts + the patched scheduler).
#define CFG_MODULE_ID "{mid}"
#define CFG_VEC {vec}
#define CFG_GOLDIN  "output/mobilenet-v2/goldens/{mid}.goldin"
#define CFG_GOLDOUT "output/mobilenet-v2/goldens/{mid}.goldout"
#define CFG_IC {c}
#define CFG_OC {c}
#define CFG_KH 3
#define CFG_KW 3
#define CFG_SH 1
#define CFG_SW 1
#define CFG_PH 1
#define CFG_PW 1
#define CFG_IH {h}
#define CFG_IW {h}
#define CFG_OH {h}
#define CFG_OW {h}
#define CFG_WEIGHT_BASE {wbase}
#define CFG_BIAS_BASE {bbase}
#define CFG_SCALE_MULT 0
#define CFG_SCALE_SHIFT 0
#define CFG_ZP 0
#define CFG_ACT_IN_BASE 0
#define CFG_ACT_OUT_BASE {out_base}
#define CFG_IC_CHUNKS {chunks}
#define CFG_OC_PASSES {chunks}
#define CFG_N_IN_PIXELS {px}
#define CFG_N_OUT_PIXELS {px}
#define CFG_IN_BYTES_PER_SAMPLE {c}
#define CFG_OUT_BYTES_PER_SAMPLE {c}
#define CFG_DEPTHWISE 1
"""
    out = REPO / "tb" / "engine_iso_cfg.h"
    out.write_text(hdr, encoding="utf-8", newline="\n")
    print(f"[gen-dw-iso] wrote {out} for {mid} vec {vec} "
          f"(C={c} {h}x{h} wbase={wbase} bbase={bbase} chunks={chunks} out_base={out_base})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
