#!/usr/bin/env python3
"""gen_mbv2_dense_engine_iso_cfg.py — emit tb/engine_iso_cfg.h for a DENSE
(pointwise 1x1) MBV2 engine dispatch, with every geometry/base value parsed
DIRECTLY from the deployed scheduler ROMs (output/mobilenet-v2/rtl/
nn2rtl_scheduler.v) — so the iso config can never drift from the dispatch
table the e2e top actually runs.

Companion of scripts/gen_dw_engine_iso_cfg.py (which owns the depthwise rows
+ the FC 'linear' row). Built for the [KPAR4] gate: dense dispatches are the
FAST 4-taps/cycle path, so iso-proving a small (IC=16) and a large (IC=960)
dense conv at WLAT=2 covers the new walk + bank repack end to end.

Usage: python scripts/gen_mbv2_dense_engine_iso_cfg.py <conv> [vec]
       e.g. <conv> = 816 (dispatch 1, IC=16) or 898 (dispatch 38, IC=960)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCHED = REPO / "output" / "mobilenet-v2" / "rtl" / "nn2rtl_scheduler.v"

# dispatch order (mirrors the deployed scheduler; FC appended at 46).
MODULES = [
    "node_conv_814", "node_conv_816", "node_conv_820", "node_conv_822",
    "node_conv_824", "node_conv_826", "node_conv_828", "node_conv_832",
    "node_conv_834", "node_conv_836", "node_conv_838", "node_conv_840",
    "node_conv_842", "node_conv_844", "node_conv_846", "node_conv_850",
    "node_conv_852", "node_conv_854", "node_conv_856", "node_conv_858",
    "node_conv_860", "node_conv_862", "node_conv_864", "node_conv_866",
    "node_conv_868", "node_conv_870", "node_conv_872", "node_conv_874",
    "node_conv_876", "node_conv_878", "node_conv_880", "node_conv_882",
    "node_conv_884", "node_conv_886", "node_conv_888", "node_conv_892",
    "node_conv_894", "node_conv_896", "node_conv_898", "node_conv_900",
    "node_conv_902", "node_conv_904", "node_conv_906", "node_conv_908",
    "node_conv_910", "node_conv_912", "node_linear",
]


def parse_rom(text: str, name: str) -> dict[int, int]:
    vals = {int(i): int(v)
            for i, v in re.findall(rf"6'd(\d+): {name} = \d+'d(\d+);", text)}
    if len(vals) != 47:
        raise SystemExit(f"ROM {name}: {len(vals)} rows != 47")
    return vals


def main() -> int:
    conv = sys.argv[1] if len(sys.argv) > 1 else "816"
    vec = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    mid = f"node_conv_{conv}"
    if mid not in MODULES:
        raise SystemExit(f"{mid} not an engine dispatch")
    d = MODULES.index(mid)

    t = SCHED.read_text(encoding="utf-8")
    ic = parse_rom(t, "channel_in_rom")[d]
    oc = parse_rom(t, "channel_out_rom")[d]
    kh = parse_rom(t, "kernel_h_rom")[d]
    kw = parse_rom(t, "kernel_w_rom")[d]
    sh = parse_rom(t, "stride_h_rom")[d]
    sw = parse_rom(t, "stride_w_rom")[d]
    ph = parse_rom(t, "padding_h_rom")[d]
    pw = parse_rom(t, "padding_w_rom")[d]
    ih = parse_rom(t, "input_h_rom")[d]
    iw = parse_rom(t, "input_w_rom")[d]
    oh = parse_rom(t, "output_h_rom")[d]
    ow = parse_rom(t, "output_w_rom")[d]
    wbase = parse_rom(t, "weight_base_word_rom")[d]
    bbase = parse_rom(t, "bias_base_word_rom")[d]

    if not (kh == kw == 1 and ph == pw == 0):
        raise SystemExit(f"{mid} (dispatch {d}) is not a dense 1x1: "
                         f"k={kh}x{kw} pad={ph},{pw} — use gen_dw_engine_iso_cfg.py")

    chunks = (ic + 255) // 256
    passes = (oc + 255) // 256
    n_in = ih * iw
    n_out = oh * ow
    out_base = max(4096, n_in * chunks)
    if out_base + n_out * passes > 65536:
        raise SystemExit("act regions exceed the iso act mem (64K words)")

    hdr = f"""// AUTO-GENERATED by scripts/gen_mbv2_dense_engine_iso_cfg.py {conv} {vec} — do not edit.
// DENSE engine-isolation config for {mid} (dispatch {d}): every value below
// is parsed from the deployed scheduler ROMs (nn2rtl_scheduler.v row 6'd{d}).
#define CFG_MODULE_ID "{mid}"
#define CFG_VEC {vec}
#define CFG_GOLDIN  "output/mobilenet-v2/goldens/{mid}.goldin"
#define CFG_GOLDOUT "output/mobilenet-v2/goldens/{mid}.goldout"
#define CFG_IC {ic}
#define CFG_OC {oc}
#define CFG_KH {kh}
#define CFG_KW {kw}
#define CFG_SH {sh}
#define CFG_SW {sw}
#define CFG_PH {ph}
#define CFG_PW {pw}
#define CFG_IH {ih}
#define CFG_IW {iw}
#define CFG_OH {oh}
#define CFG_OW {ow}
#define CFG_WEIGHT_BASE {wbase}
#define CFG_BIAS_BASE {bbase}
#define CFG_SCALE_MULT 0
#define CFG_SCALE_SHIFT 0
#define CFG_ZP 0
#define CFG_ACT_IN_BASE 0
#define CFG_ACT_OUT_BASE {out_base}
#define CFG_IC_CHUNKS {chunks}
#define CFG_OC_PASSES {passes}
#define CFG_N_IN_PIXELS {n_in}
#define CFG_N_OUT_PIXELS {n_out}
#define CFG_IN_BYTES_PER_SAMPLE {ic}
#define CFG_OUT_BYTES_PER_SAMPLE {oc}
#define CFG_DEPTHWISE 0
"""
    out = REPO / "tb" / "engine_iso_cfg.h"
    out.write_text(hdr, encoding="utf-8", newline="\n")
    print(f"[gen-dense-iso] wrote {out} for {mid} vec {vec} (dispatch {d}: "
          f"IC={ic} OC={oc} {ih}x{iw} wbase={wbase} bbase={bbase} "
          f"chunks={chunks} passes={passes} out_base={out_base})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
