// Build + run the Verilator END-TO-END VALUE testbench for the ResNet-8
// all-spatial nn2rtl_top.v (output/resnet8/rtl/nn2rtl_top.v).
//
// Cloned from scripts/run_mbv2_top_value.ts. Proves the assembled ResNet-8 is
// byte-exact: feeds node_conv2d.goldin (32x32x3 = 1024 RGB beats) into s_axis,
// captures the single 80-bit m_axis logit beat, compares to node_linear.goldout
// (10 INT8 logits). See tb/resnet8_top_value_tb.cpp.
//
// RTL sources:
//   - all output/resnet8/rtl/*.v (the top + 21 per-layer modules; wrapper-local
//     bodies skip_fifo / uram_weight_bank / act_unified_mem / bias_mem /
//     engine_output_fifo live inside nn2rtl_top.v itself)
//   - rtl_library/{conv_datapath.v, conv_datapath_parallel.v,
//                  conv_datapath_mp_k.v, coord_scheduler.v, line_buf_window.v,
//                  retile_bridge.v}
//   - a GENERATED inactive stub for nn2rtl_scheduler + shared_engine (same as
//     the MBV2 all-spatial build: 0 engine dispatches => engine_busy=0,
//     spatial_stall=0, so spatial_run stays 1 the whole frame). The stub port
//     widths match the resnet8 top's instantiation (verified: dispatch_idx_out
//     [0:0], banks [2:0]/[5:0], 16/22-bit engine addr, 2048/8192-bit data).
//
// Usage:
//   npx tsx scripts/run_resnet8_top_value.ts [vector_idx]
//   env:
//     RESNET8_VEC=<n>         override vector index (argv wins)
//     RESNET8_ALL_VECS=1      run all 8 vectors
//     RESNET8_MAX_CYCLES=<n>  per-frame cycle cap (deadlock fail-fast)
//     NN2RTL_VALUE_RUNONLY=1  reuse existing exe (skip rebuild)
//     NN2RTL_DUMP_PATH=<p>    raw m_axis capture dump

import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync } from "node:fs";
import { spawn } from "node:child_process";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

const netRoot   = path.join(repoRoot, "output", "resnet8");
const rtlDir    = path.join(netRoot, "rtl");
const goldenDir = path.join(netRoot, "goldens");
const tbCpp     = path.join(repoRoot, "tb", "resnet8_top_value_tb.cpp");
const outDir    = path.join(netRoot, "reports", "verilator_resnet8_top_value");
const buildLog  = path.join(outDir, "build.log");
const runLog    = path.join(outDir, "run.log");
const resultJson = path.join(outDir, "result.json");

const goldinPath  = path.join(goldenDir, "node_conv2d.goldin");
const goldoutPath = path.join(goldenDir, "node_linear.goldout");

const vectorIdx = process.argv[2] ?? "0";

const verilatorBin = process.platform === "win32"
  ? "C:/Users/User/oss-cad-suite/bin/verilator_bin.exe" : "verilator";
const makeBin = process.platform === "win32"
  ? "C:/Users/User/w64devkit/bin/make.exe" : "make";

function toForwardSlash(p: string): string { return p.replace(/\\/g, "/"); }

// Inactive stub for the vestigial engine + scheduler. Port widths MATCH the
// resnet8 nn2rtl_top.v instantiation (identical shape to the MBV2 build).
const ENGINE_SCHED_STUB = `// AUTO-GENERATED by scripts/run_resnet8_top_value.ts — DO NOT EDIT, DO NOT COMMIT.
// Inactive stubs for the all-spatial resnet8 top (empty engine schedule).
\`timescale 1ns/1ps

module nn2rtl_scheduler (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        start,
    output wire        done,
    output wire        s_axil_awvalid,
    input  wire        s_axil_awready,
    output wire [7:0]  s_axil_awaddr,
    output wire        s_axil_wvalid,
    input  wire        s_axil_wready,
    output wire [31:0] s_axil_wdata,
    output wire [3:0]  s_axil_wstrb,
    input  wire        s_axil_bvalid,
    output wire        s_axil_bready,
    input  wire [1:0]  s_axil_bresp,
    output wire        engine_start,
    input  wire        engine_busy,
    input  wire        engine_done,
    input  wire        current_loaded,
    input  wire        current_drain_complete,
    output wire [0:0]  dispatch_idx_out,
    output wire [2:0]  input_bank_sel,
    output wire [2:0]  output_bank_sel,
    output wire [5:0]  skip_bank_reserved_mask,
    output wire        spatial_stall,
    output wire        engine_output_ready
);
    assign done                    = 1'b0;
    assign s_axil_awvalid          = 1'b0;
    assign s_axil_awaddr           = 8'd0;
    assign s_axil_wvalid           = 1'b0;
    assign s_axil_wdata            = 32'd0;
    assign s_axil_wstrb            = 4'd0;
    assign s_axil_bready           = 1'b0;
    assign engine_start            = 1'b0;
    assign dispatch_idx_out        = 1'b0;
    assign input_bank_sel          = 3'd0;
    assign output_bank_sel         = 3'd0;
    assign skip_bank_reserved_mask = 6'd0;
    assign spatial_stall           = 1'b0;   // <-- never throttle the spatial chain
    assign engine_output_ready     = 1'b0;
    wire _unused = &{1'b0, start, s_axil_awready, s_axil_wready, s_axil_bvalid,
                     s_axil_bresp, engine_busy, engine_done, current_loaded,
                     current_drain_complete, clk, rst_n};
endmodule

module shared_engine (
    input  wire           clk,
    input  wire           rst_n,
    input  wire           s_axil_awvalid,
    output wire           s_axil_awready,
    input  wire [7:0]     s_axil_awaddr,
    input  wire           s_axil_wvalid,
    output wire           s_axil_wready,
    input  wire [31:0]    s_axil_wdata,
    input  wire [3:0]     s_axil_wstrb,
    output wire           s_axil_bvalid,
    input  wire           s_axil_bready,
    output wire [1:0]     s_axil_bresp,
    input  wire           s_axil_arvalid,
    output wire           s_axil_arready,
    input  wire [7:0]     s_axil_araddr,
    output wire           s_axil_rvalid,
    input  wire           s_axil_rready,
    output wire [31:0]    s_axil_rdata,
    output wire [1:0]     s_axil_rresp,
    input  wire           engine_start,
    output wire           engine_busy,
    output wire           engine_done,
    output wire [15:0]    act_in_rd_addr,
    output wire           act_in_rd_en,
    input  wire [2047:0]  act_in_rd_data,
    output wire [15:0]    act_out_wr_addr,
    output wire           act_out_wr_en,
    output wire [2047:0]  act_out_wr_data,
    output wire [21:0]    weight_rd_addr,
    output wire           weight_rd_en,
    input  wire [2047:0]  weight_rd_data,
    output wire [21:0]    bias_rd_addr,
    output wire           bias_rd_en,
    input  wire [8191:0]  bias_rd_data,
    output wire [21:0]    scale_rd_addr,
    output wire           scale_rd_en,
    input  wire [8191:0]  scale_rd_data
);
    assign s_axil_awready  = 1'b0;
    assign s_axil_wready   = 1'b0;
    assign s_axil_bvalid   = 1'b0;
    assign s_axil_bresp    = 2'b00;
    assign s_axil_arready  = 1'b0;
    assign s_axil_rvalid   = 1'b0;
    assign s_axil_rdata    = 32'd0;
    assign s_axil_rresp    = 2'b00;
    assign engine_busy     = 1'b0;   // <-- spatial_run = ~(engine_busy | spatial_stall) stays high
    assign engine_done     = 1'b0;
    assign act_in_rd_addr  = 16'd0;
    assign act_in_rd_en    = 1'b0;
    assign act_out_wr_addr = 16'd0;
    assign act_out_wr_en   = 1'b0;
    assign act_out_wr_data = 2048'd0;
    assign weight_rd_addr  = 22'd0;
    assign weight_rd_en    = 1'b0;
    assign bias_rd_addr    = 22'd0;
    assign bias_rd_en      = 1'b0;
    assign scale_rd_addr   = 22'd0;
    assign scale_rd_en     = 1'b0;
    wire _unused = &{1'b0, s_axil_awvalid, s_axil_awaddr, s_axil_wvalid, s_axil_wdata,
                     s_axil_wstrb, s_axil_bready, s_axil_arvalid, s_axil_araddr,
                     s_axil_rready, engine_start, act_in_rd_data, weight_rd_data,
                     bias_rd_data, scale_rd_data, clk, rst_n};
endmodule
`;

async function collectSources(stubPath: string): Promise<string[]> {
  const out: string[] = [
    path.join(repoRoot, "rtl_library", "conv_datapath.v"),
    path.join(repoRoot, "rtl_library", "conv_datapath_parallel.v"),
    path.join(repoRoot, "rtl_library", "conv_datapath_mp_k.v"),
    path.join(repoRoot, "rtl_library", "coord_scheduler.v"),
    path.join(repoRoot, "rtl_library", "line_buf_window.v"),
    path.join(repoRoot, "rtl_library", "retile_bridge.v"),
    stubPath,
  ];
  const entries = await readdir(rtlDir);
  for (const entry of entries) {
    // only the live rtl/*.v: skip backups (.prewire / .preimprove) + .meta.json
    if (entry.endsWith(".v") && !entry.endsWith(".prewire") && !entry.endsWith(".preimprove")) {
      out.push(path.join(rtlDir, entry));
    }
  }
  for (const p of out) if (!existsSync(p)) throw new Error(`source missing: ${p}`);
  return out;
}

function runCmd(cmd: string, args: string[], cwd: string, env: NodeJS.ProcessEnv, label: string): Promise<{ stdout: string; stderr: string; ok: boolean }> {
  console.log(`[${label}] ${cmd} ${args.slice(0, 6).join(" ")}${args.length > 6 ? " ... +" + (args.length - 6) + " args" : ""}`);
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { cwd, env, stdio: ["ignore", "pipe", "pipe"], shell: false });
    let stdout = ""; let stderr = "";
    child.stdout.on("data", (c) => { const s = c.toString(); stdout += s; process.stdout.write(s); });
    child.stderr.on("data", (c) => { const s = c.toString(); stderr += s; process.stderr.write(s); });
    child.on("close", (code) => resolve({ stdout, stderr, ok: code === 0 }));
    child.on("error", (err) => resolve({ stdout, stderr: stderr + "\n" + String(err), ok: false }));
  });
}

async function main(): Promise<void> {
  await mkdir(outDir, { recursive: true });
  if (existsSync(buildLog)) await rm(buildLog);
  if (existsSync(runLog)) await rm(runLog);

  if (!existsSync(goldinPath))  throw new Error(`goldin missing: ${goldinPath}`);
  if (!existsSync(goldoutPath)) throw new Error(`goldout missing: ${goldoutPath}`);
  if (!existsSync(tbCpp))       throw new Error(`testbench missing: ${tbCpp}`);
  console.log(`[setup] goldin : ${path.relative(repoRoot, goldinPath)}`);
  console.log(`[setup] goldout: ${path.relative(repoRoot, goldoutPath)}`);

  const buildDir = path.join(outDir, "obj_dir_value");
  const stubPath = path.join(buildDir, "engine_sched_stub.v");
  const env = { ...process.env, PATH: `C:/Users/User/oss-cad-suite/bin;C:/Users/User/w64devkit/bin;${process.env.PATH ?? ""}` };

  if (process.env.NN2RTL_VALUE_RUNONLY !== "1") {
    if (existsSync(buildDir)) {
      console.log(`[setup] clearing previous build dir ${buildDir}`);
      for (let attempt = 0; attempt < 5; attempt++) {
        try { await rm(buildDir, { recursive: true, force: true }); break; }
        catch (e: any) {
          if (attempt === 4) console.log(`[setup] rm failed after retries (${e.code}); proceeding`);
          else { console.log(`[setup] rm attempt ${attempt + 1} failed (${e.code}); retrying...`); await new Promise(r => setTimeout(r, 2000)); }
        }
      }
    }
    await mkdir(buildDir, { recursive: true });
    await writeFile(stubPath, ENGINE_SCHED_STUB, "utf8");
    console.log(`[setup] wrote inactive engine+scheduler stub ${path.relative(repoRoot, stubPath)}`);

    const sources = await collectSources(stubPath);
    console.log(`[setup] collected ${sources.length} RTL files; tb=${path.relative(repoRoot, tbCpp)}`);
    const verilatorArgs = [
      "--cc", "--exe", "-O3", "--threads", "1", "--top-module", "nn2rtl_top", "--Mdir", toForwardSlash(buildDir),
      "-CFLAGS", `-O2 -std=c++17 -DNDEBUG ${process.env.RESNET8_EXTRA_CFLAGS || ""}`.trim(),
      "--x-initial", "0",
      "-Wno-fatal",
      "-Wno-WIDTH", "-Wno-WIDTHEXPAND", "-Wno-WIDTHTRUNC", "-Wno-UNUSED", "-Wno-UNOPTFLAT", "-Wno-CASEINCOMPLETE",
      "-Wno-CASEX", "-Wno-COMBDLY", "-Wno-INITIALDLY", "-Wno-IMPLICIT", "-Wno-STMTDLY", "-Wno-MULTIDRIVEN",
      "-Wno-DECLFILENAME", "-Wno-EOFNEWLINE", "-Wno-PINMISSING", "-Wno-WIDTHCONCAT", "--replication-limit", "20000",
      ...(process.env.RESNET8_EXTRA_VARGS ? process.env.RESNET8_EXTRA_VARGS.split(/\s+/).filter(Boolean) : []),
      ...sources.map(toForwardSlash), toForwardSlash(tbCpp),
    ];
    console.log(`[verilate] starting verilator (${sources.length} RTL sources, ~2-6 min)`);
    const verilateRes = await runCmd(verilatorBin, verilatorArgs, repoRoot, env, "verilate");
    await writeFile(buildLog, "--- verilator ---\n" + verilateRes.stdout + "\n" + verilateRes.stderr, "utf8");
    if (!verilateRes.ok) { console.error("[verilate] FAILED — see " + buildLog); process.exit(2); }
    console.log("[make] compiling generated C++ (3-15 min)");
    const makeRes = await runCmd(makeBin, ["-j", "16", "-f", "Vnn2rtl_top.mk", "Vnn2rtl_top"], buildDir, env, "make");
    await writeFile(buildLog, await readFile(buildLog, "utf8") + "\n--- make ---\n" + makeRes.stdout + "\n" + makeRes.stderr, "utf8");
    if (!makeRes.ok) { console.error("[make] FAILED — see " + buildLog); process.exit(3); }
  } else {
    console.log("[runonly] skipping build; reusing existing exe");
  }

  const exePath = path.join(buildDir, process.platform === "win32" ? "Vnn2rtl_top.exe" : "Vnn2rtl_top");
  if (!existsSync(exePath)) { console.error(`[run] expected exe not found: ${exePath}`); process.exit(4); }

  // CWD = repoRoot. resnet8 $readmemh weight paths are ABSOLUTE.
  console.log(`[run] launching ${exePath} vec=${vectorIdx}`);
  const t0 = Date.now();
  const dumpPath = process.env.NN2RTL_DUMP_PATH ?? "";
  const runArgs = dumpPath
    ? [goldinPath, goldoutPath, vectorIdx, dumpPath]
    : [goldinPath, goldoutPath, vectorIdx];
  const runRes = await runCmd(exePath, runArgs, repoRoot, env, "run");
  const elapsedS = (Date.now() - t0) / 1000;
  await writeFile(runLog, runRes.stdout + "\n" + runRes.stderr, "utf8");

  const summaryLine = runRes.stdout.split(/\r?\n/).find((l) => l.includes("[tb][resnet8][summary]"));
  if (!summaryLine) { console.error("[run] no [tb][resnet8][summary] line — sim crashed/timed out"); process.exit(6); }
  const m = (re: RegExp) => { const x = summaryLine.match(re); return x ? x[1] : null; };
  // e2e cycles: prefer the per-vec line for the selected vector (or vec0 in ALL mode).
  const e2eLine = runRes.stdout.split(/\r?\n/).find((l) => /\[vec\d+\] result=.* e2e_cycles=/.test(l));
  const e2eCycles = e2eLine ? Number((e2eLine.match(/e2e_cycles=(\d+)/) ?? [])[1] ?? -1) : -1;
  const result = {
    result: m(/result=(\w+)/),
    mismatch_bytes: Number(m(/mismatch_bytes=(-?\d+)/) ?? -1),
    first_mismatch_beat: Number(m(/first_mismatch_beat=(-?\d+)/) ?? -1),
    beats_seen: Number(m(/beats_seen=(\d+)\//) ?? -1),
    beats_expected: Number(m(/beats_seen=\d+\/(\d+)/) ?? -1),
    in_beats_seen: Number(m(/in_beats=(\d+)\//) ?? -1),
    in_beats_expected: Number(m(/in_beats=\d+\/(\d+)/) ?? -1),
    e2e_cycles: e2eCycles,
    vector_idx: Number(vectorIdx),
    sim_elapsed_s: elapsedS,
    goldin: path.relative(repoRoot, goldinPath),
    goldout: path.relative(repoRoot, goldoutPath),
  };
  await writeFile(resultJson, JSON.stringify(result, null, 2), "utf8");
  console.log(`[result] ${JSON.stringify(result)}`);
  console.log(`[result] wrote ${path.relative(repoRoot, resultJson)}`);
  process.exit(result.result === "PASS" ? 0 : 1);
}

main().catch((err: unknown) => {
  console.error(err instanceof Error ? err.stack ?? err.message : String(err));
  process.exit(1);
});
