// Build + run the Verilator END-TO-END VALUE testbench for the MobileNetV2
// all-spatial nn2rtl_top.v (output/mobilenet-v2/rtl/nn2rtl_top.v).
//
// Proves the assembled MobileNetV2 is byte-exact correct (not just correct beat
// counts). Feeds node_conv_810 .goldin (vec0 by default) into s_axis, captures
// the single m_axis output beat, compares to node_linear .goldout.
// See tb/mbv2_top_value_tb.cpp.
//
// RTL sources:
//   - all output/mobilenet-v2/rtl/*.v  (the top + 99 per-layer modules; the
//     wrapper-local stubs skip_fifo / uram_weight_bank / act_unified_mem /
//     bias_mem / engine_output_fifo / ... live inside nn2rtl_top.v itself)
//   - rtl_library/{conv_datapath.v, conv_datapath_parallel.v,
//                  conv_datapath_mp_k.v, coord_scheduler.v, line_buf_window.v}
//   - a GENERATED inactive stub for nn2rtl_scheduler + shared_engine (see below)
//
// Why generated stubs:
//   The mbv2 top instantiates `nn2rtl_scheduler` and `shared_engine`, but the
//   mbv2 build is ALL-SPATIAL: output/mobilenet-v2/scheduler_schedule_empty.json
//   has zero engine dispatches, so the engine handles 0 heavy modules and is
//   purely vestigial. Those two module *definitions* are NOT shipped in the
//   mbv2 rtl dir (the ResNet output/rtl/{nn2rtl_scheduler,shared_engine_skeleton}.v
//   have INCOMPATIBLE port widths — e.g. dispatch_idx_out[3:0] vs the mbv2
//   top's [0:0]). Rather than mutate the generated top, we synthesize minimal
//   stub modules whose outputs are tied to inactive values:
//     shared_engine : engine_busy=0, engine_done=0, all rd_en/addr=0, wr_en=0
//     scheduler     : spatial_stall=0, done=0, dispatch_idx_out=0, banks=0,
//                     AXI-Lite master idle
//   With engine_busy=0 and spatial_stall=0 the top's
//   `spatial_run = ~(engine_busy | sched_spatial_stall)` stays 1 forever, so
//   the pure spatial dataflow chain runs unthrottled — exactly the all-spatial
//   value path under test. The stub is written into the build dir (test
//   infrastructure, not pipeline RTL) and added to the Verilator source list.
//
// Usage:
//   npx tsx scripts/run_mbv2_top_value.ts [vector_idx]
//   env:
//     MBV2_VEC=<n>            override vector index (argv wins)
//     MBV2_ALL_VECS=1         run all 8 vectors (slow)
//     MBV2_MAX_CYCLES=<n>     per-frame cycle cap (deadlock fail-fast)
//     NN2RTL_VALUE_RUNONLY=1  reuse the existing exe (skip rebuild)
//     NN2RTL_DUMP_PATH=<p>    raw m_axis capture dump
//
// Output:
//   output/mobilenet-v2/reports/verilator_mbv2_top_value/
//     build.log  run.log  result.json
//
// NOTE: this script BUILDS then RUNS verilator. The build is RAM-sensitive
// (~99 RTL modules + the wide engine stub). The parent orchestrator decides
// when to invoke it; the script itself does not gate on RAM.

import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync } from "node:fs";
import { spawn } from "node:child_process";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

const mbv2Root  = path.join(repoRoot, "output", "mobilenet-v2");
const rtlDir    = path.join(mbv2Root, "rtl");
const goldenDir = path.join(mbv2Root, "goldens");
const tbCpp     = path.join(repoRoot, "tb", "mbv2_top_value_tb.cpp");
const outDir    = path.join(mbv2Root, "reports", "verilator_mbv2_top_value");
const buildLog  = path.join(outDir, "build.log");
const runLog    = path.join(outDir, "run.log");
const resultJson = path.join(outDir, "result.json");

const goldinPath  = path.join(goldenDir, "node_conv_810.goldin");
const goldoutPath = path.join(goldenDir, "node_linear.goldout");

const vectorIdx = process.argv[2] ?? "0";

const verilatorBin = process.platform === "win32"
  ? "C:/Users/User/oss-cad-suite/bin/verilator_bin.exe" : "verilator";
const makeBin = process.platform === "win32"
  ? "C:/Users/User/w64devkit/bin/make.exe" : "make";

function toForwardSlash(p: string): string { return p.replace(/\\/g, "/"); }

// Inactive stub for the vestigial engine + scheduler. Port widths MUST match
// the mbv2 nn2rtl_top.v instantiation (verified against the generated top:
// dispatch_idx_out[0:0], banks [2:0]/[5:0], engine act/weight/bias/scale buses
// at 16/22-bit addr, 2048/8192-bit data). All outputs are held at the
// power-on-safe inactive value so spatial_run stays high for the whole frame.
const ENGINE_SCHED_STUB = `// AUTO-GENERATED by scripts/run_mbv2_top_value.ts — DO NOT EDIT, DO NOT COMMIT.
// Inactive stubs for the all-spatial mbv2 top (empty engine schedule).
\`timescale 1ns/1ps

module nn2rtl_scheduler (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        start,
    output wire        done,
    // AXI4-Lite master to engine config_register_block (idle)
    output wire        s_axil_awvalid,
    input  wire        s_axil_awready,
    output wire [7:0]  s_axil_awaddr,
    output wire        s_axil_wvalid,
    input  wire        s_axil_wready,
    output wire [31:0] s_axil_wdata,
    output wire [3:0]  s_axil_wstrb,
    input  wire        s_axil_bvalid,
    output wire        s_axil_bready,
    input  wire [1:0]  s_axil_bresp,
    // Engine handshake
    output wire        engine_start,
    input  wire        engine_busy,
    input  wire        engine_done,
    input  wire        current_loaded,
    input  wire        current_drain_complete,
    output wire [0:0]  dispatch_idx_out,
    output wire [2:0]  input_bank_sel,
    output wire [2:0]  output_bank_sel,
    output wire [5:0]  skip_bank_reserved_mask,
    // Dataflow chain handshake — held inactive so spatial_run stays high
    output wire        spatial_stall,
    output wire        engine_output_ready
);
    assign done                    = 1'b0;
    assign s_axil_awvalid          = 1'b0;
    assign s_axil_awaddr           = 8'd0;
    assign s_axil_wvalid           = 1'b0;
    assign s_axil_wdata            = 32'd0;
    assign s_axil_wstrb            = 4'd0;
    assign s_axil_bready           = 1'b0;
    assign engine_start            = 1'b0;
    assign dispatch_idx_out        = 1'b0;
    assign input_bank_sel          = 3'd0;
    assign output_bank_sel         = 3'd0;
    assign skip_bank_reserved_mask = 6'd0;
    assign spatial_stall           = 1'b0;   // <-- never throttle the spatial chain
    assign engine_output_ready     = 1'b0;
    // unused inputs (silence lint): start, *_ready, *_valid, *_resp, engine_*, current_*
    wire _unused = &{1'b0, start, s_axil_awready, s_axil_wready, s_axil_bvalid,
                     s_axil_bresp, engine_busy, engine_done, current_loaded,
                     current_drain_complete, clk, rst_n};
endmodule

module shared_engine (
    input  wire           clk,
    input  wire           rst_n,
    // AXI4-Lite slave (driven by scheduler stub — held idle)
    input  wire           s_axil_awvalid,
    output wire           s_axil_awready,
    input  wire [7:0]     s_axil_awaddr,
    input  wire           s_axil_wvalid,
    output wire           s_axil_wready,
    input  wire [31:0]    s_axil_wdata,
    input  wire [3:0]     s_axil_wstrb,
    output wire           s_axil_bvalid,
    input  wire           s_axil_bready,
    output wire [1:0]     s_axil_bresp,
    input  wire           s_axil_arvalid,
    output wire           s_axil_arready,
    input  wire [7:0]     s_axil_araddr,
    output wire           s_axil_rvalid,
    input  wire           s_axil_rready,
    output wire [31:0]    s_axil_rdata,
    output wire [1:0]     s_axil_rresp,
    // Engine handshake — never busy, never done (0 heavy dispatches)
    input  wire           engine_start,
    output wire           engine_busy,
    output wire           engine_done,
    // Activation-in read port (unused)
    output wire [15:0]    act_in_rd_addr,
    output wire           act_in_rd_en,
    input  wire [2047:0]  act_in_rd_data,
    // Activation-out write port (unused)
    output wire [15:0]    act_out_wr_addr,
    output wire           act_out_wr_en,
    output wire [2047:0]  act_out_wr_data,
    // Weight read port (unused)
    output wire [21:0]    weight_rd_addr,
    output wire           weight_rd_en,
    input  wire [2047:0]  weight_rd_data,
    // Bias read port (unused)
    output wire [21:0]    bias_rd_addr,
    output wire           bias_rd_en,
    input  wire [8191:0]  bias_rd_data,
    // Scale read port (unused)
    output wire [21:0]    scale_rd_addr,
    output wire           scale_rd_en,
    input  wire [8191:0]  scale_rd_data
);
    assign s_axil_awready  = 1'b0;
    assign s_axil_wready   = 1'b0;
    assign s_axil_bvalid   = 1'b0;
    assign s_axil_bresp    = 2'b00;
    assign s_axil_arready   = 1'b0;
    assign s_axil_rvalid   = 1'b0;
    assign s_axil_rdata    = 32'd0;
    assign s_axil_rresp    = 2'b00;
    assign engine_busy     = 1'b0;   // <-- spatial_run = ~(engine_busy | spatial_stall) stays high
    assign engine_done     = 1'b0;
    assign act_in_rd_addr  = 16'd0;
    assign act_in_rd_en    = 1'b0;
    assign act_out_wr_addr = 16'd0;
    assign act_out_wr_en   = 1'b0;
    assign act_out_wr_data = 2048'd0;
    assign weight_rd_addr  = 22'd0;
    assign weight_rd_en    = 1'b0;
    assign bias_rd_addr    = 22'd0;
    assign bias_rd_en      = 1'b0;
    assign scale_rd_addr   = 22'd0;
    assign scale_rd_en     = 1'b0;
    wire _unused = &{1'b0, s_axil_awvalid, s_axil_awaddr, s_axil_wvalid, s_axil_wdata,
                     s_axil_wstrb, s_axil_bready, s_axil_arvalid, s_axil_araddr,
                     s_axil_rready, engine_start, act_in_rd_data, weight_rd_data,
                     bias_rd_data, scale_rd_data, clk, rst_n};
endmodule
`;

async function collectSources(stubPath: string): Promise<string[]> {
  // 5 rtl_library helpers (shared spatial datapath/scheduler primitives).
  const out: string[] = [
    path.join(repoRoot, "rtl_library", "conv_datapath.v"),
    path.join(repoRoot, "rtl_library", "conv_datapath_parallel.v"),
    path.join(repoRoot, "rtl_library", "conv_datapath_mp_k.v"),
    path.join(repoRoot, "rtl_library", "coord_scheduler.v"),
    path.join(repoRoot, "rtl_library", "line_buf_window.v"),
    // wave-2 tiled<->flat retile bridges (retile_gather / retile_scatter),
    // instantiated by the final-stage boundaries in nn2rtl_top.v.
    path.join(repoRoot, "rtl_library", "retile_bridge.v"),
    // generated inactive engine + scheduler stub
    stubPath,
  ];
  // all .v in the mbv2 rtl dir: the top + the 99 per-layer modules. Skip
  // .preimprove / failure-corpus snapshots — only the live rtl/*.v.
  const entries = await readdir(rtlDir);
  for (const entry of entries) {
    if (entry.endsWith(".v") && !entry.endsWith(".preimprove")) {
      out.push(path.join(rtlDir, entry));
    }
  }
  for (const p of out) if (!existsSync(p)) throw new Error(`source missing: ${p}`);
  return out;
}

function runCmd(cmd: string, args: string[], cwd: string, env: NodeJS.ProcessEnv, label: string): Promise<{ stdout: string; stderr: string; ok: boolean }> {
  console.log(`[${label}] ${cmd} ${args.slice(0, 6).join(" ")}${args.length > 6 ? " ... +" + (args.length - 6) + " args" : ""}`);
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { cwd, env, stdio: ["ignore", "pipe", "pipe"], shell: false });
    let stdout = ""; let stderr = "";
    child.stdout.on("data", (c) => { const s = c.toString(); stdout += s; process.stdout.write(s); });
    child.stderr.on("data", (c) => { const s = c.toString(); stderr += s; process.stderr.write(s); });
    child.on("close", (code) => resolve({ stdout, stderr, ok: code === 0 }));
    child.on("error", (err) => resolve({ stdout, stderr: stderr + "\n" + String(err), ok: false }));
  });
}

async function main(): Promise<void> {
  await mkdir(outDir, { recursive: true });
  if (existsSync(buildLog)) await rm(buildLog);
  if (existsSync(runLog)) await rm(runLog);

  if (!existsSync(goldinPath))  throw new Error(`goldin missing: ${goldinPath}`);
  if (!existsSync(goldoutPath)) throw new Error(`goldout missing: ${goldoutPath}`);
  if (!existsSync(tbCpp))       throw new Error(`testbench missing: ${tbCpp}`);
  console.log(`[setup] goldin : ${path.relative(repoRoot, goldinPath)}`);
  console.log(`[setup] goldout: ${path.relative(repoRoot, goldoutPath)}`);

  const buildDir = path.join(outDir, "obj_dir_value");
  const stubPath = path.join(buildDir, "engine_sched_stub.v");
  const env = { ...process.env, PATH: `C:/Users/User/oss-cad-suite/bin;C:/Users/User/w64devkit/bin;${process.env.PATH ?? ""}` };

  if (process.env.NN2RTL_VALUE_RUNONLY !== "1") {
    if (existsSync(buildDir)) {
      console.log(`[setup] clearing previous build dir ${buildDir}`);
      for (let attempt = 0; attempt < 5; attempt++) {
        try { await rm(buildDir, { recursive: true, force: true }); break; }
        catch (e: any) {
          if (attempt === 4) console.log(`[setup] rm failed after retries (${e.code}); proceeding`);
          else { console.log(`[setup] rm attempt ${attempt + 1} failed (${e.code}); retrying...`); await new Promise(r => setTimeout(r, 2000)); }
        }
      }
    }
    await mkdir(buildDir, { recursive: true });
    await writeFile(stubPath, ENGINE_SCHED_STUB, "utf8");
    console.log(`[setup] wrote inactive engine+scheduler stub ${path.relative(repoRoot, stubPath)}`);

    const sources = await collectSources(stubPath);
    console.log(`[setup] collected ${sources.length} RTL files; tb=${path.relative(repoRoot, tbCpp)}`);
    const verilatorArgs = [
      "--cc", "--exe", "-O3", "--threads", "4", "--top-module", "nn2rtl_top", "--Mdir", toForwardSlash(buildDir),
      "-CFLAGS", "-O2 -std=c++17 -DNDEBUG",
      "--x-initial", "0",   // force uninitialized state to 0 (FPGA power-on), hardware-faithful
      "-Wno-fatal",         // mbv2 modules carry benign lint; do not abort the build
      "-Wno-WIDTH", "-Wno-WIDTHEXPAND", "-Wno-WIDTHTRUNC", "-Wno-UNUSED", "-Wno-UNOPTFLAT", "-Wno-CASEINCOMPLETE",
      "-Wno-CASEX", "-Wno-COMBDLY", "-Wno-INITIALDLY", "-Wno-IMPLICIT", "-Wno-STMTDLY", "-Wno-MULTIDRIVEN",
      "-Wno-DECLFILENAME", "-Wno-EOFNEWLINE", "-Wno-PINMISSING", "-Wno-WIDTHCONCAT", "--replication-limit", "20000",
      ...sources.map(toForwardSlash), toForwardSlash(tbCpp),
    ];
    console.log(`[verilate] starting verilator (${sources.length} RTL sources, ~5-15 min)`);
    const verilateRes = await runCmd(verilatorBin, verilatorArgs, repoRoot, env, "verilate");
    await writeFile(buildLog, "--- verilator ---\n" + verilateRes.stdout + "\n" + verilateRes.stderr, "utf8");
    if (!verilateRes.ok) { console.error("[verilate] FAILED — see " + buildLog); process.exit(2); }
    console.log("[make] compiling generated C++ (10-30 min)");
    const makeRes = await runCmd(makeBin, ["-j", "16", "-f", "Vnn2rtl_top.mk", "Vnn2rtl_top"], buildDir, env, "make");
    await writeFile(buildLog, await readFile(buildLog, "utf8") + "\n--- make ---\n" + makeRes.stdout + "\n" + makeRes.stderr, "utf8");
    if (!makeRes.ok) { console.error("[make] FAILED — see " + buildLog); process.exit(3); }
  } else {
    console.log("[runonly] skipping build; reusing existing exe");
  }

  const exePath = path.join(buildDir, process.platform === "win32" ? "Vnn2rtl_top.exe" : "Vnn2rtl_top");
  if (!existsSync(exePath)) { console.error(`[run] expected exe not found: ${exePath}`); process.exit(4); }

  // CWD = repoRoot. The mbv2 $readmemh weight paths are ABSOLUTE so cwd does not
  // affect weight loading (unlike the ResNet engine which uses relative paths),
  // but we keep it consistent for any relative path that may appear later.
  console.log(`[run] launching ${exePath} vec=${vectorIdx}`);
  const t0 = Date.now();
  const dumpPath = process.env.NN2RTL_DUMP_PATH ?? "";  // argv[4]: raw m_axis capture dump
  const runArgs = dumpPath
    ? [goldinPath, goldoutPath, vectorIdx, dumpPath]
    : [goldinPath, goldoutPath, vectorIdx];
  const runRes = await runCmd(exePath, runArgs, repoRoot, env, "run");
  const elapsedS = (Date.now() - t0) / 1000;
  await writeFile(runLog, runRes.stdout + "\n" + runRes.stderr, "utf8");

  const summaryLine = runRes.stdout.split(/\r?\n/).find((l) => l.includes("[tb][mbv2][summary]"));
  if (!summaryLine) { console.error("[run] no [tb][mbv2][summary] line — sim crashed/timed out"); process.exit(6); }
  const m = (re: RegExp) => { const x = summaryLine.match(re); return x ? x[1] : null; };
  const result = {
    result: m(/result=(\w+)/),
    mismatch_bytes: Number(m(/mismatch_bytes=(-?\d+)/) ?? -1),
    first_mismatch_beat: Number(m(/first_mismatch_beat=(-?\d+)/) ?? -1),
    beats_seen: Number(m(/beats_seen=(\d+)\//) ?? -1),
    beats_expected: Number(m(/beats_seen=\d+\/(\d+)/) ?? -1),
    in_beats_seen: Number(m(/in_beats=(\d+)\//) ?? -1),
    in_beats_expected: Number(m(/in_beats=\d+\/(\d+)/) ?? -1),
    vector_idx: Number(vectorIdx),
    sim_elapsed_s: elapsedS,
    goldin: path.relative(repoRoot, goldinPath),
    goldout: path.relative(repoRoot, goldoutPath),
  };
  await writeFile(resultJson, JSON.stringify(result, null, 2), "utf8");
  console.log(`[result] ${JSON.stringify(result)}`);
  console.log(`[result] wrote ${path.relative(repoRoot, resultJson)}`);
  process.exit(result.result === "PASS" ? 0 : 1);
}

main().catch((err: unknown) => {
  console.error(err instanceof Error ? err.stack ?? err.message : String(err));
  process.exit(1);
});
