// ResNet-8 ENGINE-LESS (all-spatial) Vivado synth + full impl driver.
// Cloned from scripts/run_mbv2_synth.ts and adapted for the ZCU104 (xczu7ev),
// targeting the SAME part FINN used so the 3-way comparison row is apples-to-apples.
//
// Synthesises the byte-exact (e2e gate 8/8, 2,541,691 cyc) ResNet-8 top — the
// EXACT same source set that scripts/run_resnet8_top_value.ts (the Verilator e2e)
// compiles:
//   - output/resnet8/rtl/nn2rtl_top.v  (module nn2rtl_top — the ENGINE-LESS wrapper;
//     skip_fifo / frame_gate_fifo / uram_weight_bank / act_unified_mem / bias_mem /
//     engine_output_fifo / engine_output_bridge live INLINE inside this file)
//   - every per-layer module output/resnet8/rtl/node_*.v (21 of them)
//   - rtl_library/{conv_datapath,conv_datapath_parallel,conv_datapath_mp_k,
//                  coord_scheduler,line_buf_window,retile_bridge}.v
//   - a GENERATED INACTIVE stub for nn2rtl_scheduler + shared_engine (IDENTICAL to
//     the e2e build's ENGINE_SCHED_STUB) — NOT output/rtl/{nn2rtl_scheduler,
//     shared_engine_skeleton}.v (those are the ResNet-50/MBV2-modified shared files;
//     using them would change behaviour AND pull in the engine sub-blocks). The stub
//     ties engine_busy=0/spatial_stall=0 so the spatial chain runs the whole frame.
//
// $readmemh paths are rewritten to absolute so Vivado finds the weight .hex.
// The INERT engine path's MEM_INIT_FILE refs (uram_weights_bank*.mem / bias.mem /
// scale.mem) point at files that don't exist (the banks are DEPTH(0) degenerate, never
// read). We generate tiny zero-init placeholders for them so synth never aborts on a
// missing init file — byte-exactness is preserved (inert, unread, opt_design prunes).
//
// FLOW: synth_design -> opt_design -> place_design -> phys_opt_design -> route_design
//       -> report_utilization + report_timing_summary (post-route). ResNet-8 is tiny
//       (~FINN's 25K LUT class) so full impl is fast (~15-40 min).
//
// Per-stage checkpoints persist to output/resnet8/reports/synth/checkpoints/ so a
// timeout/kill is resumable.
//
// Usage:
//   NN2RTL_VIVADO_BIN=D:/vivado/2025.2/Vivado/bin/vivado.bat \
//   NN2RTL_RAM_KILL_PCT=90 \
//   npx tsx scripts/run_resnet8_synth.ts [--part=xczu7ev-ffvc1156-2-e] \
//        [--clock-ns=10] [--threads=8] [--synth-only]

import { readFile, writeFile, mkdir, copyFile, readdir, rm, rename } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync } from "node:fs";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import os from "node:os";

import {
  parseVivadoReport,
  resolveVivadoCommand,
  toVivadoPath,
  withTempDir,
  VIVADO_TIMEOUT_MS,
  VIVADO_MAX_BUFFER_BYTES,
  type VivadoSynthesisReport,
} from "../mcp/tools.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const rawArgs = process.argv.slice(2);

function flag(name: string, fallback?: string): string | undefined {
  const eq = rawArgs.find((a) => a.startsWith(`--${name}=`));
  if (eq) return eq.slice(name.length + 3);
  const idx = rawArgs.indexOf(`--${name}`);
  if (idx >= 0 && rawArgs[idx + 1] && !rawArgs[idx + 1].startsWith("--")) return rawArgs[idx + 1];
  return fallback;
}

// ZCU104 = xczu7ev-ffvc1156-2-e (the part FINN used). Speed grade -2.
const part = flag("part") ?? "xczu7ev-ffvc1156-2-e";
const clockNs = Number(flag("clock-ns") ?? "10");
const threads = Number(flag("threads") ?? "8");
const topModule = "nn2rtl_top";
const synthOnly = rawArgs.includes("--synth-only");
const flatten = flag("flatten") ?? "rebuilt";
// Optional synth_design -directive (e.g. RuntimeOptimized) to cut synthesis time on
// designs with pathological combinational cones (the fully-unrolled node_conv2d_2).
// Changes optimization EFFORT only, not function -> byte-exact.
const synthDirective = flag("synth-directive") ?? "";

const rtlDir = path.join(repoRoot, "output", "resnet8", "rtl");
const weightsDir = path.join(repoRoot, "output", "resnet8", "weights");
const reportsDir = path.join(repoRoot, "output", "resnet8", "reports", "synth");
const safeCheckpointDir = path.join(reportsDir, "checkpoints");
const jsonReportPath = path.join(reportsDir, "resnet8_synth.json");
const logPath = path.join(reportsDir, "resnet8_synth.log");

// INACTIVE engine + scheduler stub — byte-for-byte the SAME stub the e2e gate uses
// (scripts/run_resnet8_top_value.ts ENGINE_SCHED_STUB). Ties engine_busy=0 and
// spatial_stall=0 so spatial_run = ~(engine_busy | spatial_stall) stays high.
const ENGINE_SCHED_STUB = `// AUTO-GENERATED by scripts/run_resnet8_synth.ts — inactive engine+scheduler stub.
\`timescale 1ns/1ps

module nn2rtl_scheduler (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        start,
    output wire        done,
    output wire        s_axil_awvalid,
    input  wire        s_axil_awready,
    output wire [7:0]  s_axil_awaddr,
    output wire        s_axil_wvalid,
    input  wire        s_axil_wready,
    output wire [31:0] s_axil_wdata,
    output wire [3:0]  s_axil_wstrb,
    input  wire        s_axil_bvalid,
    output wire        s_axil_bready,
    input  wire [1:0]  s_axil_bresp,
    output wire        engine_start,
    input  wire        engine_busy,
    input  wire        engine_done,
    input  wire        current_loaded,
    input  wire        current_drain_complete,
    output wire [0:0]  dispatch_idx_out,
    output wire [2:0]  input_bank_sel,
    output wire [2:0]  output_bank_sel,
    output wire [5:0]  skip_bank_reserved_mask,
    output wire        spatial_stall,
    output wire        engine_output_ready
);
    assign done                    = 1'b0;
    assign s_axil_awvalid          = 1'b0;
    assign s_axil_awaddr           = 8'd0;
    assign s_axil_wvalid           = 1'b0;
    assign s_axil_wdata            = 32'd0;
    assign s_axil_wstrb            = 4'd0;
    assign s_axil_bready           = 1'b0;
    assign engine_start            = 1'b0;
    assign dispatch_idx_out        = 1'b0;
    assign input_bank_sel          = 3'd0;
    assign output_bank_sel         = 3'd0;
    assign skip_bank_reserved_mask = 6'd0;
    assign spatial_stall           = 1'b0;
    assign engine_output_ready     = 1'b0;
    wire _unused = &{1'b0, start, s_axil_awready, s_axil_wready, s_axil_bvalid,
                     s_axil_bresp, engine_busy, engine_done, current_loaded,
                     current_drain_complete, clk, rst_n};
endmodule

module shared_engine (
    input  wire           clk,
    input  wire           rst_n,
    input  wire           s_axil_awvalid,
    output wire           s_axil_awready,
    input  wire [7:0]     s_axil_awaddr,
    input  wire           s_axil_wvalid,
    output wire           s_axil_wready,
    input  wire [31:0]    s_axil_wdata,
    input  wire [3:0]     s_axil_wstrb,
    output wire           s_axil_bvalid,
    input  wire           s_axil_bready,
    output wire [1:0]     s_axil_bresp,
    input  wire           s_axil_arvalid,
    output wire           s_axil_arready,
    input  wire [7:0]     s_axil_araddr,
    output wire           s_axil_rvalid,
    input  wire           s_axil_rready,
    output wire [31:0]    s_axil_rdata,
    output wire [1:0]     s_axil_rresp,
    input  wire           engine_start,
    output wire           engine_busy,
    output wire           engine_done,
    output wire [15:0]    act_in_rd_addr,
    output wire           act_in_rd_en,
    input  wire [2047:0]  act_in_rd_data,
    output wire [15:0]    act_out_wr_addr,
    output wire           act_out_wr_en,
    output wire [2047:0]  act_out_wr_data,
    output wire [21:0]    weight_rd_addr,
    output wire           weight_rd_en,
    input  wire [2047:0]  weight_rd_data,
    output wire [21:0]    bias_rd_addr,
    output wire           bias_rd_en,
    input  wire [8191:0]  bias_rd_data,
    output wire [21:0]    scale_rd_addr,
    output wire           scale_rd_en,
    input  wire [8191:0]  scale_rd_data
);
    assign s_axil_awready  = 1'b0;
    assign s_axil_wready   = 1'b0;
    assign s_axil_bvalid   = 1'b0;
    assign s_axil_bresp    = 2'b00;
    assign s_axil_arready  = 1'b0;
    assign s_axil_rvalid   = 1'b0;
    assign s_axil_rdata    = 32'd0;
    assign s_axil_rresp    = 2'b00;
    assign engine_busy     = 1'b0;
    assign engine_done     = 1'b0;
    assign act_in_rd_addr  = 16'd0;
    assign act_in_rd_en    = 1'b0;
    assign act_out_wr_addr = 16'd0;
    assign act_out_wr_en   = 1'b0;
    assign act_out_wr_data = 2048'd0;
    assign weight_rd_addr  = 22'd0;
    assign weight_rd_en    = 1'b0;
    assign bias_rd_addr    = 22'd0;
    assign bias_rd_en      = 1'b0;
    assign scale_rd_addr   = 22'd0;
    assign scale_rd_en     = 1'b0;
    wire _unused = &{1'b0, s_axil_awvalid, s_axil_awaddr, s_axil_wvalid, s_axil_wdata,
                     s_axil_wstrb, s_axil_bready, s_axil_arvalid, s_axil_araddr,
                     s_axil_rready, engine_start, act_in_rd_data, weight_rd_data,
                     bias_rd_data, scale_rd_data, clk, rst_n};
endmodule
`;

function isExcludedRtl(entry: string): boolean {
  // only live rtl/*.v; the .prewire / .preimprove / .preadd87fix / .pretensor_perOC /
  // .prestride2 / .preparallel / .prefifo backups do NOT end in ".v" so the .endsWith(".v")
  // filter already drops them. Belt-and-suspenders: drop any backup-named file.
  if (!entry.endsWith(".v")) return true;
  if (/\.pre[a-z0-9_]*\.v$|\.bak/.test(entry)) return true;
  return false;
}

function tclQuote(value: string): string {
  return `"${toVivadoPath(value).replace(/(["$[\]])/g, "\\$1")}"`;
}

function convertReadmemhAbs(source: string, repoRootAbs: string): string {
  const fix = (p: string): string => toVivadoPath(path.isAbsolute(p) ? p : path.resolve(repoRootAbs, p));
  return source
    .replace(/(\$readmemh\s*\(\s*)"([^"]+)"/g, (_m, prefix: string, p: string) => `${prefix}"${fix(p)}"`)
    .replace(/(MEM_INIT_FILE\s*[=(]\s*)"([^"]+)"/g,
      (_m, prefix: string, p: string) => (p.length === 0 ? `${prefix}""` : `${prefix}"${fix(p)}"`));
}

async function collectSources(stubPath: string): Promise<string[]> {
  const out: string[] = [
    path.join(repoRoot, "rtl_library", "conv_datapath.v"),
    path.join(repoRoot, "rtl_library", "conv_datapath_parallel.v"),
    path.join(repoRoot, "rtl_library", "conv_datapath_mp_k.v"),
    path.join(repoRoot, "rtl_library", "coord_scheduler.v"),
    path.join(repoRoot, "rtl_library", "line_buf_window.v"),
    path.join(repoRoot, "rtl_library", "retile_bridge.v"),
    stubPath,
  ];
  const entries = await readdir(rtlDir);
  for (const entry of entries) {
    if (!isExcludedRtl(entry)) out.push(path.join(rtlDir, entry));
  }
  const tops = out.filter((p) => path.basename(p) === "nn2rtl_top.v");
  if (tops.length !== 1) throw new Error(`expected exactly nn2rtl_top.v, got: ${tops.map((p) => path.basename(p)).join(", ")}`);
  for (const p of out) if (!existsSync(p)) throw new Error(`source missing: ${p}`);
  return out;
}

function buildTcl(input: {
  verilogPaths: string[];
  utilReportPath: string;
  timingReportPath: string;
  checkpointPath: string;
}): string {
  const postRouteUtilPath = input.utilReportPath.replace(/_util\.rpt$/, "_postroute_util.rpt");
  const postRouteTimingPath = input.timingReportPath.replace(/_timing\.rpt$/, "_postroute_timing.rpt");
  const postRoutePowerPath = input.timingReportPath.replace(/_timing\.rpt$/, "_postroute_power.rpt");
  const placedUtilPath = input.utilReportPath.replace(/_util\.rpt$/, "_placed_util.rpt");
  const placedTimingPath = input.timingReportPath.replace(/_timing\.rpt$/, "_placed_timing.rpt");
  const synthDcpPath = input.checkpointPath.replace(/\.dcp$/, "_synth.dcp");
  const optDcpPath = input.checkpointPath.replace(/\.dcp$/, "_opt.dcp");
  const placedDcpPath = input.checkpointPath.replace(/\.dcp$/, "_placed.dcp");
  const physoptDcpPath = input.checkpointPath.replace(/\.dcp$/, "_physopt.dcp");
  return [
    `set_param general.maxThreads ${threads}`,
    `puts "NN2RTL_INFO: maxThreads requested=${threads} effective=[get_param general.maxThreads]"`,
    `read_verilog -sv ${input.verilogPaths.map(tclQuote).join(" \\\n                 ")}`,
    `puts "NN2RTL_INFO: auto_detect_xpm"`,
    `auto_detect_xpm`,
    `puts "NN2RTL_INFO: synth_design (define NN2RTL_SYNTHESIS=1) top=${topModule} part=${part}"`,
    `synth_design -top ${topModule} -part ${part} -flatten_hierarchy ${flatten}${synthDirective ? ` -directive ${synthDirective}` : ""} -verilog_define NN2RTL_SYNTHESIS=1`,
    `create_clock -name clk -period ${clockNs} [get_ports clk]`,
    `puts "NN2RTL_INFO: synth-level utilization (saved + mirrored)"`,
    `report_utilization -file ${tclQuote(input.utilReportPath + ".synth")}`,
    `report_utilization -hierarchical -hierarchical_depth 3 -file ${tclQuote(input.utilReportPath + ".synth.hier")}`,
    `puts "NN2RTL_INFO: write SYNTH checkpoint"`,
    `write_checkpoint -force ${tclQuote(synthDcpPath)}`,
    ...(synthOnly
      ? [
          `file copy -force ${tclQuote(input.utilReportPath + ".synth")} ${tclQuote(input.utilReportPath)}`,
          `puts "NN2RTL_INFO: --synth-only complete (no opt/place/route)"`,
        ]
      : [
          `puts "NN2RTL_INFO: opt_design"`,
          `opt_design`,
          `write_checkpoint -force ${tclQuote(optDcpPath)}`,
          `puts "NN2RTL_INFO: place_design"`,
          `place_design`,
          `write_checkpoint -force ${tclQuote(placedDcpPath)}`,
          `report_utilization -file ${tclQuote(placedUtilPath)}`,
          `report_timing_summary -max_paths 10 -file ${tclQuote(placedTimingPath)}`,
          `puts "NN2RTL_INFO: phys_opt_design (pre-route)"`,
          `catch { phys_opt_design }`,
          `write_checkpoint -force ${tclQuote(physoptDcpPath)}`,
          `puts "NN2RTL_INFO: route_design"`,
          `route_design`,
          `write_checkpoint -force ${tclQuote(input.checkpointPath)}`,
          `puts "NN2RTL_INFO: post-route phys_opt_design (hold/setup cleanup)"`,
          `catch { phys_opt_design }`,
          `write_checkpoint -force ${tclQuote(input.checkpointPath)}`,
          `report_utilization -file ${tclQuote(postRouteUtilPath)}`,
          `report_timing_summary -check_timing_verbose -max_paths 20 -file ${tclQuote(postRouteTimingPath)}`,
          `catch { report_power -file ${tclQuote(postRoutePowerPath)} }`,
          `catch { file copy -force ${tclQuote(postRouteUtilPath)} ${tclQuote(input.utilReportPath)} }`,
          `catch { file copy -force ${tclQuote(postRouteTimingPath)} ${tclQuote(input.timingReportPath)} }`,
          `puts "NN2RTL_INFO: read_checkpoint sanity (routed dcp re-open)"`,
          `catch { read_checkpoint ${tclQuote(input.checkpointPath)} } rcerr; if {$rcerr ne ""} { puts "NN2RTL_WARN: routed dcp re-open FAILED: $rcerr" } else { puts "NN2RTL_INFO: routed dcp re-open OK" }`,
          `puts "NN2RTL_INFO: full flow complete"`,
        ]),
  ].join("\n") + "\n";
}

const execFileP = promisify(execFile);

async function main(): Promise<void> {
  await mkdir(reportsDir, { recursive: true });
  await mkdir(safeCheckpointDir, { recursive: true });

  for (const stale of ["resnet8_post_synth.dcp", "resnet8_post_opt.dcp", "resnet8_post_placed.dcp", "resnet8_post_routed.dcp"]) {
    const p = path.join(safeCheckpointDir, stale);
    if (existsSync(p)) { await rm(p, { force: true }); console.log(`[resnet8-synth] cleared stale ${stale}`); }
  }
  for (const stale of ["resnet8_util.rpt.synth", "resnet8_util.rpt.synth.hier", "resnet8_placed_util.rpt",
    "resnet8_placed_timing.rpt", "resnet8_postroute_util.rpt", "resnet8_postroute_timing.rpt"]) {
    const p = path.join(reportsDir, stale);
    if (existsSync(p)) { await rm(p, { force: true }); }
  }

  const report = await withTempDir("nn2rtl-resnet8synth-", async (tempDir) => {
    // 1) write the inactive engine+scheduler stub into the tempdir
    const stubPath = path.join(tempDir, "engine_sched_stub.v");
    await writeFile(stubPath, ENGINE_SCHED_STUB, "utf8");

    const sources = await collectSources(stubPath);
    console.log(`[resnet8-synth] collected ${sources.length} source files`);
    console.log(`[resnet8-synth] top=${topModule} part=${part} clock_ns=${clockNs} threads=${threads} synthOnly=${synthOnly}`);

    const copiedPaths: string[] = [];
    for (const src of sources) {
      const dest = path.join(tempDir, path.basename(src));
      if (src === stubPath) { copiedPaths.push(dest); continue; }
      const text = await readFile(src, "utf8");
      await writeFile(dest, convertReadmemhAbs(text, repoRoot), "utf8");
      copiedPaths.push(dest);
    }

    // 2) belt-and-suspenders: copy weight .hex/.mem into tempdir (basename-relative lookups)
    if (existsSync(weightsDir)) {
      const mems = (await readdir(weightsDir)).filter((f) => f.endsWith(".mem") || f.endsWith(".hex"));
      for (const m of mems) await copyFile(path.join(weightsDir, m), path.join(tempDir, m));
      console.log(`[resnet8-synth] copied ${mems.length} weight .mem/.hex into tempdir`);
    }

    // 3) The INERT engine path references uram_weights_bank*.mem / bias.mem / scale.mem that
    //    don't exist (the URAM banks are DEPTH(0) degenerate, never read). Generate tiny
    //    zero-init placeholders in BOTH output/resnet8/weights/ (the rewritten absolute path)
    //    and the tempdir so neither XPM MEMORY_INIT_FILE nor $readmemh aborts synth. Inert =>
    //    byte-exactness preserved; opt_design prunes the unread banks.
    const placeholderMems = [
      "uram_weights_bank0.mem", "uram_weights_bank1.mem", "uram_weights_bank2.mem", "uram_weights_bank3.mem",
      "uram_weights_bank4.mem", "uram_weights_bank5.mem", "uram_weights_bank6.mem", "uram_weights_bank7.mem",
      "bias.mem", "scale.mem",
    ];
    for (const m of placeholderMems) {
      const live = path.join(weightsDir, m);
      if (!existsSync(live)) { await writeFile(live, "0\n", "utf8"); console.log(`[resnet8-synth] generated zero-init placeholder ${m}`); }
      await copyFile(live, path.join(tempDir, m)).catch(() => {});
    }

    const utilReportPath = path.join(tempDir, "resnet8_util.rpt");
    const timingReportPath = path.join(tempDir, "resnet8_timing.rpt");
    const checkpointPath = path.join(tempDir, "resnet8.dcp");
    const tclPath = path.join(tempDir, "resnet8_synth.tcl");
    await writeFile(tclPath, buildTcl({ verilogPaths: copiedPaths, utilReportPath, timingReportPath, checkpointPath }), "utf8");

    const vivadoBin = resolveVivadoCommand(process.env);
    const vivadoArgs = ["-mode", "batch", "-source", toVivadoPath(tclPath), "-notrace"];
    const isWindowsBatch = process.platform === "win32" && /\.(bat|cmd)$/i.test(vivadoBin);
    const spawnFile = isWindowsBatch ? "cmd.exe" : vivadoBin;
    const spawnArgs = isWindowsBatch ? ["/c", vivadoBin, ...vivadoArgs] : vivadoArgs;
    console.log(`[resnet8-synth] launching: ${spawnFile} ${spawnArgs.join(" ")}`);

    const timeoutMs = (() => {
      const e = process.env.NN2RTL_VIVADO_TIMEOUT_MS;
      return e && Number.isFinite(Number(e)) && Number(e) > 0 ? Number(e) : VIVADO_TIMEOUT_MS;
    })();
    console.log(`[resnet8-synth] timeout=${(timeoutMs / 3600000).toFixed(1)}h`);

    const dcpMap = [
      { src: checkpointPath.replace(/\.dcp$/, "_synth.dcp"), dst: "resnet8_post_synth.dcp" },
      { src: checkpointPath.replace(/\.dcp$/, "_opt.dcp"), dst: "resnet8_post_opt.dcp" },
      { src: checkpointPath.replace(/\.dcp$/, "_placed.dcp"), dst: "resnet8_post_placed.dcp" },
      { src: checkpointPath, dst: "resnet8_post_routed.dcp" },
    ];
    const reportNames = ["resnet8_util.rpt.synth", "resnet8_util.rpt.synth.hier", "resnet8_placed_util.rpt",
      "resnet8_placed_timing.rpt", "resnet8_postroute_util.rpt", "resnet8_postroute_timing.rpt",
      "resnet8_postroute_power.rpt", "vivado.log", "vivado.jou"];
    let polling = true;
    const persist = async (force = false) => {
      for (const { src, dst } of dcpMap) {
        const d = path.join(safeCheckpointDir, dst);
        if (existsSync(src) && (force || !existsSync(d))) {
          try { const tmp = d + ".tmp"; await copyFile(src, tmp); await rename(tmp, d); console.log(`[resnet8-synth] persisted ${dst}${force ? " (final)" : ""}`); } catch { /* mid-write */ }
        }
      }
      for (const r of reportNames) {
        const s = path.join(tempDir, r), d = path.join(reportsDir, r);
        const alwaysRefresh = r === "vivado.log" || r === "vivado.jou";
        if (existsSync(s) && (alwaysRefresh || !existsSync(d))) { try { await copyFile(s, d); } catch { /* mid-write */ } }
      }
    };
    const poller = (async () => { while (polling) { await persist(); await new Promise((r) => setTimeout(r, 30000)); } })();

    const t0 = Date.now();
    let stdout = "", stderr = "", exitOk = true;
    let ramKillMsg = "";
    {
      const ramKillPct = (() => {
        const v = Number(process.env.NN2RTL_RAM_KILL_PCT);
        return Number.isFinite(v) && v > 0 && v < 100 ? v : 90;
      })();
      const totalMem = os.totalmem();
      console.log(
        `[resnet8-synth] RAM watchdog armed: kill at >= ${ramKillPct}% used ` +
          `(total ${(totalMem / 1073741824).toFixed(1)}GB, poll 4s)`,
      );
      const res = await new Promise<{ stdout: string; stderr: string; ok: boolean }>((resolve) => {
        const child = execFile(
          spawnFile,
          spawnArgs,
          { cwd: tempDir, env: process.env, timeout: timeoutMs, maxBuffer: VIVADO_MAX_BUFFER_BYTES },
          (err, soCb, seCb) => {
            clearInterval(poll);
            const so = typeof soCb === "string" ? soCb : (soCb?.toString() ?? "");
            const se = typeof seCb === "string" ? seCb : (seCb?.toString() ?? (err as Error | null)?.message ?? "");
            resolve({ stdout: so, stderr: se, ok: !err && !ramKillMsg });
          },
        );
        const poll = setInterval(() => {
          const freeGB = os.freemem() / 1073741824;
          const usedPct = (1 - os.freemem() / totalMem) * 100;
          if (usedPct >= ramKillPct && !ramKillMsg) {
            ramKillMsg =
              `[resnet8-synth][WATCHDOG] RAM ${usedPct.toFixed(1)}% used >= ${ramKillPct}% ` +
              `(free ${freeGB.toFixed(1)}GB) — KILLING Vivado tree (pid ${child.pid}); resume from latest resnet8_post_*.dcp`;
            console.error(ramKillMsg);
            clearInterval(poll);
            try { if (child.pid) execFileP("taskkill", ["/PID", String(child.pid), "/T", "/F"]).catch(() => {}); } catch { /* ignore */ }
            try { execFileP("taskkill", ["/IM", "vivado.exe", "/T", "/F"]).catch(() => {}); } catch { /* ignore */ }
          }
        }, 4000);
      });
      stdout = res.stdout; stderr = res.stderr; exitOk = res.ok;
    }
    polling = false; await poller; await persist(true);
    const elapsed = (Date.now() - t0) / 1000;
    console.log(`[resnet8-synth] vivado returned in ${elapsed.toFixed(1)}s (ok=${exitOk}${ramKillMsg ? ", RAM-KILLED" : ""})`);

    const utilReport = existsSync(utilReportPath) ? await readFile(utilReportPath, "utf8")
      : (existsSync(path.join(reportsDir, "resnet8_util.rpt.synth")) ? await readFile(path.join(reportsDir, "resnet8_util.rpt.synth"), "utf8") : "");
    const timingReport = existsSync(timingReportPath) ? await readFile(timingReportPath, "utf8") : "";
    const combined = [ramKillMsg, stdout, stderr, "--- util ---", utilReport, "--- timing ---", timingReport].filter(Boolean).join("\n");
    await writeFile(logPath, combined, "utf8");
    const parsed = parseVivadoReport(combined, clockNs, part);
    parsed.success = exitOk && parsed.success;
    return { ...parsed, elapsed_s: elapsed };
  });

  await writeFile(jsonReportPath, JSON.stringify(report, null, 2), "utf8");
  console.log(`[resnet8-synth] wrote ${path.relative(repoRoot, jsonReportPath)}`);
  const r = report as VivadoSynthesisReport & { elapsed_s: number };
  console.log(`[resnet8-synth] success=${report.success} LUT=${report.lut_count} FF=${report.ff_count} DSP=${report.dsp_count} BRAM36=${report.bram36_count} WNS=${report.setup_wns_ns ?? "n/a"} elapsed=${r.elapsed_s.toFixed(0)}s`);
  if (!report.success) { console.error("[resnet8-synth] FAILED/incomplete — see log + checkpoints"); process.exit(2); }
}

main().catch((err) => {
  console.error("[resnet8-synth] FATAL:", err instanceof Error ? (err.stack ?? err.message) : String(err));
  process.exit(1);
});
