// Auto-generated by scripts/build_scheduler.py - DO NOT EDIT.
// Deterministic scheduler FSM for nn2rtl shared-engine dispatch.
// Number of engine dispatches: 17
// Register map source-of-truth: docs/agent_tasks/10_engine_config_register_block.md

module nn2rtl_scheduler (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        start,
    output reg         done,
    // AXI4-Lite master to engine config_register_block
    output reg         s_axil_awvalid,
    input  wire        s_axil_awready,
    output reg  [7:0]  s_axil_awaddr,
    output reg         s_axil_wvalid,
    input  wire        s_axil_wready,
    output reg  [31:0] s_axil_wdata,
    output reg  [3:0]  s_axil_wstrb,
    input  wire        s_axil_bvalid,
    output reg         s_axil_bready,
    input  wire [1:0]  s_axil_bresp,
    // Engine handshake
    output reg         engine_start,
    input  wire        engine_busy,
    input  wire        engine_done,
    // Per-dispatch input-loader handshake (Fix 11): the wrapper
    // muxes the active dispatch's loaded signal here. The
    // scheduler waits on it in S_WAIT_LOAD before pulsing
    // CONTROL.start, so the engine never reads from a
    // half-filled activation BRAM.
    input  wire        current_loaded,
    // Per-dispatch output-FIFO drain handshake (Fix 14): the
    // engine writes its outputs into a shared FIFO; each
    // dispatch's bridge drains the expected number of beats.
    // The scheduler waits in S_WAIT_DRAIN until this asserts,
    // so dispatch N+1 cannot start while dispatch N's beats
    // still sit in the FIFO (which would interleave them).
    input  wire        current_drain_complete,
    // Dispatch index exposed so the wrapper's loaded-mux can
    // select the correct per-dispatch loaded signal.
    output wire [4:0] dispatch_idx_out,
    // Activation BRAM bank selection
    output reg  [2:0] input_bank_sel,
    output reg  [2:0] output_bank_sel,
    output reg  [5:0] skip_bank_reserved_mask,
    // Dataflow chain handshake
    output reg         spatial_stall,
    output reg         engine_output_ready
);

    // ------------------------------------------------------------
    // FSM state encoding
    // ------------------------------------------------------------
    localparam [3:0] S_IDLE        = 4'd0;
    localparam [3:0] S_WRITE       = 4'd1;
    localparam [3:0] S_WRITE_RESP  = 4'd3;
    localparam [3:0] S_NEXT_STEP   = 4'd4;
    localparam [3:0] S_WAIT_LOAD   = 4'd9;   // Fix 11: wait for input loader before starting engine
    localparam [3:0] S_PULSE_START = 4'd5;
    localparam [3:0] S_WAIT_DONE   = 4'd6;
    localparam [3:0] S_WAIT_DRAIN  = 4'd10;  // Fix 14: wait for engine_output_fifo to drain
    localparam [3:0] S_NEXT_DISP   = 4'd7;
    localparam [3:0] S_DONE        = 4'd8;

    reg aw_acked_r, w_acked_r;

    reg [3:0]           state, next_state;
    reg [4:0] dispatch_idx;
    assign dispatch_idx_out = dispatch_idx;
    reg [3:0] write_step;
    localparam [4:0] LAST_DISPATCH = 5'd16;
    localparam [3:0] LAST_STEP     = 4'd12;

    reg [15:0] channel_in_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: channel_in_rom = 16'd256;
            5'd1: channel_in_rom = 16'd512;
            5'd2: channel_in_rom = 16'd256;
            5'd3: channel_in_rom = 16'd256;
            5'd4: channel_in_rom = 16'd1024;
            5'd5: channel_in_rom = 16'd256;
            5'd6: channel_in_rom = 16'd256;
            5'd7: channel_in_rom = 16'd256;
            5'd8: channel_in_rom = 16'd1024;
            5'd9: channel_in_rom = 16'd512;
            5'd10: channel_in_rom = 16'd512;
            5'd11: channel_in_rom = 16'd2048;
            5'd12: channel_in_rom = 16'd512;
            5'd13: channel_in_rom = 16'd512;
            5'd14: channel_in_rom = 16'd2048;
            5'd15: channel_in_rom = 16'd512;
            5'd16: channel_in_rom = 16'd512;
            default: channel_in_rom = 16'd0;
        endcase
    end

    reg [15:0] channel_out_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: channel_out_rom = 16'd256;
            5'd1: channel_out_rom = 16'd1024;
            5'd2: channel_out_rom = 16'd256;
            5'd3: channel_out_rom = 16'd256;
            5'd4: channel_out_rom = 16'd256;
            5'd5: channel_out_rom = 16'd256;
            5'd6: channel_out_rom = 16'd256;
            5'd7: channel_out_rom = 16'd256;
            5'd8: channel_out_rom = 16'd512;
            5'd9: channel_out_rom = 16'd512;
            5'd10: channel_out_rom = 16'd2048;
            5'd11: channel_out_rom = 16'd512;
            5'd12: channel_out_rom = 16'd512;
            5'd13: channel_out_rom = 16'd2048;
            5'd14: channel_out_rom = 16'd512;
            5'd15: channel_out_rom = 16'd512;
            5'd16: channel_out_rom = 16'd2048;
            default: channel_out_rom = 16'd0;
        endcase
    end

    reg [3:0] kernel_h_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: kernel_h_rom = 4'd3;
            5'd1: kernel_h_rom = 4'd1;
            5'd2: kernel_h_rom = 4'd3;
            5'd3: kernel_h_rom = 4'd3;
            5'd4: kernel_h_rom = 4'd1;
            5'd5: kernel_h_rom = 4'd3;
            5'd6: kernel_h_rom = 4'd3;
            5'd7: kernel_h_rom = 4'd3;
            5'd8: kernel_h_rom = 4'd1;
            5'd9: kernel_h_rom = 4'd3;
            5'd10: kernel_h_rom = 4'd1;
            5'd11: kernel_h_rom = 4'd1;
            5'd12: kernel_h_rom = 4'd3;
            5'd13: kernel_h_rom = 4'd1;
            5'd14: kernel_h_rom = 4'd1;
            5'd15: kernel_h_rom = 4'd3;
            5'd16: kernel_h_rom = 4'd1;
            default: kernel_h_rom = 4'd0;
        endcase
    end

    reg [3:0] kernel_w_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: kernel_w_rom = 4'd3;
            5'd1: kernel_w_rom = 4'd1;
            5'd2: kernel_w_rom = 4'd3;
            5'd3: kernel_w_rom = 4'd3;
            5'd4: kernel_w_rom = 4'd1;
            5'd5: kernel_w_rom = 4'd3;
            5'd6: kernel_w_rom = 4'd3;
            5'd7: kernel_w_rom = 4'd3;
            5'd8: kernel_w_rom = 4'd1;
            5'd9: kernel_w_rom = 4'd3;
            5'd10: kernel_w_rom = 4'd1;
            5'd11: kernel_w_rom = 4'd1;
            5'd12: kernel_w_rom = 4'd3;
            5'd13: kernel_w_rom = 4'd1;
            5'd14: kernel_w_rom = 4'd1;
            5'd15: kernel_w_rom = 4'd3;
            5'd16: kernel_w_rom = 4'd1;
            default: kernel_w_rom = 4'd0;
        endcase
    end

    reg [2:0] stride_h_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: stride_h_rom = 3'd2;
            5'd1: stride_h_rom = 3'd2;
            5'd2: stride_h_rom = 3'd1;
            5'd3: stride_h_rom = 3'd1;
            5'd4: stride_h_rom = 3'd1;
            5'd5: stride_h_rom = 3'd1;
            5'd6: stride_h_rom = 3'd1;
            5'd7: stride_h_rom = 3'd1;
            5'd8: stride_h_rom = 3'd1;
            5'd9: stride_h_rom = 3'd2;
            5'd10: stride_h_rom = 3'd1;
            5'd11: stride_h_rom = 3'd1;
            5'd12: stride_h_rom = 3'd1;
            5'd13: stride_h_rom = 3'd1;
            5'd14: stride_h_rom = 3'd1;
            5'd15: stride_h_rom = 3'd1;
            5'd16: stride_h_rom = 3'd1;
            default: stride_h_rom = 3'd0;
        endcase
    end

    reg [2:0] stride_w_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: stride_w_rom = 3'd2;
            5'd1: stride_w_rom = 3'd2;
            5'd2: stride_w_rom = 3'd1;
            5'd3: stride_w_rom = 3'd1;
            5'd4: stride_w_rom = 3'd1;
            5'd5: stride_w_rom = 3'd1;
            5'd6: stride_w_rom = 3'd1;
            5'd7: stride_w_rom = 3'd1;
            5'd8: stride_w_rom = 3'd1;
            5'd9: stride_w_rom = 3'd2;
            5'd10: stride_w_rom = 3'd1;
            5'd11: stride_w_rom = 3'd1;
            5'd12: stride_w_rom = 3'd1;
            5'd13: stride_w_rom = 3'd1;
            5'd14: stride_w_rom = 3'd1;
            5'd15: stride_w_rom = 3'd1;
            5'd16: stride_w_rom = 3'd1;
            default: stride_w_rom = 3'd0;
        endcase
    end

    reg [2:0] padding_h_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: padding_h_rom = 3'd1;
            5'd1: padding_h_rom = 3'd0;
            5'd2: padding_h_rom = 3'd1;
            5'd3: padding_h_rom = 3'd1;
            5'd4: padding_h_rom = 3'd0;
            5'd5: padding_h_rom = 3'd1;
            5'd6: padding_h_rom = 3'd1;
            5'd7: padding_h_rom = 3'd1;
            5'd8: padding_h_rom = 3'd0;
            5'd9: padding_h_rom = 3'd1;
            5'd10: padding_h_rom = 3'd0;
            5'd11: padding_h_rom = 3'd0;
            5'd12: padding_h_rom = 3'd1;
            5'd13: padding_h_rom = 3'd0;
            5'd14: padding_h_rom = 3'd0;
            5'd15: padding_h_rom = 3'd1;
            5'd16: padding_h_rom = 3'd0;
            default: padding_h_rom = 3'd0;
        endcase
    end

    reg [2:0] padding_w_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: padding_w_rom = 3'd1;
            5'd1: padding_w_rom = 3'd0;
            5'd2: padding_w_rom = 3'd1;
            5'd3: padding_w_rom = 3'd1;
            5'd4: padding_w_rom = 3'd0;
            5'd5: padding_w_rom = 3'd1;
            5'd6: padding_w_rom = 3'd1;
            5'd7: padding_w_rom = 3'd1;
            5'd8: padding_w_rom = 3'd0;
            5'd9: padding_w_rom = 3'd1;
            5'd10: padding_w_rom = 3'd0;
            5'd11: padding_w_rom = 3'd0;
            5'd12: padding_w_rom = 3'd1;
            5'd13: padding_w_rom = 3'd0;
            5'd14: padding_w_rom = 3'd0;
            5'd15: padding_w_rom = 3'd1;
            5'd16: padding_w_rom = 3'd0;
            default: padding_w_rom = 3'd0;
        endcase
    end

    reg [8:0] input_h_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: input_h_rom = 9'd28;
            5'd1: input_h_rom = 9'd28;
            5'd2: input_h_rom = 9'd14;
            5'd3: input_h_rom = 9'd14;
            5'd4: input_h_rom = 9'd14;
            5'd5: input_h_rom = 9'd14;
            5'd6: input_h_rom = 9'd14;
            5'd7: input_h_rom = 9'd14;
            5'd8: input_h_rom = 9'd14;
            5'd9: input_h_rom = 9'd14;
            5'd10: input_h_rom = 9'd7;
            5'd11: input_h_rom = 9'd7;
            5'd12: input_h_rom = 9'd7;
            5'd13: input_h_rom = 9'd7;
            5'd14: input_h_rom = 9'd7;
            5'd15: input_h_rom = 9'd7;
            5'd16: input_h_rom = 9'd7;
            default: input_h_rom = 9'd0;
        endcase
    end

    reg [8:0] input_w_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: input_w_rom = 9'd28;
            5'd1: input_w_rom = 9'd28;
            5'd2: input_w_rom = 9'd14;
            5'd3: input_w_rom = 9'd14;
            5'd4: input_w_rom = 9'd14;
            5'd5: input_w_rom = 9'd14;
            5'd6: input_w_rom = 9'd14;
            5'd7: input_w_rom = 9'd14;
            5'd8: input_w_rom = 9'd14;
            5'd9: input_w_rom = 9'd14;
            5'd10: input_w_rom = 9'd7;
            5'd11: input_w_rom = 9'd7;
            5'd12: input_w_rom = 9'd7;
            5'd13: input_w_rom = 9'd7;
            5'd14: input_w_rom = 9'd7;
            5'd15: input_w_rom = 9'd7;
            5'd16: input_w_rom = 9'd7;
            default: input_w_rom = 9'd0;
        endcase
    end

    reg [8:0] output_h_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: output_h_rom = 9'd14;
            5'd1: output_h_rom = 9'd14;
            5'd2: output_h_rom = 9'd14;
            5'd3: output_h_rom = 9'd14;
            5'd4: output_h_rom = 9'd14;
            5'd5: output_h_rom = 9'd14;
            5'd6: output_h_rom = 9'd14;
            5'd7: output_h_rom = 9'd14;
            5'd8: output_h_rom = 9'd14;
            5'd9: output_h_rom = 9'd7;
            5'd10: output_h_rom = 9'd7;
            5'd11: output_h_rom = 9'd7;
            5'd12: output_h_rom = 9'd7;
            5'd13: output_h_rom = 9'd7;
            5'd14: output_h_rom = 9'd7;
            5'd15: output_h_rom = 9'd7;
            5'd16: output_h_rom = 9'd7;
            default: output_h_rom = 9'd0;
        endcase
    end

    reg [8:0] output_w_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: output_w_rom = 9'd14;
            5'd1: output_w_rom = 9'd14;
            5'd2: output_w_rom = 9'd14;
            5'd3: output_w_rom = 9'd14;
            5'd4: output_w_rom = 9'd14;
            5'd5: output_w_rom = 9'd14;
            5'd6: output_w_rom = 9'd14;
            5'd7: output_w_rom = 9'd14;
            5'd8: output_w_rom = 9'd14;
            5'd9: output_w_rom = 9'd7;
            5'd10: output_w_rom = 9'd7;
            5'd11: output_w_rom = 9'd7;
            5'd12: output_w_rom = 9'd7;
            5'd13: output_w_rom = 9'd7;
            5'd14: output_w_rom = 9'd7;
            5'd15: output_w_rom = 9'd7;
            5'd16: output_w_rom = 9'd7;
            default: output_w_rom = 9'd0;
        endcase
    end

    reg [19:0] weight_base_word_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: weight_base_word_rom = 20'd0;  // [K5-DEDUP] was 11155 (pre-dedup)
            5'd1: weight_base_word_rom = 20'd2304;  // [K5-DEDUP] was 14483 (pre-dedup)
            5'd2: weight_base_word_rom = 20'd4352;  // [K5-DEDUP] was 17555 (pre-dedup)
            5'd3: weight_base_word_rom = 20'd6656;  // [K5-DEDUP] was 21907 (pre-dedup)
            5'd4: weight_base_word_rom = 20'd8960;  // [K5-DEDUP] was 25235 (pre-dedup)
            5'd5: weight_base_word_rom = 20'd9984;  // [K5-DEDUP] was 26259 (pre-dedup)
            5'd6: weight_base_word_rom = 20'd12288;  // [K5-DEDUP] was 30611 (pre-dedup)
            5'd7: weight_base_word_rom = 20'd14592;  // [K5-DEDUP] was 34963 (pre-dedup)
            5'd8: weight_base_word_rom = 20'd16896;  // [K5-DEDUP] was 38291 (pre-dedup)
            5'd9: weight_base_word_rom = 20'd18944;  // [K5-DEDUP] was 40339 (pre-dedup)
            5'd10: weight_base_word_rom = 20'd28160;  // [K5-DEDUP] was 49555 (pre-dedup)
            5'd11: weight_base_word_rom = 20'd32256;  // [K5-DEDUP] was 61843 (pre-dedup)
            5'd12: weight_base_word_rom = 20'd36352;  // [K5-DEDUP] was 65939 (pre-dedup)
            5'd13: weight_base_word_rom = 20'd45568;  // [K5-DEDUP] was 75155 (pre-dedup)
            5'd14: weight_base_word_rom = 20'd49664;  // [K5-DEDUP] was 79251 (pre-dedup)
            5'd15: weight_base_word_rom = 20'd53760;  // [K5-DEDUP] was 83347 (pre-dedup)
            5'd16: weight_base_word_rom = 20'd62976;  // [K5-DEDUP] was 92563 (pre-dedup)
            default: weight_base_word_rom = 20'd0;
        endcase
    end

    reg [15:0] bias_base_word_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: bias_base_word_rom = 16'd31;
            5'd1: bias_base_word_rom = 16'd34;
            5'd2: bias_base_word_rom = 16'd33;
            5'd3: bias_base_word_rom = 16'd28;
            5'd4: bias_base_word_rom = 16'd40;
            5'd5: bias_base_word_rom = 16'd32;
            5'd6: bias_base_word_rom = 16'd29;
            5'd7: bias_base_word_rom = 16'd30;
            5'd8: bias_base_word_rom = 16'd38;
            5'd9: bias_base_word_rom = 16'd41;
            5'd10: bias_base_word_rom = 16'd12;
            5'd11: bias_base_word_rom = 16'd2;
            5'd12: bias_base_word_rom = 16'd43;
            5'd13: bias_base_word_rom = 16'd4;
            5'd14: bias_base_word_rom = 16'd0;
            5'd15: bias_base_word_rom = 16'd45;
            5'd16: bias_base_word_rom = 16'd20;
            default: bias_base_word_rom = 16'd0;
        endcase
    end

    reg [31:0] scale_mult_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: scale_mult_rom = 32'd764989767;
            5'd1: scale_mult_rom = 32'd782593650;
            5'd2: scale_mult_rom = 32'd1019650106;
            5'd3: scale_mult_rom = 32'd1180535669;
            5'd4: scale_mult_rom = 32'd1383171936;
            5'd5: scale_mult_rom = 32'd1238607715;
            5'd6: scale_mult_rom = 32'd1072697595;
            5'd7: scale_mult_rom = 32'd853358271;
            5'd8: scale_mult_rom = 32'd1373765162;
            5'd9: scale_mult_rom = 32'd986946539;
            5'd10: scale_mult_rom = 32'd1130221862;
            5'd11: scale_mult_rom = 32'd1459867458;
            5'd12: scale_mult_rom = 32'd1438966774;
            5'd13: scale_mult_rom = 32'd1175135978;
            5'd14: scale_mult_rom = 32'd1125111570;
            5'd15: scale_mult_rom = 32'd1310752209;
            5'd16: scale_mult_rom = 32'd814231008;
            default: scale_mult_rom = 32'd0;
        endcase
    end

    reg [5:0] scale_shift_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: scale_shift_rom = 6'd33;
            5'd1: scale_shift_rom = 6'd31;
            5'd2: scale_shift_rom = 6'd33;
            5'd3: scale_shift_rom = 6'd33;
            5'd4: scale_shift_rom = 6'd34;
            5'd5: scale_shift_rom = 6'd33;
            5'd6: scale_shift_rom = 6'd33;
            5'd7: scale_shift_rom = 6'd33;
            5'd8: scale_shift_rom = 6'd33;
            5'd9: scale_shift_rom = 6'd34;
            5'd10: scale_shift_rom = 6'd34;
            5'd11: scale_shift_rom = 6'd33;
            5'd12: scale_shift_rom = 6'd34;
            5'd13: scale_shift_rom = 6'd33;
            5'd14: scale_shift_rom = 6'd33;
            5'd15: scale_shift_rom = 6'd33;
            5'd16: scale_shift_rom = 6'd32;
            default: scale_shift_rom = 6'd0;
        endcase
    end

    reg [7:0] zero_point_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: zero_point_rom = 8'd0;
            5'd1: zero_point_rom = 8'd0;
            5'd2: zero_point_rom = 8'd0;
            5'd3: zero_point_rom = 8'd0;
            5'd4: zero_point_rom = 8'd0;
            5'd5: zero_point_rom = 8'd0;
            5'd6: zero_point_rom = 8'd0;
            5'd7: zero_point_rom = 8'd0;
            5'd8: zero_point_rom = 8'd0;
            5'd9: zero_point_rom = 8'd0;
            5'd10: zero_point_rom = 8'd0;
            5'd11: zero_point_rom = 8'd0;
            5'd12: zero_point_rom = 8'd0;
            5'd13: zero_point_rom = 8'd0;
            5'd14: zero_point_rom = 8'd0;
            5'd15: zero_point_rom = 8'd0;
            5'd16: zero_point_rom = 8'd0;
            default: zero_point_rom = 8'd0;
        endcase
    end

    reg [2:0] input_bank_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: input_bank_rom = 3'd2;
            5'd1: input_bank_rom = 3'd0;
            5'd2: input_bank_rom = 3'd2;
            5'd3: input_bank_rom = 3'd2;
            5'd4: input_bank_rom = 3'd0;
            5'd5: input_bank_rom = 3'd2;
            5'd6: input_bank_rom = 3'd2;
            5'd7: input_bank_rom = 3'd2;
            5'd8: input_bank_rom = 3'd0;
            5'd9: input_bank_rom = 3'd2;
            5'd10: input_bank_rom = 3'd2;
            5'd11: input_bank_rom = 3'd1;
            5'd12: input_bank_rom = 3'd2;
            5'd13: input_bank_rom = 3'd2;
            5'd14: input_bank_rom = 3'd0;
            5'd15: input_bank_rom = 3'd2;
            5'd16: input_bank_rom = 3'd2;
            default: input_bank_rom = 3'd0;
        endcase
    end

    reg [2:0] output_bank_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: output_bank_rom = 3'd1;
            5'd1: output_bank_rom = 3'd2;
            5'd2: output_bank_rom = 3'd0;
            5'd3: output_bank_rom = 3'd1;
            5'd4: output_bank_rom = 3'd1;
            5'd5: output_bank_rom = 3'd1;
            5'd6: output_bank_rom = 3'd1;
            5'd7: output_bank_rom = 3'd1;
            5'd8: output_bank_rom = 3'd1;
            5'd9: output_bank_rom = 3'd1;
            5'd10: output_bank_rom = 3'd1;
            5'd11: output_bank_rom = 3'd0;
            5'd12: output_bank_rom = 3'd0;
            5'd13: output_bank_rom = 3'd0;
            5'd14: output_bank_rom = 3'd1;
            5'd15: output_bank_rom = 3'd1;
            5'd16: output_bank_rom = 3'd1;
            default: output_bank_rom = 3'd0;
        endcase
    end

    reg [5:0] skip_mask_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: skip_mask_rom = 6'd1;
            5'd1: skip_mask_rom = 6'd2;
            5'd2: skip_mask_rom = 6'd2;
            5'd3: skip_mask_rom = 6'd1;
            5'd4: skip_mask_rom = 6'd0;
            5'd5: skip_mask_rom = 6'd1;
            5'd6: skip_mask_rom = 6'd1;
            5'd7: skip_mask_rom = 6'd1;
            5'd8: skip_mask_rom = 6'd0;
            5'd9: skip_mask_rom = 6'd1;
            5'd10: skip_mask_rom = 6'd1;
            5'd11: skip_mask_rom = 6'd0;
            5'd12: skip_mask_rom = 6'd2;
            5'd13: skip_mask_rom = 6'd2;
            5'd14: skip_mask_rom = 6'd0;
            5'd15: skip_mask_rom = 6'd1;
            5'd16: skip_mask_rom = 6'd1;
            default: skip_mask_rom = 6'd0;
        endcase
    end

    reg [15:0] act_in_base_word_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: act_in_base_word_rom = 16'd8192;
            5'd1: act_in_base_word_rom = 16'd0;
            5'd2: act_in_base_word_rom = 16'd8192;
            5'd3: act_in_base_word_rom = 16'd12288;  // [OVERLAP] remap (was 8192); see ENGINE_OVERLAP_ANALYSIS.md
            5'd4: act_in_base_word_rom = 16'd0;
            5'd5: act_in_base_word_rom = 16'd8192;
            5'd6: act_in_base_word_rom = 16'd12544;  // [OVERLAP] remap (was 8192); see ENGINE_OVERLAP_ANALYSIS.md
            5'd7: act_in_base_word_rom = 16'd8192;
            5'd8: act_in_base_word_rom = 16'd0;
            5'd9: act_in_base_word_rom = 16'd8192;
            5'd10: act_in_base_word_rom = 16'd12800;  // [OVERLAP] remap (was 8192); see ENGINE_OVERLAP_ANALYSIS.md
            5'd11: act_in_base_word_rom = 16'd4096;
            5'd12: act_in_base_word_rom = 16'd8192;
            5'd13: act_in_base_word_rom = 16'd12928;  // [OVERLAP] remap (was 8192); see ENGINE_OVERLAP_ANALYSIS.md
            5'd14: act_in_base_word_rom = 16'd0;
            5'd15: act_in_base_word_rom = 16'd8192;
            5'd16: act_in_base_word_rom = 16'd13056;  // [OVERLAP] remap (was 8192); see ENGINE_OVERLAP_ANALYSIS.md
            default: act_in_base_word_rom = 16'd0;
        endcase
    end

    reg [15:0] act_out_base_word_rom;
    always @(*) begin
        case (dispatch_idx)
            5'd0: act_out_base_word_rom = 16'd4096;
            5'd1: act_out_base_word_rom = 16'd8192;
            5'd2: act_out_base_word_rom = 16'd0;
            5'd3: act_out_base_word_rom = 16'd4096;
            5'd4: act_out_base_word_rom = 16'd4096;
            5'd5: act_out_base_word_rom = 16'd4096;
            5'd6: act_out_base_word_rom = 16'd4096;
            5'd7: act_out_base_word_rom = 16'd4096;
            5'd8: act_out_base_word_rom = 16'd4096;
            5'd9: act_out_base_word_rom = 16'd4096;
            5'd10: act_out_base_word_rom = 16'd4096;
            5'd11: act_out_base_word_rom = 16'd0;
            5'd12: act_out_base_word_rom = 16'd0;
            5'd13: act_out_base_word_rom = 16'd0;
            5'd14: act_out_base_word_rom = 16'd4096;
            5'd15: act_out_base_word_rom = 16'd4096;
            5'd16: act_out_base_word_rom = 16'd4096;
            default: act_out_base_word_rom = 16'd0;
        endcase
    end

    // ------------------------------------------------------------
    // Per-step AXI write address + data
    // ------------------------------------------------------------
    reg [7:0]  step_addr;
    reg [31:0] step_data;
    always @(*) begin
        step_addr = 8'h00;
        step_data = 32'd0;
        case (write_step)
            4'd0: begin step_addr = 8'h00; step_data = {16'd0, channel_in_rom}; end
            4'd1: begin step_addr = 8'h04; step_data = {16'd0, channel_out_rom}; end
            4'd2: begin step_addr = 8'h08; step_data = {24'd0, kernel_h_rom, kernel_w_rom}; end
            4'd3: begin step_addr = 8'h0C; step_data = {26'd0, stride_h_rom, stride_w_rom}; end
            4'd4: begin step_addr = 8'h10; step_data = {26'd0, padding_h_rom, padding_w_rom}; end
            4'd5: begin step_addr = 8'h14; step_data = {7'd0, input_h_rom, 7'd0, input_w_rom}; end
            4'd6: begin step_addr = 8'h18; step_data = {7'd0, output_h_rom, 7'd0, output_w_rom}; end
            4'd7: begin step_addr = 8'h1C; step_data = {12'd0, weight_base_word_rom}; end
            4'd8: begin step_addr = 8'h20; step_data = {16'd0, bias_base_word_rom}; end
            4'd9: begin step_addr = 8'h24; step_data = scale_mult_rom; end
            4'd10: begin step_addr = 8'h28; step_data = {18'd0, zero_point_rom, scale_shift_rom}; end
            4'd11: begin step_addr = 8'h34; step_data = {16'd0, act_in_base_word_rom}; end
            4'd12: begin step_addr = 8'h38; step_data = {16'd0, act_out_base_word_rom}; end
            default: begin step_addr = 8'h00; step_data = 32'd0; end
        endcase
    end

    // ------------------------------------------------------------
    // FSM next-state logic
    // ------------------------------------------------------------
    always @(*) begin
        next_state = state;
        case (state)
            S_IDLE:        if (start) next_state = S_WRITE;
            // S_WRITE asserts AW and W in the same cycle. A correct AXI4-Lite
            // slave fires the handshake when (awvalid & awready & wvalid & wready)
            // are all true in one cycle. aw_acked_r / w_acked_r let the slave
            // return the two ready signals in different cycles too.
            S_WRITE:
                if ((aw_acked_r || (s_axil_awvalid && s_axil_awready)) &&
                    (w_acked_r  || (s_axil_wvalid  && s_axil_wready)))
                    next_state = S_WRITE_RESP;
            S_WRITE_RESP:  if (s_axil_bvalid)  next_state = S_NEXT_STEP;
            // Fix 11: after the final config write, wait until the input
            // loader bridge for the current dispatch has finished filling
            // the activation BRAM. current_loaded comes from a wrapper-
            // side mux over per-dispatch `loaded` signals.
            S_NEXT_STEP:   next_state = (write_step == LAST_STEP) ? S_WAIT_LOAD : S_WRITE;
            S_WAIT_LOAD:   if (current_loaded) next_state = S_PULSE_START;
            S_PULSE_START: next_state = S_WAIT_DONE;
            // Fix 14: between dispatches, wait in S_WAIT_DRAIN until the
            // engine_output_fifo has been fully drained by this dispatch's
            // bridge. Otherwise dispatch N+1's writes would interleave with
            // N's outputs still in the FIFO. spatial_stall=0 in this state
            // so the spatial chain runs and drains the bridge → FIFO →
            // downstream relu/add → next input_loader path.
            S_WAIT_DONE:   if (engine_done) next_state = S_WAIT_DRAIN;
            S_WAIT_DRAIN:  if (current_drain_complete) next_state = S_NEXT_DISP;
            S_NEXT_DISP:   next_state = (dispatch_idx == LAST_DISPATCH) ? S_DONE : S_WRITE;
            S_DONE:        next_state = S_DONE;
            default:       next_state = S_IDLE;
        endcase
    end

    // ------------------------------------------------------------
    // Sequential state + counters
    // ------------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state        <= S_IDLE;
            dispatch_idx <= {5{1'b0}};
            write_step   <= {4{1'b0}};
            aw_acked_r   <= 1'b0;
            w_acked_r    <= 1'b0;
        end else begin
            state <= next_state;
            if (state == S_IDLE && start) begin
                dispatch_idx <= {5{1'b0}};
                write_step   <= {4{1'b0}};
            end
            if (state == S_NEXT_STEP) begin
                if (write_step == LAST_STEP) begin
                    write_step <= {4{1'b0}};
                end else begin
                    write_step <= write_step + 1'b1;
                end
            end
            if (state == S_NEXT_DISP && dispatch_idx != LAST_DISPATCH) begin
                dispatch_idx <= dispatch_idx + 1'b1;
            end
            // Latch per-channel handshake acks while in S_WRITE; clear
            // when leaving S_WRITE so the next register write starts fresh.
            if (state == S_WRITE) begin
                if (s_axil_awvalid && s_axil_awready) aw_acked_r <= 1'b1;
                if (s_axil_wvalid  && s_axil_wready)  w_acked_r  <= 1'b1;
            end else begin
                aw_acked_r <= 1'b0;
                w_acked_r  <= 1'b0;
            end
        end
    end

    // ------------------------------------------------------------
    // Output assignments
    // ------------------------------------------------------------
    always @(*) begin
        s_axil_awvalid          = 1'b0;
        s_axil_awaddr           = 8'd0;
        s_axil_wvalid           = 1'b0;
        s_axil_wdata            = 32'd0;
        s_axil_wstrb            = 4'b1111;
        s_axil_bready           = 1'b0;
        engine_start            = 1'b0;
        done                    = 1'b0;
        spatial_stall           = 1'b0;
        engine_output_ready     = 1'b0;
        input_bank_sel          = input_bank_rom;
        output_bank_sel         = output_bank_rom;
        skip_bank_reserved_mask = skip_mask_rom;

        case (state)
            S_IDLE: begin
                spatial_stall = 1'b0;
            end
            // Single S_WRITE: drive AW and W simultaneously. Hold each
            // valid line high until its respective handshake fires, then
            // (per the FSM next-state logic) wait for the other before
            // transitioning to S_WRITE_RESP.
            S_WRITE: begin
                s_axil_awvalid = ~aw_acked_r;
                s_axil_awaddr  = step_addr;
                s_axil_wvalid  = ~w_acked_r;
                s_axil_wdata   = step_data;
                s_axil_wstrb   = 4'b1111;
                spatial_stall  = 1'b1;
            end
            S_WRITE_RESP: begin
                s_axil_bready = 1'b1;
                spatial_stall = 1'b1;
            end
            S_NEXT_STEP: begin
                spatial_stall = 1'b1;
            end
            S_WAIT_LOAD: begin
                spatial_stall = 1'b0; // let the spatial chain keep filling the loader BRAM
            end
            S_PULSE_START: begin
                // Fix 11: CONTROL.start AXI write is removed; this pin is now
                // the SOLE engine-start trigger. We reach here only after
                // S_WAIT_LOAD has observed current_loaded, so the activation
                // BRAM is guaranteed populated for this dispatch.
                engine_start  = 1'b1;
                spatial_stall = 1'b1;
            end
            S_WAIT_DONE: begin
                // [OVERLAP] engine/spatial overlap: the chain keeps streaming
                // while the engine runs. Safe because (1) every dispatch
                // input region is loader-private (5 remapped to bank 3),
                // (2) the engine no longer writes the act BRAM (FIFO-only
                // output), (3) skip FIFOs bound at full-map < DEPTH.
                spatial_stall = 1'b0;
            end
            S_WAIT_DRAIN: begin
                // Fix 14: chain MUST run so the bridge can drain the
                // engine_output_fifo and feed downstream relu/add layers.
                spatial_stall = 1'b0;
            end
            S_NEXT_DISP: begin
                spatial_stall       = 1'b1;
                engine_output_ready = 1'b1;
            end
            S_DONE: begin
                done                = 1'b1;
            end
            default: begin
                spatial_stall = 1'b0;
            end
        endcase
    end

    wire _unused_s_axil_bresp = |s_axil_bresp;

endmodule
